import type { Course } from './types';

// A2 — Elementary French (CEFR A2)
// Builds on A1: past tense (passé composé, imparfait), opinions, social interactions
export const a2Course: Course = {
  level: 'A2',
  title: 'A2 — Élémentaire',
  book: 'Parlez A2',
  description:
    "Continue your journey. You'll master the passé composé and imparfait to talk about past events, express opinions, navigate social situations, and discuss memories, travel, health, and housing.",
  cefrDescription:
    'Can understand sentences and frequently used expressions related to areas of most immediate relevance. Can communicate in simple and routine tasks requiring a simple and direct exchange of information on familiar and routine matters.',
  color: '#C19A4B',
  units: [
    {
      id: 'a2-u1',
      title: 'Memories and the Past',
      titleFr: 'Souvenirs',
      theme: 'Passé composé & childhood',
      description: 'Talk about what you did yesterday, last week, or in your childhood.',
      lessons: [
        {
          id: 'a2-u1-l1',
          title: 'The Passé Composé',
          titleFr: 'Le passé composé',
          description: 'Learn the main French past tense — used to talk about completed actions in the past.',
          objectives: [
            'Form the passé composé with avoir and être',
            'Conjugate regular -er, -ir, -re verbs in the past',
            'Use common irregular past participles',
            'Talk about what you did yesterday',
          ],
          vocabulary: [
            { fr: 'hier', en: 'yesterday', example: 'Hier, je suis allé au cinéma.', exampleEn: 'Yesterday, I went to the movies.', category: 'time' },
            { fr: 'la semaine dernière', en: 'last week', example: 'La semaine dernière, j\'ai voyagé.', exampleEn: 'Last week, I traveled.', category: 'time' },
            { fr: 'le mois dernier', en: 'last month', example: 'Le mois dernier, il a neigé.', exampleEn: 'Last month, it snowed.', category: 'time' },
            { fr: 'l\'année dernière', en: 'last year', example: 'L\'année dernière, nous sommes allés en Italie.', exampleEn: 'Last year, we went to Italy.', category: 'time' },
            { fr: 'avant', en: 'before', example: 'Avant, j\'habitais à Lyon.', exampleEn: 'Before, I lived in Lyon.', category: 'time' },
            { fr: 'mon enfance', en: 'my childhood', example: 'Dans mon enfance, je jouais au parc.', exampleEn: 'In my childhood, I played in the park.', category: 'life' },
            { fr: 'un souvenir', en: 'a memory', example: 'J\'ai un bon souvenir de cette époque.', exampleEn: 'I have a good memory of that time.', category: 'life' },
            { fr: 'se souvenir de', en: 'to remember', example: 'Je me souviens de toi.', exampleEn: 'I remember you.', category: 'verbs' },
            { fr: 'oublier', en: 'to forget', example: 'J\'ai oublié mon parapluie.', exampleEn: 'I forgot my umbrella.', category: 'verbs' },
            { fr: 'raconter', en: 'to tell (a story)', example: 'Raconte-moi ton voyage !', exampleEn: 'Tell me about your trip!', category: 'verbs' },
          ],
          grammar: [
            {
              title: 'Forming the passé composé',
              explanation:
                "The passé composé is the main past tense in spoken French. It is formed with an auxiliary (avoir or être) + past participle. Most verbs use avoir; about 14 verbs of motion/reflexive use être.",
              examples: [
                { fr: 'J\'ai mangé. (I have eaten / I ate)', en: 'Avoir + mangé (past participle of manger).' },
                { fr: 'Je suis allé. (I went)', en: 'Être + allé. Note: agreement with subject for être verbs.' },
                { fr: 'Nous avons fini. (We finished)', en: 'Avoir + fini (past participle of finir).' },
              ],
              table: {
                caption: 'Past participles of common verbs',
                headers: ['Infinitive', 'Past participle', 'Auxiliary'],
                rows: [
                  ['manger', 'mangé', 'avoir'],
                  ['finir', 'fini', 'avoir'],
                  ['prendre', 'pris', 'avoir'],
                  ['aller', 'allé(e)(s)', 'être'],
                  ['venir', 'venu(e)(s)', 'être'],
                  ['faire', 'fait', 'avoir'],
                  ['être', 'été', 'avoir'],
                  ['avoir', 'eu', 'avoir'],
                ],
              },
              tip: 'With être, the past participle agrees with the subject: elle est allée (f), ils sont venus (m pl), elles sont venues (f pl).',
            },
            {
              title: 'The "Dr. & Mrs. Vandertramp" verbs (être)',
              explanation:
                "These 14 verbs (and their compounds) use être as their auxiliary in the passé composé. Most are verbs of motion: aller, venir, arriver, partir, entrer, sortir, monter, descendre, naître, mourir, rester, tomber, retourner, devenir, plus reflexive verbs.",
              examples: [
                { fr: 'Je suis allé au cinéma.', en: 'I went to the cinema.' },
                { fr: 'Elle est venue à la fête.', en: 'She came to the party.' },
                { fr: 'Ils sont partis à 8h.', en: 'They left at 8.' },
                { fr: 'Nous sommes restés à la maison.', en: 'We stayed at home.' },
              ],
              tip: 'A mnemonic: Dr. Mrs. Vandertramp — each letter is the start of an être verb.',
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'être',
              translation: 'to be',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'suis' },
                { pronoun: 'tu', form: 'es' },
                { pronoun: 'il/elle', form: 'est' },
                { pronoun: 'nous', form: 'sommes' },
                { pronoun: 'vous', form: 'êtes' },
                { pronoun: 'ils/elles', form: 'sont' },
              ],
              sentenceRule: 'Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
              sentenceExamples: [
                { fr: 'Je suis étudiant.', en: 'I am a student.' },
                { fr: 'Tu es français ?', en: 'Are you French?' },
                { fr: 'Nous sommes à Paris.', en: 'We are in Paris.' },
              ],
            },
            {
              infinitive: 'avoir',
              translation: 'to have',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'j\'', form: 'ai' },
                { pronoun: 'tu', form: 'as' },
                { pronoun: 'il/elle', form: 'a' },
                { pronoun: 'nous', form: 'avons' },
                { pronoun: 'vous', form: 'avez' },
                { pronoun: 'ils/elles', form: 'ont' },
              ],
              sentenceRule: 'Subject + avoir + noun. Used for possession, age (J\'ai 20 ans), and expressions like avoir faim/soif/froid. Age uses avoir, NOT être.',
              sentenceExamples: [
                { fr: 'J\'ai un frère.', en: 'I have a brother.' },
                { fr: 'Tu as vingt ans.', en: 'You are twenty.' },
                { fr: 'Il a faim.', en: 'He is hungry.' },
              ],
            }
            ],
            practice: [
              {
                id: 'a2-u1-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "être" for "je":',
                promptFr: 'je _____',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'je suis — correct form of "être".',
              },
              {
                id: 'a2-u1-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "être".',
                options: ['est', 'suis', 'es', 'sommes'],
                answer: 0,
                explanation: 'il/elle est — correct conjugation of "être".',
              },
              {
                id: 'a2-u1-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'The correct form is "suis".',
              },
              {
                id: 'a2-u1-l1-conj-1-1',
                type: 'conjugation',
                prompt: 'Conjugate "avoir" for "tu":',
                promptFr: 'tu _____',
                answer: 'as',
                acceptable: ['as'],
                explanation: 'tu as — correct form of "avoir".',
              },
              {
                id: 'a2-u1-l1-conj-1-2',
                type: 'multiple_choice',
                prompt: 'Complete: "nous _____" with the correct form of "avoir".',
                options: ['avons', 'ai', 'as', 'a'],
                answer: 0,
                explanation: 'nous avons — correct conjugation of "avoir".',
              },
              {
                id: 'a2-u1-l1-conj-1-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Tu _____ vingt ans." (You are twenty.) — form of "avoir"',
                answer: 'as',
                acceptable: ['as'],
                explanation: 'The correct form is "as".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Lucas', fr: 'Tu as fait quoi hier, Marie ?', en: 'What did you do yesterday, Marie?' },
            { speaker: 'B', name: 'Marie', fr: 'Hier, je suis allée au musée avec ma sœur. Nous avons vu une exposition sur Picasso.', en: 'Yesterday, I went to the museum with my sister. We saw a Picasso exhibition.' },
            { speaker: 'A', name: 'Lucas', fr: 'Super ! Et le soir, qu\'est-ce que tu as fait ?', en: 'Great! And in the evening, what did you do?' },
            { speaker: 'B', name: 'Marie', fr: 'Le soir, nous avons dîné dans un petit restaurant italien. J\'ai pris des pâtes délicieuses.', en: 'In the evening, we had dinner in a small Italian restaurant. I had delicious pasta.' },
            { speaker: 'A', name: 'Lucas', fr: 'Moi, je suis resté à la maison. J\'ai regardé un film.', en: 'Me, I stayed home. I watched a movie.' },
            { speaker: 'B', name: 'Marie', fr: 'Quel film tu as vu ?', en: 'What movie did you watch?' },
            { speaker: 'A', name: 'Lucas', fr: 'J\'ai vu "Le Fabuleux Destin d\'Amélie Poulain". C\'est un classique !', en: 'I saw "Amélie". It\'s a classic!' },
          ],
          exercises: [
            {
              id: 'a2-u1-l1-e1',
              type: 'multiple_choice',
              prompt: 'Which auxiliary does "aller" use in the passé composé?',
              options: ['avoir', 'être', 'faire', 'both'],
              answer: 1,
              explanation: 'Aller is a motion verb — it uses être: je suis allé(e).',
            },
            {
              id: 'a2-u1-l2-e2',
              type: 'fill_blank',
              prompt: 'Complete: "Hier, j\'_____ mangé au restaurant."',
              answer: 'ai',
              explanation: 'J\'ai mangé = I ate. Manger uses avoir.',
            },
            {
              id: 'a2-u1-l3-e3',
              type: 'multiple_choice',
              prompt: 'What is the past participle of "prendre"?',
              options: ['prendu', 'pris', 'prendi', 'prendre'],
              answer: 1,
              explanation: 'Prendre → pris (irregular). Like: apprendre → appris, comprendre → compris.',
            },
            {
              id: 'a2-u1-l4-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "We went to Italy last year."',
              answer: 'Nous sommes allés en Italie l\'année dernière',
              acceptable: ['nous sommes allés en italie l année dernière'],
              explanation: 'Aller + être. Nous (m) → allés. En Italie (countries).',
            },
            {
              id: 'a2-u1-l5-e5',
              type: 'true_false',
              prompt: 'With être verbs, the past participle agrees with the subject in gender and number.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. Elle est allée (f), ils sont venus (m pl), elles sont venues (f pl).',
            },
          ],
          culturalNote:
            "The French love to 'raconter' (tell stories). A typical French dinner can last 2-3 hours, with everyone sharing stories about their day, week, or trips. Asking 'Qu\'est-ce que tu as fait ce week-end ?' is a classic Monday morning question at work.",
          estimatedMinutes: 35,
        },
        {
          id: 'a2-u1-l2',
          title: 'The Imparfait',
          titleFr: 'L\'imparfait',
          description: 'Learn the imperfect tense — used for descriptions, habits, and ongoing past actions.',
          objectives: [
            'Form the imparfait from the nous form',
            'Use imparfait for descriptions and habits',
            'Distinguish imparfait from passé composé',
            'Describe your childhood',
          ],
          vocabulary: [
            { fr: 'quand j\'étais petit(e)', en: 'when I was little', example: 'Quand j\'étais petite, j\'adorais les bonbons.', exampleEn: 'When I was little, I loved candy.', category: 'childhood' },
            { fr: 'avant', en: 'before / in the past', example: 'Avant, j\'habitais à la campagne.', exampleEn: 'Before, I lived in the countryside.', category: 'time' },
            { fr: 'tous les jours', en: 'every day', example: 'Tous les jours, je marchais à l\'école.', exampleEn: 'Every day, I walked to school.', category: 'habit' },
            { fr: 'souvent', en: 'often', example: 'Je jouais souvent au parc.', exampleEn: 'I often played in the park.', category: 'frequency' },
            { fr: 'parfois', en: 'sometimes', example: 'Parfois, nous allions à la mer.', exampleEn: 'Sometimes, we went to the sea.', category: 'frequency' },
            { fr: 'la campagne', en: 'the countryside', example: 'J\'aimais la campagne.', exampleEn: 'I liked the countryside.', category: 'places' },
            { fr: 'la mer', en: 'the sea', example: 'Nous allions à la mer en été.', exampleEn: 'We went to the sea in summer.', category: 'places' },
            { fr: 'l\'école', en: 'school', example: 'À l\'école, j\'étais bon en maths.', exampleEn: 'At school, I was good at math.', category: 'education' },
            { fr: 'les copains', en: 'friends (informal)', example: 'Je jouais avec mes copains.', exampleEn: 'I played with my friends.', category: 'people' },
            { fr: 'grandir', en: 'to grow up', example: 'J\'ai grandi à Lyon.', exampleEn: 'I grew up in Lyon.', category: 'verbs' },
          ],
          grammar: [
            {
              title: 'Forming the imparfait',
              explanation:
                "The imparfait is formed from the nous form of the present tense: drop the -ons ending and add -ais, -ais, -ait, -ions, -iez, -aient. The only exception is être, whose stem is 'ét-'.",
              examples: [
                { fr: 'parler → nous parlons → je parlais', en: 'I was speaking / I used to speak' },
                { fr: 'finir → nous finissons → je finissais', en: 'I was finishing / I used to finish' },
                { fr: 'être → j\'étais', en: 'I was (being)' },
              ],
              table: {
                caption: 'Imparfait endings',
                headers: ['Pronoun', 'Ending', 'Example (parler)'],
                rows: [
                  ['je', '-ais', 'parlais'],
                  ['tu', '-ais', 'parlais'],
                  ['il/elle', '-ait', 'parlait'],
                  ['nous', '-ions', 'parlions'],
                  ['vous', '-iez', 'parliez'],
                  ['ils/elles', '-aient', 'parlaent'],
                ],
              },
              tip: "All forms have the same sound (é /ɛ/), except nous (-jɔ̃) and vous (-je).",
            },
            {
              title: 'Imparfait vs. Passé Composé',
              explanation:
                "Use the imparfait for: descriptions, ongoing actions, habits ('I used to...'), and background. Use the passé composé for: completed actions, specific events, and actions that moved the story forward.",
              examples: [
                { fr: 'Il pleuvait (imparfait) quand je suis sorti (passé composé).', en: 'It was raining when I went out.' },
                { fr: 'Quand j\'étais enfant, j\'allais à la mer tous les étés.', en: 'When I was a child, I went to the sea every summer (habit).' },
                { fr: 'Hier, j\'ai rencontré Sophie.', en: 'Yesterday, I met Sophie (specific event).' },
              ],
              tip: 'Imparfait = setting the scene; Passé composé = what happened.',
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'avoir',
              translation: 'to have',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'j\'', form: 'ai' },
                { pronoun: 'tu', form: 'as' },
                { pronoun: 'il/elle', form: 'a' },
                { pronoun: 'nous', form: 'avons' },
                { pronoun: 'vous', form: 'avez' },
                { pronoun: 'ils/elles', form: 'ont' },
              ],
              sentenceRule: 'Subject + avoir + noun. Used for possession, age (J\'ai 20 ans), and expressions like avoir faim/soif/froid. Age uses avoir, NOT être.',
              sentenceExamples: [
                { fr: 'J\'ai un frère.', en: 'I have a brother.' },
                { fr: 'Tu as vingt ans.', en: 'You are twenty.' },
                { fr: 'Il a faim.', en: 'He is hungry.' },
              ],
            }
            ],
            practice: [
              {
                id: 'a2-u1-l2-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "avoir" for "j\'":',
                promptFr: 'j\' _____',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'j\' ai — correct form of "avoir".',
              },
              {
                id: 'a2-u1-l2-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "avoir".',
                options: ['a', 'ai', 'as', 'avons'],
                answer: 0,
                explanation: 'il/elle a — correct conjugation of "avoir".',
              },
              {
                id: 'a2-u1-l2-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "J\'_____ un frère." (I have a brother.) — form of "avoir"',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'The correct form is "ai".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Paul', fr: 'Tu étais comment quand tu étais enfant, Léa ?', en: 'What were you like when you were a child, Léa?' },
            { speaker: 'B', name: 'Léa', fr: 'J\'étais très timide. Je parlais peu, mais je lisais beaucoup.', en: 'I was very shy. I spoke little, but I read a lot.' },
            { speaker: 'A', name: 'Paul', fr: 'Tu habitais où à ce moment-là ?', en: 'Where did you live at that time?' },
            { speaker: 'B', name: 'Léa', fr: 'J\'habitais à Nantes, près de la Loire. Tous les week-ends, nous allions nous promener au bord du fleuve.', en: 'I lived in Nantes, near the Loire. Every weekend, we went walking along the river.' },
            { speaker: 'A', name: 'Paul', fr: 'C\'est charmant. Et tu avais des amis ?', en: 'That\'s charming. Did you have friends?' },
            { speaker: 'B', name: 'Léa', fr: 'Oui, j\'avais deux meilleures amies. Nous jouions ensemble tous les jours après l\'école.', en: 'Yes, I had two best friends. We played together every day after school.' },
            { speaker: 'A', name: 'Paul', fr: 'Tu les vois encore ?', en: 'Do you still see them?' },
            { speaker: 'B', name: 'Léa', fr: 'Malheureusement non. L\'une habite au Canada maintenant.', en: 'Unfortunately no. One lives in Canada now.' },
          ],
          exercises: [
            {
              id: 'a2-u1-l2-e1',
              type: 'multiple_choice',
              prompt: 'What is the imparfait stem of "finir" (nous finissons)?',
              options: ['fin-', 'finiss-', 'fini-', 'finiss-'],
              answer: 1,
              explanation: 'Drop -ons from nous finissons → finiss-. Then add -ais: je finissais.',
            },
            {
              id: 'a2-u1-l2-e2',
              type: 'fill_blank',
              prompt: 'Complete: "Quand j\'_____ enfant, j\'adorais les bonbons."',
              answer: 'étais',
              explanation: 'Être in imparfait: j\'étais, tu étais, il était, etc.',
            },
            {
              id: 'a2-u1-l2-e3',
              type: 'multiple_choice',
              prompt: 'Which tense for "I used to play tennis every Sunday"?',
              options: ['Passé composé', 'Imparfait', 'Présent', 'Futur'],
              answer: 1,
              explanation: 'Habitual past actions use imparfait: Je jouais au tennis tous les dimanches.',
            },
            {
              id: 'a2-u1-l2-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "When I was little, I lived in Lyon."',
              answer: 'Quand j\'étais petit, j\'habitais à Lyon',
              acceptable: ['quand j étais petit j habitais à lyon'],
              explanation: 'Imparfait for both: j\'étais (was being) + j\'habitais (used to live).',
            },
            {
              id: 'a2-u1-l2-e5',
              type: 'true_false',
              prompt: 'The imparfait is used for completed, specific past events.',
              options: ['True', 'False'],
              answer: 1,
              explanation: 'False. The imparfait is for descriptions and habits. Passé composé is for completed events.',
            },
          ],
          culturalNote:
            "French schools have a long tradition of 'la rédaction' (essay writing). Children are encouraged from a young age to write stories about their weekends, holidays, and childhood memories. This cultural emphasis on storytelling shapes the way French people converse — anecdotes and detailed narratives are highly valued.",
          estimatedMinutes: 35,
        },
      ],
    },
    {
      id: 'a2-u2',
      title: 'Travel and Discovery',
      titleFr: 'Voyages',
      theme: 'Future, travel & transportation',
      description: 'Plan future trips, talk about transportation, and use the futur proche.',
      lessons: [
        {
          id: 'a2-u2-l1',
          title: 'Planning the Future',
          titleFr: 'Planifier l\'avenir',
          description: 'Use aller + infinitive to talk about what you are going to do.',
          objectives: [
            'Form the futur proche (aller + infinitif)',
            'Talk about future plans and intentions',
            'Use travel vocabulary',
            'Book a hotel and a train ticket',
          ],
          vocabulary: [
            { fr: 'le voyage', en: 'the trip', example: 'Je vais faire un voyage.', exampleEn: 'I\'m going to take a trip.', category: 'travel' },
            { fr: 'le billet', en: 'the ticket', example: 'Je vais acheter un billet de train.', exampleEn: 'I\'m going to buy a train ticket.', category: 'travel' },
            { fr: 'la valise', en: 'the suitcase', example: 'Je vais faire ma valise.', exampleEn: 'I\'m going to pack my suitcase.', category: 'travel' },
            { fr: 'l\'avion', en: 'the plane', example: 'Nous allons prendre l\'avion.', exampleEn: 'We\'re going to take the plane.', category: 'transport' },
            { fr: 'le train', en: 'the train', example: 'Le train arrive à 14h.', exampleEn: 'The train arrives at 2 PM.', category: 'transport' },
            { fr: 'la voiture', en: 'the car', example: 'Je vais louer une voiture.', exampleEn: 'I\'m going to rent a car.', category: 'transport' },
            { fr: 'l\'hôtel', en: 'the hotel', example: 'Nous allons réserver un hôtel.', exampleEn: 'We\'re going to book a hotel.', category: 'travel' },
            { fr: 'la plage', en: 'the beach', example: 'Nous allons à la plage.', exampleEn: 'We\'re going to the beach.', category: 'places' },
            { fr: 'la montagne', en: 'the mountain', example: 'Ils vont à la montagne.', exampleEn: 'They\'re going to the mountains.', category: 'places' },
            { fr: 'réserver', en: 'to book / reserve', example: 'Je vais réserver une chambre.', exampleEn: 'I\'m going to book a room.', category: 'verbs' },
            { fr: 'partir', en: 'to leave', example: 'Nous allons partir demain.', exampleEn: 'We\'re going to leave tomorrow.', category: 'verbs' },
            { fr: 'visiter', en: 'to visit (a place)', example: 'Je vais visiter Paris.', exampleEn: 'I\'m going to visit Paris.', category: 'verbs' },
          ],
          grammar: [
            {
              title: 'Futur proche — aller + infinitif',
              explanation:
                "The futur proche (near future) is the easiest way to talk about the future in French. It is formed with the present tense of 'aller' + the infinitive of the main verb. It is used for plans, intentions, and near-future events.",
              examples: [
                { fr: 'Je vais manger.', en: 'I am going to eat.' },
                { fr: 'Tu vas voyager.', en: 'You are going to travel.' },
                { fr: 'Nous allons partir demain.', en: 'We are going to leave tomorrow.' },
              ],
              table: {
                caption: 'Conjugation of aller (for futur proche)',
                headers: ['Pronoun', 'aller', 'Example'],
                rows: [
                  ['je', 'vais', 'je vais partir'],
                  ['tu', 'vas', 'tu vas manger'],
                  ['il/elle', 'va', 'il va venir'],
                  ['nous', 'allons', 'nous allons étudier'],
                  ['vous', 'allez', 'vous allez travailler'],
                  ['ils/elles', 'vont', 'ils vont arriver'],
                ],
              },
              tip: 'The futur proche is more common in spoken French than the futur simple, especially for near-future plans.',
            },
            {
              title: 'Prepositions with countries and cities',
              explanation:
                "Prepositions change depending on the gender of the country and whether it's a city. Cities always take 'à'. Countries take 'en' (feminine) or 'au' (masculine).",
              examples: [
                { fr: 'à Paris, à Lyon, à Tokyo', en: 'Cities always use à.' },
                { fr: 'en France, en Italie, en Chine', en: 'Feminine countries use en.' },
                { fr: 'au Canada, au Japon, au Maroc', en: 'Masculine countries use au.' },
                { fr: 'aux États-Unis, aux Pays-Bas', en: 'Plural countries use aux.' },
              ],
              tip: "Most countries ending in -e are feminine (la France, l'Italie). Exceptions: le Mexique, le Mozambique, le Cambodge, le Zimbabwe.",
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'avoir',
              translation: 'to have',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'j\'', form: 'ai' },
                { pronoun: 'tu', form: 'as' },
                { pronoun: 'il/elle', form: 'a' },
                { pronoun: 'nous', form: 'avons' },
                { pronoun: 'vous', form: 'avez' },
                { pronoun: 'ils/elles', form: 'ont' },
              ],
              sentenceRule: 'Subject + avoir + noun. Used for possession, age (J\'ai 20 ans), and expressions like avoir faim/soif/froid. Age uses avoir, NOT être.',
              sentenceExamples: [
                { fr: 'J\'ai un frère.', en: 'I have a brother.' },
                { fr: 'Tu as vingt ans.', en: 'You are twenty.' },
                { fr: 'Il a faim.', en: 'He is hungry.' },
              ],
            }
            ],
            practice: [
              {
                id: 'a2-u2-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "avoir" for "j\'":',
                promptFr: 'j\' _____',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'j\' ai — correct form of "avoir".',
              },
              {
                id: 'a2-u2-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "avoir".',
                options: ['a', 'ai', 'as', 'avons'],
                answer: 0,
                explanation: 'il/elle a — correct conjugation of "avoir".',
              },
              {
                id: 'a2-u2-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "J\'_____ un frère." (I have a brother.) — form of "avoir"',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'The correct form is "ai".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Camille', fr: 'Qu\'est-ce que tu vas faire cet été, Thomas ?', en: 'What are you going to do this summer, Thomas?' },
            { speaker: 'B', name: 'Thomas', fr: 'Je vais voyager en Italie avec ma copine. Nous allons visiter Rome et Florence.', en: 'I\'m going to travel to Italy with my girlfriend. We\'re going to visit Rome and Florence.' },
            { speaker: 'A', name: 'Camille', fr: 'Super ! Comment vous allez y aller ? En avion ?', en: 'Great! How are you going to go? By plane?' },
            { speaker: 'B', name: 'Thomas', fr: 'Non, nous allons prendre le train. C\'est plus écologique.', en: 'No, we\'re going to take the train. It\'s more eco-friendly.' },
            { speaker: 'A', name: 'Camille', fr: 'Vous allez réserver un hôtel ?', en: 'Are you going to book a hotel?' },
            { speaker: 'B', name: 'Thomas', fr: 'Oui, nous allons réserver un petit hôtel à Rome. Et toi, tu vas partir en vacances ?', en: 'Yes, we\'re going to book a small hotel in Rome. And you, are you going on vacation?' },
            { speaker: 'A', name: 'Camille', fr: 'Je vais aller au Maroc avec ma famille. Nous allons rester deux semaines.', en: 'I\'m going to Morocco with my family. We\'re going to stay two weeks.' },
          ],
          exercises: [
            {
              id: 'a2-u2-l1-e1',
              type: 'multiple_choice',
              prompt: 'How do you say "I am going to travel" in French?',
              options: ['Je voyage', 'Je vais voyager', 'Je voyagerai', 'Je voyageais'],
              answer: 1,
              explanation: 'Futur proche = aller (present) + infinitive: je vais voyager.',
            },
            {
              id: 'a2-u2-l1-e2',
              type: 'fill_blank',
              prompt: 'Complete: "Nous _____ partir demain." (We are going to leave tomorrow.)',
              answer: 'allons',
              explanation: 'Nous + allons + infinitive: nous allons partir.',
            },
            {
              id: 'a2-u2-l1-e3',
              type: 'multiple_choice',
              prompt: 'Which preposition: "Je vais _____ Italie." (I am going to Italy.)',
              options: ['à l\'', 'au', 'en', 'aux'],
              answer: 2,
              explanation: 'Italie is feminine → en Italie.',
            },
            {
              id: 'a2-u2-l1-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "We are going to take the train."',
              answer: 'Nous allons prendre le train',
              acceptable: ['nous allons prendre le train'],
              explanation: 'Nous allons + prendre (infinitive) + le train.',
            },
            {
              id: 'a2-u2-l1-e5',
              type: 'true_false',
              prompt: 'The futur proche is more common in spoken French than the futur simple.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. The futur proche (aller + infinitif) is the most natural way to talk about near-future plans.',
            },
          ],
          culturalNote:
            "France has an extensive high-speed train network called TGV (Train à Grande Vitesse). The TGV can reach 320 km/h and connects Paris to Marseille in just 3 hours. The SNCF (French national railway) is the main operator — booking in advance can save you up to 70% on tickets.",
          estimatedMinutes: 35,
        },
      ],
    },
    {
      id: 'a2-u3',
      title: 'Health and Body',
      titleFr: 'Santé',
      theme: 'Body, illness & advice',
      description: 'Talk about your body, describe symptoms, and give advice using devoir.',
      lessons: [
        {
          id: 'a2-u3-l1',
          title: 'At the Doctor',
          titleFr: 'Chez le médecin',
          description: 'Describe symptoms, talk to a doctor, and understand medical advice.',
          objectives: [
            'Name body parts',
            'Describe common symptoms',
            'Use devoir for advice (tu dois...)',
            'Understand basic medical instructions',
          ],
          vocabulary: [
            { fr: 'le corps', en: 'the body', example: 'Le corps humain est fascinant.', exampleEn: 'The human body is fascinating.', category: 'body' },
            { fr: 'la tête', en: 'the head', example: 'J\'ai mal à la tête.', exampleEn: 'I have a headache.', category: 'body' },
            { fr: 'le ventre', en: 'the stomach', example: 'J\'ai mal au ventre.', exampleEn: 'I have a stomach ache.', category: 'body' },
            { fr: 'le dos', en: 'the back', example: 'J\'ai mal au dos.', exampleEn: 'My back hurts.', category: 'body' },
            { fr: 'la gorge', en: 'the throat', example: 'J\'ai mal à la gorge.', exampleEn: 'My throat hurts.', category: 'body' },
            { fr: 'le bras', en: 'the arm', example: 'Mon bras me fait mal.', exampleEn: 'My arm hurts.', category: 'body' },
            { fr: 'la jambe', en: 'the leg', example: 'Ma jambe est cassée.', exampleEn: 'My leg is broken.', category: 'body' },
            { fr: 'avoir mal à', en: 'to have pain in', example: 'J\'ai mal à la tête.', exampleEn: 'I have a headache.', category: 'medical' },
            { fr: 'la fièvre', en: 'the fever', example: 'J\'ai de la fièvre.', exampleEn: 'I have a fever.', category: 'medical' },
            { fr: 'la toux', en: 'the cough', example: 'J\'ai une toux sèche.', exampleEn: 'I have a dry cough.', category: 'medical' },
            { fr: 'le rhume', en: 'the cold', example: 'J\'ai attrapé un rhume.', exampleEn: 'I caught a cold.', category: 'medical' },
            { fr: 'le médicament', en: 'the medicine', example: 'Prenez ce médicament trois fois par jour.', exampleEn: 'Take this medicine three times a day.', category: 'medical' },
          ],
          grammar: [
            {
              title: 'Expression: avoir mal à',
              explanation:
                "To express pain, French uses 'avoir mal à' + body part. The preposition 'à' changes to 'au' (m), 'à la' (f), or 'à l\'' (vowel).",
              examples: [
                { fr: 'J\'ai mal à la tête.', en: 'I have a headache.' },
                { fr: 'J\'ai mal au ventre.', en: 'I have a stomach ache.' },
                { fr: 'J\'ai mal aux pieds.', en: 'My feet hurt.' },
                { fr: 'J\'ai mal à l\'oreille.', en: 'My ear hurts.' },
              ],
              tip: 'Avoir mal à + definite article + body part. Always use the article, even though English doesn\'t.',
            },
            {
              title: 'Devoir — must / should / have to',
              explanation:
                "Devoir is used to express obligation, necessity, or advice. The meaning changes with the tense: present = must/should, conditional = ought to (softer advice).",
              examples: [
                { fr: 'Tu dois voir un médecin.', en: 'You must see a doctor.' },
                { fr: 'Vous devez vous reposer.', en: 'You must rest.' },
                { fr: 'Tu ne dois pas fumer.', en: 'You must not smoke.' },
              ],
              table: {
                caption: 'Conjugation of devoir',
                headers: ['Pronoun', 'devoir'],
                rows: [
                  ['je', 'dois'],
                  ['tu', 'dois'],
                  ['il/elle', 'doit'],
                  ['nous', 'devons'],
                  ['vous', 'devez'],
                  ['ils/elles', 'doivent'],
                ],
              },
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'être',
              translation: 'to be',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'suis' },
                { pronoun: 'tu', form: 'es' },
                { pronoun: 'il/elle', form: 'est' },
                { pronoun: 'nous', form: 'sommes' },
                { pronoun: 'vous', form: 'êtes' },
                { pronoun: 'ils/elles', form: 'sont' },
              ],
              sentenceRule: 'Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
              sentenceExamples: [
                { fr: 'Je suis étudiant.', en: 'I am a student.' },
                { fr: 'Tu es français ?', en: 'Are you French?' },
                { fr: 'Nous sommes à Paris.', en: 'We are in Paris.' },
              ],
            },
            {
              infinitive: 'avoir',
              translation: 'to have',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'j\'', form: 'ai' },
                { pronoun: 'tu', form: 'as' },
                { pronoun: 'il/elle', form: 'a' },
                { pronoun: 'nous', form: 'avons' },
                { pronoun: 'vous', form: 'avez' },
                { pronoun: 'ils/elles', form: 'ont' },
              ],
              sentenceRule: 'Subject + avoir + noun. Used for possession, age (J\'ai 20 ans), and expressions like avoir faim/soif/froid. Age uses avoir, NOT être.',
              sentenceExamples: [
                { fr: 'J\'ai un frère.', en: 'I have a brother.' },
                { fr: 'Tu as vingt ans.', en: 'You are twenty.' },
                { fr: 'Il a faim.', en: 'He is hungry.' },
              ],
            }
            ],
            practice: [
              {
                id: 'a2-u3-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "être" for "je":',
                promptFr: 'je _____',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'je suis — correct form of "être".',
              },
              {
                id: 'a2-u3-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "être".',
                options: ['est', 'suis', 'es', 'sommes'],
                answer: 0,
                explanation: 'il/elle est — correct conjugation of "être".',
              },
              {
                id: 'a2-u3-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'The correct form is "suis".',
              },
              {
                id: 'a2-u3-l1-conj-1-1',
                type: 'conjugation',
                prompt: 'Conjugate "avoir" for "tu":',
                promptFr: 'tu _____',
                answer: 'as',
                acceptable: ['as'],
                explanation: 'tu as — correct form of "avoir".',
              },
              {
                id: 'a2-u3-l1-conj-1-2',
                type: 'multiple_choice',
                prompt: 'Complete: "nous _____" with the correct form of "avoir".',
                options: ['avons', 'ai', 'as', 'a'],
                answer: 0,
                explanation: 'nous avons — correct conjugation of "avoir".',
              },
              {
                id: 'a2-u3-l1-conj-1-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Tu _____ vingt ans." (You are twenty.) — form of "avoir"',
                answer: 'as',
                acceptable: ['as'],
                explanation: 'The correct form is "as".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Médecin', fr: 'Bonjour, qu\'est-ce qui ne va pas ?', en: 'Hello, what\'s wrong?' },
            { speaker: 'B', name: 'Patient', fr: 'Bonjour, docteur. J\'ai mal à la gorge et j\'ai de la fièvre depuis deux jours.', en: 'Hello, doctor. My throat hurts and I\'ve had a fever for two days.' },
            { speaker: 'A', name: 'Médecin', fr: 'Vous avez aussi de la toux ?', en: 'Do you also have a cough?' },
            { speaker: 'B', name: 'Patient', fr: 'Oui, une toux sèche. Et j\'ai mal à la tête.', en: 'Yes, a dry cough. And I have a headache.' },
            { speaker: 'A', name: 'Médecin', fr: 'C\'est probablement un rhume. Vous devez vous reposer pendant trois jours.', en: 'It\'s probably a cold. You must rest for three days.' },
            { speaker: 'B', name: 'Patient', fr: 'Je dois prendre des médicaments ?', en: 'Should I take medicine?' },
            { speaker: 'A', name: 'Médecin', fr: 'Oui, prenez ce sirop deux fois par jour. Et buvez beaucoup d\'eau.', en: 'Yes, take this syrup twice a day. And drink plenty of water.' },
            { speaker: 'B', name: 'Patient', fr: 'Merci, docteur. Au revoir.', en: 'Thank you, doctor. Goodbye.' },
          ],
          exercises: [
            {
              id: 'a2-u3-l1-e1',
              type: 'multiple_choice',
              prompt: 'How do you say "I have a headache"?',
              options: ['J\'ai mal au ventre', 'J\'ai mal à la tête', 'J\'ai mal au dos', 'Je suis malade'],
              answer: 1,
              explanation: 'Avoir mal à la tête = to have a headache. Tête is feminine → à la.',
            },
            {
              id: 'a2-u3-l1-e2',
              type: 'fill_blank',
              prompt: 'Complete: "Tu _____ voir un médecin." (You must see a doctor.)',
              answer: 'dois',
              explanation: 'Tu + dois + infinitive: tu dois voir.',
            },
            {
              id: 'a2-u3-l1-e3',
              type: 'multiple_choice',
              prompt: 'Which body part is "le ventre"?',
              options: ['The head', 'The stomach', 'The back', 'The throat'],
              answer: 1,
              explanation: 'Le ventre = the stomach/belly. J\'ai mal au ventre = stomach ache.',
            },
            {
              id: 'a2-u3-l1-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "I have a fever."',
              answer: 'J\'ai de la fièvre',
              acceptable: ['j ai de la fièvre'],
              explanation: 'Avoir + de la (partitive) + fièvre.',
            },
            {
              id: 'a2-u3-l1-e5',
              type: 'true_false',
              prompt: '"Devoir" can express advice or obligation.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. Tu dois (you must) is stronger; tu devrais (you should) is softer advice.',
            },
          ],
          culturalNote:
            "In France, healthcare is largely public and very affordable. The 'Sécurité Sociale' covers about 70% of medical costs, and most people have 'mutuelle' insurance for the rest. A standard doctor visit (consultation) costs 25€. The emergency number for medical help is 15 (SAMU).",
          estimatedMinutes: 30,
        },
      ],
    },
    {
      id: 'a2-u4',
      title: 'Housing and Home',
      titleFr: 'Logement',
      theme: 'House, furniture & pronouns',
      description: 'Describe your home, talk about rooms and furniture, and use direct object pronouns.',
      lessons: [
        {
          id: 'a2-u4-l1',
          title: 'Describing Your Home',
          titleFr: 'Décrire sa maison',
          description: 'Name rooms and furniture, use direct object pronouns (le, la, les).',
          objectives: [
            'Name rooms (chambre, cuisine, salon)',
            'Describe furniture',
            'Use direct object pronouns (le, la, les)',
            'Talk about where you live',
          ],
          vocabulary: [
            { fr: 'la maison', en: 'the house', example: 'J\'habite dans une maison.', exampleEn: 'I live in a house.', category: 'housing' },
            { fr: 'l\'appartement', en: 'the apartment', example: 'Mon appartement est petit.', exampleEn: 'My apartment is small.', category: 'housing' },
            { fr: 'la chambre', en: 'the bedroom', example: 'Ma chambre est à l\'étage.', exampleEn: 'My bedroom is upstairs.', category: 'rooms' },
            { fr: 'la cuisine', en: 'the kitchen', example: 'La cuisine est grande.', exampleEn: 'The kitchen is big.', category: 'rooms' },
            { fr: 'le salon', en: 'the living room', example: 'Nous mangeons dans le salon.', exampleEn: 'We eat in the living room.', category: 'rooms' },
            { fr: 'la salle de bain', en: 'the bathroom', example: 'La salle de bain a une baignoire.', exampleEn: 'The bathroom has a bathtub.', category: 'rooms' },
            { fr: 'les toilettes', en: 'the toilet(s)', example: 'Où sont les toilettes ?', exampleEn: 'Where are the toilets?', category: 'rooms' },
            { fr: 'le lit', en: 'the bed', example: 'Mon lit est confortable.', exampleEn: 'My bed is comfortable.', category: 'furniture' },
            { fr: 'la table', en: 'the table', example: 'La table est en bois.', exampleEn: 'The table is wooden.', category: 'furniture' },
            { fr: 'le canapé', en: 'the sofa', example: 'Le canapé est gris.', exampleEn: 'The sofa is grey.', category: 'furniture' },
            { fr: 'l\'armoire', en: 'the wardrobe', example: 'Mes vêtements sont dans l\'armoire.', exampleEn: 'My clothes are in the wardrobe.', category: 'furniture' },
            { fr: 'le balcon', en: 'the balcony', example: 'J\'ai des plantes sur le balcon.', exampleEn: 'I have plants on the balcony.', category: 'housing' },
          ],
          grammar: [
            {
              title: 'Direct object pronouns — le, la, les',
              explanation:
                "Direct object pronouns replace a direct object (a noun that receives the action directly). They go BEFORE the verb. 'le' = him/it (m), 'la' = her/it (f), 'les' = them.",
              examples: [
                { fr: 'Je vois le chat. → Je le vois.', en: 'I see the cat. → I see it.' },
                { fr: 'Je vois la table. → Je la vois.', en: 'I see the table. → I see it.' },
                { fr: 'Je vois les livres. → Je les vois.', en: 'I see the books. → I see them.' },
                { fr: 'Tu aimes Marie ? → Oui, je l\'aime.', en: 'You like Marie? → Yes, I like her.' },
              ],
              table: {
                caption: 'Direct object pronouns',
                headers: ['Person', 'Pronoun'],
                rows: [
                  ['me', 'me / m\''],
                  ['you', 'te / t\''],
                  ['him/it (m)', 'le / l\''],
                  ['her/it (f)', 'la / l\''],
                  ['us', 'nous'],
                  ['you (formal/pl)', 'vous'],
                  ['them', 'les'],
                ],
              },
              tip: 'Before a vowel, le/la become l\': Je l\'aime (I love him/her).',
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'être',
              translation: 'to be',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'suis' },
                { pronoun: 'tu', form: 'es' },
                { pronoun: 'il/elle', form: 'est' },
                { pronoun: 'nous', form: 'sommes' },
                { pronoun: 'vous', form: 'êtes' },
                { pronoun: 'ils/elles', form: 'sont' },
              ],
              sentenceRule: 'Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
              sentenceExamples: [
                { fr: 'Je suis étudiant.', en: 'I am a student.' },
                { fr: 'Tu es français ?', en: 'Are you French?' },
                { fr: 'Nous sommes à Paris.', en: 'We are in Paris.' },
              ],
            }
            ],
            practice: [
              {
                id: 'a2-u4-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "être" for "je":',
                promptFr: 'je _____',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'je suis — correct form of "être".',
              },
              {
                id: 'a2-u4-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "être".',
                options: ['est', 'suis', 'es', 'sommes'],
                answer: 0,
                explanation: 'il/elle est — correct conjugation of "être".',
              },
              {
                id: 'a2-u4-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'The correct form is "suis".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Sophie', fr: 'Tu habites où maintenant, Marc ?', en: 'Where do you live now, Marc?' },
            { speaker: 'B', name: 'Marc', fr: 'J\'habite dans un appartement à Lyon. Il a trois pièces.', en: 'I live in an apartment in Lyon. It has three rooms.' },
            { speaker: 'A', name: 'Sophie', fr: 'C\'est grand ? Tu as un balcon ?', en: 'Is it big? Do you have a balcony?' },
            { speaker: 'B', name: 'Marc', fr: 'Oui, j\'ai un balcon avec une belle vue. Et j\'ai un grand salon avec un canapé confortable.', en: 'Yes, I have a balcony with a nice view. And I have a big living room with a comfortable sofa.' },
            { speaker: 'A', name: 'Sophie', fr: 'Tu l\'aimes, ton appartement ?', en: 'Do you like your apartment?' },
            { speaker: 'B', name: 'Marc', fr: 'Oui, je l\'adore ! Et toi, tu habites toujours dans ta maison ?', en: 'Yes, I love it! And you, do you still live in your house?' },
            { speaker: 'A', name: 'Sophie', fr: 'Oui, on l\'aime beaucoup. Mais on voudrait une plus grande chambre pour les enfants.', en: 'Yes, we like it a lot. But we\'d like a bigger bedroom for the kids.' },
          ],
          exercises: [
            {
              id: 'a2-u4-l1-e1',
              type: 'multiple_choice',
              prompt: 'Replace the object: "Je vois Marie." → "Je _____ vois."',
              options: ['le', 'la', 'les', 'lui'],
              answer: 1,
              explanation: 'Marie is feminine singular → la. Je la vois.',
            },
            {
              id: 'a2-u4-l1-e2',
              type: 'fill_blank',
              prompt: 'Complete: "Tu aimes les livres ? Oui, je _____ aime."',
              answer: 'les',
              explanation: 'Livres is plural → les. Je les aime.',
            },
            {
              id: 'a2-u4-l1-e3',
              type: 'multiple_choice',
              prompt: 'Where do direct object pronouns go in French?',
              options: ['After the verb', 'Before the verb', 'At the end', 'They don\'t exist'],
              answer: 1,
              explanation: 'In French, direct object pronouns go BEFORE the verb: Je le vois (not Je vois le).',
            },
            {
              id: 'a2-u4-l1-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "I love it." (referring to "le livre", masculine)',
              answer: 'Je l\'aime',
              acceptable: ['je l aime', 'je laime'],
              explanation: 'Le livre → le → l\' (before vowel of aimer). Je l\'aime.',
            },
            {
              id: 'a2-u4-l1-e5',
              type: 'true_false',
              prompt: 'In French, direct object pronouns are placed before the conjugated verb.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. Je le vois = I see him/it. (Pronoun before verb.)',
            },
          ],
          culturalNote:
            "In French cities, most people live in apartments, not houses. The typical French apartment has a 'salon' (living room), 'cuisine' (kitchen — often separate), 'chambres' (bedrooms), and 'salle de bain' (bathroom). The toilets ('les WC') are often in a separate tiny room! Rent in Paris is among the highest in Europe.",
          estimatedMinutes: 30,
        },
      ],
    },
    {
      id: 'a2-u5',
      title: 'Food and Cooking',
      titleFr: 'Nourriture et cuisine',
      theme: 'Food vocabulary, recipes & pronouns Y/EN',
      description: 'Talk about food, follow a recipe, and use the pronouns y and en.',
      lessons: [
        {
          id: 'a2-u5-l1',
          title: 'In the Kitchen',
          titleFr: 'Dans la cuisine',
          description: 'Learn food vocabulary, kitchen verbs, and follow a simple recipe.',
          objectives: [
            'Name common foods (fruits, vegetables, meat, dairy)',
            'Use kitchen verbs (couper, mélanger, cuire)',
            'Follow a simple recipe in French',
            'Use the pronoun "en" for quantities',
          ],
          vocabulary: [
            { fr: 'la pomme', en: 'the apple', example: 'Je mange une pomme.', exampleEn: 'I eat an apple.', category: 'fruits' },
            { fr: 'la banane', en: 'the banana', example: 'Une banane mûre.', exampleEn: 'A ripe banana.', category: 'fruits' },
            { fr: 'l\'orange', en: 'the orange', example: 'Un jus d\'orange.', exampleEn: 'An orange juice.', category: 'fruits' },
            { fr: 'la fraise', en: 'the strawberry', example: 'Des fraises avec de la crème.', exampleEn: 'Strawberries with cream.', category: 'fruits' },
            { fr: 'le citron', en: 'the lemon', example: 'Un citron pressé.', exampleEn: 'A squeezed lemon.', category: 'fruits' },
            { fr: 'la tomate', en: 'the tomato', example: 'Une salade de tomates.', exampleEn: 'A tomato salad.', category: 'vegetables' },
            { fr: 'la carotte', en: 'the carrot', example: 'Des carottes râpées.', exampleEn: 'Grated carrots.', category: 'vegetables' },
            { fr: 'la pomme de terre', en: 'the potato', example: 'Purée de pommes de terre.', exampleEn: 'Mashed potatoes.', category: 'vegetables' },
            { fr: "l'oignon", en: 'the onion', example: 'Coupez l\'oignon.', exampleEn: 'Cut the onion.', category: 'vegetables' },
            { fr: "l'ail", en: 'the garlic', example: 'Une gousse d\'ail.', exampleEn: 'A clove of garlic.', category: 'vegetables' },
            { fr: 'la salade', en: 'the salad / lettuce', example: 'Une salade verte.', exampleEn: 'A green salad.', category: 'vegetables' },
            { fr: 'le poulet', en: 'the chicken', example: 'Du poulet rôti.', exampleEn: 'Roast chicken.', category: 'meat' },
            { fr: 'le bœuf', en: 'the beef', example: 'Un steak de bœuf.', exampleEn: 'A beef steak.', category: 'meat' },
            { fr: 'le porc', en: 'the pork', example: 'Du porc grillé.', exampleEn: 'Grilled pork.', category: 'meat' },
            { fr: 'le poisson', en: 'the fish', example: 'Un poisson frais.', exampleEn: 'A fresh fish.', category: 'meat' },
            { fr: 'le fromage', en: 'the cheese', example: 'Un plateau de fromages.', exampleEn: 'A cheese platter.', category: 'dairy' },
            { fr: 'le lait', en: 'the milk', example: 'Un verre de lait.', exampleEn: 'A glass of milk.', category: 'dairy' },
            { fr: 'le beurre', en: 'the butter', example: 'Du beurre sur la tartine.', exampleEn: 'Butter on the bread.', category: 'dairy' },
            { fr: 'la crème', en: 'the cream', example: 'De la crème fraîche.', exampleEn: 'Fresh cream.', category: 'dairy' },
            { fr: 'les œufs', en: 'the eggs', example: 'Trois œufs.', exampleEn: 'Three eggs.', category: 'dairy' },
            { fr: 'couper', en: 'to cut', example: 'Coupez les tomates.', exampleEn: 'Cut the tomatoes.', category: 'verbs' },
            { fr: 'mélanger', en: 'to mix', example: 'Mélangez le sucre et la farine.', exampleEn: 'Mix the sugar and flour.', category: 'verbs' },
            { fr: 'cuire', en: 'to cook', example: 'Cuire au four 30 minutes.', exampleEn: 'Bake for 30 minutes.', category: 'verbs' },
            { fr: 'ajouter', en: 'to add', example: 'Ajoutez du sel.', exampleEn: 'Add some salt.', category: 'verbs' },
            { fr: 'verser', en: 'to pour', example: 'Versez le lait.', exampleEn: 'Pour the milk.', category: 'verbs' },
            { fr: 'la farine', en: 'the flour', example: 'De la farine pour le gâteau.', exampleEn: 'Flour for the cake.', category: 'pantry' },
            { fr: 'le sucre', en: 'the sugar', example: 'Du sucre dans le café.', exampleEn: 'Sugar in coffee.', category: 'pantry' },
            { fr: 'le sel', en: 'the salt', example: 'Une pincée de sel.', exampleEn: 'A pinch of salt.', category: 'pantry' },
            { fr: 'le poivre', en: 'the pepper', example: 'Du poivre noir.', exampleEn: 'Black pepper.', category: 'pantry' },
            { fr: "l'huile", en: 'the oil', example: "De l'huile d'olive.", exampleEn: 'Olive oil.', category: 'pantry' },
          ],
          grammar: [
            {
              title: 'The pronoun "en" — for quantities',
              explanation:
                "The pronoun 'en' replaces quantities and partitive articles. Use it to avoid repeating a noun. 'En' generally goes before the verb.",
              examples: [
                { fr: 'Tu veux du pain ? — Oui, j\'en veux.', en: 'Do you want bread? — Yes, I want some (of it).' },
                { fr: 'Tu as combien de pommes ? — J\'en ai trois.', en: 'How many apples do you have? — I have three (of them).' },
                { fr: 'Tu achètes du fromage ? — J\'en achète.', en: 'Are you buying cheese? — I\'m buying some.' },
              ],
              tip: '"En" replaces "du/de la/des + noun" or "number + de + noun". Always placed before the verb.',
            },
            {
              title: 'The pronoun "y" — for places',
              explanation:
                "The pronoun 'y' replaces a place introduced by 'à' (or another preposition of place). It means 'there' in English. It goes before the verb.",
              examples: [
                { fr: 'Tu vas à Paris ? — Oui, j\'y vais.', en: 'Are you going to Paris? — Yes, I\'m going there.' },
                { fr: 'Tu es chez toi ? — Oui, j\'y suis.', en: 'Are you at home? — Yes, I\'m there.' },
                { fr: 'Tu vas au musée ? — J\'y vais demain.', en: 'Are you going to the museum? — I\'m going there tomorrow.' },
              ],
              tip: 'Y replaces à + place. Always placed before the verb. Common in everyday conversation.',
            },
            {
              title: 'Imperative in recipes',
              explanation:
                "French recipes use the imperative mood — the verb without a subject. For -er verbs, drop the -s in the tu form: 'tu manges' → 'mange !' (eat!).",
              examples: [
                { fr: 'Coupez les tomates. (vous/both)', en: 'Cut the tomatoes.' },
                { fr: 'Ajoutez du sel. (vous/both)', en: 'Add salt.' },
                { fr: 'Mélange bien ! (tu, informal)', en: 'Mix well!' },
              ],
              tip: "Recipes typically use the 'vous' form of imperative (coupez, ajoutez, mélangez) — even for one person — because it sounds more formal/standard.",
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'aller',
              translation: 'to go',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'vais' },
                { pronoun: 'tu', form: 'vas' },
                { pronoun: 'il/elle', form: 'va' },
                { pronoun: 'nous', form: 'allons' },
                { pronoun: 'vous', form: 'allez' },
                { pronoun: 'ils/elles', form: 'vont' },
              ],
              sentenceRule: 'Subject + aller + preposition + place. à + le = au, à + les = aux. Also: aller + infinitive = near future (Je vais manger).',
              sentenceExamples: [
                { fr: 'Je vais au cinéma.', en: 'I go to the cinema.' },
                { fr: 'Nous allons à Paris.', en: 'We go to Paris.' },
                { fr: 'Je vais manger.', en: 'I am going to eat.' },
              ],
            },
            {
              infinitive: 'être',
              translation: 'to be',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'suis' },
                { pronoun: 'tu', form: 'es' },
                { pronoun: 'il/elle', form: 'est' },
                { pronoun: 'nous', form: 'sommes' },
                { pronoun: 'vous', form: 'êtes' },
                { pronoun: 'ils/elles', form: 'sont' },
              ],
              sentenceRule: 'Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
              sentenceExamples: [
                { fr: 'Je suis étudiant.', en: 'I am a student.' },
                { fr: 'Tu es français ?', en: 'Are you French?' },
                { fr: 'Nous sommes à Paris.', en: 'We are in Paris.' },
              ],
            }
            ],
            practice: [
              {
                id: 'a2-u5-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "aller" for "je":',
                promptFr: 'je _____',
                answer: 'vais',
                acceptable: ['vais'],
                explanation: 'je vais — correct form of "aller".',
              },
              {
                id: 'a2-u5-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "aller".',
                options: ['va', 'vais', 'vas', 'allons'],
                answer: 0,
                explanation: 'il/elle va — correct conjugation of "aller".',
              },
              {
                id: 'a2-u5-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Je _____ au cinéma." (I go to the cinema.) — form of "aller"',
                answer: 'vais',
                acceptable: ['vais'],
                explanation: 'The correct form is "vais".',
              },
              {
                id: 'a2-u5-l1-conj-1-1',
                type: 'conjugation',
                prompt: 'Conjugate "être" for "tu":',
                promptFr: 'tu _____',
                answer: 'es',
                acceptable: ['es'],
                explanation: 'tu es — correct form of "être".',
              },
              {
                id: 'a2-u5-l1-conj-1-2',
                type: 'multiple_choice',
                prompt: 'Complete: "nous _____" with the correct form of "être".',
                options: ['sommes', 'suis', 'es', 'est'],
                answer: 0,
                explanation: 'nous sommes — correct conjugation of "être".',
              },
              {
                id: 'a2-u5-l1-conj-1-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Tu _____ français ?" (Are you French?) — form of "être"',
                answer: 'es',
                acceptable: ['es'],
                explanation: 'The correct form is "es".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Marie', fr: 'Tu veux m\'aider à faire un gâteau ?', en: 'Do you want to help me make a cake?' },
            { speaker: 'B', name: 'Luc', fr: 'Bien sûr ! Qu\'est-ce qu\'on fait ?', en: 'Of course! What are we making?' },
            { speaker: 'A', name: 'Marie', fr: 'Un gâteau au chocolat. D\'abord, casse trois œufs dans un bol.', en: 'A chocolate cake. First, crack three eggs into a bowl.' },
            { speaker: 'B', name: 'Luc', fr: 'Ensuite ?', en: 'Then?' },
            { speaker: 'A', name: 'Marie', fr: 'Ajoute 100 grammes de sucre et mélange bien. Puis, ajoute la farine et le chocolat fondu.', en: 'Add 100 grams of sugar and mix well. Then, add the flour and melted chocolate.' },
            { speaker: 'B', name: 'Luc', fr: 'On cuit combien de temps ?', en: 'How long do we bake it?' },
            { speaker: 'A', name: 'Marie', fr: 'On cuit 30 minutes à 180 degrés. Tu veux goûter la pâte ?', en: 'We bake for 30 minutes at 180 degrees. Do you want to taste the batter?' },
            { speaker: 'B', name: 'Luc', fr: 'Oui, j\'en veux bien !', en: 'Yes, I want some! (using en)' },
          ],
          exercises: [
            {
              id: 'a2-u5-l1-e1',
              type: 'multiple_choice',
              prompt: 'Complete with the pronoun "en": "Tu veux du pain ? — Oui, j\'_____ veux."',
              options: ['y', 'en', 'le', 'la'],
              answer: 1,
              explanation: 'En replaces "du pain" (partitive + noun).',
            },
            {
              id: 'a2-u5-l1-e2',
              type: 'multiple_choice',
              prompt: 'Complete with "y": "Tu vas à Paris ? — Oui, j\'_____ vais."',
              options: ['y', 'en', 'le', 'y en'],
              answer: 0,
              explanation: 'Y replaces "à Paris" (place preposition + location).',
            },
            {
              id: 'a2-u5-l1-e3',
              type: 'fill_blank',
              prompt: 'Complete: "Tu as combien de pommes ? — J\'_____ ai trois."',
              answer: 'en',
              explanation: 'En replaces "de pommes" after a quantity.',
            },
            {
              id: 'a2-u5-l1-e4',
              type: 'matching',
              prompt: 'Match each food to its French name.',
              pairs: [
                { left: 'the apple', right: 'la pomme' },
                { left: 'the tomato', right: 'la tomate' },
                { left: 'the chicken', right: 'le poulet' },
                { left: 'the cheese', right: 'le fromage' },
                { left: 'the eggs', right: 'les œufs' },
                { left: 'the milk', right: 'le lait' },
              ],
              answer: {},
            },
            {
              id: 'a2-u5-l1-e5',
              type: 'true_false',
              prompt: '"En" is used to replace quantities and partitive articles.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. En replaces "du/de la/des + noun" or quantities.',
            },
            {
              id: 'a2-u5-l1-e6',
              type: 'translate_to_fr',
              prompt: 'Translate (using en): "I want some." (referring to "du fromage")',
              answer: "J'en veux",
              acceptable: ['j en veux'],
              explanation: 'En replaces "du fromage". J\'en veux = I want some.',
            },
            {
              id: 'a2-u5-l1-e7',
              type: 'multiple_choice',
              prompt: 'What does "Cuire au four" mean?',
              options: ['Cut the oven', 'Bake in the oven', 'Open the oven', 'Clean the oven'],
              answer: 1,
              explanation: 'Cuire = to cook. Au four = in the oven. So "bake in the oven".',
            },
          ],
          activities: [
            {
              id: 'a2-u5-l1-a1',
              type: 'word_bank',
              prompt: 'Build: "I eat an apple."',
              wordBank: ['Je', 'mange', 'une', 'pomme', 'la'],
              answer: 'Je mange une pomme',
              acceptable: ['je mange une pomme'],
              explanation: 'Standard subject + verb + article + noun.',
            },
            {
              id: 'a2-u5-l1-a2',
              type: 'dictation',
              prompt: 'Listen and type what you hear.',
              audioText: 'Ajoutez du sel et du poivre.',
              answer: 'Ajoutez du sel et du poivre.',
              acceptable: ['ajoutez du sel et du poivre'],
              explanation: 'A typical recipe instruction.',
            },
            {
              id: 'a2-u5-l1-a3',
              type: 'pronoun_replace',
              prompt: 'Replace the underlined noun with "en": "Tu veux _____du fromage_____ ?" → "Oui, j\'en veux." Question: replace "du fromage" with the pronoun.',
              answer: 'en',
              acceptable: ['en'],
              explanation: 'En replaces du fromage.',
            },
            {
              id: 'a2-u5-l1-a4',
              type: 'reorder',
              prompt: 'Reorder the recipe instruction: "sel / ajoutez / du"',
              words: ['Ajoutez', 'du', 'sel.'],
              answer: 'Ajoutez du sel.',
              acceptable: ['ajoutez du sel'],
              explanation: 'Imperative form: Ajoutez + du + sel.',
            },
            {
              id: 'a2-u5-l1-a5',
              type: 'matching',
              prompt: 'Match each kitchen verb to its English meaning.',
              pairs: [
                { left: 'couper', right: 'to cut' },
                { left: 'mélanger', right: 'to mix' },
                { left: 'cuire', right: 'to cook' },
                { left: 'ajouter', right: 'to add' },
                { left: 'verser', right: 'to pour' },
              ],
              answer: {},
            },
            {
              id: 'a2-u5-l1-a6',
              type: 'fill_blank',
              prompt: 'Complete with "en": "Tu achètes du pain ? — Oui, j\'_____ achète."',
              answer: 'en',
              explanation: 'En replaces "du pain".',
            },
          ],
          culturalNote:
            "French cuisine is famously listed as an Intangible Cultural Heritage by UNESCO. The traditional French meal has 4 courses: entrée (starter), plat principal (main dish), fromage (cheese), and dessert. The baguette is so important that French law defines what can be called a 'baguette de tradition française' — only flour, water, salt, and yeast, no additives. The average French person eats 30 kg of cheese per year — the highest in the world!",
          estimatedMinutes: 40,
        },
      ],
    },
    {
      id: 'a2-u6',
      title: 'Shopping and Clothing',
      titleFr: 'Les achats et les vêtements',
      theme: 'Clothing vocabulary, comparisons & shopping',
      description: 'Shop for clothes, ask for sizes, and use comparative and superlative forms.',
      lessons: [
        {
          id: 'a2-u6-l1',
          title: 'Buying Clothes',
          titleFr: 'Acheter des vêtements',
          description: 'Learn clothing vocabulary, ask for sizes, and use comparatives.',
          objectives: [
            'Name clothing items (chemise, pantalon, robe)',
            'Ask for sizes and colors',
            'Use comparatives (plus...que, moins...que, aussi...que)',
            'Use superlatives (le plus, le moins)',
          ],
          vocabulary: [
            { fr: 'le vêtement', en: 'the clothing item', example: 'Un vêtement chaud.', exampleEn: 'A warm clothing item.', category: 'clothing' },
            { fr: 'la chemise', en: 'the shirt', example: 'Une chemise blanche.', exampleEn: 'A white shirt.', category: 'clothing' },
            { fr: 'le pantalon', en: 'the pants', example: 'Un pantalon noir.', exampleEn: 'Black pants.', category: 'clothing' },
            { fr: 'la robe', en: 'the dress', example: 'Une robe rouge.', exampleEn: 'A red dress.', category: 'clothing' },
            { fr: 'la jupe', en: 'the skirt', example: 'Une jupe longue.', exampleEn: 'A long skirt.', category: 'clothing' },
            { fr: 'le pull', en: 'the sweater', example: 'Un pull en laine.', exampleEn: 'A wool sweater.', category: 'clothing' },
            { fr: 'le t-shirt', en: 'the t-shirt', example: 'Un t-shirt bleu.', exampleEn: 'A blue t-shirt.', category: 'clothing' },
            { fr: 'la veste', en: 'the jacket', example: 'Une veste en cuir.', exampleEn: 'A leather jacket.', category: 'clothing' },
            { fr: 'le manteau', en: 'the coat', example: 'Un manteau d\'hiver.', exampleEn: 'A winter coat.', category: 'clothing' },
            { fr: 'les chaussures', en: 'the shoes', example: 'Des chaussures noires.', exampleEn: 'Black shoes.', category: 'clothing' },
            { fr: 'les baskets', en: 'the sneakers', example: 'Des baskets blanches.', exampleEn: 'White sneakers.', category: 'clothing' },
            { fr: 'les chaussettes', en: 'the socks', example: 'Une paire de chaussettes.', exampleEn: 'A pair of socks.', category: 'clothing' },
            { fr: 'le chapeau', en: 'the hat', example: 'Un chapeau noir.', exampleEn: 'A black hat.', category: 'clothing' },
            { fr: 'les lunettes', en: 'the glasses', example: 'Des lunettes de soleil.', exampleEn: 'Sunglasses.', category: 'clothing' },
            { fr: 'la taille', en: 'the size (clothing)', example: 'Quelle est votre taille ?', exampleEn: 'What is your size?', category: 'shopping' },
            { fr: 'la pointure', en: 'the size (shoes)', example: 'Quelle est votre pointure ?', exampleEn: 'What is your shoe size?', category: 'shopping' },
            { fr: 'petit(e)', en: 'small', example: 'Une petite taille.', exampleEn: 'A small size.', category: 'sizes' },
            { fr: 'moyen(ne)', en: 'medium', example: 'Une taille moyenne.', exampleEn: 'A medium size.', category: 'sizes' },
            { fr: 'grand(e)', en: 'large / big', example: 'Une grande taille.', exampleEn: 'A large size.', category: 'sizes' },
            { fr: 'essayer', en: 'to try on', example: 'Je voudrais essayer.', exampleEn: 'I would like to try on.', category: 'verbs' },
            { fr: 'ça va', en: 'it fits', example: 'Ça va, cette chemise ?', exampleEn: 'Does this shirt fit?', category: 'shopping' },
            { fr: 'ça ne va pas', en: 'it doesn\'t fit', example: 'Ça ne va pas.', exampleEn: 'It doesn\'t fit.', category: 'shopping' },
            { fr: 'trop petit', en: 'too small', example: 'C\'est trop petit.', exampleEn: 'It\'s too small.', category: 'sizes' },
            { fr: 'trop grand', en: 'too big', example: 'C\'est trop grand.', exampleEn: 'It\'s too big.', category: 'sizes' },
            { fr: 'rouge', en: 'red', example: 'Une robe rouge.', exampleEn: 'A red dress.', category: 'colors' },
            { fr: 'bleu(e)', en: 'blue', example: 'Un t-shirt bleu.', exampleEn: 'A blue t-shirt.', category: 'colors' },
            { fr: 'vert(e)', en: 'green', example: 'Une veste verte.', exampleEn: 'A green jacket.', category: 'colors' },
            { fr: 'noir(e)', en: 'black', example: 'Un pantalon noir.', exampleEn: 'Black pants.', category: 'colors' },
            { fr: 'blanc(he)', en: 'white', example: 'Une chemise blanche.', exampleEn: 'A white shirt.', category: 'colors' },
            { fr: 'jaune', en: 'yellow', example: 'Un pull jaune.', exampleEn: 'A yellow sweater.', category: 'colors' },
          ],
          grammar: [
            {
              title: 'Comparatives — plus / moins / aussi...que',
              explanation:
                "To compare two things in French, use 'plus...que' (more...than), 'moins...que' (less...than), or 'aussi...que' (as...as). The adjective goes between plus/moins/aussi and que.",
              examples: [
                { fr: 'Cette robe est plus chère que celle-ci.', en: 'This dress is more expensive than this one.' },
                { fr: 'Ce pantalon est moins cher que l\'autre.', en: 'These pants are less expensive than the other.' },
                { fr: 'Cette chemise est aussi belle que celle-là.', en: 'This shirt is as beautiful as that one.' },
              ],
              tip: "The adjective agrees in gender/number with the noun it describes: cher → chère (f), chers (m pl), chères (f pl).",
            },
            {
              title: 'Superlatives — le plus / le moins',
              explanation:
                "For the superlative (the most, the least), use 'le/la/les plus' or 'le/la/les moins' before the adjective.",
              examples: [
                { fr: 'C\'est la plus belle robe.', en: 'It\'s the most beautiful dress.' },
                { fr: 'C\'est le moins cher.', en: 'It\'s the least expensive.' },
                { fr: 'Ce sont les meilleures chaussures.', en: 'These are the best shoes. (bon → meilleur, irregular)' },
              ],
              tip: 'Good → meilleur (better), best → le meilleur. Bad → pire (worse), worst → le pire. These are irregular.',
            },
            {
              title: 'Demonstrative adjectives — ce, cet, cette, ces',
              explanation:
                "Demonstrative adjectives point out specific things: 'this/that/these/those'. Use 'ce' for masculine singular, 'cet' for masculine singular before a vowel, 'cette' for feminine singular, 'ces' for plural (both genders).",
              examples: [
                { fr: 'ce pull (m)', en: 'this sweater' },
                { fr: 'cet imperméable (m, vowel)', en: 'this raincoat' },
                { fr: 'cette robe (f)', en: 'this dress' },
                { fr: 'ces chaussures (pl)', en: 'these shoes' },
              ],
              table: {
                caption: 'Demonstrative adjectives',
                headers: ['Gender', 'Singular', 'Plural'],
                rows: [
                  ['Masculine', 'ce / cet (before vowel)', 'ces'],
                  ['Feminine', 'cette', 'ces'],
                ],
              },
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'avoir',
              translation: 'to have',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'j\'', form: 'ai' },
                { pronoun: 'tu', form: 'as' },
                { pronoun: 'il/elle', form: 'a' },
                { pronoun: 'nous', form: 'avons' },
                { pronoun: 'vous', form: 'avez' },
                { pronoun: 'ils/elles', form: 'ont' },
              ],
              sentenceRule: 'Subject + avoir + noun. Used for possession, age (J\'ai 20 ans), and expressions like avoir faim/soif/froid. Age uses avoir, NOT être.',
              sentenceExamples: [
                { fr: 'J\'ai un frère.', en: 'I have a brother.' },
                { fr: 'Tu as vingt ans.', en: 'You are twenty.' },
                { fr: 'Il a faim.', en: 'He is hungry.' },
              ],
            },
            {
              infinitive: 'être',
              translation: 'to be',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'suis' },
                { pronoun: 'tu', form: 'es' },
                { pronoun: 'il/elle', form: 'est' },
                { pronoun: 'nous', form: 'sommes' },
                { pronoun: 'vous', form: 'êtes' },
                { pronoun: 'ils/elles', form: 'sont' },
              ],
              sentenceRule: 'Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
              sentenceExamples: [
                { fr: 'Je suis étudiant.', en: 'I am a student.' },
                { fr: 'Tu es français ?', en: 'Are you French?' },
                { fr: 'Nous sommes à Paris.', en: 'We are in Paris.' },
              ],
            },
            {
              infinitive: 'aller',
              translation: 'to go',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'vais' },
                { pronoun: 'tu', form: 'vas' },
                { pronoun: 'il/elle', form: 'va' },
                { pronoun: 'nous', form: 'allons' },
                { pronoun: 'vous', form: 'allez' },
                { pronoun: 'ils/elles', form: 'vont' },
              ],
              sentenceRule: 'Subject + aller + preposition + place. à + le = au, à + les = aux. Also: aller + infinitive = near future (Je vais manger).',
              sentenceExamples: [
                { fr: 'Je vais au cinéma.', en: 'I go to the cinema.' },
                { fr: 'Nous allons à Paris.', en: 'We go to Paris.' },
                { fr: 'Je vais manger.', en: 'I am going to eat.' },
              ],
            }
            ],
            practice: [
              {
                id: 'a2-u6-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "avoir" for "j\'":',
                promptFr: 'j\' _____',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'j\' ai — correct form of "avoir".',
              },
              {
                id: 'a2-u6-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "avoir".',
                options: ['a', 'ai', 'as', 'avons'],
                answer: 0,
                explanation: 'il/elle a — correct conjugation of "avoir".',
              },
              {
                id: 'a2-u6-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "J\'_____ un frère." (I have a brother.) — form of "avoir"',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'The correct form is "ai".',
              },
              {
                id: 'a2-u6-l1-conj-1-1',
                type: 'conjugation',
                prompt: 'Conjugate "être" for "tu":',
                promptFr: 'tu _____',
                answer: 'es',
                acceptable: ['es'],
                explanation: 'tu es — correct form of "être".',
              },
              {
                id: 'a2-u6-l1-conj-1-2',
                type: 'multiple_choice',
                prompt: 'Complete: "nous _____" with the correct form of "être".',
                options: ['sommes', 'suis', 'es', 'est'],
                answer: 0,
                explanation: 'nous sommes — correct conjugation of "être".',
              },
              {
                id: 'a2-u6-l1-conj-1-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Tu _____ français ?" (Are you French?) — form of "être"',
                answer: 'es',
                acceptable: ['es'],
                explanation: 'The correct form is "es".',
              },
              {
                id: 'a2-u6-l1-conj-2-1',
                type: 'conjugation',
                prompt: 'Conjugate "aller" for "il/elle":',
                promptFr: 'il/elle _____',
                answer: 'va',
                acceptable: ['va'],
                explanation: 'il/elle va — correct form of "aller".',
              },
              {
                id: 'a2-u6-l1-conj-2-2',
                type: 'multiple_choice',
                prompt: 'Complete: "vous _____" with the correct form of "aller".',
                options: ['allez', 'vais', 'vas', 'va'],
                answer: 0,
                explanation: 'vous allez — correct conjugation of "aller".',
              },
              {
                id: 'a2-u6-l1-conj-2-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Je _____ manger." (I am going to eat.) — form of "aller"',
                answer: 'vais',
                acceptable: ['vais'],
                explanation: 'The correct form is "vais".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Vendeur', fr: 'Bonjour, je peux vous aider ?', en: 'Hello, can I help you?' },
            { speaker: 'B', name: 'Cliente', fr: 'Oui, je cherche une chemise blanche.', en: 'Yes, I\'m looking for a white shirt.' },
            { speaker: 'A', name: 'Vendeur', fr: 'Quelle taille ?', en: 'What size?' },
            { speaker: 'B', name: 'Cliente', fr: 'Taille M. Et je voudrais essayer.', en: 'Size M. And I\'d like to try it on.' },
            { speaker: 'A', name: 'Vendeur', fr: 'Voici. La cabine est par là.', en: 'Here you go. The fitting room is over there.' },
            { speaker: 'B', name: 'Cliente', fr: 'Cette chemise est trop petite. Vous avez une taille plus grande ?', en: 'This shirt is too small. Do you have a bigger size?' },
            { speaker: 'A', name: 'Vendeur', fr: 'Oui, voici la taille L. C\'est la plus grande que nous avons.', en: 'Yes, here\'s size L. It\'s the largest we have.' },
            { speaker: 'B', name: 'Cliente', fr: 'Parfait, elle me va. Combien ça coûte ?', en: 'Perfect, it fits me. How much does it cost?' },
          ],
          exercises: [
            {
              id: 'a2-u6-l1-e1',
              type: 'multiple_choice',
              prompt: 'Complete: "Cette robe est _____ chère que celle-ci." (more expensive)',
              options: ['plus', 'moins', 'aussi', 'très'],
              answer: 0,
              explanation: 'Plus...que = more...than.',
            },
            {
              id: 'a2-u6-l1-e2',
              type: 'fill_blank',
              prompt: 'Complete: "Ce pantalon est _____ cher que l\'autre." (less expensive)',
              answer: 'moins',
              explanation: 'Moins...que = less...than.',
            },
            {
              id: 'a2-u6-l1-e3',
              type: 'multiple_choice',
              prompt: 'Which demonstrative: "_____ robe" (this dress, feminine)?',
              options: ['ce', 'cet', 'cette', 'ces'],
              answer: 2,
              explanation: 'Robe is feminine singular → cette.',
            },
            {
              id: 'a2-u6-l1-e4',
              type: 'multiple_choice',
              prompt: 'Which demonstrative: "_____ imperméable" (this raincoat, masculine starting with vowel)?',
              options: ['ce', 'cet', 'cette', 'ces'],
              answer: 1,
              explanation: 'Before a vowel, ce becomes cet (even for masculine).',
            },
            {
              id: 'a2-u6-l1-e5',
              type: 'true_false',
              prompt: '"Le meilleur" means "the best".',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. Bon → meilleur (better), le meilleur (the best) — irregular comparative/superlative.',
            },
            {
              id: 'a2-u6-l1-e6',
              type: 'matching',
              prompt: 'Match each clothing item to its French name.',
              pairs: [
                { left: 'the shirt', right: 'la chemise' },
                { left: 'the pants', right: 'le pantalon' },
                { left: 'the dress', right: 'la robe' },
                { left: 'the sweater', right: 'le pull' },
                { left: 'the shoes', right: 'les chaussures' },
                { left: 'the coat', right: 'le manteau' },
              ],
              answer: {},
            },
            {
              id: 'a2-u6-l1-e7',
              type: 'translate_to_fr',
              prompt: 'Translate: "It\'s too small."',
              answer: "C'est trop petit",
              acceptable: ['c est trop petit', 'c est trop petit'],
              explanation: 'C\'est + trop + petit (masculine adjective).',
            },
          ],
          activities: [
            {
              id: 'a2-u6-l1-a1',
              type: 'word_bank',
              prompt: 'Build: "I am looking for a white shirt."',
              wordBank: ['Je', 'cherche', 'une', 'chemise', 'blanche', 'noir'],
              answer: 'Je cherche une chemise blanche',
              acceptable: ['je cherche une chemise blanche'],
              explanation: 'Chercher = to look for. Blanche agrees with chemise (f).',
            },
            {
              id: 'a2-u6-l1-a2',
              type: 'dictation',
              prompt: 'Listen and type what you hear.',
              audioText: 'Cette chemise est trop petite.',
              answer: 'Cette chemise est trop petite.',
              acceptable: ['cette chemise est trop petite'],
              explanation: 'A common fitting-room comment.',
            },
            {
              id: 'a2-u6-l1-a3',
              type: 'transformation',
              prompt: 'Make comparative: "Cette robe est belle." → "Cette robe est _____ belle _____ l\'autre." (as beautiful as)',
              answer: 'aussi, que',
              acceptable: ['aussi que', 'aussi,que'],
              explanation: 'aussi...que = as...as.',
            },
            {
              id: 'a2-u6-l1-a4',
              type: 'fill_blank',
              prompt: 'Complete: "C\'est _____ plus belle robe du magasin." (the most beautiful dress)',
              answer: 'la',
              explanation: 'Superlative: la plus belle (la + plus + adjective).',
            },
            {
              id: 'a2-u6-l1-a5',
              type: 'matching',
              prompt: 'Match each color to its French name.',
              pairs: [
                { left: 'red', right: 'rouge' },
                { left: 'blue', right: 'bleu' },
                { left: 'green', right: 'vert' },
                { left: 'black', right: 'noir' },
                { left: 'white', right: 'blanc' },
                { left: 'yellow', right: 'jaune' },
              ],
              answer: {},
            },
            {
              id: 'a2-u6-l1-a6',
              type: 'reorder',
              prompt: 'Reorder: "vous / quelle / taille / ?"',
              words: ['Quelle', 'taille', 'êtes-vous', '?'],
              answer: 'Quelle taille êtes-vous ?',
              acceptable: ['quelle taille êtes-vous'],
              explanation: 'Actually the more common form is "Quelle est votre taille ?"',
            },
          ],
          culturalNote:
            "French fashion is world-famous — Paris is one of the fashion capitals of the world along with Milan, London, and New York. Famous French brands include Chanel, Dior, Louis Vuitton, Hermès, and Saint Laurent. The French 'soldes' (sales) happen twice a year — in January-February and June-July — by law. Outside of these periods, shops cannot discount items as much. This is unique to France!",
          estimatedMinutes: 40,
        },
      ],
    },
  ],
};
