import type { Course } from './types';

// B1 — Intermediate French (CEFR B1)
// Focuses on arguments, abstract concepts, media, debates
export const b1Course: Course = {
  level: 'B1',
  title: 'B1 — Intermédiaire',
  book: 'Parlez B1',
  description:
    "Step into the intermediate level. You'll learn to express opinions, defend arguments, use the subjunctive and conditional, and engage with real-world French media — news, debates, films, and literature.",
  cefrDescription:
    'Can understand the main points of clear standard input on familiar matters regularly encountered in work, school, leisure, etc. Can deal with most situations likely to arise while traveling. Can produce simple connected text on topics that are familiar or of personal interest.',
  color: '#B45309',
  units: [
    {
      id: 'b1-u1',
      title: 'Opinions and Arguments',
      titleFr: 'Opinions et arguments',
      theme: 'Expressing opinions & logical connectors',
      description: 'Express nuanced opinions, agree and disagree, and use logical connectors.',
      lessons: [
        {
          id: 'b1-u1-l1',
          title: 'Expressing Your Opinion',
          titleFr: 'Exprimer son opinion',
          description: 'Use structures like "à mon avis", "je pense que", "il me semble que" to express opinions.',
          objectives: [
            'Express opinions formally and informally',
            'Agree and disagree politely',
            'Use logical connectors (cependant, néanmoins, en revanche)',
            'Structure a short argument',
          ],
          vocabulary: [
            { fr: 'à mon avis', en: 'in my opinion', example: 'À mon avis, il faut agir maintenant.', exampleEn: 'In my opinion, we must act now.', category: 'opinion' },
            { fr: 'je pense que', en: 'I think that', example: 'Je pense que c\'est une bonne idée.', exampleEn: 'I think it\'s a good idea.', category: 'opinion' },
            { fr: 'il me semble que', en: 'it seems to me that', example: 'Il me semble qu\'il a raison.', exampleEn: 'It seems to me he\'s right.', category: 'opinion' },
            { fr: 'selon moi', en: 'according to me', example: 'Selon moi, le projet est viable.', exampleEn: 'According to me, the project is viable.', category: 'opinion' },
            { fr: 'je suis d\'accord', en: 'I agree', example: 'Je suis d\'accord avec toi.', exampleEn: 'I agree with you.', category: 'agreement' },
            { fr: 'je ne suis pas d\'accord', en: 'I disagree', example: 'Je ne suis pas d\'accord.', exampleEn: 'I disagree.', category: 'agreement' },
            { fr: 'c\'est vrai que', en: 'it\'s true that', example: 'C\'est vrai que c\'est difficile.', exampleEn: 'It\'s true that it\'s difficult.', category: 'agreement' },
            { fr: 'cependant', en: 'however', example: 'C\'est cher, cependant c\'est de qualité.', exampleEn: 'It\'s expensive, however it\'s quality.', category: 'connectors' },
            { fr: 'néanmoins', en: 'nevertheless', example: 'Il pleut ; néanmoins, je sors.', exampleEn: 'It\'s raining; nevertheless, I\'m going out.', category: 'connectors' },
            { fr: 'en revanche', en: 'on the other hand', example: 'Il est intelligent ; en revanche, il est paresseux.', exampleEn: 'He\'s smart; on the other hand, he\'s lazy.', category: 'connectors' },
            { fr: 'par conséquent', en: 'consequently', example: 'Il a neigé ; par conséquent, les routes sont fermées.', exampleEn: 'It snowed; consequently, roads are closed.', category: 'connectors' },
            { fr: 'en effet', en: 'indeed / in fact', example: 'Il est fatigué. En effet, il a beaucoup travaillé.', exampleEn: 'He\'s tired. Indeed, he worked a lot.', category: 'connectors' },
          ],
          grammar: [
            {
              title: 'Structuring an argument',
              explanation:
                "A good argument in French follows a clear structure: introduce the topic, state your opinion, give reasons with examples, acknowledge the counter-argument, and conclude. Logical connectors help guide the reader/listener.",
              examples: [
                { fr: 'À mon avis, le télétravail est positif. D\'abord, il fait gagner du temps. Ensuite, il réduit le stress. Cependant, il peut isoler. En conclusion, c\'est un progrès si on garde du lien social.', en: 'In my opinion, remote work is positive. First, it saves time. Then, it reduces stress. However, it can isolate. In conclusion, it\'s progress if we keep social ties.' },
              ],
              table: {
                caption: 'Logical connectors by function',
                headers: ['Function', 'Connectors'],
                rows: [
                  ['Addition', 'de plus, en outre, par ailleurs'],
                  ['Opposition', 'cependant, néanmoins, en revanche, pourtant'],
                  ['Cause', 'parce que, car, en effet, puisque'],
                  ['Consequence', 'donc, par conséquent, c\'est pourquoi'],
                  ['Conclusion', 'en conclusion, pour conclure, finalement'],
                ],
              },
              tip: 'When you disagree, soften it: "Je comprends ton point de vue, mais..." (I understand your point, but...).',
            },
            {
              title: 'Il me semble que + indicatif ou subjonctif ?',
              explanation:
                "'Il me semble que' is followed by the indicative when expressing your own perception: 'Il me semble qu\'il est tard.' But 'Il ne me semble pas que' (negative) takes the subjunctive: 'Il ne me semble pas qu\'il soit tard.'",
              examples: [
                { fr: 'Il me semble qu\'il a raison.', en: 'It seems to me he\'s right.' },
                { fr: 'Il me semble qu\'elle vient.', en: 'It seems to me she\'s coming.' },
              ],
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'être',
              translation: 'to be',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'suis' },
                { pronoun: 'tu', form: 'es' },
                { pronoun: 'il/elle', form: 'est' },
                { pronoun: 'nous', form: 'sommes' },
                { pronoun: 'vous', form: 'êtes' },
                { pronoun: 'ils/elles', form: 'sont' },
              ],
              sentenceRule: 'Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
              sentenceExamples: [
                { fr: 'Je suis étudiant.', en: 'I am a student.' },
                { fr: 'Tu es français ?', en: 'Are you French?' },
                { fr: 'Nous sommes à Paris.', en: 'We are in Paris.' },
              ],
            },
            {
              infinitive: 'avoir',
              translation: 'to have',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'j\'', form: 'ai' },
                { pronoun: 'tu', form: 'as' },
                { pronoun: 'il/elle', form: 'a' },
                { pronoun: 'nous', form: 'avons' },
                { pronoun: 'vous', form: 'avez' },
                { pronoun: 'ils/elles', form: 'ont' },
              ],
              sentenceRule: 'Subject + avoir + noun. Used for possession, age (J\'ai 20 ans), and expressions like avoir faim/soif/froid. Age uses avoir, NOT être.',
              sentenceExamples: [
                { fr: 'J\'ai un frère.', en: 'I have a brother.' },
                { fr: 'Tu as vingt ans.', en: 'You are twenty.' },
                { fr: 'Il a faim.', en: 'He is hungry.' },
              ],
            }
            ],
            practice: [
              {
                id: 'b1-u1-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "être" for "je":',
                promptFr: 'je _____',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'je suis — correct form of "être".',
              },
              {
                id: 'b1-u1-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "être".',
                options: ['est', 'suis', 'es', 'sommes'],
                answer: 0,
                explanation: 'il/elle est — correct conjugation of "être".',
              },
              {
                id: 'b1-u1-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'The correct form is "suis".',
              },
              {
                id: 'b1-u1-l1-conj-1-1',
                type: 'conjugation',
                prompt: 'Conjugate "avoir" for "tu":',
                promptFr: 'tu _____',
                answer: 'as',
                acceptable: ['as'],
                explanation: 'tu as — correct form of "avoir".',
              },
              {
                id: 'b1-u1-l1-conj-1-2',
                type: 'multiple_choice',
                prompt: 'Complete: "nous _____" with the correct form of "avoir".',
                options: ['avons', 'ai', 'as', 'a'],
                answer: 0,
                explanation: 'nous avons — correct conjugation of "avoir".',
              },
              {
                id: 'b1-u1-l1-conj-1-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Tu _____ vingt ans." (You are twenty.) — form of "avoir"',
                answer: 'as',
                acceptable: ['as'],
                explanation: 'The correct form is "as".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Claire', fr: 'À mon avis, le télétravail devrait devenir la norme. Qu\'en penses-tu ?', en: 'In my opinion, remote work should become the norm. What do you think?' },
            { speaker: 'B', name: 'Antoine', fr: 'Je ne suis pas d\'accord. Selon moi, le présentiel favorise la créativité et le lien social.', en: 'I disagree. According to me, in-person work favors creativity and social ties.' },
            { speaker: 'A', name: 'Claire', fr: 'C\'est vrai que le contact humain est important. Cependant, le télétravail fait gagner énormément de temps de transport.', en: 'It\'s true that human contact is important. However, remote work saves a lot of commute time.' },
            { speaker: 'B', name: 'Antoine', fr: 'Je comprends ton point de vue. Néanmoins, beaucoup de personnes se sentent isolées chez elles.', en: 'I understand your point. Nevertheless, many people feel isolated at home.' },
            { speaker: 'A', name: 'Claire', fr: 'En effet, c\'est un risque. Par conséquent, le mieux serait un modèle hybride : deux jours à la maison, trois au bureau.', en: 'Indeed, that\'s a risk. Consequently, the best would be a hybrid model: two days at home, three at the office.' },
            { speaker: 'B', name: 'Antoine', fr: 'Là, je suis tout à fait d\'accord avec toi ! C\'est un compromis raisonnable.', en: 'There, I completely agree with you! It\'s a reasonable compromise.' },
          ],
          exercises: [
            {
              id: 'b1-u1-l1-e1',
              type: 'multiple_choice',
              prompt: 'Which expression means "in my opinion"?',
              options: ['En effet', 'À mon avis', 'Par conséquent', 'En revanche'],
              answer: 1,
              explanation: 'À mon avis = in my opinion. Other options: en effet (indeed), par conséquent (consequently), en revanche (on the other hand).',
            },
            {
              id: 'b1-u1-l1-e2',
              type: 'fill_blank',
              prompt: 'Complete: "Il pleut ; _____, je prends mon parapluie." (therefore)',
              answer: 'par conséquent',
              acceptable: ['donc', 'par consequent'],
              explanation: 'Par conséquent = consequently/therefore. "Donc" also works.',
            },
            {
              id: 'b1-u1-l1-e3',
              type: 'multiple_choice',
              prompt: 'Which connector expresses opposition?',
              options: ['De plus', 'Ensuite', 'Cependant', 'Donc'],
              answer: 2,
              explanation: 'Cependant = however. De plus (addition), Ensuite (sequence), Donc (consequence).',
            },
            {
              id: 'b1-u1-l1-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "However, I disagree."',
              answer: 'Cependant, je ne suis pas d\'accord',
              acceptable: ['néanmoins je ne suis pas d accord', 'cependant je ne suis pas d accord'],
              explanation: 'Cependant / néanmoins / en revanche = however. Je ne suis pas d\'accord = I disagree.',
            },
            {
              id: 'b1-u1-l1-e5',
              type: 'true_false',
              prompt: '"En revanche" is used to introduce an opposing idea.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. En revanche = on the other hand / however.',
            },
          ],
          culturalNote:
            "The French love debate ('le débat'). It is a national sport — discussions about politics, philosophy, food, or cinema can last hours. The French school system trains students in 'la dissertation' (structured essay with thesis, antithesis, synthesis) from age 15. Don't be surprised if a casual dinner turns into a passionate debate!",
          estimatedMinutes: 35,
        },
        {
          id: 'b1-u1-l2',
          title: 'The Subjunctive Mood',
          titleFr: 'Le subjonctif présent',
          description: 'Learn when and how to use the subjunctive — essential for expressing doubt, emotion, and necessity.',
          objectives: [
            'Form the present subjunctive of regular verbs',
            'Recognize common irregular subjunctives',
            'Use the subjunctive after expressions of necessity',
            'Use the subjunctive after expressions of emotion',
          ],
          vocabulary: [
            { fr: 'il faut que', en: 'it is necessary that', example: 'Il faut que tu viennes.', exampleEn: 'It\'s necessary that you come.', category: 'subjunctive triggers' },
            { fr: 'je veux que', en: 'I want that', example: 'Je veux que tu saches la vérité.', exampleEn: 'I want you to know the truth.', category: 'subjunctive triggers' },
            { fr: 'j\'ai peur que', en: 'I\'m afraid that', example: 'J\'ai peur qu\'il soit en retard.', exampleEn: 'I\'m afraid he\'s late.', category: 'subjunctive triggers' },
            { fr: 'je suis content que', en: 'I\'m happy that', example: 'Je suis content que tu sois là.', exampleEn: 'I\'m happy you\'re here.', category: 'subjunctive triggers' },
            { fr: 'bien que', en: 'although', example: 'Bien qu\'il soit fatigué, il travaille.', exampleEn: 'Although he\'s tired, he works.', category: 'subjunctive triggers' },
            { fr: 'pour que', en: 'so that', example: 'Je t\'explique pour que tu comprennes.', exampleEn: 'I explain so that you understand.', category: 'subjunctive triggers' },
            { fr: 'avant que', en: 'before', example: 'Avant qu\'il arrive, finis ton travail.', exampleEn: 'Before he arrives, finish your work.', category: 'subjunctive triggers' },
            { fr: 'sans que', en: 'without', example: 'Il est parti sans qu\'on le voie.', exampleEn: 'He left without anyone seeing him.', category: 'subjunctive triggers' },
            { fr: 'douter que', en: 'to doubt that', example: 'Je doute qu\'il vienne.', exampleEn: 'I doubt he\'ll come.', category: 'subjunctive triggers' },
            { fr: 'il est important que', en: 'it is important that', example: 'Il est important que nous parlions.', exampleEn: 'It\'s important that we speak.', category: 'subjunctive triggers' },
          ],
          grammar: [
            {
              title: 'Forming the present subjunctive',
              explanation:
                "Take the ils/elles form of the present indicative, drop the -ent ending, and add the subjunctive endings: -e, -es, -e, -ions, -iez, -ent. For -er verbs, the subjunctive looks identical to the present indicative (except nous and vous).",
              examples: [
                { fr: 'parler → ils parlent → parl- → que je parle', en: 'to speak → that I speak' },
                { fr: 'finir → ils finissent → finiss- → que je finisse', en: 'to finish → that I finish' },
                { fr: 'attendre → ils attendent → attend- → que j\'attende', en: 'to wait → that I wait' },
              ],
              table: {
                caption: 'Subjunctive endings',
                headers: ['Pronoun', 'Ending', 'parler', 'finir'],
                rows: [
                  ['que je', '-e', 'parle', 'finisse'],
                  ['que tu', '-es', 'parles', 'finisses'],
                  ['qu\'il/elle', '-e', 'parle', 'finisse'],
                  ['que nous', '-ions', 'parlions', 'finissions'],
                  ['que vous', '-iez', 'parliez', 'finissiez'],
                  ['qu\'ils/elles', '-ent', 'parlent', 'finissent'],
                ],
              },
              tip: 'The nous and vous forms are always different from the present indicative — they take -ions and -iez.',
            },
            {
              title: 'Common irregular subjunctives',
              explanation:
                "Some verbs have irregular subjunctive stems. The most common: être, avoir, aller, faire, pouvoir, savoir, vouloir.",
              examples: [
                { fr: 'être → que je sois, que tu sois, qu\'il soit...', en: 'that I am' },
                { fr: 'avoir → que j\'aie, que tu aies, qu\'il ait...', en: 'that I have' },
                { fr: 'faire → que je fasse, que tu fasses, qu\'il fasse...', en: 'that I do' },
                { fr: 'pouvoir → que je puisse, que tu puisses...', en: 'that I can' },
                { fr: 'savoir → que je sache, que tu saches...', en: 'that I know' },
              ],
              tip: 'For être, the stem is "soi-". For avoir, the stem is "ai-". These must be memorized.',
            },
            {
              title: 'When to use the subjunctive',
              explanation:
                "The subjunctive is used after expressions of: necessity (il faut que), wish/desire (je veux que), emotion (je suis content que), doubt (je doute que), and certain conjunctions (bien que, pour que, avant que). The subjunctive expresses subjectivity, not facts.",
              examples: [
                { fr: 'Il faut que tu partes maintenant.', en: 'You must leave now.' },
                { fr: 'Je suis ravi que vous soyez venus.', en: 'I\'m delighted that you came.' },
                { fr: 'Bien qu\'il soit malade, il travaille.', en: 'Although he\'s sick, he works.' },
              ],
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'avoir',
              translation: 'to have',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'j\'', form: 'ai' },
                { pronoun: 'tu', form: 'as' },
                { pronoun: 'il/elle', form: 'a' },
                { pronoun: 'nous', form: 'avons' },
                { pronoun: 'vous', form: 'avez' },
                { pronoun: 'ils/elles', form: 'ont' },
              ],
              sentenceRule: 'Subject + avoir + noun. Used for possession, age (J\'ai 20 ans), and expressions like avoir faim/soif/froid. Age uses avoir, NOT être.',
              sentenceExamples: [
                { fr: 'J\'ai un frère.', en: 'I have a brother.' },
                { fr: 'Tu as vingt ans.', en: 'You are twenty.' },
                { fr: 'Il a faim.', en: 'He is hungry.' },
              ],
            }
            ],
            practice: [
              {
                id: 'b1-u1-l2-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "avoir" for "j\'":',
                promptFr: 'j\' _____',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'j\' ai — correct form of "avoir".',
              },
              {
                id: 'b1-u1-l2-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "avoir".',
                options: ['a', 'ai', 'as', 'avons'],
                answer: 0,
                explanation: 'il/elle a — correct conjugation of "avoir".',
              },
              {
                id: 'b1-u1-l2-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "J\'_____ un frère." (I have a brother.) — form of "avoir"',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'The correct form is "ai".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Mère', fr: 'Il faut que tu fasses tes devoirs avant de sortir !', en: 'You must do your homework before going out!' },
            { speaker: 'B', name: 'Fils', fr: 'Mais maman, je veux que mes amis m\'attendent !', en: 'But mom, I want my friends to wait for me!' },
            { speaker: 'A', name: 'Mère', fr: 'Bien que tu sois pressé, les devoirs sont importants. Il faut que tu les finisses.', en: 'Although you\'re in a hurry, homework is important. You must finish it.' },
            { speaker: 'B', name: 'Fils', fr: 'D\'accord. Mais je doute que je puisse finir avant 18h.', en: 'OK. But I doubt I can finish before 6 PM.' },
            { speaker: 'A', name: 'Mère', fr: 'Je suis contente que tu comprennes. Fais de ton mieux !', en: 'I\'m happy you understand. Do your best!' },
            { speaker: 'B', name: 'Fils', fr: 'D\'accord, maman. Pour que tu sois contente, je vais tout finir.', en: 'OK mom. So that you\'re happy, I\'ll finish everything.' },
          ],
          exercises: [
            {
              id: 'b1-u1-l2-e1',
              type: 'multiple_choice',
              prompt: 'Complete: "Il faut que tu _____." (you must come)',
              options: ['viens', 'viennes', 'venir', 'venirs'],
              answer: 1,
              explanation: 'After "il faut que", use subjunctive: tu viennes.',
            },
            {
              id: 'b1-u1-l2-e2',
              type: 'fill_blank',
              prompt: 'Subjunctive of "être": "Je suis content que tu _____ là."',
              answer: 'sois',
              explanation: 'Subjunctive of être: que je sois, que tu sois, qu\'il soit...',
            },
            {
              id: 'b1-u1-l2-e3',
              type: 'multiple_choice',
              prompt: 'Which expression does NOT trigger the subjunctive?',
              options: ['Il faut que', 'Je pense que', 'Bien que', 'Pour que'],
              answer: 1,
              explanation: 'Je pense que takes the indicative (it expresses belief, not doubt).',
            },
            {
              id: 'b1-u1-l2-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "I want you to know." (use vouloir + savoir)',
              answer: 'Je veux que tu saches',
              acceptable: ['je veux que tu saches'],
              explanation: 'Je veux que + subjunctive of savoir: que tu saches.',
            },
            {
              id: 'b1-u1-l2-e5',
              type: 'true_false',
              prompt: 'The subjunctive is used after "bien que" (although).',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. Bien que + subjunctive: Bien qu\'il soit fatigué...',
            },
          ],
          culturalNote:
            "The subjunctive is fading in casual spoken French — many young speakers simplify it. However, in formal writing, journalism, and literature, it remains essential. A famous French joke: 'Le subjonctif, c\'est comme la grammaire : on l\'apprend à l\'école et on l\'oublie après.' (The subjunctive is like grammar: you learn it at school and forget it after.)",
          estimatedMinutes: 40,
        },
      ],
    },
    {
      id: 'b1-u2',
      title: 'Media and News',
      titleFr: 'Médias et actualité',
      theme: 'News, conditionals & reported speech',
      description: 'Understand French news, use the conditional mood, and report what others say.',
      lessons: [
        {
          id: 'b1-u2-l1',
          title: 'The Conditional Mood',
          titleFr: 'Le conditionnel',
          description: 'Use the conditional to express hypotheses, politeness, and reported information.',
          objectives: [
            'Form the present conditional',
            'Use "si" clauses with conditionals',
            'Express politeness with the conditional',
            'Recognize the conditional as "future in the past"',
          ],
          vocabulary: [
            { fr: 'si', en: 'if', example: 'Si j\'avais le temps, je voyagerais.', exampleEn: 'If I had time, I would travel.', category: 'condition' },
            { fr: 'je voudrais', en: 'I would like', example: 'Je voudrais un café.', exampleEn: 'I would like a coffee.', category: 'politeness' },
            { fr: 'je pourrais', en: 'I could', example: 'Je pourrais t\'aider.', exampleEn: 'I could help you.', category: 'conditional' },
            { fr: 'il faudrait', en: 'one should / it would be necessary', example: 'Il faudrait partir tôt.', exampleEn: 'We should leave early.', category: 'conditional' },
            { fr: 'à condition que', en: 'on condition that', example: 'Je viendrai à condition qu\'il vienne.', exampleEn: 'I\'ll come on condition that he comes.', category: 'condition' },
            { fr: 'au cas où', en: 'in case', example: 'Prends un parapluie au cas où il pleuvrait.', exampleEn: 'Take an umbrella in case it rains.', category: 'condition' },
            { fr: 'selon les journalistes', en: 'according to journalists', example: 'Selon les journalistes, le projet est annulé.', exampleEn: 'According to journalists, the project is canceled.', category: 'media' },
            { fr: 'les informations', en: 'the news', example: 'Je regarde les informations à 20h.', exampleEn: 'I watch the news at 8 PM.', category: 'media' },
            { fr: 'le journal', en: 'the newspaper / the news', example: 'Le journal de 20h.', exampleEn: 'The 8 PM news.', category: 'media' },
            { fr: 'un journaliste', en: 'a journalist', example: 'La journaliste interviewe le ministre.', exampleEn: 'The journalist is interviewing the minister.', category: 'media' },
          ],
          grammar: [
            {
              title: 'Forming the present conditional',
              explanation:
                "The conditional is formed with the futur stem + imparfait endings (-ais, -ais, -ait, -ions, -iez, -aient). It is used for hypotheses, polite requests, and reported future events ('future in the past').",
              examples: [
                { fr: 'parler → parler- → je parlerais (I would speak)', en: 'Stem of futur simple + imparfait endings.' },
                { fr: 'finir → finir- → je finirais (I would finish)', en: 'Same pattern.' },
                { fr: 'être → ser- → je serais (I would be)', en: 'Irregular stem (same as futur).' },
                { fr: 'avoir → aur- → j\'aurais (I would have)', en: 'Irregular stem.' },
              ],
              table: {
                caption: 'Conditional of common verbs',
                headers: ['Verb', 'je', 'tu', 'il', 'nous', 'vous', 'ils'],
                rows: [
                  ['être', 'serais', 'serais', 'serait', 'serions', 'seriez', 'seraient'],
                  ['avoir', 'aurais', 'aurais', 'aurait', 'aurions', 'auriez', 'auraient'],
                  ['aller', 'irais', 'irais', 'irait', 'irions', 'iriez', 'iraient'],
                  ['faire', 'ferais', 'ferais', 'ferait', 'ferions', 'feriez', 'feraient'],
                  ['pouvoir', 'pourrais', 'pourrais', 'pourrait', 'pourrions', 'pourriez', 'pourraient'],
                ],
              },
              tip: 'The conditional uses the same stems as the futur simple — only the endings differ (-ai → -ais for je).',
            },
            {
              title: 'Si clauses — hypothetical sentences',
              explanation:
                "French uses three types of 'si' clauses: (1) Si + présent → futur (real possibility), (2) Si + imparfait → conditionnel (hypothetical), (3) Si + plus-que-parfait → conditionnel passé (unreal past).",
              examples: [
                { fr: 'Si tu étudies, tu réussiras.', en: 'If you study, you will succeed. (real)' },
                { fr: 'Si tu étudiais, tu réussirais.', en: 'If you studied, you would succeed. (hypothetical)' },
                { fr: 'Si tu avais étudié, tu aurais réussi.', en: 'If you had studied, you would have succeeded. (unreal past)' },
              ],
              table: {
                caption: 'Si clause patterns',
                headers: ['Type', 'Si clause', 'Main clause'],
                rows: [
                  ['Real', 'présent', 'futur simple'],
                  ['Hypothetical', 'imparfait', 'conditionnel présent'],
                  ['Unreal past', 'plus-que-parfait', 'conditionnel passé'],
                ],
              },
              tip: 'In the hypothetical si clause, the imparfait is used (not the conditional). NEVER say "Si je serais" — it\'s "Si j\'étais".',
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'avoir',
              translation: 'to have',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'j\'', form: 'ai' },
                { pronoun: 'tu', form: 'as' },
                { pronoun: 'il/elle', form: 'a' },
                { pronoun: 'nous', form: 'avons' },
                { pronoun: 'vous', form: 'avez' },
                { pronoun: 'ils/elles', form: 'ont' },
              ],
              sentenceRule: 'Subject + avoir + noun. Used for possession, age (J\'ai 20 ans), and expressions like avoir faim/soif/froid. Age uses avoir, NOT être.',
              sentenceExamples: [
                { fr: 'J\'ai un frère.', en: 'I have a brother.' },
                { fr: 'Tu as vingt ans.', en: 'You are twenty.' },
                { fr: 'Il a faim.', en: 'He is hungry.' },
              ],
            }
            ],
            practice: [
              {
                id: 'b1-u2-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "avoir" for "j\'":',
                promptFr: 'j\' _____',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'j\' ai — correct form of "avoir".',
              },
              {
                id: 'b1-u2-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "avoir".',
                options: ['a', 'ai', 'as', 'avons'],
                answer: 0,
                explanation: 'il/elle a — correct conjugation of "avoir".',
              },
              {
                id: 'b1-u2-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "J\'_____ un frère." (I have a brother.) — form of "avoir"',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'The correct form is "ai".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Journaliste', fr: 'Selon nos informations, le gouvernement annoncerait une réforme la semaine prochaine.', en: 'According to our information, the government would announce a reform next week.' },
            { speaker: 'B', name: 'Invité', fr: 'Si c\'était vrai, ce serait une bonne nouvelle pour les citoyens.', en: 'If that were true, it would be good news for citizens.' },
            { speaker: 'A', name: 'Journaliste', fr: 'Que feriez-vous si vous étiez au gouvernement ?', en: 'What would you do if you were in government?' },
            { speaker: 'B', name: 'Invité', fr: 'Si j\'étais ministre, je investirais davantage dans l\'éducation. Il faudrait aussi réduire les impôts.', en: 'If I were minister, I would invest more in education. It would also be necessary to reduce taxes.' },
            { speaker: 'A', name: 'Journaliste', fr: 'Mais si le budget était limité, comment feriez-vous ?', en: 'But if the budget were limited, how would you do it?' },
            { speaker: 'B', name: 'Invité', fr: 'Je pourrais trouver des économies ailleurs. Au cas où le budget augmenterait, je créerais plus de places à l\'université.', en: 'I could find savings elsewhere. In case the budget increased, I would create more university places.' },
          ],
          exercises: [
            {
              id: 'b1-u2-l1-e1',
              type: 'multiple_choice',
              prompt: 'Complete: "Si j\'avais le temps, je _____ voyager."',
              options: ['vais', 'irais', 'allais', 'irai'],
              answer: 1,
              explanation: 'Si + imparfait → conditionnel présent. Aller → j\'irais.',
            },
            {
              id: 'b1-u2-l1-e2',
              type: 'fill_blank',
              prompt: 'Conditional of "être": "Si j\'étais riche, je _____ généreux."',
              answer: 'serais',
              explanation: 'Conditional of être: je serais, tu serais, il serait.',
            },
            {
              id: 'b1-u2-l1-e3',
              type: 'multiple_choice',
              prompt: 'Which sentence is grammatically correct?',
              options: ['Si je serais riche, j\'achèterais une maison', 'Si j\'étais riche, j\'achèterais une maison', 'Si je suis riche, j\'achète une maison', 'Si j\'aurai riche, j\'achèterai une maison'],
              answer: 1,
              explanation: 'After si, NEVER use the conditional. Use imparfait: Si j\'étais riche.',
            },
            {
              id: 'b1-u2-l1-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "I would like a coffee, please." (polite)',
              answer: 'Je voudrais un café, s\'il vous plaît',
              acceptable: ['je voudrais un café s il vous plaît'],
              explanation: 'Vouloir in conditional = polite form: je voudrais.',
            },
            {
              id: 'b1-u2-l1-e5',
              type: 'true_false',
              prompt: 'The conditional is used in journalism to report unconfirmed information.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. "Le gouvernement annoncerait..." = "The government would announce..." (unconfirmed).',
            },
          ],
          culturalNote:
            "French TV news ('le journal de 20h') on TF1 and France 2 is a national ritual, watched by millions every evening. France has a strong tradition of investigative journalism, with magazines like 'Le Canard Enchaîné' (satirical/investigative) and 'Mediapart' (online). The press is largely subsidized by the state to ensure pluralism.",
          estimatedMinutes: 40,
        },
      ],
    },
    {
      id: 'b1-u3',
      title: 'Work and Career',
      titleFr: 'Travail et carrière',
      theme: 'Professional life & plus-que-parfait',
      description: 'Talk about your career, write a CV, and use the plus-que-parfait.',
      lessons: [
        {
          id: 'b1-u3-l1',
          title: 'Professional Life',
          titleFr: 'La vie professionnelle',
          description: 'Use professional vocabulary, talk about your career path, and use the plus-que-parfait.',
          objectives: [
            'Use professional French vocabulary',
            'Describe your career and education',
            'Form the plus-que-parfait',
            'Talk about a sequence of past events',
          ],
          vocabulary: [
            { fr: 'le travail', en: 'work / job', example: 'Je cherche du travail.', exampleEn: 'I\'m looking for work.', category: 'work' },
            { fr: 'le métier', en: 'profession / trade', example: 'Quel est votre métier ?', exampleEn: 'What is your profession?', category: 'work' },
            { fr: 'la carrière', en: 'career', example: 'Il a une belle carrière.', exampleEn: 'He has a beautiful career.', category: 'work' },
            { fr: 'l\'entreprise', en: 'company', example: 'Je travaille dans une petite entreprise.', exampleEn: 'I work in a small company.', category: 'work' },
            { fr: 'le patron', en: 'boss', example: 'Mon patron est sympa.', exampleEn: 'My boss is nice.', category: 'work' },
            { fr: 'les collègues', en: 'colleagues', example: 'Mes collègues sont gentils.', exampleEn: 'My colleagues are kind.', category: 'work' },
            { fr: 'le salaire', en: 'salary', example: 'Mon salaire a augmenté.', exampleEn: 'My salary increased.', category: 'work' },
            { fr: 'un entretien d\'embauche', en: 'a job interview', example: 'J\'ai un entretien d\'embauche demain.', exampleEn: 'I have a job interview tomorrow.', category: 'work' },
            { fr: 'le CV', en: 'CV / résumé', example: 'J\'ai envoyé mon CV.', exampleEn: 'I sent my CV.', category: 'work' },
            { fr: 'démissionner', en: 'to resign', example: 'Il a démissionné hier.', exampleEn: 'He resigned yesterday.', category: 'work' },
            { fr: 'être embauché(e)', en: 'to be hired', example: 'Elle a été embauchée.', exampleEn: 'She was hired.', category: 'work' },
            { fr: 'le chômage', en: 'unemployment', example: 'Le chômage baisse.', exampleEn: 'Unemployment is decreasing.', category: 'work' },
          ],
          grammar: [
            {
              title: 'Plus-que-parfait — the past of the past',
              explanation:
                "The plus-que-parfait is used to describe an action that happened BEFORE another past action. It is formed with the imparfait of avoir/être + past participle.",
              examples: [
                { fr: 'Quand je suis arrivé, le train était déjà parti.', en: 'When I arrived, the train had already left.' },
                { fr: 'Elle avait fini son travail quand j\'ai appelé.', en: 'She had finished her work when I called.' },
                { fr: 'J\'avais mangé avant qu\'il arrive.', en: 'I had eaten before he arrived.' },
              ],
              tip: 'Think of it as the "past before the past" — used to set background for the passé composé.',
            },
            {
              title: 'Sequence of past events',
              explanation:
                "When telling a story, the plus-que-parfait establishes what had already happened, the imparfait describes the scene, and the passé composé moves the action forward.",
              examples: [
                { fr: 'J\'avais préparé le dîner (PQP). Il pleuvait (IMP). Quand il est arrivé (PC), nous avons mangé (PC).', en: 'I had prepared dinner. It was raining. When he arrived, we ate.' },
              ],
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'être',
              translation: 'to be',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'suis' },
                { pronoun: 'tu', form: 'es' },
                { pronoun: 'il/elle', form: 'est' },
                { pronoun: 'nous', form: 'sommes' },
                { pronoun: 'vous', form: 'êtes' },
                { pronoun: 'ils/elles', form: 'sont' },
              ],
              sentenceRule: 'Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
              sentenceExamples: [
                { fr: 'Je suis étudiant.', en: 'I am a student.' },
                { fr: 'Tu es français ?', en: 'Are you French?' },
                { fr: 'Nous sommes à Paris.', en: 'We are in Paris.' },
              ],
            },
            {
              infinitive: 'avoir',
              translation: 'to have',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'j\'', form: 'ai' },
                { pronoun: 'tu', form: 'as' },
                { pronoun: 'il/elle', form: 'a' },
                { pronoun: 'nous', form: 'avons' },
                { pronoun: 'vous', form: 'avez' },
                { pronoun: 'ils/elles', form: 'ont' },
              ],
              sentenceRule: 'Subject + avoir + noun. Used for possession, age (J\'ai 20 ans), and expressions like avoir faim/soif/froid. Age uses avoir, NOT être.',
              sentenceExamples: [
                { fr: 'J\'ai un frère.', en: 'I have a brother.' },
                { fr: 'Tu as vingt ans.', en: 'You are twenty.' },
                { fr: 'Il a faim.', en: 'He is hungry.' },
              ],
            }
            ],
            practice: [
              {
                id: 'b1-u3-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "être" for "je":',
                promptFr: 'je _____',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'je suis — correct form of "être".',
              },
              {
                id: 'b1-u3-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "être".',
                options: ['est', 'suis', 'es', 'sommes'],
                answer: 0,
                explanation: 'il/elle est — correct conjugation of "être".',
              },
              {
                id: 'b1-u3-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'The correct form is "suis".',
              },
              {
                id: 'b1-u3-l1-conj-1-1',
                type: 'conjugation',
                prompt: 'Conjugate "avoir" for "tu":',
                promptFr: 'tu _____',
                answer: 'as',
                acceptable: ['as'],
                explanation: 'tu as — correct form of "avoir".',
              },
              {
                id: 'b1-u3-l1-conj-1-2',
                type: 'multiple_choice',
                prompt: 'Complete: "nous _____" with the correct form of "avoir".',
                options: ['avons', 'ai', 'as', 'a'],
                answer: 0,
                explanation: 'nous avons — correct conjugation of "avoir".',
              },
              {
                id: 'b1-u3-l1-conj-1-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Tu _____ vingt ans." (You are twenty.) — form of "avoir"',
                answer: 'as',
                acceptable: ['as'],
                explanation: 'The correct form is "as".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Recruteur', fr: 'Bonjour. Vous avez quelles expériences professionnelles ?', en: 'Hello. What professional experience do you have?' },
            { speaker: 'B', name: 'Candidat', fr: 'J\'avais travaillé trois ans dans une start-up avant de postuler ici. Avant cela, j\'avais fait un stage dans une grande entreprise.', en: 'I had worked three years in a start-up before applying here. Before that, I had done an internship in a big company.' },
            { speaker: 'A', name: 'Recruteur', fr: 'Et pourquoi avez-vous quitté votre précédent poste ?', en: 'And why did you leave your previous position?' },
            { speaker: 'B', name: 'Candidat', fr: 'J\'avais atteint le plafond dans cette entreprise. Je cherchais de nouveaux défis.', en: 'I had reached the ceiling in that company. I was looking for new challenges.' },
            { speaker: 'A', name: 'Recruteur', fr: 'Quel salaire espériez-vous ?', en: 'What salary were you hoping for?' },
            { speaker: 'B', name: 'Candidat', fr: 'J\'espérais un salaire autour de 35 000 euros, avec des possibilités d\'évolution.', en: 'I was hoping for a salary around 35,000 euros, with possibilities for advancement.' },
            { speaker: 'A', name: 'Recruteur', fr: 'C\'est faisable. Nous vous recontacterons après avoir vu les autres candidats.', en: 'That\'s doable. We\'ll contact you again after seeing the other candidates.' },
          ],
          exercises: [
            {
              id: 'b1-u3-l1-e1',
              type: 'multiple_choice',
              prompt: 'What is the plus-que-parfait of "manger" for "j\'"?',
              options: ['j\'ai mangé', 'j\'avais mangé', 'j\'avais mange', 'je mangeais'],
              answer: 1,
              explanation: 'Imparfait of avoir + past participle: j\'avais mangé.',
            },
            {
              id: 'b1-u3-l1-e2',
              type: 'fill_blank',
              prompt: 'Complete: "Quand je suis arrivé, le train _____ déjà parti."',
              answer: 'était',
              explanation: 'Partir uses être. Plus-que-parfait: était parti.',
            },
            {
              id: 'b1-u3-l1-e3',
              type: 'multiple_choice',
              prompt: 'When do you use the plus-que-parfait?',
              options: ['For recent past', 'For future past', 'For an action before another past action', 'For present habits'],
              answer: 2,
              explanation: 'The plus-que-parfait describes an action that happened before another past action.',
            },
            {
              id: 'b1-u3-l1-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "I had finished my work."',
              answer: "J'avais fini mon travail",
              acceptable: ['j avais fini mon travail'],
              explanation: 'Imparfait of avoir + past participle of finir: j\'avais fini.',
            },
            {
              id: 'b1-u3-l1-e5',
              type: 'true_false',
              prompt: 'The plus-que-parfait is formed with imparfait of avoir/être + past participle.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. Ex: j\'avais parlé, j\'étais allé.',
            },
          ],
          culturalNote:
            "In France, the legal work week is 35 hours. Workers have 5 weeks of paid vacation per year — among the highest in the world. The French CV is typically 1-2 pages, with a photo (optional but common), and includes personal details like age and marital status that would be unusual in American CVs.",
          estimatedMinutes: 35,
        },
      ],
    },
    {
      id: 'b1-u4',
      title: 'Environment and Society',
      titleFr: 'Environnement et société',
      theme: 'Environment, cause & consequence',
      description: 'Discuss environmental issues, use cause-and-effect structures.',
      lessons: [
        {
          id: 'b1-u4-l1',
          title: 'Talking About the Environment',
          titleFr: 'Parler de l\'environnement',
          description: 'Use vocabulary for climate issues and express cause and consequence.',
          objectives: [
            'Use environmental vocabulary',
            'Express cause (à cause de, grâce à)',
            'Express consequence (donc, par conséquent)',
            'Form the passive voice',
          ],
          vocabulary: [
            { fr: 'l\'environnement', en: 'the environment', example: 'Il faut protéger l\'environnement.', exampleEn: 'We must protect the environment.', category: 'environment' },
            { fr: 'le climat', en: 'the climate', example: 'Le climat change.', exampleEn: 'The climate is changing.', category: 'environment' },
            { fr: 'la pollution', en: 'pollution', example: 'La pollution de l\'air est grave.', exampleEn: 'Air pollution is serious.', category: 'environment' },
            { fr: 'le réchauffement', en: 'warming', example: 'Le réchauffement climatique.', exampleEn: 'Global warming.', category: 'environment' },
            { fr: 'les déchets', en: 'waste / trash', example: 'Trier les déchets est important.', exampleEn: 'Sorting waste is important.', category: 'environment' },
            { fr: 'recycler', en: 'to recycle', example: 'Je recycle le plastique.', exampleEn: 'I recycle plastic.', category: 'environment' },
            { fr: 'l\'énergie renouvelable', en: 'renewable energy', example: 'Les énergies renouvelables progressent.', exampleEn: 'Renewable energies are progressing.', category: 'environment' },
            { fr: 'à cause de', en: 'because of (negative)', example: 'À cause de la pollution, l\'air est mauvais.', exampleEn: 'Because of pollution, the air is bad.', category: 'cause' },
            { fr: 'grâce à', en: 'thanks to (positive)', example: 'Grâce à l\'électricité verte, on pollue moins.', exampleEn: 'Thanks to green electricity, we pollute less.', category: 'cause' },
            { fr: 'en raison de', en: 'due to (neutral)', example: 'En raison du vent, l\'avion est en retard.', exampleEn: 'Due to wind, the plane is late.', category: 'cause' },
            { fr: 'donc', en: 'therefore', example: 'Il pleut, donc je reste.', exampleEn: 'It\'s raining, therefore I stay.', category: 'consequence' },
            { fr: 'par conséquent', en: 'consequently', example: 'Il est malade ; par conséquent, il ne vient pas.', exampleEn: 'He\'s sick; consequently, he\'s not coming.', category: 'consequence' },
          ],
          grammar: [
            {
              title: 'Cause expressions: à cause de vs. grâce à',
              explanation:
                "'À cause de' introduces a negative cause (something bad). 'Grâce à' introduces a positive cause (something good). 'En raison de' is neutral, used in formal contexts.",
              examples: [
                { fr: 'À cause de la grève, le train est annulé.', en: 'Because of the strike (bad), the train is canceled.' },
                { fr: 'Grâce à ton aide, j\'ai réussi.', en: 'Thanks to your help (good), I succeeded.' },
                { fr: 'En raison de travaux, la route est fermée.', en: 'Due to road works (neutral), the road is closed.' },
              ],
              tip: 'All three are followed by a NOUN, not a sentence. For a sentence, use "parce que".',
            },
            {
              title: 'The passive voice',
              explanation:
                "The passive voice is formed with être + past participle. It is used when the action is more important than who did it. The agent (who did it) is introduced with 'par'.",
              examples: [
                { fr: 'La maison est construite par des ouvriers.', en: 'The house is built by workers.' },
                { fr: 'Le pain est fait avec de la farine.', en: 'Bread is made with flour.' },
                { fr: 'Ce livre a été écrit en 1950.', en: 'This book was written in 1950.' },
              ],
              tip: 'French uses the passive less than English. Often, "on" + active verb replaces it: "On a construit la maison" (They built the house / The house was built).',
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'vouloir',
              translation: 'to want',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'veux' },
                { pronoun: 'tu', form: 'veux' },
                { pronoun: 'il/elle', form: 'veut' },
                { pronoun: 'nous', form: 'voulons' },
                { pronoun: 'vous', form: 'voulez' },
                { pronoun: 'ils/elles', form: 'veulent' },
              ],
              sentenceRule: 'Subject + vouloir + noun/infinitive. Je voudrais (conditional) = I would like — polite form for ordering. Irregular.',
              sentenceExamples: [
                { fr: 'Je veux un café.', en: 'I want a coffee.' },
                { fr: 'Tu veux venir ?', en: 'Do you want to come?' },
                { fr: 'Je voudrais un thé.', en: 'I would like a tea.' },
              ],
            },
            {
              infinitive: 'prendre',
              translation: 'to take',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'prends' },
                { pronoun: 'tu', form: 'prends' },
                { pronoun: 'il/elle', form: 'prend' },
                { pronoun: 'nous', form: 'prenons' },
                { pronoun: 'vous', form: 'prenez' },
                { pronoun: 'ils/elles', form: 'prennent' },
              ],
              sentenceRule: 'Subject + prendre + transport (Je prends le métro). Also: prendre un café, prendre le petit-déjeuner. Irregular -re verb.',
              sentenceExamples: [
                { fr: 'Je prends le bus.', en: 'I take the bus.' },
                { fr: 'Tu prends un café ?', en: 'Will you have a coffee?' },
                { fr: 'Nous prenons le train.', en: 'We take the train.' },
              ],
            }
            ],
            practice: [
              {
                id: 'b1-u4-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "vouloir" for "je":',
                promptFr: 'je _____',
                answer: 'veux',
                acceptable: ['veux'],
                explanation: 'je veux — correct form of "vouloir".',
              },
              {
                id: 'b1-u4-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "vouloir".',
                options: ['veut', 'veux', 'veux', 'voulons'],
                answer: 0,
                explanation: 'il/elle veut — correct conjugation of "vouloir".',
              },
              {
                id: 'b1-u4-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Je _____ un café." (I want a coffee.) — form of "vouloir"',
                answer: 'veux',
                acceptable: ['veux'],
                explanation: 'The correct form is "veux".',
              },
              {
                id: 'b1-u4-l1-conj-1-1',
                type: 'conjugation',
                prompt: 'Conjugate "prendre" for "tu":',
                promptFr: 'tu _____',
                answer: 'prends',
                acceptable: ['prends'],
                explanation: 'tu prends — correct form of "prendre".',
              },
              {
                id: 'b1-u4-l1-conj-1-2',
                type: 'multiple_choice',
                prompt: 'Complete: "nous _____" with the correct form of "prendre".',
                options: ['prenons', 'prends', 'prends', 'prend'],
                answer: 0,
                explanation: 'nous prenons — correct conjugation of "prendre".',
              },
              {
                id: 'b1-u4-l1-conj-1-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Tu _____ un café ?" (Will you have a coffee?) — form of "prendre"',
                answer: 'prends',
                acceptable: ['prends'],
                explanation: 'The correct form is "prends".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Léa', fr: 'À cause du réchauffement climatique, les étés sont de plus en plus chauds.', en: 'Because of global warming, summers are getting hotter and hotter.' },
            { speaker: 'B', name: 'Tom', fr: 'C\'est vrai. Heureusement, grâce aux énergies renouvelables, on commence à réduire la pollution.', en: 'True. Fortunately, thanks to renewable energies, we\'re starting to reduce pollution.' },
            { speaker: 'A', name: 'Léa', fr: 'Mais est-ce que c\'est suffisant ? Par conséquent, il faudrait des lois plus strictes.', en: 'But is it enough? Consequently, we would need stricter laws.' },
            { speaker: 'B', name: 'Tom', fr: 'Tu as raison. Le recyclage est important, mais il ne suffit pas.', en: 'You\'re right. Recycling is important, but it\'s not enough.' },
            { speaker: 'A', name: 'Léa', fr: 'En raison de l\'urgence, tout le monde doit agir.', en: 'Due to the urgency, everyone must act.' },
            { speaker: 'B', name: 'Tom', fr: 'Tout à fait. Chaque geste compte.', en: 'Absolutely. Every action counts.' },
          ],
          exercises: [
            {
              id: 'b1-u4-l1-e1',
              type: 'multiple_choice',
              prompt: 'Which expression has a NEGATIVE connotation?',
              options: ['Grâce à', 'À cause de', 'En raison de', 'Donc'],
              answer: 1,
              explanation: 'À cause de introduces a negative cause. Grâce à is positive.',
            },
            {
              id: 'b1-u4-l1-e2',
              type: 'fill_blank',
              prompt: 'Complete: "_____ ton aide, j\'ai réussi." (Thanks to your help)',
              answer: 'Grâce à',
              acceptable: ['grâce à', 'grace a'],
              explanation: 'Grâce à = thanks to (positive).',
            },
            {
              id: 'b1-u4-l1-e3',
              type: 'multiple_choice',
              prompt: 'Which is the passive form of "On construit la maison"?',
              options: ['La maison construit', 'La maison est construite', 'La maison a construit', 'La maison construire'],
              answer: 1,
              explanation: 'Passive = être + past participle: La maison est construite.',
            },
            {
              id: 'b1-u4-l1-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "Because of the strike, the train is canceled."',
              answer: 'À cause de la grève, le train est annulé',
              acceptable: ['à cause de la greve le train est annulé'],
              explanation: 'À cause de + noun (negative cause).',
            },
            {
              id: 'b1-u4-l1-e5',
              type: 'true_false',
              prompt: '"Grâce à" introduces a positive cause.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. Grâce à = thanks to (something positive).',
            },
          ],
          culturalNote:
            "France is a leader in low-carbon electricity thanks to nuclear power (about 70% of production). The country has banned single-use plastic packaging for many fruits and vegetables since 2022. The 'mairie' (city hall) of Paris has launched ambitious programs to reduce car traffic and plant trees — by 2030, Paris aims to be carbon-neutral.",
          estimatedMinutes: 35,
        },
      ],
    },
    {
      id: 'b1-u5',
      title: 'Technology and Modern Life',
      titleFr: 'Technologie et vie moderne',
      theme: 'Technology, internet & indirect speech',
      description: 'Discuss technology, report what others say, and use indirect questions.',
      lessons: [
        {
          id: 'b1-u5-l1',
          title: 'In the Digital Age',
          titleFr: 'À l\'ère numérique',
          description: 'Talk about technology, social media, and report what others say.',
          objectives: [
            'Use technology vocabulary (ordinateur, smartphone, réseau social)',
            'Form indirect questions (Il demande si...)',
            'Report speech with "dire que"',
            'Discuss pros and cons of technology',
          ],
          vocabulary: [
            { fr: "l'ordinateur", en: 'the computer', example: 'Mon ordinateur est en panne.', exampleEn: 'My computer is broken.', category: 'tech' },
            { fr: 'le smartphone', en: 'the smartphone', example: 'Je ne peux pas vivre sans smartphone.', exampleEn: 'I can\'t live without a smartphone.', category: 'tech' },
            { fr: "l'internet", en: 'the internet', example: 'Une connexion internet rapide.', exampleEn: 'A fast internet connection.', category: 'tech' },
            { fr: 'le réseau social', en: 'the social network', example: 'Les réseaux sociaux sont populaires.', exampleEn: 'Social networks are popular.', category: 'tech' },
            { fr: "l'application (app)", en: 'the app', example: 'J\'ai téléchargé une nouvelle application.', exampleEn: 'I downloaded a new app.', category: 'tech' },
            { fr: 'le courriel (email)', en: 'the email', example: 'Je vais envoyer un courriel.', exampleEn: 'I\'ll send an email.', category: 'tech' },
            { fr: 'le message', en: 'the message', example: 'Un message texte.', exampleEn: 'A text message.', category: 'tech' },
            { fr: 'télécharger', en: 'to download', example: 'J\'ai téléchargé un film.', exampleEn: 'I downloaded a movie.', category: 'verbs' },
            { fr: 'partager', en: 'to share', example: 'Elle a partagé une photo.', exampleEn: 'She shared a photo.', category: 'verbs' },
            { fr: 'se connecter', en: 'to log in / connect', example: 'Connecte-toi à ton compte.', exampleEn: 'Log into your account.', category: 'verbs' },
            { fr: 'se déconnecter', en: 'to log out', example: 'Déconnecte-toi après usage.', exampleEn: 'Log out after use.', category: 'verbs' },
            { fr: 'le mot de passe', en: 'the password', example: 'Quel est ton mot de passe ?', exampleEn: 'What is your password?', category: 'tech' },
            { fr: "l'écran", en: 'the screen', example: 'Un grand écran.', exampleEn: 'A large screen.', category: 'tech' },
            { fr: 'le clavier', en: 'the keyboard', example: 'Tape sur le clavier.', exampleEn: 'Type on the keyboard.', category: 'tech' },
            { fr: 'la souris', en: 'the mouse (computer)', example: 'Une souris sans fil.', exampleEn: 'A wireless mouse.', category: 'tech' },
            { fr: 'les données', en: 'the data', example: 'La protection des données.', exampleEn: 'Data protection.', category: 'tech' },
            { fr: 'le pirate', en: 'the hacker', example: 'Les pirates informatiques.', exampleEn: 'Computer hackers.', category: 'tech' },
            { fr: 'la intelligence artificielle', en: 'the artificial intelligence', example: "L'IA transforme le monde.", exampleEn: 'AI is transforming the world.', category: 'tech' },
            { fr: "l'algorithme", en: 'the algorithm', example: 'Un algorithme complexe.', exampleEn: 'A complex algorithm.', category: 'tech' },
            { fr: 'addictif', en: 'addictive', example: 'Les réseaux sont addictifs.', exampleEn: 'Networks are addictive.', category: 'adjectives' },
          ],
          grammar: [
            {
              title: 'Indirect questions',
              explanation:
                "Indirect questions report a question without using quotation marks. They are introduced by 'si' (if/whether) for yes/no questions, or by a question word (qui, que, où, quand, comment, pourquoi, ce que) for wh-questions. The subject usually comes BEFORE the verb (no inversion).",
              examples: [
                { fr: 'Il demande si tu viens.', en: 'He asks if you are coming.' },
                { fr: 'Je ne sais pas quand il arrive.', en: 'I don\'t know when he is arriving.' },
                { fr: 'Elle veut savoir où tu habites.', en: 'She wants to know where you live.' },
                { fr: 'Dis-moi ce que tu penses.', en: 'Tell me what you think.' },
              ],
              tip: "After 'si' (if/whether), use statement word order: 'si tu viens' (not 'si viens-tu').",
            },
            {
              title: 'Reported speech with dire que',
              explanation:
                "To report what someone said, use 'dire que' + statement. The tense often shifts: present → imparfait, passé composé → plus-que-parfait.",
              examples: [
                { fr: 'Il dit : « Je suis fatigué. » → Il dit qu\'il est fatigué.', en: 'He says: "I am tired." → He says (that) he is tired.' },
                { fr: 'Il a dit : « Je suis fatigué. » → Il a dit qu\'il était fatigué.', en: 'He said: "I am tired." → He said (that) he was tired.' },
              ],
              tip: 'In French, "que" is required (unlike English where "that" can be dropped): "Il dit qu\'il est fatigué" — never "Il dit il est fatigué".',
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'aller',
              translation: 'to go',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'vais' },
                { pronoun: 'tu', form: 'vas' },
                { pronoun: 'il/elle', form: 'va' },
                { pronoun: 'nous', form: 'allons' },
                { pronoun: 'vous', form: 'allez' },
                { pronoun: 'ils/elles', form: 'vont' },
              ],
              sentenceRule: 'Subject + aller + preposition + place. à + le = au, à + les = aux. Also: aller + infinitive = near future (Je vais manger).',
              sentenceExamples: [
                { fr: 'Je vais au cinéma.', en: 'I go to the cinema.' },
                { fr: 'Nous allons à Paris.', en: 'We go to Paris.' },
                { fr: 'Je vais manger.', en: 'I am going to eat.' },
              ],
            },
            {
              infinitive: 'être',
              translation: 'to be',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'suis' },
                { pronoun: 'tu', form: 'es' },
                { pronoun: 'il/elle', form: 'est' },
                { pronoun: 'nous', form: 'sommes' },
                { pronoun: 'vous', form: 'êtes' },
                { pronoun: 'ils/elles', form: 'sont' },
              ],
              sentenceRule: 'Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
              sentenceExamples: [
                { fr: 'Je suis étudiant.', en: 'I am a student.' },
                { fr: 'Tu es français ?', en: 'Are you French?' },
                { fr: 'Nous sommes à Paris.', en: 'We are in Paris.' },
              ],
            }
            ],
            practice: [
              {
                id: 'b1-u5-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "aller" for "je":',
                promptFr: 'je _____',
                answer: 'vais',
                acceptable: ['vais'],
                explanation: 'je vais — correct form of "aller".',
              },
              {
                id: 'b1-u5-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "aller".',
                options: ['va', 'vais', 'vas', 'allons'],
                answer: 0,
                explanation: 'il/elle va — correct conjugation of "aller".',
              },
              {
                id: 'b1-u5-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Je _____ au cinéma." (I go to the cinema.) — form of "aller"',
                answer: 'vais',
                acceptable: ['vais'],
                explanation: 'The correct form is "vais".',
              },
              {
                id: 'b1-u5-l1-conj-1-1',
                type: 'conjugation',
                prompt: 'Conjugate "être" for "tu":',
                promptFr: 'tu _____',
                answer: 'es',
                acceptable: ['es'],
                explanation: 'tu es — correct form of "être".',
              },
              {
                id: 'b1-u5-l1-conj-1-2',
                type: 'multiple_choice',
                prompt: 'Complete: "nous _____" with the correct form of "être".',
                options: ['sommes', 'suis', 'es', 'est'],
                answer: 0,
                explanation: 'nous sommes — correct conjugation of "être".',
              },
              {
                id: 'b1-u5-l1-conj-1-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Tu _____ français ?" (Are you French?) — form of "être"',
                answer: 'es',
                acceptable: ['es'],
                explanation: 'The correct form is "es".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Clara', fr: 'Tu as vu ? Marc a dit qu\'il quitte son travail.', en: 'Did you see? Marc said he\'s leaving his job.' },
            { speaker: 'B', name: 'Tom', fr: 'Vraiment ? Je me demande pourquoi.', en: 'Really? I wonder why.' },
            { speaker: 'A', name: 'Clara', fr: 'Il a dit que c\'était à cause du stress. Tu sais s\'il a un autre projet ?', en: 'He said it was because of stress. Do you know if he has another project?' },
            { speaker: 'B', name: 'Tom', fr: 'Je ne sais pas. Je vais lui demander s\'il veut en parler.', en: 'I don\'t know. I\'ll ask him if he wants to talk about it.' },
            { speaker: 'A', name: 'Clara', fr: 'Tu penses que les réseaux sociaux ont changé notre façon de travailler ?', en: 'Do you think social media has changed how we work?' },
            { speaker: 'B', name: 'Tom', fr: 'Certainement. D\'un côté, c\'est plus facile de communiquer. De l\'autre, c\'est très addictif.', en: 'Certainly. On one hand, it\'s easier to communicate. On the other, it\'s very addictive.' },
            { speaker: 'A', name: 'Clara', fr: 'Tu sais combien de temps on passe sur notre smartphone par jour ?', en: 'Do you know how much time we spend on our smartphone per day?' },
            { speaker: 'B', name: 'Tom', fr: 'Je crois que c\'est plus de trois heures en moyenne. C\'est énorme !', en: 'I think it\'s more than three hours on average. That\'s huge!' },
          ],
          exercises: [
            {
              id: 'b1-u5-l1-e1',
              type: 'multiple_choice',
              prompt: 'Transform to indirect question: "Viens-tu ?" → "Je me demande _____ tu viens."',
              options: ['si', 'que', 'ce que', 'est-ce que'],
              answer: 0,
              explanation: 'For yes/no questions, use "si": Je me demande si tu viens.',
            },
            {
              id: 'b1-u5-l1-e2',
              type: 'fill_blank',
              prompt: 'Complete: "Il a dit _____ il était fatigué." (that)',
              answer: 'que',
              explanation: 'Reported speech uses "dire que": il a dit qu\'il était fatigué.',
            },
            {
              id: 'b1-u5-l1-e3',
              type: 'multiple_choice',
              prompt: 'Which sentence is correct for "I don\'t know where he lives"?',
              options: ['Je ne sais pas où vit-il.', 'Je ne sais pas où il vit.', 'Je ne sais pas où vit il.', 'Je ne sais pas où est-il.'],
              answer: 1,
              explanation: 'Indirect questions use statement word order: où il vit (not où vit-il).',
            },
            {
              id: 'b1-u5-l1-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "She asks if I am hungry."',
              answer: 'Elle demande si j\'ai faim',
              acceptable: ['elle demande si j ai faim'],
              explanation: 'Indirect question with si: Elle demande si + subject + verb.',
            },
            {
              id: 'b1-u5-l1-e5',
              type: 'true_false',
              prompt: 'In indirect questions, you keep the inversion (e.g. "Je me demande où vas-tu").',
              options: ['True', 'False'],
              answer: 1,
              explanation: 'False. Indirect questions use statement order: "Je me demande où tu vas".',
            },
            {
              id: 'b1-u5-l1-e6',
              type: 'matching',
              prompt: 'Match each tech term to its French name.',
              pairs: [
                { left: 'the computer', right: "l'ordinateur" },
                { left: 'the smartphone', right: 'le smartphone' },
                { left: 'the social network', right: 'le réseau social' },
                { left: 'the password', right: 'le mot de passe' },
                { left: 'the screen', right: "l'écran" },
                { left: 'the data', right: 'les données' },
              ],
              answer: {},
            },
            {
              id: 'b1-u5-l1-e7',
              type: 'multiple_choice',
              prompt: 'What does "se connecter" mean?',
              options: ['To disconnect', 'To log in / connect', 'To download', 'To share'],
              answer: 1,
              explanation: 'Se connecter = to log in / to connect. Se déconnecter = to log out.',
            },
          ],
          activities: [
            {
              id: 'b1-u5-l1-a1',
              type: 'transformation',
              prompt: 'Transform to indirect question: "Où habites-tu ?" → "Je veux savoir _____ "',
              answer: 'où tu habites',
              acceptable: ['où tu habites'],
              explanation: 'Statement word order: où tu habites (no inversion).',
            },
            {
              id: 'b1-u5-l1-a2',
              type: 'transformation',
              prompt: 'Report this speech: Il dit : « Je suis malade. » → Il dit qu\'',
              answer: 'il est malade',
              acceptable: ['il est malade'],
              explanation: 'que + il + est malade. Subject-verb order, present tense stays if main verb is present.',
            },
            {
              id: 'b1-u5-l1-a3',
              type: 'dictation',
              prompt: 'Listen and type what you hear.',
              audioText: 'Je ne sais pas quand il arrive.',
              answer: 'Je ne sais pas quand il arrive.',
              acceptable: ['je ne sais pas quand il arrive'],
              explanation: 'An indirect question with "quand".',
            },
            {
              id: 'b1-u5-l1-a4',
              type: 'word_bank',
              prompt: 'Build: "I downloaded a new app."',
              wordBank: ['J\'ai', 'téléchargé', 'une', 'nouvelle', 'application', 'envoyé'],
              answer: "J'ai téléchargé une nouvelle application",
              acceptable: ['j ai téléchargé une nouvelle application'],
              explanation: 'Passé composé: J\'ai téléchargé + object.',
            },
            {
              id: 'b1-u5-l1-a5',
              type: 'fill_blank',
              prompt: 'Complete: "Je me demande _____ il viendra." (whether)',
              answer: 'si',
              explanation: 'For yes/no indirect questions, use "si".',
            },
            {
              id: 'b1-u5-l1-a6',
              type: 'reorder',
              prompt: 'Reorder: "demander / je / si / vais / je / lui / viendra / il"',
              words: ['Je', 'vais', 'lui', 'demander', 'si', 'il', 'viendra.'],
              answer: 'Je vais lui demander si il viendra.',
              acceptable: ['je vais lui demander si il viendra', 'je vais lui demander s il viendra'],
              explanation: '"si il" contracts to "s\'il" in proper French.',
            },
          ],
          culturalNote:
            "France has a strong tradition of tech skepticism alongside tech adoption. The 'Loi Hadopi' (2009) tried to combat illegal downloading with fines, but was widely mocked. France created the world's first digital ministry in 2017. The CNIL (Commission Nationale de l'Informatique et des Libertés) is one of Europe's strictest data protection agencies — they fined Google €150 million in 2021 for privacy violations. Paris has become a major European AI hub, with Meta's FAIR lab and many startups.",
          estimatedMinutes: 40,
        },
      ],
    },
  ],
};
