import type { Course } from './types';

// B2 — Upper Intermediate French (CEFR B2)
// Emphasizes fluency, nuanced discussions, defending viewpoints, complex texts
export const b2Course: Course = {
  level: 'B2',
  title: 'B2 — Avancé',
  book: 'Parlez B2',
  description:
    "Master the upper-intermediate level. You'll defend complex viewpoints, debate like a native, understand literary and journalistic texts, and master advanced structures like the subjunctive in all contexts, discourse markers, and registers of language.",
  cefrDescription:
    'Can understand the main ideas of complex text on both concrete and abstract topics, including technical discussions in their field of specialization. Can interact with a degree of fluency and spontaneity that makes regular interaction with native speakers quite possible without strain for either party.',
  color: '#7C2D3F',
  units: [
    {
      id: 'b2-u1',
      title: 'Identities and Cultures',
      titleFr: 'Identités et cultures',
      theme: 'Cultural nuances & language registers',
      description: 'Explore francophone identities and master formal vs. informal registers.',
      lessons: [
        {
          id: 'b2-u1-l1',
          title: 'Registers of Language',
          titleFr: 'Les registres de langue',
          description: 'Distinguish formal, standard, and informal registers; know when to use each.',
          objectives: [
            'Identify formal (soutenu), standard (courant), and informal (familier) registers',
            'Use appropriate register in different social contexts',
            'Recognize slang (argot) and verlan',
            'Adapt language to audience',
          ],
          vocabulary: [
            { fr: 'le registre soutenu', en: 'formal register', example: 'Je vous saurais gré de bien vouloir...', exampleEn: 'I would be grateful if you would...', category: 'register' },
            { fr: 'le registre courant', en: 'standard register', example: 'Est-ce que vous pourriez...', exampleEn: 'Could you...', category: 'register' },
            { fr: 'le registre familier', en: 'informal register', example: 'Tu peux...', exampleEn: 'Can you...', category: 'register' },
            { fr: 'l\'argot', en: 'slang', example: 'C\'est ouf ! (= fou)', exampleEn: 'That\'s crazy!', category: 'register' },
            { fr: 'le verlan', en: 'verlan (reversed syllables)', example: 'Une meuf (= femme)', exampleEn: 'A girl/woman', category: 'register' },
            { fr: 'boulot', en: 'job (informal)', example: 'Je vais au boulot.', exampleEn: 'I\'m going to work.', category: 'informal' },
            { fr: 'fric', en: 'money (informal)', example: 'Il a beaucoup de fric.', exampleEn: 'He has a lot of money.', category: 'informal' },
            { fr: 'bagnole', en: 'car (informal)', example: 'Ma bagnole est en panne.', exampleEn: 'My car broke down.', category: 'informal' },
            { fr: 'la bouffe', en: 'food (informal)', example: 'On va manger de la bouffe.', exampleEn: 'We\'re going to eat.', category: 'informal' },
            { fr: 'un potes', en: 'a buddy', example: 'Je sors avec mes potes.', exampleEn: 'I\'m going out with my buddies.', category: 'informal' },
            { fr: 'je vous saurais gré', en: 'I would be grateful (very formal)', example: 'Je vous saurais gré de m\'aider.', exampleEn: 'I would be grateful for your help.', category: 'formal' },
            { fr: 'il convient de', en: 'it is appropriate to (formal)', example: 'Il convient de noter que...', exampleEn: 'It should be noted that...', category: 'formal' },
          ],
          grammar: [
            {
              title: 'Three registers of French',
              explanation:
                "French has three main registers: soutenu (formal, written, speeches), courant (standard, used in most situations), and familier (informal, with friends). The choice depends on context, audience, and relationship. Using the wrong register can sound rude or pretentious.",
              examples: [
                { fr: 'Soutenu: Je vous saurais gré de bien vouloir m\'aider.', en: 'I would be grateful if you would help me.' },
                { fr: 'Courant: Pourriez-vous m\'aider, s\'il vous plaît ?', en: 'Could you help me, please?' },
                { fr: 'Familier: Tu peux m\'aider ?', en: 'Can you help me?' },
              ],
              table: {
                caption: 'Same idea, three registers',
                headers: ['Idea', 'Soutenu', 'Courant', 'Familier'],
                rows: [
                  ['I don\'t know', 'Je l\'ignore', 'Je ne sais pas', 'J\'en sais rien'],
                  ['It\'s expensive', 'Le prix s\'avère élevé', 'C\'est cher', 'C\'est de l\'arnaque'],
                  ['I\'m tired', 'Je suis épuisé', 'Je suis fatigué', 'Je suis claqué'],
                  ['Goodbye', 'Je vous prie d\'agréer...', 'Au revoir', 'Salut / Tchao'],
                ],
              },
              tip: 'When in doubt, use the courant register. Better to be slightly formal than rude.',
            },
            {
              title: 'Verlan — French slang reversal',
              explanation:
                "Verlan (from 'l\'envers' reversed) is a slang that reverses syllables. Common examples: femme → meuf, fou → ouf, arabe → beur. It originated in the banlieues (suburbs) and is now widely understood.",
              examples: [
                { fr: 'femme → meuf', en: 'woman' },
                { fr: 'fou → ouf', en: 'crazy' },
                { fr: 'arabe → beur', en: 'Arab (reclaimed)' },
                { fr: 'pourri → ripou', en: 'corrupt (cop)' },
              ],
              tip: "Verlan is informal — don't use it in professional contexts.",
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'être',
              translation: 'to be',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'suis' },
                { pronoun: 'tu', form: 'es' },
                { pronoun: 'il/elle', form: 'est' },
                { pronoun: 'nous', form: 'sommes' },
                { pronoun: 'vous', form: 'êtes' },
                { pronoun: 'ils/elles', form: 'sont' },
              ],
              sentenceRule: 'Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
              sentenceExamples: [
                { fr: 'Je suis étudiant.', en: 'I am a student.' },
                { fr: 'Tu es français ?', en: 'Are you French?' },
                { fr: 'Nous sommes à Paris.', en: 'We are in Paris.' },
              ],
            },
            {
              infinitive: 'avoir',
              translation: 'to have',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'j\'', form: 'ai' },
                { pronoun: 'tu', form: 'as' },
                { pronoun: 'il/elle', form: 'a' },
                { pronoun: 'nous', form: 'avons' },
                { pronoun: 'vous', form: 'avez' },
                { pronoun: 'ils/elles', form: 'ont' },
              ],
              sentenceRule: 'Subject + avoir + noun. Used for possession, age (J\'ai 20 ans), and expressions like avoir faim/soif/froid. Age uses avoir, NOT être.',
              sentenceExamples: [
                { fr: 'J\'ai un frère.', en: 'I have a brother.' },
                { fr: 'Tu as vingt ans.', en: 'You are twenty.' },
                { fr: 'Il a faim.', en: 'He is hungry.' },
              ],
            }
            ],
            practice: [
              {
                id: 'b2-u1-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "être" for "je":',
                promptFr: 'je _____',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'je suis — correct form of "être".',
              },
              {
                id: 'b2-u1-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "être".',
                options: ['est', 'suis', 'es', 'sommes'],
                answer: 0,
                explanation: 'il/elle est — correct conjugation of "être".',
              },
              {
                id: 'b2-u1-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'The correct form is "suis".',
              },
              {
                id: 'b2-u1-l1-conj-1-1',
                type: 'conjugation',
                prompt: 'Conjugate "avoir" for "tu":',
                promptFr: 'tu _____',
                answer: 'as',
                acceptable: ['as'],
                explanation: 'tu as — correct form of "avoir".',
              },
              {
                id: 'b2-u1-l1-conj-1-2',
                type: 'multiple_choice',
                prompt: 'Complete: "nous _____" with the correct form of "avoir".',
                options: ['avons', 'ai', 'as', 'a'],
                answer: 0,
                explanation: 'nous avons — correct conjugation of "avoir".',
              },
              {
                id: 'b2-u1-l1-conj-1-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Tu _____ vingt ans." (You are twenty.) — form of "avoir"',
                answer: 'as',
                acceptable: ['as'],
                explanation: 'The correct form is "as".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Lucas', fr: 'Salut mec, ça va ? T\'as vu la meuf là-bas, c\'est ouf !', en: 'Hey man, you OK? Did you see the girl over there, that\'s crazy!' },
            { speaker: 'B', name: 'Antoine', fr: 'Lucas, on est dans un entretien, là ! Il faut parler correctement.', en: 'Lucas, we\'re in an interview! You need to speak properly.' },
            { speaker: 'A', name: 'Lucas', fr: 'Oh pardon, monsieur. Je vous prie de m\'excuser pour mon registre inadapté.', en: 'Oh sorry, sir. I beg you to excuse my inappropriate register.' },
            { speaker: 'B', name: 'Antoine', fr: 'Ce n\'est pas nécessaire d\'exagérer non plus. Un langage courant suffit.', en: 'No need to exaggerate either. Standard language is enough.' },
            { speaker: 'A', name: 'Lucas', fr: 'Je comprends. Pourriez-vous me redonner une chance ?', en: 'I understand. Could you give me another chance?' },
            { speaker: 'B', name: 'Antoine', fr: 'Bien sûr. Mais à l\'avenir, il convient de noter que le registre compte autant que le fond.', en: 'Of course. But in the future, it should be noted that register matters as much as content.' },
          ],
          exercises: [
            {
              id: 'b2-u1-l1-e1',
              type: 'multiple_choice',
              prompt: 'Which is the formal (soutenu) way to say "I don\'t know"?',
              options: ['J\'en sais rien', 'Je ne sais pas', 'Je l\'ignore', 'No idea'],
              answer: 2,
              explanation: 'Je l\'ignore is formal. Je ne sais pas is standard. J\'en sais rien is informal.',
            },
            {
              id: 'b2-u1-l1-e2',
              type: 'fill_blank',
              prompt: 'Verlan of "femme" = _____',
              answer: 'meuf',
              explanation: 'Verlan reverses syllables: femme → meuf.',
            },
            {
              id: 'b2-u1-l1-e3',
              type: 'multiple_choice',
              prompt: 'Which word is informal for "car"?',
              options: ['Voiture', 'Véhicule', 'Bagnole', 'Automobile'],
              answer: 2,
              explanation: 'Bagnole is informal. Voiture is standard. Véhicule/automobile are formal.',
            },
            {
              id: 'b2-u1-l1-e4',
              type: 'translate_to_fr',
              prompt: 'Translate (formal): "I would be grateful if you would help me."',
              answer: 'Je vous saurais gré de bien vouloir m\'aider',
              acceptable: ['je vous saurais gré de bien vouloir m aider'],
              explanation: 'Formal expression: je vous saurais gré de + infinitive.',
            },
            {
              id: 'b2-u1-l1-e5',
              type: 'true_false',
              prompt: '"Verlan" is created by reversing the syllables of a word.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. Verlan = l\'envers (reverse). Examples: femme → meuf, fou → ouf.',
            },
          ],
          culturalNote:
            "The French language is regulated by the Académie française, founded in 1635 by Cardinal Richelieu. The 40 'immortels' (members) work to protect French from English influence, suggesting French alternatives to English words (e.g., 'courriel' for 'email'). However, in everyday life, English loanwords like 'le week-end', 'le parking', and 'le shopping' are everywhere.",
          estimatedMinutes: 40,
        },
        {
          id: 'b2-u1-l2',
          title: 'The Francophone World',
          titleFr: 'La francophonie',
          description: 'Discover the diversity of French-speaking countries and their linguistic particularities.',
          objectives: [
            'Identify major francophone countries',
            'Understand regional variations of French',
            'Discuss French as a global language',
            'Recognize Quebec, Belgian, Swiss, African French',
          ],
          vocabulary: [
            { fr: 'la francophonie', en: 'the French-speaking world', example: 'La francophonie compte 300 millions de locuteurs.', exampleEn: 'The French-speaking world has 300 million speakers.', category: 'francophonie' },
            { fr: 'un francophone', en: 'a French speaker', example: 'Il est francophone.', exampleEn: 'He\'s a French speaker.', category: 'francophonie' },
            { fr: 'la langue maternelle', en: 'mother tongue', example: 'Le français est ma langue maternelle.', exampleEn: 'French is my mother tongue.', category: 'language' },
            { fr: 'la langue officielle', en: 'official language', example: 'Le français est langue officielle au Sénégal.', exampleEn: 'French is the official language of Senegal.', category: 'language' },
            { fr: 'le Québec', en: 'Quebec', example: 'Au Québec, on dit "char" pour "voiture".', exampleEn: 'In Quebec, they say "char" for "car".', category: 'regions' },
            { fr: 'la Belgique', en: 'Belgium', example: 'En Belgique, on dit "septante" pour 70.', exampleEn: 'In Belgium, they say "septante" for 70.', category: 'regions' },
            { fr: 'la Suisse', en: 'Switzerland', example: 'En Suisse, on dit "huitante" pour 80.', exampleEn: 'In Switzerland, they say "huitante" for 80.', category: 'regions' },
            { fr: 'l\'Afrique francophone', en: 'French-speaking Africa', example: 'Plusieurs pays africains sont francophones.', exampleEn: 'Several African countries are French-speaking.', category: 'regions' },
            { fr: 'un accent', en: 'an accent', example: 'Il a un accent québécois.', exampleEn: 'He has a Quebec accent.', category: 'language' },
            { fr: 'un régionalisme', en: 'a regionalism', example: 'Ce mot est un régionalisme.', exampleEn: 'This word is a regionalism.', category: 'language' },
          ],
          grammar: [
            {
              title: 'Regional variations of French',
              explanation:
                "French varies across regions. In Quebec, 'char' = car, 'magasiner' = to shop. In Belgium/Switzerland, numbers are simpler (septante, huitante, nonante). In African French, you hear 'en faire le koki' (to gossip).",
              examples: [
                { fr: 'Québec: char (voiture)', en: 'car' },
                { fr: 'Québec: courriel (e-mail)', en: 'email (officially promoted)' },
                { fr: 'Belgique: septante (soixante-dix)', en: 'seventy' },
                { fr: 'Afrique: le go-à (la ville)', en: 'the city (regional)' },
              ],
              tip: 'If you learn French for Canada, study Quebec French specifically — pronunciation and vocabulary differ significantly.',
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'avoir',
              translation: 'to have',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'j\'', form: 'ai' },
                { pronoun: 'tu', form: 'as' },
                { pronoun: 'il/elle', form: 'a' },
                { pronoun: 'nous', form: 'avons' },
                { pronoun: 'vous', form: 'avez' },
                { pronoun: 'ils/elles', form: 'ont' },
              ],
              sentenceRule: 'Subject + avoir + noun. Used for possession, age (J\'ai 20 ans), and expressions like avoir faim/soif/froid. Age uses avoir, NOT être.',
              sentenceExamples: [
                { fr: 'J\'ai un frère.', en: 'I have a brother.' },
                { fr: 'Tu as vingt ans.', en: 'You are twenty.' },
                { fr: 'Il a faim.', en: 'He is hungry.' },
              ],
            }
            ],
            practice: [
              {
                id: 'b2-u1-l2-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "avoir" for "j\'":',
                promptFr: 'j\' _____',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'j\' ai — correct form of "avoir".',
              },
              {
                id: 'b2-u1-l2-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "avoir".',
                options: ['a', 'ai', 'as', 'avons'],
                answer: 0,
                explanation: 'il/elle a — correct conjugation of "avoir".',
              },
              {
                id: 'b2-u1-l2-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "J\'_____ un frère." (I have a brother.) — form of "avoir"',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'The correct form is "ai".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Mélanie', fr: 'D\'où viens-tu, Karim ?', en: 'Where are you from, Karim?' },
            { speaker: 'B', name: 'Karim', fr: 'Je viens du Maroc. Le français est ma deuxième langue, mais on l\'utilise beaucoup.', en: 'I\'m from Morocco. French is my second language, but we use it a lot.' },
            { speaker: 'A', name: 'Mélanie', fr: 'Et toi, Luc ?', en: 'And you, Luc?' },
            { speaker: 'C', name: 'Luc', fr: 'Moi, je viens du Québec. Mon français est un peu différent, avec des mots comme "char" et "magasiner".', en: 'I\'m from Quebec. My French is a bit different, with words like "char" and "magasiner".' },
            { speaker: 'A', name: 'Mélanie', fr: 'C\'est fascinant ! La francophonie est vraiment diverse.', en: 'Fascinating! The French-speaking world is really diverse.' },
            { speaker: 'B', name: 'Karim', fr: 'Oui, on est 300 millions de francophones dans le monde. L\'Afrique est le continent où le français croît le plus.', en: 'Yes, we\'re 300 million French speakers in the world. Africa is the continent where French grows the most.' },
            { speaker: 'C', name: 'Luc', fr: 'Même si nos accents sont différents, on se comprend !', en: 'Even if our accents are different, we understand each other!' },
          ],
          exercises: [
            {
              id: 'b2-u1-l2-e1',
              type: 'multiple_choice',
              prompt: 'How do they say "70" in Belgium?',
              options: ['soixante-dix', 'septante', 'sept-dix', 'septante-dix'],
              answer: 1,
              explanation: 'In Belgium and Switzerland: septante. In France: soixante-dix.',
            },
            {
              id: 'b2-u1-l2-e2',
              type: 'fill_blank',
              prompt: 'Complete: "Au _____, on dit \\"char\\" pour \\"voiture\\"."',
              answer: 'Québec',
              acceptable: ['quebec'],
              explanation: 'Quebec French uses "char" for car.',
            },
            {
              id: 'b2-u1-l2-e3',
              type: 'multiple_choice',
              prompt: 'How many French speakers are there in the world?',
              options: ['30 millions', '100 millions', '300 millions', '1 milliard'],
              answer: 2,
              explanation: 'About 300 million French speakers worldwide, growing fast in Africa.',
            },
            {
              id: 'b2-u1-l2-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "French is my mother tongue."',
              answer: 'Le français est ma langue maternelle',
              acceptable: ['le français est ma langue maternelle'],
              explanation: 'Langue maternelle = mother tongue.',
            },
            {
              id: 'b2-u1-l2-e5',
              type: 'true_false',
              prompt: 'French is growing fastest in Africa.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. Due to population growth, French is expanding rapidly in African countries.',
            },
          ],
          culturalNote:
            "The Organisation Internationale de la Francophonie (OIF) has 88 member states. French is the official language in 29 countries — second only to English. The Democratic Republic of Congo is the most populous French-speaking country (95M people). French is also one of the official languages of the UN, EU, NATO, and the Olympic Games.",
          estimatedMinutes: 35,
        },
      ],
    },
    {
      id: 'b2-u2',
      title: 'Science and Hypothesis',
      titleFr: 'Sciences et hypothèses',
      theme: 'Hypothesis & scientific discourse',
      description: 'Express hypotheses, talk about science and technology, and master conditional structures.',
      lessons: [
        {
          id: 'b2-u2-l1',
          title: 'Hypothesis and Discovery',
          titleFr: 'Hypothèse et découverte',
          description: 'Use advanced conditional structures and scientific vocabulary.',
          objectives: [
            'Use the conditionnel passé for unreal past',
            'Express hypothesis with "si" + plus-que-parfait',
            'Use scientific and technical vocabulary',
            'Discuss technological advances',
          ],
          vocabulary: [
            { fr: 'une hypothèse', en: 'a hypothesis', example: 'Je formule une hypothèse.', exampleEn: 'I form a hypothesis.', category: 'science' },
            { fr: 'une découverte', en: 'a discovery', example: 'C\'est une découverte majeure.', exampleEn: 'It\'s a major discovery.', category: 'science' },
            { fr: 'une expérience', en: 'an experiment', example: 'L\'expérience a échoué.', exampleEn: 'The experiment failed.', category: 'science' },
            { fr: 'la technologie', en: 'technology', example: 'La technologie progresse vite.', exampleEn: 'Technology progresses fast.', category: 'technology' },
            { fr: 'l\'intelligence artificielle', en: 'artificial intelligence', example: 'L\'IA transforme le travail.', exampleEn: 'AI is transforming work.', category: 'technology' },
            { fr: 'les données', en: 'data', example: 'Les données sont collectées.', exampleEn: 'Data is being collected.', category: 'technology' },
            { fr: 'un algorithme', en: 'an algorithm', example: 'Cet algorithme est complexe.', exampleEn: 'This algorithm is complex.', category: 'technology' },
            { fr: 'si j\'avais su', en: 'if I had known', example: 'Si j\'avais su, je ne serais pas venu.', exampleEn: 'If I had known, I wouldn\'t have come.', category: 'hypothesis' },
            { fr: 'j\'aurais dû', en: 'I should have', example: 'J\'aurais dû étudier davantage.', exampleEn: 'I should have studied more.', category: 'hypothesis' },
            { fr: 'à supposer que', en: 'supposing that', example: 'À supposer qu\'il vienne...', exampleEn: 'Supposing he comes...', category: 'hypothesis' },
            { fr: 'en admettant que', en: 'admitting that', example: 'En admettant qu\'il ait raison...', exampleEn: 'Admitting he\'s right...', category: 'hypothesis' },
            { fr: 'pour peu que', en: 'provided that / as long as', example: 'Pour peu qu\'il fasse un effort...', exampleEn: 'As long as he makes an effort...', category: 'hypothesis' },
          ],
          grammar: [
            {
              title: 'Conditionnel passé — unreal past',
              explanation:
                "The conditionnel passé expresses what would have happened but didn't. It is formed with the conditional of avoir/être + past participle. Used with 'si + plus-que-parfait' to express regret or unreal past.",
              examples: [
                { fr: 'Si j\'avais su, je serais venu.', en: 'If I had known, I would have come.' },
                { fr: 'J\'aurais aimé te voir.', en: 'I would have liked to see you.' },
                { fr: 'Tu aurais dû me prévenir.', en: 'You should have warned me.' },
              ],
              table: {
                caption: 'Conditionnel passé of common verbs',
                headers: ['Verb', 'je', 'tu', 'il', 'nous', 'vous', 'ils'],
                rows: [
                  ['être', 'serais été... Ah, wait — would have been', 'aurais été', 'aurait été', 'aurions été', 'auriez été', 'auraient été'],
                  ['avoir', 'aurais eu', 'aurais eu', 'aurait eu', 'aurions eu', 'auriez eu', 'auraient eu'],
                  ['faire', 'aurais fait', 'aurais fait', 'aurait fait', 'aurions fait', 'auriez fait', 'auraient fait'],
                ],
              },
              tip: 'Être and avoir both use avoir as auxiliary in the conditionnel passé: j\'aurais été, j\'aurais eu.',
            },
            {
              title: 'Advanced "si" structures',
              explanation:
                "Beyond the three main 'si' types, French has literary expressions of hypothesis: 'à supposer que' + subjunctive, 'en admettant que' + subjunctive, 'quand bien même' + conditional (even if).",
              examples: [
                { fr: 'À supposer qu\'il vienne, on sera ravis.', en: 'Supposing he comes, we\'ll be delighted.' },
                { fr: 'En admettant qu\'il ait raison, que faire ?', en: 'Admitting he\'s right, what to do?' },
                { fr: 'Quand bien même il serait là, je ne le verrais pas.', en: 'Even if he were there, I wouldn\'t see him.' },
              ],
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'avoir',
              translation: 'to have',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'j\'', form: 'ai' },
                { pronoun: 'tu', form: 'as' },
                { pronoun: 'il/elle', form: 'a' },
                { pronoun: 'nous', form: 'avons' },
                { pronoun: 'vous', form: 'avez' },
                { pronoun: 'ils/elles', form: 'ont' },
              ],
              sentenceRule: 'Subject + avoir + noun. Used for possession, age (J\'ai 20 ans), and expressions like avoir faim/soif/froid. Age uses avoir, NOT être.',
              sentenceExamples: [
                { fr: 'J\'ai un frère.', en: 'I have a brother.' },
                { fr: 'Tu as vingt ans.', en: 'You are twenty.' },
                { fr: 'Il a faim.', en: 'He is hungry.' },
              ],
            }
            ],
            practice: [
              {
                id: 'b2-u2-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "avoir" for "j\'":',
                promptFr: 'j\' _____',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'j\' ai — correct form of "avoir".',
              },
              {
                id: 'b2-u2-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "avoir".',
                options: ['a', 'ai', 'as', 'avons'],
                answer: 0,
                explanation: 'il/elle a — correct conjugation of "avoir".',
              },
              {
                id: 'b2-u2-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "J\'_____ un frère." (I have a brother.) — form of "avoir"',
                answer: 'ai',
                acceptable: ['ai'],
                explanation: 'The correct form is "ai".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Sophie', fr: 'Si l\'intelligence artificielle n\'avait pas été inventée, comment travaillerions-nous aujourd\'hui ?', en: 'If AI hadn\'t been invented, how would we work today?' },
            { speaker: 'B', name: 'Marc', fr: 'Nous aurions continué à faire beaucoup de tâches manuelles. J\'aurais passé des heures à trier des données.', en: 'We would have continued doing many manual tasks. I would have spent hours sorting data.' },
            { speaker: 'A', name: 'Sophie', fr: 'Tu crois qu\'on aurait perdu moins de temps ou plus de temps ?', en: 'Do you think we would have lost less time or more time?' },
            { speaker: 'B', name: 'Marc', fr: 'À supposer que l\'IA devienne trop puissante, on devrait mettre des limites.', en: 'Supposing AI becomes too powerful, we should set limits.' },
            { speaker: 'A', name: 'Sophie', fr: 'Tu as raison. J\'aurais dû y penser plus tôt. L\'éthique est essentielle.', en: 'You\'re right. I should have thought about it earlier. Ethics is essential.' },
            { speaker: 'B', name: 'Marc', fr: 'En admettant qu\'on régule bien l\'IA, elle pourra nous aider énormément.', en: 'Admitting we regulate AI well, it can help us enormously.' },
          ],
          exercises: [
            {
              id: 'b2-u2-l1-e1',
              type: 'multiple_choice',
              prompt: 'Complete: "Si j\'avais su, je _____ venu."',
              options: ['serais', 'aurais', 'suis', 'avais'],
              answer: 0,
              explanation: 'Venir uses être. Conditionnel passé: je serais venu.',
            },
            {
              id: 'b2-u2-l1-e2',
              type: 'fill_blank',
              prompt: 'Complete: "Tu _____ dû étudier davantage." (You should have studied more.)',
              answer: 'aurais',
              explanation: 'Conditionnel passé of devoir: tu aurais dû.',
            },
            {
              id: 'b2-u2-l1-e3',
              type: 'multiple_choice',
              prompt: 'What structure for "If I had known, I would have come"?',
              options: ['Si je sais, je viendrai', 'Si je savais, je viendrais', 'Si j\'avais su, je serais venu', 'Si j\'aurai su, je viendrai'],
              answer: 2,
              explanation: 'Type 3: si + plus-que-parfait + conditionnel passé.',
            },
            {
              id: 'b2-u2-l1-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "I should have warned you."',
              answer: 'J\'aurais dû te prévenir',
              acceptable: ['j aurais dû te prévenir'],
              explanation: 'Conditionnel passé of devoir: j\'aurais dû + infinitive.',
            },
            {
              id: 'b2-u2-l1-e5',
              type: 'true_false',
              prompt: 'The conditionnel passé expresses an unreal past action.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. It expresses what would have happened but didn\'t.',
            },
          ],
          culturalNote:
            "France has a strong scientific tradition: Pierre and Marie Curie (radioactivity), Louis Pasteur (microbiology), Blaise Pascal (mathematics), and more recently CERN (in Switzerland, partly French). The CNRS (Centre National de la Recherche Scientifique) is Europe's largest research organization. France invests heavily in AI — Paris has one of Europe's largest AI research hubs, especially around Meta's FAIR lab.",
          estimatedMinutes: 40,
        },
      ],
    },
    {
      id: 'b2-u3',
      title: 'Politics and Debate',
      titleFr: 'Politique et débat',
      theme: 'Defending viewpoints & complex discourse',
      description: 'Defend complex viewpoints, debate formally, and master discourse markers.',
      lessons: [
        {
          id: 'b2-u3-l1',
          title: 'Defending Your Position',
          titleFr: 'Défendre sa position',
          description: 'Use advanced discourse markers and structures to defend a position formally.',
          objectives: [
            'Use advanced discourse markers (d\'une part... d\'autre part, non seulement... mais aussi)',
            'Express concession and restriction',
            'Use the subjunctive in advanced contexts',
            'Structure a formal debate',
          ],
          vocabulary: [
            { fr: 'd\'une part... d\'autre part', en: 'on one hand... on the other hand', example: 'D\'une part c\'est utile, d\'autre part c\'est cher.', exampleEn: 'On one hand it\'s useful, on the other it\'s expensive.', category: 'discourse' },
            { fr: 'non seulement... mais aussi', en: 'not only... but also', example: 'Non seulement il est intelligent, mais aussi travailleur.', exampleEn: 'Not only is he smart, but also hardworking.', category: 'discourse' },
            { fr: 'toutefois', en: 'however / nevertheless', example: 'Toutefois, il faut noter...', exampleEn: 'However, it should be noted...', category: 'discourse' },
            { fr: 'quoique', en: 'although / albeit', example: 'Quoique fatigué, il continue.', exampleEn: 'Although tired, he continues.', category: 'concession' },
            { fr: 'sans compter que', en: 'not to mention that', example: 'Sans compter que c\'est cher.', exampleEn: 'Not to mention it\'s expensive.', category: 'discourse' },
            { fr: 'dans la mesure où', en: 'insofar as', example: 'Dans la mesure où c\'est possible...', exampleEn: 'Insofar as it\'s possible...', category: 'discourse' },
            { fr: 'il n\'en demeure pas moins que', en: 'nevertheless / it remains the case that', example: 'Il n\'en demeure pas moins que c\'est vrai.', exampleEn: 'It remains the case that it\'s true.', category: 'discourse' },
            { fr: 'sauf si', en: 'unless', example: 'Je viendrai sauf si tu refuses.', exampleEn: 'I\'ll come unless you refuse.', category: 'condition' },
            { fr: 'à condition que', en: 'on condition that', example: 'À condition que tu viennes.', exampleEn: 'On condition that you come.', category: 'condition' },
            { fr: 'le débat', en: 'the debate', example: 'Le débat est passionné.', exampleEn: 'The debate is passionate.', category: 'politics' },
            { fr: 'une opinion', en: 'an opinion', example: 'Chacun a son opinion.', exampleEn: 'Everyone has their opinion.', category: 'politics' },
            { fr: 'voter', en: 'to vote', example: 'Je vais voter demain.', exampleEn: 'I\'m going to vote tomorrow.', category: 'politics' },
          ],
          grammar: [
            {
              title: 'Advanced discourse markers',
              explanation:
                "Discourse markers organize speech and signal relationships between ideas. At B2 level, you should use varied markers, not just 'mais' and 'donc'.",
              examples: [
                { fr: 'D\'une part, le projet est ambitieux ; d\'autre part, il coûte cher.', en: 'On one hand, the project is ambitious; on the other, it\'s expensive.' },
                { fr: 'Non seulement il travaille vite, mais aussi il fait peu d\'erreurs.', en: 'Not only does he work fast, but he also makes few mistakes.' },
                { fr: 'Toutefois, il faut reconnaître que le projet est risqué.', en: 'However, one must acknowledge that the project is risky.' },
                { fr: 'Il n\'en demeure pas moins que la décision revient au patron.', en: 'It remains the case that the decision is up to the boss.' },
              ],
              table: {
                caption: 'Discourse markers by function',
                headers: ['Function', 'Markers'],
                rows: [
                  ['Addition', 'de plus, en outre, non seulement...mais aussi, sans compter que'],
                  ['Opposition', 'cependant, néanmoins, toutefois, quoique, en revanche'],
                  ['Cause', 'car, en effet, dans la mesure où'],
                  ['Condition', 'à condition que, sauf si, pourvu que'],
                  ['Conclusion', 'en somme, en définitive, il n\'en demeure pas moins que'],
                ],
              },
              tip: "Mix formal and standard markers. Overusing 'cependant' sounds academic; vary with 'mais', 'pourtant', 'toutefois'.",
            },
            {
              title: 'Subjunctive after concession',
              explanation:
                "After 'quoique' (although), 'bien que' (although), 'pour que' (so that), and 'sans que' (without), use the subjunctive. These are common in formal writing and debate.",
              examples: [
                { fr: 'Quoiqu\'il soit fatigué, il continue.', en: 'Although he\'s tired, he continues.' },
                { fr: 'Bien qu\'elle ait travaillé, elle a échoué.', en: 'Although she worked, she failed.' },
                { fr: 'Sans qu\'on le lui demande, il a aidé.', en: 'Without anyone asking, he helped.' },
              ],
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'être',
              translation: 'to be',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'suis' },
                { pronoun: 'tu', form: 'es' },
                { pronoun: 'il/elle', form: 'est' },
                { pronoun: 'nous', form: 'sommes' },
                { pronoun: 'vous', form: 'êtes' },
                { pronoun: 'ils/elles', form: 'sont' },
              ],
              sentenceRule: 'Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
              sentenceExamples: [
                { fr: 'Je suis étudiant.', en: 'I am a student.' },
                { fr: 'Tu es français ?', en: 'Are you French?' },
                { fr: 'Nous sommes à Paris.', en: 'We are in Paris.' },
              ],
            },
            {
              infinitive: 'avoir',
              translation: 'to have',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'j\'', form: 'ai' },
                { pronoun: 'tu', form: 'as' },
                { pronoun: 'il/elle', form: 'a' },
                { pronoun: 'nous', form: 'avons' },
                { pronoun: 'vous', form: 'avez' },
                { pronoun: 'ils/elles', form: 'ont' },
              ],
              sentenceRule: 'Subject + avoir + noun. Used for possession, age (J\'ai 20 ans), and expressions like avoir faim/soif/froid. Age uses avoir, NOT être.',
              sentenceExamples: [
                { fr: 'J\'ai un frère.', en: 'I have a brother.' },
                { fr: 'Tu as vingt ans.', en: 'You are twenty.' },
                { fr: 'Il a faim.', en: 'He is hungry.' },
              ],
            }
            ],
            practice: [
              {
                id: 'b2-u3-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "être" for "je":',
                promptFr: 'je _____',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'je suis — correct form of "être".',
              },
              {
                id: 'b2-u3-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "être".',
                options: ['est', 'suis', 'es', 'sommes'],
                answer: 0,
                explanation: 'il/elle est — correct conjugation of "être".',
              },
              {
                id: 'b2-u3-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"',
                answer: 'suis',
                acceptable: ['suis'],
                explanation: 'The correct form is "suis".',
              },
              {
                id: 'b2-u3-l1-conj-1-1',
                type: 'conjugation',
                prompt: 'Conjugate "avoir" for "tu":',
                promptFr: 'tu _____',
                answer: 'as',
                acceptable: ['as'],
                explanation: 'tu as — correct form of "avoir".',
              },
              {
                id: 'b2-u3-l1-conj-1-2',
                type: 'multiple_choice',
                prompt: 'Complete: "nous _____" with the correct form of "avoir".',
                options: ['avons', 'ai', 'as', 'a'],
                answer: 0,
                explanation: 'nous avons — correct conjugation of "avoir".',
              },
              {
                id: 'b2-u3-l1-conj-1-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Tu _____ vingt ans." (You are twenty.) — form of "avoir"',
                answer: 'as',
                acceptable: ['as'],
                explanation: 'The correct form is "as".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Modérateur', fr: 'Madame, quel est votre avis sur la réforme des retraites ?', en: 'Madam, what is your opinion on the pension reform?' },
            { speaker: 'B', name: 'Élue', fr: 'D\'une part, je comprends l\'inquiétude des citoyens. D\'autre part, le système actuel n\'est plus viable à long terme.', en: 'On one hand, I understand citizens\' concerns. On the other hand, the current system is no longer viable long-term.' },
            { speaker: 'A', name: 'Modérateur', fr: 'Mais concrètement, que proposez-vous ?', en: 'But concretely, what do you propose?' },
            { speaker: 'B', name: 'Élue', fr: 'Non seulement il faut relever l\'âge de départ, mais aussi encourager le travail des seniors. Toutefois, cela doit se faire progressivement.', en: 'Not only must we raise the retirement age, but also encourage seniors\' work. However, this must be done gradually.' },
            { speaker: 'A', name: 'Modérateur', fr: 'Et vos opposants disent que c\'est injuste ?', en: 'And your opponents say it\'s unfair?' },
            { speaker: 'B', name: 'Élue', fr: 'Il n\'en demeure pas moins que sans réforme, le système s\'effondrera. Quoique difficiles, ces mesures sont nécessaires.', en: 'It remains the case that without reform, the system will collapse. Although difficult, these measures are necessary.' },
          ],
          exercises: [
            {
              id: 'b2-u3-l1-e1',
              type: 'multiple_choice',
              prompt: 'Complete: "_____ il est intelligent, _____ il travaille dur."',
              options: ['D\'une part... d\'autre part', 'Non seulement... mais aussi', 'Soit... soit', 'Ni... ni'],
              answer: 1,
              explanation: 'Non seulement... mais aussi = not only... but also.',
            },
            {
              id: 'b2-u3-l1-e2',
              type: 'fill_blank',
              prompt: 'Complete: "_____ qu\'il soit malade, il travaille." (Although)',
              answer: 'Bien',
              acceptable: ['quoique'],
              explanation: 'Bien que or quoique + subjunctive = although.',
            },
            {
              id: 'b2-u3-l1-e3',
              type: 'multiple_choice',
              prompt: 'Which means "nevertheless"?',
              options: ['En outre', 'Toutefois', 'En effet', 'Quant à'],
              answer: 1,
              explanation: 'Toutefois = however/nevertheless. En outre = furthermore. En effet = indeed.',
            },
            {
              id: 'b2-u3-l1-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "Not only is she smart, but also hardworking."',
              answer: 'Non seulement elle est intelligente, mais aussi travailleuse',
              acceptable: ['non seulement elle est intelligente mais aussi travailleuse'],
              explanation: 'Non seulement... mais aussi + adjectives.',
            },
            {
              id: 'b2-u3-l1-e5',
              type: 'true_false',
              prompt: '"Bien que" is followed by the subjunctive.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. Bien que + subjunctive: bien qu\'il soit fatigué.',
            },
          ],
          culturalNote:
            "France has a strong tradition of political debate — TV shows like 'C dans l\'air', 'C à vous', and 'Bourdin Direct' feature heated discussions daily. The French 'concours' (debating competition) and 'khâgne' (literary prep class) train students in eloquence. The Académie française defines 'le bon usage' — but the French people themselves constantly debate what is 'correct' French.",
          estimatedMinutes: 40,
        },
      ],
    },
    {
      id: 'b2-u4',
      title: 'Literature and Style',
      titleFr: 'Littérature et style',
      theme: 'Literature & stylistic devices',
      description: 'Discover French literature, understand stylistic devices, and analyze texts.',
      lessons: [
        {
          id: 'b2-u4-l1',
          title: 'French Literary Heritage',
          titleFr: 'Le patrimoine littéraire français',
          description: 'Discover major French authors and learn to analyze literary texts.',
          objectives: [
            'Identify major French authors and works',
            'Recognize literary genres',
            'Use literary vocabulary',
            'Analyze a short text',
          ],
          vocabulary: [
            { fr: 'un roman', en: 'a novel', example: 'J\'ai lu un roman de Victor Hugo.', exampleEn: 'I read a novel by Victor Hugo.', category: 'literature' },
            { fr: 'une nouvelle', en: 'a short story', example: 'Maupassant a écrit des nouvelles.', exampleEn: 'Maupassant wrote short stories.', category: 'literature' },
            { fr: 'un poème', en: 'a poem', example: 'Ce poème est de Baudelaire.', exampleEn: 'This poem is by Baudelaire.', category: 'literature' },
            { fr: 'une pièce de théâtre', en: 'a play', example: 'Cyrano est une pièce de théâtre.', exampleEn: 'Cyrano is a play.', category: 'literature' },
            { fr: 'un auteur', en: 'an author', example: 'Cet auteur est célèbre.', exampleEn: 'This author is famous.', category: 'literature' },
            { fr: 'un personnage', en: 'a character', example: 'Le personnage principal est complexe.', exampleEn: 'The main character is complex.', category: 'literature' },
            { fr: 'un genre littéraire', en: 'a literary genre', example: 'Le roman policier est un genre littéraire.', exampleEn: 'The detective novel is a literary genre.', category: 'literature' },
            { fr: 'le style', en: 'the style', example: 'Son style est unique.', exampleEn: 'Their style is unique.', category: 'literature' },
            { fr: 'une métaphore', en: 'a metaphor', example: 'Cette métaphore est puissante.', exampleEn: 'This metaphor is powerful.', category: 'style' },
            { fr: 'une comparaison', en: 'a comparison', example: 'Il utilise une comparaison.', exampleEn: 'He uses a comparison.', category: 'style' },
            { fr: 'la narration', en: 'the narration', example: 'La narration est au présent.', exampleEn: 'The narration is in present tense.', category: 'style' },
            { fr: 'le symbolisme', en: 'symbolism', example: 'Le symbolisme est riche.', exampleEn: 'The symbolism is rich.', category: 'style' },
          ],
          grammar: [
            {
              title: 'Stylistic devices in French',
              explanation:
                "Literary French uses specific devices: métaphore (metaphor), comparaison (comparison with comme), allitération (sound repetition), hyperbole (exaggeration), litote (understatement). Recognizing these helps you appreciate texts.",
              examples: [
                { fr: 'Métaphore: "Cet homme est un lion." (He IS a lion)', en: 'Direct comparison without "like".' },
                { fr: 'Comparaison: "Cet homme est courageux comme un lion."', en: 'Comparison with "comme".' },
                { fr: 'Hyperbole: "Je meurs de faim." (I\'m dying of hunger)', en: 'Exaggeration.' },
                { fr: 'Litote: "Va, je ne te hais point." (le Cid) — meaning "I love you."', en: 'Understatement expressing the opposite.' },
              ],
              tip: "Famous French litotes: 'Ce n\'est pas mauvais' (= it's excellent), 'Je ne te déteste pas' (= I love you).",
            },
            {
              title: 'The "passé simple" — literary past tense',
              explanation:
                "The passé simple is used in literary texts (novels, history) for completed past actions. It is rarely used in spoken French but you must recognize it. Common forms: il aima, il finit, il vendit, il fut, il eut.",
              examples: [
                { fr: 'Il aima cette femme toute sa vie.', en: 'He loved this woman all his life.' },
                { fr: 'Elle naquit en 1900 et mourut en 1980.', en: 'She was born in 1900 and died in 1980.' },
                { fr: 'Le roi vit le château et l\'admira.', en: 'The king saw the castle and admired it.' },
              ],
              table: {
                caption: 'Passé simple of common verbs',
                headers: ['Verb', 'il form'],
                rows: [
                  ['aimer', 'aima'],
                  ['finir', 'finit'],
                  ['vend re', 'vendit'],
                  ['être', 'fut'],
                  ['avoir', 'eut'],
                  ['aller', 'alla'],
                  ['faire', 'fit'],
                  ['venir', 'vint'],
                ],
              },
              tip: 'You don\'t need to USE the passé simple in conversation, but you should RECOGNIZE it when reading.',
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'vouloir',
              translation: 'to want',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'veux' },
                { pronoun: 'tu', form: 'veux' },
                { pronoun: 'il/elle', form: 'veut' },
                { pronoun: 'nous', form: 'voulons' },
                { pronoun: 'vous', form: 'voulez' },
                { pronoun: 'ils/elles', form: 'veulent' },
              ],
              sentenceRule: 'Subject + vouloir + noun/infinitive. Je voudrais (conditional) = I would like — polite form for ordering. Irregular.',
              sentenceExamples: [
                { fr: 'Je veux un café.', en: 'I want a coffee.' },
                { fr: 'Tu veux venir ?', en: 'Do you want to come?' },
                { fr: 'Je voudrais un thé.', en: 'I would like a tea.' },
              ],
            },
            {
              infinitive: 'prendre',
              translation: 'to take',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'prends' },
                { pronoun: 'tu', form: 'prends' },
                { pronoun: 'il/elle', form: 'prend' },
                { pronoun: 'nous', form: 'prenons' },
                { pronoun: 'vous', form: 'prenez' },
                { pronoun: 'ils/elles', form: 'prennent' },
              ],
              sentenceRule: 'Subject + prendre + transport (Je prends le métro). Also: prendre un café, prendre le petit-déjeuner. Irregular -re verb.',
              sentenceExamples: [
                { fr: 'Je prends le bus.', en: 'I take the bus.' },
                { fr: 'Tu prends un café ?', en: 'Will you have a coffee?' },
                { fr: 'Nous prenons le train.', en: 'We take the train.' },
              ],
            }
            ],
            practice: [
              {
                id: 'b2-u4-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "vouloir" for "je":',
                promptFr: 'je _____',
                answer: 'veux',
                acceptable: ['veux'],
                explanation: 'je veux — correct form of "vouloir".',
              },
              {
                id: 'b2-u4-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "vouloir".',
                options: ['veut', 'veux', 'veux', 'voulons'],
                answer: 0,
                explanation: 'il/elle veut — correct conjugation of "vouloir".',
              },
              {
                id: 'b2-u4-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Je _____ un café." (I want a coffee.) — form of "vouloir"',
                answer: 'veux',
                acceptable: ['veux'],
                explanation: 'The correct form is "veux".',
              },
              {
                id: 'b2-u4-l1-conj-1-1',
                type: 'conjugation',
                prompt: 'Conjugate "prendre" for "tu":',
                promptFr: 'tu _____',
                answer: 'prends',
                acceptable: ['prends'],
                explanation: 'tu prends — correct form of "prendre".',
              },
              {
                id: 'b2-u4-l1-conj-1-2',
                type: 'multiple_choice',
                prompt: 'Complete: "nous _____" with the correct form of "prendre".',
                options: ['prenons', 'prends', 'prends', 'prend'],
                answer: 0,
                explanation: 'nous prenons — correct conjugation of "prendre".',
              },
              {
                id: 'b2-u4-l1-conj-1-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Tu _____ un café ?" (Will you have a coffee?) — form of "prendre"',
                answer: 'prends',
                acceptable: ['prends'],
                explanation: 'The correct form is "prends".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Prof', fr: 'Aujourd\'hui, nous allons étudier un extrait des "Misérables" de Victor Hugo. Qui connaît cette œuvre ?', en: 'Today, we\'ll study an extract from "Les Misérables" by Victor Hugo. Who knows this work?' },
            { speaker: 'B', name: 'Élève', fr: 'C\'est un roman du XIXe siècle. Le personnage principal est Jean Valjean, n\'est-ce pas ?', en: 'It\'s a 19th-century novel. The main character is Jean Valjean, right?' },
            { speaker: 'A', name: 'Prof', fr: 'Exactement. Hugo utilise de nombreuses métaphores. Par exemple, "la nuit de l\'ignorance" est une métaphore de l\'éducation.', en: 'Exactly. Hugo uses many metaphors. For example, "the night of ignorance" is a metaphor for education.' },
            { speaker: 'B', name: 'Élève', fr: 'Et le style ? Hugo emploie le passé simple, non ?', en: 'And the style? Hugo uses the passé simple, right?' },
            { speaker: 'A', name: 'Prof', fr: 'Oui, comme dans "Il aima Cosette profondément." Le passé simple est caractéristique du roman classique.', en: 'Yes, as in "He loved Cosette profoundly." The passé simple is characteristic of the classical novel.' },
            { speaker: 'B', name: 'Élève', fr: 'C\'est fascinant ! La littérature française est riche.', en: 'Fascinating! French literature is rich.' },
          ],
          exercises: [
            {
              id: 'b2-u4-l1-e1',
              type: 'multiple_choice',
              prompt: 'Who wrote "Les Misérables"?',
              options: ['Émile Zola', 'Victor Hugo', 'Marcel Proust', 'Albert Camus'],
              answer: 1,
              explanation: 'Victor Hugo wrote Les Misérables (1862). A monumental French novel.',
            },
            {
              id: 'b2-u4-l1-e2',
              type: 'fill_blank',
              prompt: 'Complete: "Ce homme est un lion" est une _____.',
              answer: 'métaphore',
              explanation: 'A direct comparison without "comme" is a metaphor.',
            },
            {
              id: 'b2-u4-l1-e3',
              type: 'multiple_choice',
              prompt: 'What is the passé simple of "être" for "il"?',
              options: ['était', 'a été', 'fut', 'sera'],
              answer: 2,
              explanation: 'Il fut = he was (literary past).',
            },
            {
              id: 'b2-u4-l1-e4',
              type: 'translate_to_fr',
              prompt: 'Translate: "This poem is by Baudelaire."',
              answer: 'Ce poème est de Baudelaire',
              acceptable: ['ce poème est de baudelaire'],
              explanation: 'Use "être de" to indicate authorship: est de [author].',
            },
            {
              id: 'b2-u4-l1-e5',
              type: 'true_false',
              prompt: 'The passé simple is commonly used in spoken French.',
              options: ['True', 'False'],
              answer: 1,
              explanation: 'False. It is used in literature, not in everyday speech.',
            },
          ],
          culturalNote:
            "France has 16 Nobel Prize winners in Literature — more than any other country. Major authors: Molière (theater), Victor Hugo (romanticism), Marcel Proust (modernism), Albert Camus (existentialism), Simone de Beauvoir (feminism). The 'Prix Goncourt' is France's most prestigious literary prize, awarded every November. Reading French literature is one of the best ways to reach true fluency.",
          estimatedMinutes: 40,
        },
      ],
    },
    {
      id: 'b2-u5',
      title: 'Economy and Globalization',
      titleFr: 'Économie et mondialisation',
      theme: 'Economy, abstract nouns & complex sentences',
      description: 'Discuss economic issues, globalization, and use complex sentence structures.',
      lessons: [
        {
          id: 'b2-u5-l1',
          title: 'The Global Economy',
          titleFr: "L'économie mondiale",
          description: 'Use economic vocabulary and complex sentence structures to debate globalization.',
          objectives: [
            'Use economic vocabulary (croissance, chômage, inflation)',
            'Form complex sentences with "bien que", "quoique"',
            'Use nominalization (verbs → abstract nouns)',
            'Discuss pros and cons of globalization',
          ],
          vocabulary: [
            { fr: "l'économie", en: 'the economy', example: "L'économie mondiale.", exampleEn: 'The global economy.', category: 'economy' },
            { fr: 'la croissance', en: 'growth (economic)', example: 'La croissance est forte.', exampleEn: 'Growth is strong.', category: 'economy' },
            { fr: 'le chômage', en: 'unemployment', example: 'Le chômage baisse.', exampleEn: 'Unemployment is falling.', category: 'economy' },
            { fr: "l'inflation", en: 'inflation', example: "L'inflation augmente.", exampleEn: 'Inflation is rising.', category: 'economy' },
            { fr: 'la récession', en: 'recession', example: 'Une récession économique.', exampleEn: 'An economic recession.', category: 'economy' },
            { fr: 'la crise', en: 'crisis', example: 'La crise de 2008.', exampleEn: 'The 2008 crisis.', category: 'economy' },
            { fr: 'la mondialisation', en: 'globalization', example: 'La mondialisation a des avantages.', exampleEn: 'Globalization has advantages.', category: 'globalization' },
            { fr: 'le commerce', en: 'trade / commerce', example: 'Le commerce international.', exampleEn: 'International trade.', category: 'economy' },
            { fr: "l'importation", en: 'import', example: "L'importation de produits.", exampleEn: 'Importing products.', category: 'economy' },
            { fr: "l'exportation", en: 'export', example: "L'exportation de vin.", exampleEn: 'Exporting wine.', category: 'economy' },
            { fr: 'la concurrence', en: 'competition', example: 'La concurrence est rude.', exampleEn: 'Competition is fierce.', category: 'economy' },
            { fr: 'le marché', en: 'the market', example: 'Le marché libre.', exampleEn: 'The free market.', category: 'economy' },
            { fr: 'le PIB', en: 'GDP', example: 'Le PIB français.', exampleEn: 'The French GDP.', category: 'economy' },
            { fr: 'le pouvoir d\'achat', en: 'purchasing power', example: 'Le pouvoir d\'achat diminue.', exampleEn: 'Purchasing power is decreasing.', category: 'economy' },
            { fr: 'le salaire minimum', en: 'minimum wage', example: 'Le SMIC, salaire minimum.', exampleEn: 'The SMIC, minimum wage.', category: 'economy' },
            { fr: 'la pauvreté', en: 'poverty', example: 'Lutter contre la pauvreté.', exampleEn: 'Fight against poverty.', category: 'economy' },
            { fr: 'les inégalités', en: 'inequalities', example: 'Les inégalités sociales.', exampleEn: 'Social inequalities.', category: 'economy' },
            { fr: 'le développement durable', en: 'sustainable development', example: 'Le développement durable est essentiel.', exampleEn: 'Sustainable development is essential.', category: 'globalization' },
            { fr: 'une multinationale', en: 'a multinational corporation', example: 'Une multinationale américaine.', exampleEn: 'An American multinational.', category: 'economy' },
            { fr: 'délocaliser', en: 'to offshore / outsource', example: 'Délocaliser la production.', exampleEn: 'To offshore production.', category: 'verbs' },
          ],
          grammar: [
            {
              title: 'Nominalization — turning verbs into abstract nouns',
              explanation:
                "In formal French (especially B2/C1 level), verbs are often turned into abstract nouns. This makes speech more sophisticated: 'la croissance' (growth) instead of 'grandir' (to grow), 'le développement' (development) instead of 'développer' (to develop). Common suffixes: -tion, -ment, -age, -ure, -esse.",
              examples: [
                { fr: 'développer → le développement', en: 'to develop → development' },
                { fr: 'croître → la croissance', en: 'to grow → growth' },
                { fr: 'décider → la décision', en: 'to decide → decision' },
                { fr: 'gouverner → le gouvernement', en: 'to govern → government' },
              ],
              tip: 'Abstract nouns let you express complex ideas compactly. Use them in formal writing and debates.',
            },
            {
              title: 'Complex sentences with concession',
              explanation:
                "At B2 level, you should master concession structures: 'bien que' + subjunctive, 'quoique' + subjunctive, 'sans que' + subjunctive, 'tout en' + gerund. These show nuance in arguments.",
              examples: [
                { fr: 'Bien que la mondialisation ait des avantages, elle crée des inégalités.', en: 'Although globalization has advantages, it creates inequalities.' },
                { fr: 'Quoique le PIB augmente, le chômage reste élevé.', en: 'Although GDP is increasing, unemployment remains high.' },
                { fr: 'Le gouvernement a agi sans que les citoyens soient consultés.', en: 'The government acted without citizens being consulted.' },
                { fr: 'Tout en reconnaissant les difficultés, je reste optimiste.', en: 'While acknowledging the difficulties, I remain optimistic.' },
              ],
              tip: 'After bien que / quoique / sans que / pour que / avant que → always use SUBJUNCTIVE.',
            },
            {
              title: 'Expressing cause and consequence formally',
              explanation:
                "Formal French uses several structures to express cause and consequence: 'en raison de' + noun, 'grâce à' + noun (positive), 'à cause de' + noun (negative), 'étant donné que' + indicative, 'dans la mesure où' + indicative.",
              examples: [
                { fr: 'En raison de la crise, le chômage a augmenté.', en: 'Due to the crisis, unemployment increased.' },
                { fr: 'Étant donné que la demande baisse, les prix vont suivre.', en: 'Given that demand is falling, prices will follow.' },
                { fr: 'Dans la mesure où les salaires stagnent, le pouvoir d\'achat diminue.', en: 'Insofar as wages stagnate, purchasing power decreases.' },
              ],
            },
          ],
                    conjugation: {
            verbs: [
            {
              infinitive: 'aller',
              translation: 'to go',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'vais' },
                { pronoun: 'tu', form: 'vas' },
                { pronoun: 'il/elle', form: 'va' },
                { pronoun: 'nous', form: 'allons' },
                { pronoun: 'vous', form: 'allez' },
                { pronoun: 'ils/elles', form: 'vont' },
              ],
              sentenceRule: 'Subject + aller + preposition + place. à + le = au, à + les = aux. Also: aller + infinitive = near future (Je vais manger).',
              sentenceExamples: [
                { fr: 'Je vais au cinéma.', en: 'I go to the cinema.' },
                { fr: 'Nous allons à Paris.', en: 'We go to Paris.' },
                { fr: 'Je vais manger.', en: 'I am going to eat.' },
              ],
            },
            {
              infinitive: 'être',
              translation: 'to be',
              tense: 'Présent',
              conjugations: [
                { pronoun: 'je', form: 'suis' },
                { pronoun: 'tu', form: 'es' },
                { pronoun: 'il/elle', form: 'est' },
                { pronoun: 'nous', form: 'sommes' },
                { pronoun: 'vous', form: 'êtes' },
                { pronoun: 'ils/elles', form: 'sont' },
              ],
              sentenceRule: 'Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
              sentenceExamples: [
                { fr: 'Je suis étudiant.', en: 'I am a student.' },
                { fr: 'Tu es français ?', en: 'Are you French?' },
                { fr: 'Nous sommes à Paris.', en: 'We are in Paris.' },
              ],
            }
            ],
            practice: [
              {
                id: 'b2-u5-l1-conj-0-1',
                type: 'conjugation',
                prompt: 'Conjugate "aller" for "je":',
                promptFr: 'je _____',
                answer: 'vais',
                acceptable: ['vais'],
                explanation: 'je vais — correct form of "aller".',
              },
              {
                id: 'b2-u5-l1-conj-0-2',
                type: 'multiple_choice',
                prompt: 'Complete: "il/elle _____" with the correct form of "aller".',
                options: ['va', 'vais', 'vas', 'allons'],
                answer: 0,
                explanation: 'il/elle va — correct conjugation of "aller".',
              },
              {
                id: 'b2-u5-l1-conj-0-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Je _____ au cinéma." (I go to the cinema.) — form of "aller"',
                answer: 'vais',
                acceptable: ['vais'],
                explanation: 'The correct form is "vais".',
              },
              {
                id: 'b2-u5-l1-conj-1-1',
                type: 'conjugation',
                prompt: 'Conjugate "être" for "tu":',
                promptFr: 'tu _____',
                answer: 'es',
                acceptable: ['es'],
                explanation: 'tu es — correct form of "être".',
              },
              {
                id: 'b2-u5-l1-conj-1-2',
                type: 'multiple_choice',
                prompt: 'Complete: "nous _____" with the correct form of "être".',
                options: ['sommes', 'suis', 'es', 'est'],
                answer: 0,
                explanation: 'nous sommes — correct conjugation of "être".',
              },
              {
                id: 'b2-u5-l1-conj-1-3',
                type: 'fill_blank',
                prompt: 'Fill in the blank: "Tu _____ français ?" (Are you French?) — form of "être"',
                answer: 'es',
                acceptable: ['es'],
                explanation: 'The correct form is "es".',
              },
            ],
          },
dialogue: [
            { speaker: 'A', name: 'Moderateur', fr: 'Aujourd\'hui, nous débattrons de la mondialisation. Madame, votre avis ?', en: 'Today, we will debate globalization. Madam, your opinion?' },
            { speaker: 'B', name: 'Économiste', fr: 'Bien que la mondialisation ait créé des richesses, elle a aussi creusé les inégalités. Le pouvoir d\'achat des classes moyennes stagne.', en: 'Although globalization has created wealth, it has also deepened inequalities. Middle-class purchasing power is stagnating.' },
            { speaker: 'A', name: 'Moderateur', fr: 'Et vous, monsieur ? Êtes-vous d\'accord ?', en: 'And you, sir? Do you agree?' },
            { speaker: 'C', name: 'Entrepreneur', fr: 'Pas tout à fait. Étant donné que le commerce international s\'est développé, des millions de personnes sont sorties de la pauvreté, surtout en Asie.', en: 'Not quite. Given that international trade has developed, millions of people have escaped poverty, especially in Asia.' },
            { speaker: 'B', name: 'Économiste', fr: 'Je le concède. Toutefois, la délocalisation a détruit des emplois dans les pays développés. Dans la mesure où les entreprises cherchent le moindre coût, les travailleurs locaux pâtissent.', en: 'I concede that. However, offshoring has destroyed jobs in developed countries. Insofar as companies seek the lowest cost, local workers suffer.' },
            { speaker: 'C', name: 'Entrepreneur', fr: 'Sans que cela soit faux, il faut reconnaître que de nouveaux secteurs ont émergé. Le développement durable crée aujourd\'hui de nombreux emplois.', en: 'Without that being false, we must acknowledge that new sectors have emerged. Sustainable development today creates numerous jobs.' },
            { speaker: 'A', name: 'Moderateur', fr: 'Pour conclure, la mondialisation a donc des effets contrastés. Merci à nos invités.', en: 'To conclude, globalization thus has mixed effects. Thank you to our guests.' },
          ],
          exercises: [
            {
              id: 'b2-u5-l1-e1',
              type: 'multiple_choice',
              prompt: 'Complete with the correct mood: "Bien qu\'il _____ fatigué, il travaille."',
              options: ['est', 'soit', 'était', 'sera'],
              answer: 1,
              explanation: 'Bien que + subjunctive: soit.',
            },
            {
              id: 'b2-u5-l1-e2',
              type: 'multiple_choice',
              prompt: 'Which expression introduces a NEGATIVE cause?',
              options: ['Grâce à', 'En raison de', 'À cause de', 'Étant donné que'],
              answer: 2,
              explanation: 'À cause de = because of (negative). Grâce à = thanks to (positive).',
            },
            {
              id: 'b2-u5-l1-e3',
              type: 'fill_blank',
              prompt: 'Complete: "_____ la crise, le chômage a augmenté." (Due to the crisis)',
              answer: 'En raison de',
              acceptable: ['en raison de', "à cause de"],
              explanation: 'En raison de + noun = due to. (À cause de also works.)',
            },
            {
              id: 'b2-u5-l1-e4',
              type: 'multiple_choice',
              prompt: 'Which is the nominalization of "développer" (to develop)?',
              options: ['le développement', 'la développement', 'le développe', 'la développe'],
              answer: 0,
              explanation: 'Développer → le développement (m).',
            },
            {
              id: 'b2-u5-l1-e5',
              type: 'true_false',
              prompt: 'After "sans que", you use the subjunctive mood.',
              options: ['True', 'False'],
              answer: 0,
              explanation: 'True. Sans que + subjunctive: "sans que les citoyens soient consultés".',
            },
            {
              id: 'b2-u5-l1-e6',
              type: 'matching',
              prompt: 'Match each economic term to its French name.',
              pairs: [
                { left: 'the economy', right: "l'économie" },
                { left: 'unemployment', right: 'le chômage' },
                { left: 'inflation', right: "l'inflation" },
                { left: 'globalization', right: 'la mondialisation' },
                { left: 'GDP', right: 'le PIB' },
                { left: 'crisis', right: 'la crise' },
              ],
              answer: {},
            },
            {
              id: 'b2-u5-l1-e7',
              type: 'translate_to_fr',
              prompt: 'Translate: "Although the GDP is increasing, unemployment remains high."',
              answer: 'Bien que le PIB augmente, le chômage reste élevé',
              acceptable: ['bien que le pib augmente le chômage reste élevé'],
              explanation: 'Bien que + subjunctive (augmente), then main clause.',
            },
          ],
          activities: [
            {
              id: 'b2-u5-l1-a1',
              type: 'transformation',
              prompt: 'Transform: "Le PIB augmente." → "_____ que le PIB augmente, le chômage reste élevé." (Although)',
              answer: 'Bien',
              acceptable: ['bien', 'quoique'],
              explanation: 'Bien que or quoique + subjunctive for concession.',
            },
            {
              id: 'b2-u5-l1-a2',
              type: 'transformation',
              prompt: 'Nominalize: "décider" (verb) → ?',
              answer: 'la décision',
              acceptable: ['la décision'],
              explanation: 'Verb → abstract noun: décider → la décision.',
            },
            {
              id: 'b2-u5-l1-a3',
              type: 'transformation',
              prompt: 'Nominalize: "gouverner" (to govern) → ?',
              answer: 'le gouvernement',
              acceptable: ['le gouvernement'],
              explanation: 'Verb → abstract noun: gouverner → le gouvernement.',
            },
            {
              id: 'b2-u5-l1-a4',
              type: 'dictation',
              prompt: 'Listen and type what you hear.',
              audioText: 'En raison de la crise, le chômage a augmenté.',
              answer: 'En raison de la crise, le chômage a augmenté.',
              acceptable: ['en raison de la crise le chômage a augmenté'],
              explanation: 'Formal expression of cause.',
            },
            {
              id: 'b2-u5-l1-a5',
              type: 'word_bank',
              prompt: 'Build: "Although globalization has advantages, it creates inequalities."',
              wordBank: ['Bien', 'que', 'la', 'mondialisation', 'ait', 'des', 'avantages,', 'elle', 'crée', 'des', 'inégalités.'],
              answer: 'Bien que la mondialisation ait des avantages elle crée des inégalités',
              acceptable: ['bien que la mondialisation ait des avantages elle crée des inégalités'],
              explanation: 'Bien que + subjunctive (ait), main clause.',
            },
            {
              id: 'b2-u5-l1-a6',
              type: 'fill_blank',
              prompt: 'Complete: "Dans la _____ où les salaires stagnent, le pouvoir d\'achat diminue." (insofar as)',
              answer: 'mesure',
              explanation: 'Dans la mesure où = insofar as. Formal connector.',
            },
            {
              id: 'b2-u5-l1-a7',
              type: 'reorder',
              prompt: 'Reorder: "inégalités / la / creusé / mondialisation / a / des"',
              words: ['La', 'mondialisation', 'a', 'creusé', 'des', 'inégalités.'],
              answer: 'La mondialisation a creusé des inégalités.',
              acceptable: ['la mondialisation a creusé des inégalités'],
              explanation: 'Subject + verb + object. "Creuser des inégalités" = deepen inequalities.',
            },
          ],
          culturalNote:
            "France is the world's 7th largest economy by GDP. It has a mixed economy with strong state intervention — the government owns shares in major companies like Renault, EDF (electricity), and Air France. The famous 'SMIC' (Salaire Minimum Interprofessionnel de Croissance) is France's minimum wage — about €1,398/month net in 2024. French workers work fewer hours than most (35-hour work week) but are among the most productive per hour in the world. The French welfare state ('la Sécurité Sociale') is one of the most generous in Europe.",
          estimatedMinutes: 45,
        },
      ],
    },
  ],
};
