import type { TestQuestion } from './types';

// TCF — Test de Connaissance du Français (Expanded Question Bank)
// Administered by France Éducation International (FEI).
// Real exam: Reading 29Q/25min (progressive A1→C2), Listening 29Q/25min (progressive),
// Language structures (grammar/vocab) integrated into reading. 3 mandatory sections, plus optional speaking/writing.
// This expanded bank provides 3 full practice tests per section (135 questions total).

export interface PracticeTest {
  id: string;
  title: string;
  titleFr: string;
  description: string;
  questions: TestQuestion[];
}

export interface ExpandedTestSection {
  id: string; // 'reading' | 'listening' | 'language_structures'
  title: string;
  titleFr: string;
  description: string;
  icon: string;
  tests: PracticeTest[];
}

// ---------------------------------------------------------------------------
// READING COMPREHENSION — 3 tests × 15 questions, progressive A1 → B2/C1
// ---------------------------------------------------------------------------

const tcfReadingTest1: PracticeTest = {
  id: 'tcf-reading-test-1',
  title: 'Reading Practice Test 1',
  titleFr: 'Compréhension écrite — Test 1',
  description: '15 questions à difficulté progressive, du niveau A1 au niveau B2.',
  questions: [
    {
      id: 'tcf-r1-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Lisez : « Bonjour, je m\'appelle Lucas. J\'habite à Lyon. J\'ai 25 ans. » Que sait-on de Lucas ?',
      promptFr: 'Que sait-on de Lucas ?',
      options: [
        'Il s\'appelle Pierre.',
        'Il habite à Paris.',
        'Il a 25 ans et habite à Lyon.',
        'Il a 35 ans.',
      ],
      answer: 2,
      explanation: 'Le texte dit : "Je m\'appelle Lucas. J\'habite à Lyon. J\'ai 25 ans."',
    },
    {
      id: 'tcf-r1-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Lisez : « La pharmacie est fermée le dimanche. » Quand la pharmacie est-elle fermée ?',
      promptFr: 'Quand la pharmacie est-elle fermée ?',
      options: ['Le samedi', 'Le lundi', 'Le dimanche', 'Tous les jours'],
      answer: 2,
      explanation: 'Le texte indique : "La pharmacie est fermée le dimanche."',
    },
    {
      id: 'tcf-r1-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Lisez : « Julien a rendez-vous chez le dentiste à 16h. Il sort du bureau à 15h pour ne pas être en retard. » À quelle heure Julien sort-il du bureau ?',
      promptFr: 'À quelle heure Julien sort-il du bureau ?',
      options: ['À 16h', 'À 15h', 'À 15h30', 'À 14h'],
      answer: 1,
      explanation: 'Le texte dit : "Il sort du bureau à 15h pour ne pas être en retard."',
    },
    {
      id: 'tcf-r1-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Lisez l\'annonce : « Cours de cuisine italienne, le samedi matin de 10h à 12h. 25 € la séance, ingrédients fournis. Inscription au 04 90 12 34 56. » Que comprend le prix ?',
      promptFr: 'Que comprend le prix ?',
      options: [
        'Les ingrédients uniquement',
        'Le cours et les ingrédients',
        'Le repas du midi',
        'Un livre de cuisine',
      ],
      answer: 1,
      explanation: '"25 € la séance, ingrédients fournis" : le prix comprend le cours et les ingrédients.',
    },
    {
      id: 'tcf-r1-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Lisez : « Demain, je vais chez mes parents. Je resterai jusqu\'à dimanche. » Combien de temps restera-t-il ?',
      promptFr: 'Combien de temps restera-t-il ?',
      options: [
        'Un jour',
        'Jusqu\'à dimanche',
        'Une semaine complète',
        'Un mois',
      ],
      answer: 1,
      explanation: 'Le texte dit : "Je resterai jusqu\'à dimanche."',
    },
    {
      id: 'tcf-r1-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Lisez le courriel : « Bonjour Madame, je vous informe que je ne pourrai pas assister à la réunion de demain après-midi. Mon train a été annulé en raison d\'une grève. Pourriez-vous m\'envoyer le compte-rendu ? Cordialement. » Pourquoi l\'expéditeur ne peut-il pas venir ?',
      promptFr: 'Pourquoi l\'expéditeur ne peut-il pas venir ?',
      options: [
        'Il est malade.',
        'Son train a été annulé en raison d\'une grève.',
        'Il a un autre rendez-vous.',
        'Il a oublié.',
      ],
      answer: 1,
      explanation: 'L\'expéditeur dit : "Mon train a été annulé en raison d\'une grève."',
    },
    {
      id: 'tcf-r1-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Lisez l\'article : « Selon une récente enquête, les Français lisent en moyenne 25 minutes par jour, contre 35 il y a dix ans. La baisse touche surtout les magazines, tandis que la lecture de romans reste stable. » Que baisse le plus ?',
      promptFr: 'Que baisse le plus ?',
      options: [
        'La lecture de romans',
        'La lecture de magazines',
        'La lecture numérique',
        'La lecture pour les enfants',
      ],
      answer: 1,
      explanation: 'L\'article dit : "La baisse touche surtout les magazines".',
    },
    {
      id: 'tcf-r1-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Lisez : « Bien que la mairie ait promis de nouvelles pistes cyclables, rien n\'a encore été fait. Les associations craignent que le projet ne soit définitivement abandonné. » Que craignent les associations ?',
      promptFr: 'Que craignent les associations ?',
      options: [
        'Que le projet soit abandonné définitivement',
        'Que trop de pistes soient construites',
        'Que le projet avance trop vite',
        'Que les cyclistes soient satisfaits',
      ],
      answer: 0,
      explanation: 'Les associations "craignent que le projet ne soit définitivement abandonné".',
    },
    {
      id: 'tcf-r1-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Lisez le témoignage : « Je travaille en open-space depuis deux ans. Au début, j\'aimais l\'ambiance, mais le bruit me fatigue de plus en plus. J\'ai demandé à mon manager un casque anti-bruit, mais il a refusé. » Que demande le témoignage ?',
      promptFr: 'Que demande le témoignage ?',
      options: [
        'Un changement de bureau',
        'Un casque anti-bruit',
        'Une augmentation de salaire',
        'Le télétravail',
      ],
      answer: 1,
      explanation: 'Le témoignage dit : "J\'ai demandé à mon manager un casque anti-bruit".',
    },
    {
      id: 'tcf-r1-10',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Lisez l\'extrait : « Contrairement à ses prédécesseurs, le nouveau directeur a choisi de centraliser les décisions, suscitant la grogne des chefs de service, qui se sentent dépossédés de leurs prérogatives. » Comment les chefs de service réagissent-ils ?',
      promptFr: 'Comment les chefs de service réagissent-ils ?',
      options: [
        'Ils sont satisfaits',
        'Ils sont mécontents (grogne), se sentent dépossédés',
        'Ils démissionnent immédiatement',
        'Ils soutiennent le nouveau directeur',
      ],
      answer: 1,
      explanation: 'L\'extrait mentionne "suscitant la grogne des chefs de service, qui se sentent dépossédés".',
    },
    {
      id: 'tcf-r1-11',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Lisez : « Si le réchauffement climatique se poursuit au rythme actuel, la température moyenne en France pourrait grimper de 4 degrés d\'ici 2100, avec des conséquences dramatiques pour l\'agriculture et la biodiversité. » Que prévoit ce texte ?',
      promptFr: 'Que prévoit ce texte ?',
      options: [
        'Une baisse des températures',
        'Une hausse de 4°C en France d\'ici 2100 avec des conséquences graves',
        'Aucun changement climatique',
        'Une amélioration de l\'agriculture',
      ],
      answer: 1,
      explanation: 'Le texte prévoit "la température moyenne en France pourrait grimper de 4 degrés d\'ici 2100".',
    },
    {
      id: 'tcf-r1-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Lisez l\'éditorial : « On l\'oublie trop souvent, mais la liberté de la presse ne va pas de soi. Elle se construit chaque jour, par des journalistes qui prennent des risques, et par des lecteurs qui acceptent de payer pour l\'information. » Quel est le message principal ?',
      promptFr: 'Quel est le message principal ?',
      options: [
        'La liberté de la presse est acquise définitivement.',
        'La liberté de la presse se construit chaque jour par les journalistes et les lecteurs.',
        'La presse est gratuite partout.',
        'Les lecteurs ne sont pas importants.',
      ],
      answer: 1,
      explanation: 'L\'éditorial affirme : "Elle se construit chaque jour, par des journalistes... et par des lecteurs".',
    },
    {
      id: 'tcf-r1-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Lisez l\'extrait : « L\'urbanisme participatif séduit de nombreuses communes, mais son application reste inégale. Là où les citoyens sont réellement associés aux décisions, les projets aboutissent plus vite et sont mieux acceptés. » Que permet l\'urbanisme participatif selon le texte ?',
      promptFr: 'Que permet l\'urbanisme participatif selon le texte ?',
      options: [
        'Des projets plus lents et refusés',
        'Des projets qui aboutissent plus vite et sont mieux acceptés',
        'Une baisse de la participation citoyenne',
        'Aucune différence concrète',
      ],
      answer: 1,
      explanation: 'Le texte dit : "les projets aboutissent plus vite et sont mieux acceptés".',
    },
    {
      id: 'tcf-r1-14',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Lisez : « La sobriété numérique n\'est plus une option. Le stockage des données représente déjà près de 4% des émissions mondiales de gaz à effet de serre, et ce chiffre devrait doubler d\'ici 2030. » Quel constat est fait ?',
      promptFr: 'Quel constat est fait ?',
      options: [
        'Le numérique ne pollue pas.',
        'Le stockage des données représente ~4% des émissions mondiales et pourrait doubler d\'ici 2030.',
        'Les émissions du numérique baisseront.',
        'Le numérique représente 0% des émissions.',
      ],
      answer: 1,
      explanation: 'Le texte dit que le stockage représente "près de 4% des émissions mondiales" et "devrait doubler d\'ici 2030".',
    },
    {
      id: 'tcf-r1-15',
      type: 'multiple_choice',
      level: 'C1',
      prompt: 'Lisez : « Au-delà des querelles partisanes, c\'est bien la défiance envers l\'institution elle-même qui s\'est installée, nourrie par des décennies de promesses non tenues et de scandales répétés. » Que souligne l\'auteur ?',
      promptFr: 'Que souligne l\'auteur ?',
      options: [
        'Une simple querelle partisane',
        'Une défiance envers l\'institution, nourrie par des promesses non tenues et des scandales',
        'Une confiance renouvelée',
        'L\'absence de scandales',
      ],
      answer: 1,
      explanation: 'L\'auteur souligne "la défiance envers l\'institution elle-même... nourrie par des décennies de promesses non tenues et de scandales répétés".',
    },
  ],
};

const tcfReadingTest2: PracticeTest = {
  id: 'tcf-reading-test-2',
  title: 'Reading Practice Test 2',
  titleFr: 'Compréhension écrite — Test 2',
  description: '15 questions à difficulté progressive, du niveau A1 au niveau B2.',
  questions: [
    {
      id: 'tcf-r2-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Lisez : « Marie a deux chats. Ils s\'appellent Minou et Tom. » Combien de chats a Marie ?',
      promptFr: 'Combien de chats a Marie ?',
      options: ['Un', 'Deux', 'Trois', 'Aucun'],
      answer: 1,
      explanation: 'Le texte dit : "Marie a deux chats."',
    },
    {
      id: 'tcf-r2-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Lisez : « Le magasin ouvre à 9h et ferme à 20h. » Combien d\'heures le magasin est-il ouvert ?',
      promptFr: 'Combien d\'heures le magasin est-il ouvert ?',
      options: ['9 heures', '11 heures', '20 heures', '12 heures'],
      answer: 1,
      explanation: 'De 9h à 20h : 20 - 9 = 11 heures d\'ouverture.',
    },
    {
      id: 'tcf-r2-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Lisez : « Ce week-end, Sophie va au marché avec sa mère. Elles achètent des légumes pour préparer une soupe. » Que vont-elles faire avec les légumes ?',
      promptFr: 'Que vont-elles faire avec les légumes ?',
      options: [
        'Une salade',
        'Une soupe',
        'Un gâteau',
        'Une tarte',
      ],
      answer: 1,
      explanation: 'Le texte dit : "achètent des légumes pour préparer une soupe".',
    },
    {
      id: 'tcf-r2-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Lisez l\'annonce : « Cherche colocataire pour appartement T3, centre-ville. Loyer : 350 € charges comprises. Non-fumeur, sans animaux. Disponible immédiatement. » Que cherche l\'auteur ?',
      promptFr: 'Que cherche l\'auteur ?',
      options: [
        'Un appartement à louer',
        'Un colocataire non-fumeur, sans animaux',
        'Un meuble',
        'Un employé',
      ],
      answer: 1,
      explanation: 'L\'annonce dit : "Cherche colocataire... Non-fumeur, sans animaux".',
    },
    {
      id: 'tcf-r2-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Lisez : « Thomas adore le football. Il joue tous les mercredis avec ses amis au parc. » Quand Thomas joue-t-il au football ?',
      promptFr: 'Quand Thomas joue-t-il au football ?',
      options: [
        'Tous les jours',
        'Tous les mercredis',
        'Le week-end seulement',
        'Le lundi soir',
      ],
      answer: 1,
      explanation: 'Le texte dit : "Il joue tous les mercredis avec ses amis au parc".',
    },
    {
      id: 'tcf-r2-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Lisez : « La nouvelle ligne de tramway a été inaugurée hier par le maire. Longue de 12 km, elle dessert six quartiers et devrait désengorger le centre-ville aux heures de pointe. » Quel est l\'objectif principal de cette ligne ?',
      promptFr: 'Quel est l\'objectif principal de cette ligne ?',
      options: [
        'Desservir les quartiers extérieurs uniquement',
        'Désengorger le centre-ville aux heures de pointe',
        'Remplacer le métro',
        'Augmenter la pollution',
      ],
      answer: 1,
      explanation: 'Le texte dit : "elle devrait désengorger le centre-ville aux heures de pointe".',
    },
    {
      id: 'tcf-r2-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Lisez le témoignage : « Je travaille à domicile depuis trois ans. Au début, j\'étais ravi, mais je me sens de plus en plus isolé. Mes collègues me manquent. » Que ressent l\'auteur maintenant ?',
      promptFr: 'Que ressent l\'auteur maintenant ?',
      options: [
        'De la joie',
        'De l\'isolement, ses collègues lui manquent',
        'De l\'ennui au bureau',
        'De la fatigue physique',
      ],
      answer: 1,
      explanation: 'L\'auteur dit : "je me sens de plus en plus isolé. Mes collègues me manquent."',
    },
    {
      id: 'tcf-r2-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Lisez : « À partir du 1er janvier, le tri sélectif sera simplifié : tous les emballages plastique pourront être jetés dans la même poubelle, sans avoir à les laver. » Que change cette nouvelle règle ?',
      promptFr: 'Que change cette nouvelle règle ?',
      options: [
        'Il faudra laver tous les emballages.',
        'Tous les emballages plastique pourront être jetés ensemble, sans lavage.',
        'Le plastique ne sera plus recyclé.',
        'Le tri sera plus compliqué.',
      ],
      answer: 1,
      explanation: 'Le texte indique : "tous les emballages plastique pourront être jetés dans la même poubelle, sans avoir à les laver".',
    },
    {
      id: 'tcf-r2-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Lisez : « Le festival a été un succès, malgré une météo capricieuse. Les organisateurs envisagent déjà une édition 2026 encore plus ambitieuse. » Que prévoient les organisateurs ?',
      promptFr: 'Que prévoient les organisateurs ?',
      options: [
        'D\'annuler l\'édition 2026',
        'Une édition 2026 plus ambitieuse',
        'De réduire la taille du festival',
        'De changer de ville',
      ],
      answer: 1,
      explanation: 'Le texte dit : "Les organisateurs envisagent déjà une édition 2026 encore plus ambitieuse".',
    },
    {
      id: 'tcf-r2-10',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Lisez l\'extrait : « L\'essor du télétravail a bouleversé le marché immobilier : les quartiers centraux se vident au profit de la périphérie, où les prix restent accessibles. Les agent immobiliers tirent la sonnette d\'alarme. » Que constate-t-on ?',
      promptFr: 'Que constate-t-on ?',
      options: [
        'Les quartiers centraux se remplissent',
        'Les quartiers centraux se vident au profit de la périphérie',
        'Les prix montent en périphérie',
        'Le télétravail n\'a aucun impact',
      ],
      answer: 1,
      explanation: 'Le texte indique : "Les quartiers centraux se vident au profit de la périphérie".',
    },
    {
      id: 'tcf-r2-11',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Lisez : « Longtemps considérée comme une activité de loisir, la pratique du jardinage est désormais reconnue pour ses vertus thérapeutiques, notamment chez les personnes souffrant de dépression ou d\'anxiété. » Que reconnaît-on désormais au jardinage ?',
      promptFr: 'Que reconnaît-on désormais au jardinage ?',
      options: [
        'Uniquement une activité de loisir',
        'Des vertus thérapeutiques, notamment contre la dépression et l\'anxiété',
        'Un effet négatif sur la santé',
        'Une perte de temps',
      ],
      answer: 1,
      explanation: 'Le texte dit : "la pratique du jardinage est désormais reconnue pour ses vertus thérapeutiques, notamment chez les personnes souffrant de dépression ou d\'anxiété".',
    },
    {
      id: 'tcf-r2-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Lisez l\'analyse : « Si la croissance revient, elle ne profite pas à tous. Les inégalités de revenus se sont même creusées dans la plupart des pays développés, fragilisant le contrat social. » Que souligne cette analyse ?',
      promptFr: 'Que souligne cette analyse ?',
      options: [
        'Une croissance qui profite à tous',
        'Une croissance qui ne profite pas à tous et creuse les inégalités',
        'Une baisse des inégalités',
        'L\'absence de croissance',
      ],
      answer: 1,
      explanation: 'L\'analyse souligne : "elle ne profite pas à tous. Les inégalités de revenus se sont même creusées".',
    },
    {
      id: 'tcf-r2-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Lisez : « La réforme des retraites a fait couler beaucoup d\'encre. Au-delà des chiffres, c\'est la question de la pénibilité du travail qui reste au cœur du débat, sans véritable réponse à ce jour. » Quelle question reste centrale ?',
      promptFr: 'Quelle question reste centrale ?',
      options: [
        'Le montant des pensions',
        'La pénibilité du travail',
        'L\'âge minimal',
        'Le financement',
      ],
      answer: 1,
      explanation: 'Le texte dit : "c\'est la question de la pénibilité du travail qui reste au cœur du débat".',
    },
    {
      id: 'tcf-r2-14',
      type: 'multiple_choice',
      level: 'C1',
      prompt: 'Lisez : « La mémoire collective n\'est pas un simple réservoir de souvenirs : elle se réécrit sans cesse, au gré des recompositions identitaires et des rapports de pouvoir. » Que suggère l\'auteur ?',
      promptFr: 'Que suggère l\'auteur ?',
      options: [
        'La mémoire collective est fixe et immuable',
        'La mémoire collective se réécrit sans cesse, selon les recompositions identitaires et les rapports de pouvoir',
        'La mémoire collective n\'existe pas',
        'La mémoire collective est uniquement individuelle',
      ],
      answer: 1,
      explanation: 'L\'auteur dit : "elle se réécrit sans cesse, au gré des recompositions identitaires et des rapports de pouvoir".',
    },
    {
      id: 'tcf-r2-15',
      type: 'multiple_choice',
      level: 'C1',
      prompt: 'Lisez : « Le paradoxe est saisissant : jamais nous n\'avons disposé d\'autant d\'outils de communication, et jamais le sentiment de solitude n\'a été aussi répandu. » Que souligne l\'auteur ?',
      promptFr: 'Que souligne l\'auteur ?',
      options: [
        'Plus d\'outils de communication = moins de solitude',
        'Paradoxe : plus d\'outils de communication, mais plus de solitude',
        'La solitude a disparu',
        'Les outils de communication sont inutiles',
      ],
      answer: 1,
      explanation: 'L\'auteur souligne le paradoxe : "jamais le sentiment de solitude n\'a été aussi répandu" malgré "autant d\'outils de communication".',
    },
  ],
};

const tcfReadingTest3: PracticeTest = {
  id: 'tcf-reading-test-3',
  title: 'Reading Practice Test 3',
  titleFr: 'Compréhension écrite — Test 3',
  description: '15 questions à difficulté progressive, du niveau A1 au niveau B2.',
  questions: [
    {
      id: 'tcf-r3-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Lisez : « J\'aime le café le matin, mais je préfère le thé l\'après-midi. » Que préfère-t-il l\'après-midi ?',
      promptFr: 'Que préfère-t-il l\'après-midi ?',
      options: ['Le café', 'Le thé', 'Le jus', 'Le lait'],
      answer: 1,
      explanation: 'Le texte dit : "je préfère le thé l\'après-midi".',
    },
    {
      id: 'tcf-r3-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Lisez : « Mon frère a 30 ans. Il est médecin. » Que fait le frère ?',
      promptFr: 'Que fait le frère ?',
      options: ['Il est infirmier', 'Il est médecin', 'Il est étudiant', 'Il est pharmacien'],
      answer: 1,
      explanation: 'Le texte dit : "Il est médecin".',
    },
    {
      id: 'tcf-r3-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Lisez : « Le week-end dernier, nous sommes allés à la mer. Il faisait beau, nous avons nagé et mangé des glaces. » Qu\'ont-ils fait à la mer ?',
      promptFr: 'Qu\'ont-ils fait à la mer ?',
      options: [
        'Skier',
        'Nager et manger des glaces',
        'Visiter un musée',
        'Faire du vélo',
      ],
      answer: 1,
      explanation: 'Le texte dit : "nous avons nagé et mangé des glaces".',
    },
    {
      id: 'tcf-r3-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Lisez l\'offre : « Stage en marketing digital, 6 mois, à partir de mars. Rémunération : 600 €/mois. Envoyer CV et lettre de motivation à recrutement@startup.fr. » Quelle est la rémunération ?',
      promptFr: 'Quelle est la rémunération ?',
      options: ['500 €/mois', '600 €/mois', '1000 €/mois', 'Non rémunéré'],
      answer: 1,
      explanation: 'L\'offre indique : "Rémunération : 600 €/mois".',
    },
    {
      id: 'tcf-r3-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Lisez : « Le festival de musique commence vendredi soir à 18h et se termine dimanche minuit. Trois scènes, plus de cinquante artistes. » Combien d\'artistes sont prévus ?',
      promptFr: 'Combien d\'artistes sont prévus ?',
      options: [
        'Moins de 30',
        'Plus de 50',
        'Exactement 18',
        'Aucun',
      ],
      answer: 1,
      explanation: 'Le texte dit : "plus de cinquante artistes".',
    },
    {
      id: 'tcf-r3-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Lisez : « La nouvelle bibliothèque ouvrira ses portes en septembre. Elle proposera 50 000 ouvrages, des espaces de travail, et un auditorium pour des conférences gratuites. » Que proposera la bibliothèque ?',
      promptFr: 'Que proposera la bibliothèque ?',
      options: [
        'Uniquement des livres',
        '50 000 ouvrages, des espaces de travail, et un auditorium pour des conférences gratuites',
        'Une piscine',
        'Des cours payants',
      ],
      answer: 1,
      explanation: 'Le texte dit : "50 000 ouvrages, des espaces de travail, et un auditorium pour des conférences gratuites".',
    },
    {
      id: 'tcf-r3-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Lisez le message : « Pour ta fête, j\'ai organisé une petite surprise. Sois chez toi à 19h samedi, et ouvre bien la porte. N\'apporte rien, tout est prévu ! » Que doit faire la personne ?',
      promptFr: 'Que doit faire la personne ?',
      options: [
        'Acheter un cadeau',
        'Être chez elle à 19h samedi, sans rien apporter',
        'Préparer le repas',
        'Inviter d\'autres amis',
      ],
      answer: 1,
      explanation: 'Le message dit : "Sois chez toi à 19h samedi" et "N\'apporte rien, tout est prévu !"',
    },
    {
      id: 'tcf-r3-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Lisez : « La grève des transports durera au moins jusqu\'à vendredi. La direction annonce des discussions mercredi, mais sans garantie de reprise immédiate. » Que peut-on déduire ?',
      promptFr: 'Que peut-on déduire ?',
      options: [
        'La grève est terminée.',
        'La grève durera au moins jusqu\'à vendredi, sans garantie de reprise immédiate.',
        'Les transports fonctionnent normalement.',
        'La direction refuse toute discussion.',
      ],
      answer: 1,
      explanation: 'Le texte dit : "La grève durera au moins jusqu\'à vendredi" et "sans garantie de reprise immédiate".',
    },
    {
      id: 'tcf-r3-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Lisez : « Le médecin m\'a conseillé de marcher trente minutes par jour et de réduire ma consommation de sel. Il a aussi prescrit une prise de sang dans un mois. » Que doit faire le patient ?',
      promptFr: 'Que doit faire le patient ?',
      options: [
        'Marcher 30 min/jour, réduire le sel, faire une prise de sang dans un mois',
        'Arrêter de marcher',
        'Manger plus de sel',
        'Prendre des médicaments immédiatement',
      ],
      answer: 0,
      explanation: 'Le médecin conseille : marcher 30 min/jour, réduire le sel, prise de sang dans un mois.',
    },
    {
      id: 'tcf-r3-10',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Lisez : « Malgré un bilan économique encourageant, le gouvernement reste prudent. La conjoncture internationale, marquée par des tensions commerciales, justifie cette circonspection. » Pourquoi le gouvernement est-il prudent ?',
      promptFr: 'Pourquoi le gouvernement est-il prudent ?',
      options: [
        'Parce que le bilan économique est mauvais',
        'En raison de tensions commerciales internationales',
        'Parce que les élections approchent',
        'Parce que l\'opposition proteste',
      ],
      answer: 1,
      explanation: 'Le texte dit : "La conjoncture internationale, marquée par des tensions commerciales, justifie cette circonspection".',
    },
    {
      id: 'tcf-r3-11',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Lisez : « L\'intelligence artificielle générative inquiète les artistes, qui craignent une dévaluation de leur travail. Plusieurs associations réclament un cadre juridique encadrant l\'usage de leurs œuvres pour l\'entraînement des modèles. » Que réclament les artistes ?',
      promptFr: 'Que réclament les artistes ?',
      options: [
        'L\'interdiction totale de l\'IA',
        'Un cadre juridique encadrant l\'usage de leurs œuvres pour l\'entraînement des modèles',
        'Une baisse des prix',
        'Plus de subventions',
      ],
      answer: 1,
      explanation: 'Le texte dit : "Plusieurs associations réclament un cadre juridique encadrant l\'usage de leurs œuvres pour l\'entraînement des modèles".',
    },
    {
      id: 'tcf-r3-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Lisez : « La popularité des repas végétariens progresse dans les cantines scolaires, mais la transition se heurte au manque de formation des cuisiniers et au coût parfois élevé des protéines végétales. » Quels obstacles rencontre cette transition ?',
      promptFr: 'Quels obstacles rencontre cette transition ?',
      options: [
        'Aucun obstacle',
        'Le manque de formation des cuisiniers et le coût élevé des protéines végétales',
        'Le refus des parents',
        'L\'interdiction par la loi',
      ],
      answer: 1,
      explanation: 'Le texte cite : "le manque de formation des cuisiniers et le coût parfois élevé des protéines végétales".',
    },
    {
      id: 'tcf-r3-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Lisez l\'extrait : « Les scientifiques tirent la sonnette d\'alarme : la disparition des insectes pollinisateurs, observée depuis vingt ans, pourrait entraîner une chute dramatique des rendements agricoles. » Quel phénomène inquiète les scientifiques ?',
      promptFr: 'Quel phénomène inquiète les scientifiques ?',
      options: [
        'La disparition des oiseaux',
        'La disparition des insectes pollinisateurs, qui pourrait faire chuter les rendements agricoles',
        'La hausse des rendements agricoles',
        'L\'augmentation des insectes',
      ],
      answer: 1,
      explanation: 'Les scientifiques s\'inquiètent de "la disparition des insectes pollinisateurs... pourrait entraîner une chute dramatique des rendements agricoles".',
    },
    {
      id: 'tcf-r3-14',
      type: 'multiple_choice',
      level: 'C1',
      prompt: 'Lisez : « Au prisme de l\'histoire, la fascination pour les civilisations disparues dit peut-être moins l\'intérêt du passé que l\'angoisse de notre propre finitude. » Que suggère l\'auteur ?',
      promptFr: 'Que suggère l\'auteur ?',
      options: [
        'Que l\'intérêt pour les civilisations disparues relève uniquement de la curiosité historique',
        'Que cet intérêt reflète en réalité l\'angoisse de notre propre finitude',
        'Que les civilisations disparues n\'intéressent personne',
        'Que l\'histoire est inutile',
      ],
      answer: 1,
      explanation: 'L\'auteur suggère que cette fascination "dit peut-être moins l\'intérêt du passé que l\'angoisse de notre propre finitude".',
    },
    {
      id: 'tcf-r3-15',
      type: 'multiple_choice',
      level: 'C1',
      prompt: 'Lisez : « La notion de progrès, jadis portée par la promesse d\'un avenir meilleur, vacille aujourd\'hui sous le poids des crises écologiques et sociales, sans qu\'aucun récit unificateur ne s\'impose pour la remplacer. » Que souligne l\'auteur ?',
      promptFr: 'Que souligne l\'auteur ?',
      options: [
        'Le progrès est plus fort que jamais',
        'La notion de progrès vacille et aucun récit unificateur ne la remplace',
        'Un nouveau récit unificateur s\'impose',
        'Les crises écologiques sont terminées',
      ],
      answer: 1,
      explanation: 'L\'auteur souligne que la notion de progrès "vacille aujourd\'hui sous le poids des crises écologiques et sociales, sans qu\'aucun récit unificateur ne s\'impose pour la remplacer".',
    },
  ],
};

// ---------------------------------------------------------------------------
// LISTENING COMPREHENSION — 3 tests × 15 questions, progressive difficulty (with audioText)
// ---------------------------------------------------------------------------

const tcfListeningTest1: PracticeTest = {
  id: 'tcf-listening-test-1',
  title: 'Listening Practice Test 1',
  titleFr: 'Compréhension orale — Test 1',
  description: '15 questions à difficulté progressive (A1 → B2), avec audioText pour TTS.',
  questions: [
    {
      id: 'tcf-l1-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Écoutez et répondez : comment s\'appelle la personne ?',
      promptFr: 'Comment s\'appelle la personne ?',
      audioText: 'Bonjour, je m\'appelle Nathalie. Je suis française et j\'habite à Nantes.',
      options: ['Nathalie', 'Nadine', 'Nathanaël', 'Noémie'],
      answer: 0,
      explanation: 'La personne dit : "je m\'appelle Nathalie".',
    },
    {
      id: 'tcf-l1-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Écoutez et répondez : quel jour sommes-nous ?',
      promptFr: 'Quel jour sommes-nous ?',
      audioText: 'Aujourd\'hui, c\'est mardi. Demain, nous aurons notre réunion de service à 10 heures.',
      options: ['Lundi', 'Mardi', 'Mercredi', 'Jeudi'],
      answer: 1,
      explanation: 'L\'audio dit : "Aujourd\'hui, c\'est mardi".',
    },
    {
      id: 'tcf-l1-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez et répondez : que veut la cliente ?',
      promptFr: 'Que veut la cliente ?',
      audioText: 'Bonjour, je voudrais deux baguettes et trois croissants, s\'il vous plaît. Vous avez aussi des pains aux raisins ?',
      options: [
        'Deux baguettes et trois croissants, et demande pour pains aux raisins',
        'Trois baguettes et deux croissants',
        'Un seul pain aux raisins',
        'Rien du tout',
      ],
      answer: 0,
      explanation: 'La cliente demande "deux baguettes et trois croissants" et demande "des pains aux raisins".',
    },
    {
      id: 'tcf-l1-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez et répondez : que dit l\'annonce ?',
      promptFr: 'Que dit l\'annonce ?',
      audioText: 'Mesdames et messieurs, le musée sera exceptionnellement fermé demain mardi pour cause d\'inventaire. Merci de votre compréhension.',
      options: [
        'Le musée est ouvert demain',
        'Le musée sera fermé demain mardi pour inventaire',
        'Le musée est gratuit demain',
        'Le musée est en travaux pour un mois',
      ],
      answer: 1,
      explanation: 'L\'annonce indique : "le musée sera exceptionnellement fermé demain mardi pour cause d\'inventaire".',
    },
    {
      id: 'tcf-l1-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez la conversation : où veut aller la personne ?',
      promptFr: 'Où veut aller la personne ?',
      audioText: '— Excusez-moi, pour aller à la poste, s\'il vous plaît ?\n— Vous tournez à droite au feu, puis tout droit pendant 200 mètres. La poste est juste en face de la boulangerie.\n— Merci beaucoup !',
      options: [
        'À la boulangerie',
        'À la poste',
        'Au feu tricolore',
        'Au musée',
      ],
      answer: 1,
      explanation: 'La personne demande : "pour aller à la poste".',
    },
    {
      id: 'tcf-l1-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que dit l\'employée ?',
      promptFr: 'Que dit l\'employée ?',
      audioText: 'Bonjour, votre rendez-vous avec Monsieur Lemaire est confirmé pour jeudi à quinze heures. Pensez à apporter votre carte d\'identité et votre dernier bulletin de salaire. Une heure avant, vous recevrez un SMS de rappel.',
      options: [
        'Le rendez-vous est annulé',
        'Le rendez-vous est jeudi à 15h, avec carte d\'identité et dernier bulletin de salaire',
        'Le rendez-vous est vendredi matin',
        'Aucun document à apporter',
      ],
      answer: 1,
      explanation: 'L\'employée confirme rendez-vous jeudi à 15h, avec "carte d\'identité et votre dernier bulletin de salaire".',
    },
    {
      id: 'tcf-l1-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez le reportage : quel est le sujet ?',
      promptFr: 'Quel est le sujet ?',
      audioText: 'Aujourd\'hui, nous nous intéressons à un phénomène méconnu : les pharmacies vétérinaires en milieu rural. Avec la disparition des éleveurs, nombre d\'entre elles ferment, laissant les animaux d\'élevage sans accès aux soins à proximité.',
      options: [
        'Les pharmacies humaines',
        'Les pharmacies vétérinaires en milieu rural, qui ferment en nombre',
        'Les hôpitaux ruraux',
        'La formation des vétérinaires',
      ],
      answer: 1,
      explanation: 'Le reportage porte sur "les pharmacies vétérinaires en milieu rural" qui "ferment".',
    },
    {
      id: 'tcf-l1-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que dit le guide ?',
      promptFr: 'Que dit le guide ?',
      audioText: 'Mesdames et messieurs, bienvenue au château de Chambord. La visite dure environ une heure trente. Je vous demande de bien vouloir suivre le groupe sans vous éloigner, car certaines salles sont en restauration. Les photos sont autorisées, mais sans flash.',
      options: [
        'La visite dure 30 minutes, photos interdites',
        'La visite dure 1h30, suivre le groupe, photos sans flash',
        'La visite dure 3 heures, flash autorisé',
        'Visite libre sans guide',
      ],
      answer: 1,
      explanation: 'Le guide indique : visite d\'"une heure trente", "suivre le groupe", "photos autorisées, mais sans flash".',
    },
    {
      id: 'tcf-l1-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que dit le professeur ?',
      promptFr: 'Que dit le professeur ?',
      audioText: 'Pour la semaine prochaine, je vous demande de lire le chapitre 5 et de préparer un résumé d\'une page. N\'oubliez pas que le devoir sur table est reporté au 12. Bon week-end à tous.',
      options: [
        'Lire le chapitre 5, préparer un résumé d\'une page, devoir reporté au 12',
        'Lire le chapitre 12',
        'Pas de lecture à faire',
        'Devoir maintenu au 5',
      ],
      answer: 0,
      explanation: 'Le professeur demande de lire le chapitre 5, préparer un résumé d\'une page, et signale le devoir "reporté au 12".',
    },
    {
      id: 'tcf-l1-10',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : quel est le sujet du reportage ?',
      promptFr: 'Quel est le sujet du reportage ?',
      audioText: 'Dans notre reportage, nous suivons une jeune agricultrice qui a transformé l\'exploitation familiale en ferme biologique. Bilan après trois ans : des rendements en baisse de 15%, mais des marges supérieures grâce à des prix de vente plus élevés et à la baisse des intrants chimiques.',
      options: [
        'Une ferme biologique, rendements en baisse de 15% mais marges supérieures',
        'Une ferme industrielle',
        'Une ferme qui ferme',
        'Une exploitation sans changement',
      ],
      answer: 0,
      explanation: 'Le reportage suit "une jeune agricultrice qui a transformé l\'exploitation familiale en ferme biologique" avec "des rendements en baisse de 15%, mais des marges supérieures".',
    },
    {
      id: 'tcf-l1-11',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : qu\'explique le journaliste ?',
      promptFr: 'Qu\'explique le journaliste ?',
      audioText: 'Le marché de l\'art contemporain connaît un essor spectaculaire, dopé par les collectionneurs asiatiques et les ventes en ligne. Les prix de certaines toiles ont été multipliés par dix en moins de dix ans, suscitant l\'inquiétude des experts face à une éventuelle bulle spéculative.',
      options: [
        'Le marché de l\'art contemporain est en déclin',
        'Le marché de l\'art contemporain explose, mais une bulle spéculative est crainte',
        'Les ventes en ligne sont interdites',
        'Les collectionneurs asiatiques ont disparu',
      ],
      answer: 1,
      explanation: 'Le journaliste explique que le marché "connaît un essor spectaculaire" mais qu\'une "bulle spéculative" est crainte.',
    },
    {
      id: 'tcf-l1-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : quel est le conseil principal ?',
      promptFr: 'Quel est le conseil principal ?',
      audioText: 'Pour réussir vos entretiens d\'embauche, les recruteurs le répètent : préparez trois questions pertinentes sur l\'entreprise. Cela montre votre intérêt et votre capacité d\'analyse. Évitez les questions sur les congés ou le salaire lors du premier rendez-vous.',
      options: [
        'Poser des questions sur les congés',
        'Préparer trois questions pertinentes sur l\'entreprise',
        'Demander le salaire immédiatement',
        'Ne poser aucune question',
      ],
      answer: 1,
      explanation: 'Le conseil principal : "préparez trois questions pertinentes sur l\'entreprise".',
    },
    {
      id: 'tcf-l1-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : que dit l\'économiste ?',
      promptFr: 'Que dit l\'économiste ?',
      audioText: 'La transition écologique va créer plus d\'emplois qu\'elle n\'en détruira, à condition que les formations suivent. Le bâtiment, les énergies renouvelables et la réparation sont les secteurs qui recruteront le plus dans les dix prochaines années.',
      options: [
        'La transition écologique détruira plus d\'emplois qu\'elle n\'en créera',
        'La transition écologie créera plus d\'emplois qu\'elle n\'en détruira, si les formations suivent',
        'Aucun emploi ne sera créé',
        'Le bâtiment ne recrutera pas',
      ],
      answer: 1,
      explanation: 'L\'économiste dit que "La transition écologique va créer plus d\'emplois qu\'elle n\'en détruira, à condition que les formations suivent".',
    },
    {
      id: 'tcf-l1-14',
      type: 'multiple_choice',
      level: 'C1',
      prompt: 'Écoutez et répondez : que souligne l\'intervenant ?',
      promptFr: 'Que souligne l\'intervenant ?',
      audioText: 'L\'histoire nous l\'enseigne : les grandes crises ne se résolvent jamais par des solutions simples. Elles exigent des choix complexes, parfois douloureux, qui supposent une vision partagée du futur, faute de quoi les sociétés se fracturent.',
      options: [
        'Les crises se résolvent par des solutions simples',
        'Les crises exigent des choix complexes et une vision partagée du futur',
        'Les crises n\'ont aucun impact social',
        'Les sociétés ne se fracturent jamais',
      ],
      answer: 1,
      explanation: 'L\'intervenant souligne que les crises "exigent des choix complexes, parfois douloureux, qui supposent une vision partagée du futur".',
    },
    {
      id: 'tcf-l1-15',
      type: 'multiple_choice',
      level: 'C1',
      prompt: 'Écoutez et répondez : qu\'affirme l\'auteur ?',
      promptFr: 'Qu\'affirme l\'auteur ?',
      audioText: 'Toute œuvre d\'art véritable porte en elle une part d\'inachèvement, cette faille par laquelle le spectateur peut s\'engouffrer et donner un sens qui n\'était pas prévu.',
      options: [
        'Une œuvre d\'art est toujours achevée',
        'Toute œuvre d\'art véritable porte une part d\'inachèvement permettant au spectateur de donner un sens',
        'Le spectateur n\'a aucun rôle',
        'L\'œuvre n\'a qu\'un seul sens',
      ],
      answer: 1,
      explanation: 'L\'auteur affirme : "Toute œuvre d\'art véritable porte en elle une part d\'inachèvement".',
    },
  ],
};

const tcfListeningTest2: PracticeTest = {
  id: 'tcf-listening-test-2',
  title: 'Listening Practice Test 2',
  titleFr: 'Compréhension orale — Test 2',
  description: '15 questions à difficulté progressive (A1 → B2), avec audioText pour TTS.',
  questions: [
    {
      id: 'tcf-l2-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Écoutez et répondez : que dit la personne ?',
      promptFr: 'Que dit la personne ?',
      audioText: 'Bonjour, je voudrais un kilo de tomates et un demi-kilo de fraises, s\'il vous plaît.',
      options: [
        'Un kilo de tomates et un demi-kilo de fraises',
        'Deux kilos de tomates',
        'Un kilo de fraises',
        'Rien du tout',
      ],
      answer: 0,
      explanation: 'La personne demande "un kilo de tomates et un demi-kilo de fraises".',
    },
    {
      id: 'tcf-l2-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Écoutez et répondez : combien de personnes ?',
      promptFr: 'Combien de personnes ?',
      audioText: 'Bonjour, j\'ai réservé une table pour quatre personnes au nom de Durand, à 20 heures.',
      options: ['2 personnes', '3 personnes', '4 personnes', '5 personnes'],
      answer: 2,
      explanation: 'La personne dit : "une table pour quatre personnes".',
    },
    {
      id: 'tcf-l2-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez et répondez : que dit la météo ?',
      promptFr: 'Que dit la météo ?',
      audioText: 'Demain, sur le nord de la France, attendez-vous à un temps nuageux avec des pluies en matinée. L\'après-midi, les éclaircies reviendront, avec des températures de 18 à 21 degrés.',
      options: [
        'Pluie toute la journée',
        'Nuageux avec pluie le matin, éclaircies l\'après-midi, 18-21°C',
        'Soleil toute la journée',
        'Neige',
      ],
      answer: 1,
      explanation: 'La météo annonce : nuageux avec pluies en matinée, éclaircies l\'après-midi, 18 à 21°C.',
    },
    {
      id: 'tcf-l2-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez et répondez : que dit l\'annonce ?',
      promptFr: 'Que dit l\'annonce ?',
      audioText: 'Attention, en raison de travaux, la station "République" sera fermée du 5 au 12 juin. Les voyageurs sont invités à emprunter la ligne de bus 4 en remplacement. Merci de votre compréhension.',
      options: [
        'La station République ferme définitivement',
        'La station République sera fermée du 5 au 12 juin, bus 4 en remplacement',
        'La ligne 4 est supprimée',
        'Aucune incidence',
      ],
      answer: 1,
      explanation: 'L\'annonce indique : "station République sera fermée du 5 au 12 juin" et "bus 4 en remplacement".',
    },
    {
      id: 'tcf-l2-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez et répondez : quand part le train ?',
      promptFr: 'Quand part le train ?',
      audioText: 'Le train à destination de Strasbourg partira à 17h42 en voie 7. Embarquement immédiat, les portes ferment dans trois minutes.',
      options: ['17h42, voie 7', '17h30, voie 3', '18h00, voie 7', '17h12, voie 5'],
      answer: 0,
      explanation: 'L\'annonce indique : "à destination de Strasbourg partira à 17h42 en voie 7".',
    },
    {
      id: 'tcf-l2-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que propose la conseillère ?',
      promptFr: 'Que propose la conseillère ?',
      audioText: 'Bonjour, suite à votre demande de prêt, je vous propose trois formules : un prêt à taux fixe sur 15 ans, un prêt modulable sur 20 ans, ou un prêt in fine avec un placement associé. Prenons rendez-vous la semaine prochaine pour en discuter.',
      options: [
        'Un seul prêt possible',
        'Trois formules : prêt fixe 15 ans, prêt modulable 20 ans, prêt in fine avec placement',
        'Un refus de prêt',
        'Un prêt sur 30 ans',
      ],
      answer: 1,
      explanation: 'La conseillère propose "trois formules : un prêt à taux fixe sur 15 ans, un prêt modulable sur 20 ans, ou un prêt in fine".',
    },
    {
      id: 'tcf-l2-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que dit le loueur ?',
      promptFr: 'Que dit le loueur ?',
      audioText: 'Pour louer cette voiture, j\'aurai besoin de votre permis de conduire, d\'une carte bancaire au nom du conducteur, et d\'un justificatif de domicile. Le kilométrage est illimité, mais le plein doit être rendu au même niveau.',
      options: [
        'Juste un permis',
        'Permis, carte bancaire au nom du conducteur, justificatif de domicile ; kilométrage illimité, plein à rendre au même niveau',
        'Kilométrage limité à 100 km',
        'Aucun document requis',
      ],
      answer: 1,
      explanation: 'Le loueur demande "permis de conduire, d\'une carte bancaire... et d\'un justificatif de domicile" et précise kilométrage illimité et plein à rendre au même niveau.',
    },
    {
      id: 'tcf-l2-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez le message : que dit l\'hôtesse ?',
      promptFr: 'Que dit l\'hôtesse ?',
      audioText: 'Mesdames et messieurs, en raison d\'orages sur la région, notre vol aura environ quarante minutes de retard. Nous vous invitons à patienter en salle d\'embarquement. Un rafraîchissement vous sera offert. Merci de votre patience.',
      options: [
        'Vol annulé',
        'Retard d\'environ 40 minutes en raison d\'orages, rafraîchissement offert',
        'Vol à l\'heure',
        'Départ immédiat',
      ],
      answer: 1,
      explanation: 'L\'hôtesse annonce "environ quarante minutes de retard" en raison d\'orages, avec rafraîchissement offert.',
    },
    {
      id: 'tcf-l2-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que demande le patient ?',
      promptFr: 'Que demande le patient ?',
      audioText: '— Docteur, j\'ai des maux de tête depuis une semaine. J\'ai aussi du mal à dormir.\n— Avez-vous pris votre tension ?\n— Oui, elle est normale.\n— Je vais vous prescrire une prise de sang et on verra dans quinze jours.',
      options: [
        'Des maux de tête depuis une semaine et du mal à dormir',
        'Une fièvre',
        'Une douleur au genou',
        'Aucun symptôme',
      ],
      answer: 0,
      explanation: 'Le patient dit : "j\'ai des maux de tête depuis une semaine. J\'ai aussi du mal à dormir".',
    },
    {
      id: 'tcf-l2-10',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : quel est le sujet de l\'interview ?',
      promptFr: 'Quel est le sujet de l\'interview ?',
      audioText: 'Nous recevons aujourd\'hui une sociologue spécialiste de la solitude. Elle explique que si les seniors restent les plus touchés, les jeunes de 18-25 ans connaissent désormais un isolement aussi marqué, souvent lié à l\'usage intensif des écrans et à la précarité étudiante.',
      options: [
        'La solitude chez les seniors uniquement',
        'La solitude, qui touche aussi les 18-25 ans à cause des écrans et de la précarité',
        'L\'usage des écrans chez les enfants',
        'La précarité des retraités',
      ],
      answer: 1,
      explanation: 'L\'interview porte sur la solitude, et note que les 18-25 ans sont touchés, "souvent lié à l\'usage intensif des écrans et à la précarité étudiante".',
    },
    {
      id: 'tcf-l2-11',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : que dit l\'avocat ?',
      promptFr: 'Que dit l\'avocat ?',
      audioText: 'Sur le plan juridique, ce type de licenciement est contestable si l\'employeur n\'a pas respecté la procédure préalable, à savoir l\'entretien obligatoire et le délai de réflexion. Je vous conseille de contester devant le conseil de prud\'hommes dans un délai de douze mois.',
      options: [
        'Le licenciement ne peut jamais être contesté',
        'Le licenciement est contestable si la procédure préalable n\'a pas été respectée, à contester dans les 12 mois',
        'Le délai est de 5 ans',
        'Aucun recours possible',
      ],
      answer: 1,
      explanation: 'L\'avocat dit que le licenciement est "contestable si l\'employeur n\'a pas respecté la procédure préalable" et à contester "dans un délai de douze mois".',
    },
    {
      id: 'tcf-l2-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : que dit le chercheur ?',
      promptFr: 'Que dit le chercheur ?',
      audioText: 'Nos travaux montrent que les élèves qui pratiquent un instrument de musique régulent mieux leur attention en classe. La corrélation n\'implique pas la causalité, mais les effets sont suffisamment robustes pour recommander la musique à l\'école dès le primaire.',
      options: [
        'La musique n\'a aucun effet sur l\'attention',
        'Les élèves qui pratiquent un instrument régulent mieux leur attention, recommander la musique dès le primaire',
        'La musique nuit aux études',
        'Les effets sont trop faibles pour recommander',
      ],
      answer: 1,
      explanation: 'Le chercheur dit : "Les élèves qui pratiquent un instrument de musique régulent mieux leur attention en classe" et recommande "la musique à l\'école dès le primaire".',
    },
    {
      id: 'tcf-l2-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : que dit le journaliste ?',
      promptFr: 'Que dit le journaliste ?',
      audioText: 'Le chômage a légèrement reculé ce trimestre, mais cette baisse masque une réalité plus sombre : la hausse continue des contrats courts et du temps partiel subi. Beaucoup d\'économistes dénoncent une amélioration en trompe-l\'œil.',
      options: [
        'Le chômage augmente fortement',
        'Le chômage recule, mais masque une hausse des contrats courts et du temps partiel subi',
        'Le chômage ne change pas',
        'Le temps partiel subi a disparu',
      ],
      answer: 1,
      explanation: 'Le journaliste dit : "Le chômage a légèrement reculé" mais "cette baisse masque une réalité plus sombre : la hausse continue des contrats courts et du temps partiel subi".',
    },
    {
      id: 'tcf-l2-14',
      type: 'multiple_choice',
      level: 'C1',
      prompt: 'Écoutez et répondez : qu\'affirme l\'invité ?',
      promptFr: 'Qu\'affirme l\'invité ?',
      audioText: 'L\'innovation, contrairement à une idée reçue, ne naît pas du chaos, mais d\'une discipline exigeante : l\'élimination méthodique de tout ce qui n\'est pas essentiel. C\'est en se contraignant que l\'on libère la créativité.',
      options: [
        'L\'innovation naît du chaos',
        'L\'innovation naît d\'une discipline exigeante, en éliminant le non essentiel',
        'L\'innovation naît par hasard',
        'L\'innovation n\'exige aucune contrainte',
      ],
      answer: 1,
      explanation: 'L\'invité affirme : "L\'innovation... ne naît pas du chaos, mais d\'une discipline exigeante : l\'élimination méthodique de tout ce qui n\'est pas essentiel".',
    },
    {
      id: 'tcf-l2-15',
      type: 'multiple_choice',
      level: 'C1',
      prompt: 'Écoutez et répondez : que dit la philosophe ?',
      promptFr: 'Que dit la philosophe ?',
      audioText: 'La liberté n\'est pas l\'absence de contrainte, mais la capacité de choisir celle à laquelle on consent. C\'est en cela que se distingue l\'homme libre de l\'homme soumis : non par le nombre de ses chaînes, mais par le rapport qu\'il entretient avec elles.',
      options: [
        'La liberté est l\'absence totale de contrainte',
        'La liberté est la capacité de choisir la contrainte à laquelle on consent',
        'L\'homme libre n\'a aucune chaîne',
        'L\'homme soumis choisit ses chaînes',
      ],
      answer: 1,
      explanation: 'La philosophe affirme : "La liberté... est la capacité de choisir celle à laquelle on consent".',
    },
  ],
};

const tcfListeningTest3: PracticeTest = {
  id: 'tcf-listening-test-3',
  title: 'Listening Practice Test 3',
  titleFr: 'Compréhension orale — Test 3',
  description: '15 questions à difficulté progressive (A1 → B2), avec audioText pour TTS.',
  questions: [
    {
      id: 'tcf-l3-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Écoutez et répondez : où va la personne ?',
      promptFr: 'Où va la personne ?',
      audioText: 'Ce soir, je vais au cinéma avec mes amis. Nous avons réservé des places pour 20 heures.',
      options: ['Au cinéma', 'Au restaurant', 'Au théâtre', 'Au stade'],
      answer: 0,
      explanation: 'La personne dit : "je vais au cinéma avec mes amis".',
    },
    {
      id: 'tcf-l3-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Écoutez et répondez : que dit la personne ?',
      promptFr: 'Que dit la personne ?',
      audioText: 'J\'ai un frère et une sœur. Mon frère a 20 ans et ma sœur a 17 ans.',
      options: [
        'Deux frères',
        'Un frère de 20 ans et une sœur de 17 ans',
        'Trois sœurs',
        'Aucun frère ni sœur',
      ],
      answer: 1,
      explanation: 'La personne dit : "J\'ai un frère et une sœur. Mon frère a 20 ans et ma sœur a 17 ans."',
    },
    {
      id: 'tcf-l3-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez et répondez : que commande le client ?',
      promptFr: 'Que commande le client ?',
      audioText: '— Bonsoir, je voudrais une pizza margherita et une salade verte, s\'il vous plaît.\n— À emporter ou sur place ?\n— Sur place. Et un verre d\'eau plate, s\'il vous plaît.',
      options: [
        'Une pizza margherita, une salade verte, un verre d\'eau plate, sur place',
        'Une pizza à emporter',
        'Deux pizzas',
        'Uniquement une salade',
      ],
      answer: 0,
      explanation: 'Le client commande "une pizza margherita et une salade verte", "sur place", et "un verre d\'eau plate".',
    },
    {
      id: 'tcf-l3-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez et répondez : quel est le motif de l\'appel ?',
      promptFr: 'Quel est le motif de l\'appel ?',
      audioText: 'Bonjour, je vous appelle pour annuler ma réservation du 14 juin au nom de Petit. Une urgence familiale m\'oblige à reporter mon voyage. Pourrez-vous me rembourser ?',
      options: [
        'Confirmer une réservation',
        'Annuler une réservation du 14 juin et demander un remboursement',
        'Réserver une chambre',
        'Changer la date',
      ],
      answer: 1,
      explanation: 'L\'appel est pour "annuler ma réservation du 14 juin" et demander "un remboursement".',
    },
    {
      id: 'tcf-l3-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez et répondez : combien coûte le billet ?',
      promptFr: 'Combien coûte le billet ?',
      audioText: 'Le billet d\'entrée pour le château coûte 12 euros en plein tarif, 9 euros en tarif réduit pour les étudiants, et il est gratuit pour les moins de 12 ans.',
      options: [
        '12 € plein tarif, 9 € tarif réduit, gratuit pour les -12 ans',
        '12 € pour tous',
        'Gratuit pour tous',
        '9 € plein tarif',
      ],
      answer: 0,
      explanation: 'L\'audio indique : "12 euros en plein tarif, 9 euros en tarif réduit... gratuit pour les moins de 12 ans".',
    },
    {
      id: 'tcf-l3-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que dit le médecin ?',
      promptFr: 'Que dit le médecin ?',
      audioText: 'Vos résultats sont bons, à l\'exception de la vitamine D, qui est légèrement basse. Je vous prescris une supplémentation pendant trois mois, et je vous conseille de sortir au moins quinze minutes par jour, même en hiver.',
      options: [
        'Tout est parfait',
        'Vitamine D légèrement basse : supplémentation 3 mois + 15 min de sortie/jour',
        'Arrêter toute activité',
        'Hospitalisation immédiate',
      ],
      answer: 1,
      explanation: 'Le médecin dit : "vitamine D... légèrement basse", "supplémentation pendant trois mois" et "sortir au moins quinze minutes par jour".',
    },
    {
      id: 'tcf-l3-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que propose le guide ?',
      promptFr: 'Que propose le guide ?',
      audioText: 'La visite guidée commence à 14 heures devant l\'hôtel de ville. Elle dure deux heures et se terminera par une dégustation de produits locaux. Prévoyez des chaussures confortables, nous marcherons environ trois kilomètres.',
      options: [
        'Visite de 30 minutes, sans marche',
        'Visite de 2h à 14h devant l\'hôtel de ville, dégustation finale, 3 km de marche',
        'Visite en bus',
        'Dégustation uniquement',
      ],
      answer: 1,
      explanation: 'Le guide indique : visite à 14h, durée 2h, "dégustation de produits locaux", et "nous marcherons environ trois kilomètres".',
    },
    {
      id: 'tcf-l3-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que dit le formateur ?',
      promptFr: 'Que dit le formateur ?',
      audioText: 'Pour cette formation, je vous demande de participer activement. Le succès de ces trois jours dépendra de votre implication : exercices en groupes, mises en situation, et un bilan oral le dernier jour. Aucune note écrite, mais une présence obligatoire.',
      options: [
        'Notes écrites obligatoires',
        'Participation active, exercices en groupes, mises en situation, bilan oral, présence obligatoire',
        'Présence facultative',
        'Aucune participation requise',
      ],
      answer: 1,
      explanation: 'Le formateur demande : "participer activement", "exercices en groupes, mises en situation, et un bilan oral", et "présence obligatoire".',
    },
    {
      id: 'tcf-l3-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que dit le concierge ?',
      promptFr: 'Que dit le concierge ?',
      audioText: 'Bonjour, je vous appelle de la part de l\'immeuble. Une fuite d\'eau a été détectée au 3e étage, nous devons couper l\'eau de tout le bâtiment pendant deux heures, entre 14h et 16h. Veuillez prévoir de l\'eau pour vos besoins. Désolé pour le désagrément.',
      options: [
        'Pas de coupure d\'eau',
        'Coupure d\'eau 14h-16h pour fuite au 3e étage',
        'Coupure d\'électricité',
        'Évacuation immédiate',
      ],
      answer: 1,
      explanation: 'Le concierge annonce : "couper l\'eau de tout le bâtiment pendant deux heures, entre 14h et 16h" pour une "fuite d\'eau... au 3e étage".',
    },
    {
      id: 'tcf-l3-10',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : quel est le sujet du débat ?',
      promptFr: 'Quel est le sujet du débat ?',
      audioText: 'Notre débat d\'aujourd\'hui porte sur la semaine de quatre jours à l\'école. Pour les partisans, elle améliorerait la concentration des élèves et la qualité de vie des familles. Les opposants craignent une baisse du niveau et des difficultés de garde pour les parents qui travaillent.',
      options: [
        'La semaine de cinq jours',
        'La semaine de quatre jours à l\'école, avec partisans et opposants',
        'La scolarité à domicile',
        'Les vacances scolaires',
      ],
      answer: 1,
      explanation: 'Le débat porte sur "la semaine de quatre jours à l\'école".',
    },
    {
      id: 'tcf-l3-11',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : que dit l\'experte ?',
      promptFr: 'Que dit l\'experte ?',
      audioText: 'L\'intelligence artificielle va bouleverser de nombreux métiers administratifs d\'ici dix ans. Les tâches répétitives seront automatisées, mais les fonctions nécessitant un jugement critique, de l\'empathie ou de la créativité resteront humaines. La clé, c\'est la formation continue.',
      options: [
        'L\'IA remplacera tous les métiers',
        'L\'IA automatisera les tâches répétitives, mais le jugement critique, l\'empathie et la créativité resteront humaines ; la clé est la formation continue',
        'L\'IA ne changera rien',
        'La formation continue est inutile',
      ],
      answer: 1,
      explanation: 'L\'experte dit que "les tâches répétitives seront automatisées", que "les fonctions nécessitant un jugement critique, de l\'empathie ou de la créativité resteront humaines" et que "La clé, c\'est la formation continue".',
    },
    {
      id: 'tcf-l3-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : que dit l\'urbaniste ?',
      promptFr: 'Que dit l\'urbaniste ?',
      audioText: 'La ville du futur ne sera pas une smart city technologique, mais une ville sobre, végétalisée, et circulaire. Les technologies auront un rôle, mais secondaire. L\'essentiel tiendra à notre capacité à repenser les usages, à mutualiser les espaces et à réduire les déplacements.',
      options: [
        'La ville du futur sera surtout technologique',
        'La ville du futur sera sobre, végétalisée, circulaire ; la technologie aura un rôle secondaire',
        'La ville du futur supprimera les espaces publics',
        'La mutualisation est inutile',
      ],
      answer: 1,
      explanation: 'L\'urbaniste dit : "La ville du futur ne sera pas une smart city technologique, mais une ville sobre, végétalisée, et circulaire".',
    },
    {
      id: 'tcf-l3-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : que dit le journaliste ?',
      promptFr: 'Que dit le journaliste ?',
      audioText: 'Le Télétravail a un effet pervers peu évoqué : la concentration dans les grandes métropoles de fonctions autrefois réparties sur le territoire. Si rien n\'est fait, le risque est une France à deux vitesses, avec des villes désertées et des métropoles saturées.',
      options: [
        'Le télétravail répartit mieux les emplois',
        'Le télétravail concentre les fonctions dans les grandes métropoles, risque d\'une France à deux vitesses',
        'Le télétravail n\'a aucun effet géographique',
        'Les villes désertées se repeuplent',
      ],
      answer: 1,
      explanation: 'Le journaliste dit que le télétravail "a un effet pervers peu évoqué : la concentration dans les grandes métropoles de fonctions autrefois réparties" et craint "une France à deux vitesses".',
    },
    {
      id: 'tcf-l3-14',
      type: 'multiple_choice',
      level: 'C1',
      prompt: 'Écoutez et répondez : qu\'affirme l\'historien ?',
      promptFr: 'Qu\'affirme l\'historien ?',
      audioText: 'Les révolutions ne se font pas dans la rue, contrairement à la légende : elles s\'y achèvent. Elles commencent, presque toujours, dans l\'intimité des consciences, des lectures, des conversations, bien avant de basculer dans l\'action.',
      options: [
        'Les révolutions se font uniquement dans la rue',
        'Les révolutions commencent dans les consciences, les lectures, les conversations, et s\'achèvent dans la rue',
        'Les révolutions ne commencent jamais',
        'La rue n\'a aucun rôle',
      ],
      answer: 1,
      explanation: 'L\'historien affirme : "Elles commencent, presque toujours, dans l\'intimité des consciences, des lectures, des conversations, bien avant de basculer dans l\'action".',
    },
    {
      id: 'tcf-l3-15',
      type: 'multiple_choice',
      level: 'C1',
      prompt: 'Écoutez et répondez : que dit le philosophe ?',
      promptFr: 'Que dit le philosophe ?',
      audioText: 'Toute identité est une construction, jamais un donné. C\'est en cela qu\'elle est fragile, mais c\'est aussi ce qui la rend libre : on peut toujours la réinventer, la nier, l\'élargir. La rigidité identitaire est le propre des sociétés qui n\'osent plus se poser la question de leur avenir.',
      options: [
        'L\'identité est un donné fixe',
        'L\'identité est une construction, fragile mais libre, toujours réinventable',
        'L\'identité ne peut jamais changer',
        'La rigidité identitaire est positive',
      ],
      answer: 1,
      explanation: 'Le philosophe dit : "Toute identité est une construction, jamais un donné" et "on peut toujours la réinventer, la nier, l\'élargir".',
    },
  ],
};

// ---------------------------------------------------------------------------
// LANGUAGE STRUCTURES — 3 tests × 15 questions (grammar + vocabulary)
// ---------------------------------------------------------------------------

const tcfLangTest1: PracticeTest = {
  id: 'tcf-lang-test-1',
  title: 'Language Structures Practice Test 1',
  titleFr: 'Structures de la langue — Test 1',
  description: '15 questions — grammaire et vocabulaire, difficulté progressive.',
  questions: [
    {
      id: 'tcf-lang1-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Complétez : « ___ vous allez ? »',
      promptFr: 'Complétez la phrase.',
      options: ['Comment', 'Quel', 'Quand', 'Pourquoi'],
      answer: 0,
      explanation: 'Pour demander comment quelqu\'un va, on dit : "Comment allez-vous ?"',
    },
    {
      id: 'tcf-lang1-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Complétez : « Elle ___ une voiture rouge. »',
      promptFr: 'Complétez la phrase.',
      options: ['a', 'as', 'ont', 'est'],
      answer: 0,
      explanation: 'Avec "elle", on conjugue "avoir" en "a".',
    },
    {
      id: 'tcf-lang1-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « Hier, je ___ au cinéma avec mes amis. »',
      promptFr: 'Complétez la phrase.',
      options: ['suis allé', 'allais', 'irai', 'aller'],
      answer: 0,
      explanation: 'Passé composé avec "être" : "je suis allé" (déplacement).',
    },
    {
      id: 'tcf-lang1-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « Le match commence ___ 20 heures. »',
      promptFr: 'Complétez la phrase.',
      options: ['à', 'en', 'dans', 'pour'],
      answer: 0,
      explanation: 'Heure précise : préposition "à" → "à 20 heures".',
    },
    {
      id: 'tcf-lang1-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « C\'est la femme ___ parle avec mon père. »',
      promptFr: 'Complétez la phrase.',
      options: ['qui', 'que', 'dont', 'où'],
      answer: 0,
      explanation: 'Sujet : "qui" (la femme qui parle = la femme est sujet de "parle").',
    },
    {
      id: 'tcf-lang1-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Si j\'avais plus de temps, je ___ faire du sport. »',
      promptFr: 'Complétez la phrase.',
      options: ['ferais', 'fais', 'ferai', 'faisais'],
      answer: 0,
      explanation: 'Hypothèse présente (si + imparfait) → conditionnel présent : "je ferais".',
    },
    {
      id: 'tcf-lang1-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Il faut que nous ___ à l\'heure. »',
      promptFr: 'Complétez la phrase.',
      options: ['soyons', 'sommes', 'serons', 'étions'],
      answer: 0,
      explanation: 'Après "il faut que", on emploie le subjonctif : "que nous soyons".',
    },
    {
      id: 'tcf-lang1-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « La maison ___ je viens d\'emménager est ancienne. »',
      promptFr: 'Complétez la phrase.',
      options: ['dont', 'que', 'où', 'qui'],
      answer: 2,
      explanation: 'Lieu : "où" (la maison où je viens d\'emménager = lieu de l\'emménagement).',
    },
    {
      id: 'tcf-lang1-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Je travaille ici ___ cinq ans. »',
      promptFr: 'Complétez la phrase.',
      options: ['depuis', 'pendant', 'pour', 'dans'],
      answer: 0,
      explanation: 'Action qui continue : "depuis" (depuis 5 ans). "Pendant" marque une durée finie.',
    },
    {
      id: 'tcf-lang1-10',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Bien qu\'elle ___ très fatiguée, elle a tenu à venir. »',
      promptFr: 'Complétez la phrase.',
      options: ['soit', 'est', 'était', 'sera'],
      answer: 0,
      explanation: 'Après "bien que", on emploie le subjonctif : "bien qu\'elle soit".',
    },
    {
      id: 'tcf-lang1-11',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Je n\'ai pas pu venir ___ mes obligations professionnelles. »',
      promptFr: 'Complétez la phrase.',
      options: ['à cause de', 'grâce à', 'malgré', 'puisque'],
      answer: 0,
      explanation: 'Cause négative : "à cause de mes obligations".',
    },
    {
      id: 'tcf-lang1-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Le rapport souligne que les retards ___ en augmentation. »',
      promptFr: 'Complétez la phrase.',
      options: ['sont', 'est', 'seraient', 'était'],
      answer: 0,
      explanation: '"les retards" est pluriel, présent : "sont en augmentation".',
    },
    {
      id: 'tcf-lang1-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « ___ ses études, il a trouvé un emploi rapidement. »',
      promptFr: 'Complétez la phrase.',
      options: ['Après', 'Pendant', 'Avant', 'Malgré'],
      answer: 0,
      explanation: 'On dit "après ses études" pour une action postérieure.',
    },
    {
      id: 'tcf-lang1-14',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Cette pollution est ___ pour la santé. »',
      promptFr: 'Complétez la phrase.',
      options: ['néfaste', 'utile', 'agréable', 'indispensable'],
      answer: 0,
      explanation: '"Néfaste" = nuisible. La pollution est mauvaise pour la santé.',
    },
    {
      id: 'tcf-lang1-15',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Je te prête mon livre ___ que tu me le rendes demain. »',
      promptFr: 'Complétez la phrase.',
      options: ['pourvu', 'parce', 'bien', 'afin'],
      answer: 0,
      explanation: 'On dit "pourvu que" + subjonctif pour exprimer une condition souhaitée.',
    },
  ],
};

const tcfLangTest2: PracticeTest = {
  id: 'tcf-lang-test-2',
  title: 'Language Structures Practice Test 2',
  titleFr: 'Structures de la langue — Test 2',
  description: '15 questions — grammaire et vocabulaire, difficulté progressive.',
  questions: [
    {
      id: 'tcf-lang2-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Complétez : « Nous ___ dans une petite ville. »',
      promptFr: 'Complétez la phrase.',
      options: ['habitons', 'habitez', 'habitent', 'habite'],
      answer: 0,
      explanation: 'Avec "nous", on conjugue "habiter" en "habitons".',
    },
    {
      id: 'tcf-lang2-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Complétez : « Il est 14 heures ___. »',
      promptFr: 'Complétez la phrase.',
      options: ['et demie', 'et demi', 'et demies', 'et demis'],
      answer: 0,
      explanation: 'On dit "14 heures et demie" : "demie" s\'accorde au féminin car "heure" est féminin.',
    },
    {
      id: 'tcf-lang2-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « Mon frère est né ___ 1990. »',
      promptFr: 'Complétez la phrase.',
      options: ['en', 'à', 'dans', 'pour'],
      answer: 0,
      explanation: 'Année : préposition "en" → "en 1990".',
    },
    {
      id: 'tcf-lang2-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « ___ tu viens ce soir ? »',
      promptFr: 'Complétez la phrase.',
      options: ['Est-ce que', 'Que', 'Qui', 'Où'],
      answer: 0,
      explanation: 'Question fermée : "Est-ce que tu viens ce soir ?"',
    },
    {
      id: 'tcf-lang2-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « La fille ___ je travaille s\'appelle Léa. »',
      promptFr: 'Complétez la phrase.',
      options: ['avec qui', 'que', 'dont', 'où'],
      answer: 0,
      explanation: 'On dit "travailler avec quelqu\'un" : "avec qui" (la fille avec qui je travaille).',
    },
    {
      id: 'tcf-lang2-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Quand j\'étais enfant, je ___ la mer tous les étés. »',
      promptFr: 'Complétez la phrase.',
      options: ['allais à', 'vais à', 'irai à', 'suis allé à'],
      answer: 0,
      explanation: 'Habitude passée : imparfait "j\'allais à la mer".',
    },
    {
      id: 'tcf-lang2-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Il est possible qu\'il ___ en retard. »',
      promptFr: 'Complétez la phrase.',
      options: ['arrive', 'arrives', 'arrivera', 'arrivait'],
      answer: 0,
      explanation: 'Après "il est possible que", on emploie le subjonctif. Avec "il" : "qu\'il arrive".',
    },
    {
      id: 'tcf-lang2-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Je te rappellerai ___ je rentre. »',
      promptFr: 'Complétez la phrase.',
      options: ['dès que', 'avant que', 'bien que', 'puisque'],
      answer: 0,
      explanation: 'On dit "dès que" pour marquer la simultanéité.',
    },
    {
      id: 'tcf-lang2-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Le film ___ j\'ai vu hier était passionnant. »',
      promptFr: 'Complétez la phrase.',
      options: ['que', 'qui', 'dont', 'où'],
      answer: 0,
      explanation: 'COD : "que" (le film que j\'ai vu).',
    },
    {
      id: 'tcf-lang2-10',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Je ne pense pas qu\'il ___ raison. »',
      promptFr: 'Complétez la phrase.',
      options: ['ait', 'a', 'aura', 'avait'],
      answer: 0,
      explanation: 'Après "ne pas penser que", on emploie le subjonctif : "qu\'il ait".',
    },
    {
      id: 'tcf-lang2-11',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « ___ la pluie, la fête a été annulée. »',
      promptFr: 'Complétez la phrase.',
      options: ['À cause de', 'Grâce à', 'Malgré', 'Pendant'],
      answer: 0,
      explanation: 'Cause négative : "À cause de la pluie".',
    },
    {
      id: 'tcf-lang2-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Cette entreprise est ___ pour la qualité de ses produits. »',
      promptFr: 'Complétez la phrase.',
      options: ['connue', 'connu', 'connus', 'connues'],
      answer: 0,
      explanation: '"Entreprise" féminin singulier : "connue".',
    },
    {
      id: 'tcf-lang2-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Il a ___ de partir sans dire au revoir. »',
      promptFr: 'Complétez la phrase.',
      options: ['fini', 'finir', 'finit', 'finissant'],
      answer: 0,
      explanation: 'On dit "finir de" + infinitif : "Il a fini de partir".',
    },
    {
      id: 'tcf-lang2-14',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Le gouvernement a pris des mesures pour ___ la crise. »',
      promptFr: 'Complétez la phrase.',
      options: ['résoudre', 'résoudra', 'résolu', 'résolvant'],
      answer: 0,
      explanation: 'Après "pour", on emploie l\'infinitif : "pour résoudre la crise".',
    },
    {
      id: 'tcf-lang2-15',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Je te conseille de prendre cette décision ___, sans attendre. »',
      promptFr: 'Complétez la phrase.',
      options: ['rapidement', 'lentement', 'souvent', 'jamais'],
      answer: 0,
      explanation: '"Sans attendre" indique le besoin d\'agir vite : "rapidement".',
    },
  ],
};

const tcfLangTest3: PracticeTest = {
  id: 'tcf-lang-test-3',
  title: 'Language Structures Practice Test 3',
  titleFr: 'Structures de la langue — Test 3',
  description: '15 questions — grammaire et vocabulaire, difficulté progressive.',
  questions: [
    {
      id: 'tcf-lang3-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Complétez : « Tu ___ quelle nationalité ? »',
      promptFr: 'Complétez la phrase.',
      options: ['as', 'es', 'a', 'est'],
      answer: 0,
      explanation: 'On dit "avoir une nationalité" : "Tu as quelle nationalité ?"',
    },
    {
      id: 'tcf-lang3-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Complétez : « ___ langue parles-tu ? »',
      promptFr: 'Complétez la phrase.',
      options: ['Quelle', 'Quel', 'Qu\'', 'Quand'],
      answer: 0,
      explanation: '"Langue" est féminin singulier : "Quelle langue ?"',
    },
    {
      id: 'tcf-lang3-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « Ma sœur ___ à Paris depuis 5 ans. »',
      promptFr: 'Complétez la phrase.',
      options: ['habite', 'habites', 'habitent', 'habiter'],
      answer: 0,
      explanation: 'Avec "ma sœur" (elle), on emploie "habite" (3e personne du singulier, présent).',
    },
    {
      id: 'tcf-lang3-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « Nous allons partir ___ vacances en août. »',
      promptFr: 'Complétez la phrase.',
      options: ['en', 'à', 'pour', 'dans'],
      answer: 0,
      explanation: 'On dit "partir en vacances" : préposition "en".',
    },
    {
      id: 'tcf-lang3-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « C\'est le film ___ j\'ai préféré. »',
      promptFr: 'Complétez la phrase.',
      options: ['que', 'qui', 'dont', 'où'],
      answer: 0,
      explanation: 'COD : "que" (le film que j\'ai préféré).',
    },
    {
      id: 'tcf-lang3-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Si tu m\'avais prévenu, je ___ t\'attendre. »',
      promptFr: 'Complétez la phrase.',
      options: ['serais venu', 'viendrai', 'viendrais', 'serai venu'],
      answer: 0,
      explanation: 'Hypothèse passée (si + plus-que-parfait) → conditionnel passé : "je serais venu t\'attendre".',
    },
    {
      id: 'tcf-lang3-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Il vaut mieux que tu ___ ton médecin. »',
      promptFr: 'Complétez la phrase.',
      options: ['appelles', 'appelle', 'appelleras', 'appelais'],
      answer: 0,
      explanation: 'Après "il vaut mieux que", on emploie le subjonctif : "que tu appelles".',
    },
    {
      id: 'tcf-lang3-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « La ville ___ je suis né a beaucoup changé. »',
      promptFr: 'Complétez la phrase.',
      options: ['où', 'que', 'qui', 'dont'],
      answer: 0,
      explanation: 'Lieu : "où" (la ville où je suis né).',
    },
    {
      id: 'tcf-lang3-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Je n\'ai pas vu ce film, mais j\'aimerais ___ . »',
      promptFr: 'Complétez la phrase.',
      options: ['le voir', 'le vois', 'le verrai', 'le voyais'],
      answer: 0,
      explanation: 'Après "aimerais", on emploie l\'infinitif : "le voir".',
    },
    {
      id: 'tcf-lang3-10',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Il est important que nous ___ respectueux de l\'environnement. »',
      promptFr: 'Complétez la phrase.',
      options: ['soyons', 'sommes', 'serons', 'étions'],
      answer: 0,
      explanation: 'Après "il est important que", on emploie le subjonctif : "que nous soyons".',
    },
    {
      id: 'tcf-lang3-11',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Ce livre est ___ que je n\'arrive pas à le lâcher. »',
      promptFr: 'Complétez la phrase.',
      options: ['si captivant', 'tellement captivant', 'aussi captivant', 'autant captivant'],
      answer: 0,
      explanation: 'On dit "si + adjectif + que" pour exprimer une conséquence : "si captivant que".',
    },
    {
      id: 'tcf-lang3-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Je me demande s\'il ___ être à l\'heure. »',
      promptFr: 'Complétez la phrase.',
      options: ['va', 'allait', 'irait', 'aille'],
      answer: 0,
      explanation: 'Futur proche dans une interrogation indirecte : "s\'il va être à l\'heure".',
    },
    {
      id: 'tcf-lang3-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « La réussite de ce projet ___ de plusieurs facteurs. »',
      promptFr: 'Complétez la phrase.',
      options: ['dépend', 'dépends', 'dépendent', 'dépendait'],
      answer: 0,
      explanation: '"La réussite" singulier : "dépend" (3e personne du singulier présent).',
    },
    {
      id: 'tcf-lang3-14',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Le mot "écouter" appartient ___ groupe des verbes du 1er groupe. »',
      promptFr: 'Complétez la phrase.',
      options: ['au', 'à le', 'à la', 'du'],
      answer: 0,
      explanation: 'Contraction de "à + le" : "au groupe".',
    },
    {
      id: 'tcf-lang3-15',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Tu devrais ___ cette offre, elle est très intéressante. »',
      promptFr: 'Complétez la phrase.',
      options: ['accepter', 'acceptes', 'accepteras', 'acceptais'],
      answer: 0,
      explanation: 'Après "devrais", on emploie l\'infinitif : "accepter".',
    },
  ],
};

// ---------------------------------------------------------------------------
// EXPORTED SECTIONS
// ---------------------------------------------------------------------------

export const tcfExpandedSections: ExpandedTestSection[] = [
  {
    id: 'reading',
    title: 'Reading Comprehension',
    titleFr: 'Compréhension écrite',
    description:
      'TCF Reading: 29 questions in 25 minutes, progressive difficulty A1→C2. Choose the correct answer for each text.',
    icon: '📖',
    tests: [tcfReadingTest1, tcfReadingTest2, tcfReadingTest3],
  },
  {
    id: 'listening',
    title: 'Listening Comprehension',
    titleFr: 'Compréhension orale',
    description:
      'TCF Listening: 29 questions in 25 minutes, progressive difficulty (with audioText for TTS playback).',
    icon: '🎧',
    tests: [tcfListeningTest1, tcfListeningTest2, tcfListeningTest3],
  },
  {
    id: 'language_structures',
    title: 'Language Structures',
    titleFr: 'Structures de la langue',
    description:
      'TCF Language Structures: grammar and vocabulary questions with progressive difficulty (A1→C2).',
    icon: '✏️',
    tests: [tcfLangTest1, tcfLangTest2, tcfLangTest3],
  },
];

export default tcfExpandedSections;
