import type { MockTest } from './types';

// TCF — Test de Connaissance du Français
// Administered by France Éducation International (FEI)
// Used for: French nationality/citizenship, France residency card, Quebec CSQ, university admission
// Real test: Reading 29Q/25min, Listening 29Q/25min, plus optional Speaking (12min) and Writing (60min)
export const tcfTest: MockTest = {
  type: 'TCF',
  name: 'TCF',
  fullName: 'Test de Connaissance du Français',
  description:
    "The TCF is the French Ministry of Education's test for non-native speakers. It evaluates French proficiency on a scale from A1 to C2. It is officially recognized for French nationality applications, Quebec selection, and French university admission.",
  administeredBy: 'France Éducation International (FEI)',
  usedFor: 'French nationality/citizenship (B1 required), residency card (A2 required), Quebec CSQ, French university admission, CEFRL certification',
  color: '#B91C1C',
  sections: [
    {
      id: 'reading',
      title: 'Reading Comprehension',
      titleFr: 'Compréhension écrite',
      description: 'Read texts and answer questions. Real TCF: 29 questions in 25 minutes.',
      icon: '📖',
      questionCount: 10,
      durationMinutes: 10,
      questions: [
        {
          id: 'tcf-r-1',
          type: 'multiple_choice',
          level: 'A1',
          prompt: 'Read:\n\n"Salut Léa, c\'est Tom. Je suis à la boulangerie. Tu veux quelque chose ?"',
          options: [
            'Tom is at home.',
            'Tom is at the bakery.',
            'Tom is at the bank.',
            'Tom is at school.',
          ],
          answer: 1,
          explanation: '"Je suis à la boulangerie" = I am at the bakery.',
        },
        {
          id: 'tcf-r-2',
          type: 'multiple_choice',
          level: 'A1',
          prompt: 'Read:\n\n"HORAIRES :\nLundi - Vendredi : 9h00 - 18h00\nSamedi : 10h00 - 16h00\nDimanche : Fermé"',
          options: [
            'Open Sunday 10-16.',
            'Open Saturday 10-16.',
            'Open Monday 8-18.',
            'Closed on Saturday.',
          ],
          answer: 1,
          explanation: 'Samedi : 10h00 - 16h00 — Open Saturday 10 AM to 4 PM.',
        },
        {
          id: 'tcf-r-3',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Read:\n\n"Chers voisins, une fuite d\'eau aura lieu demain matin entre 9h et 11h dans le bâtiment B. L\'eau sera coupée pendant ces deux heures. Merci de votre compréhension."',
          options: [
            'Water will be cut for 2 hours in building B.',
            'Water will be cut all day.',
            'A water leak is happening right now.',
            'The water is fine in building B.',
          ],
          answer: 0,
          explanation: '"L\'eau sera coupée pendant ces deux heures." — Water cut for 2 hours.',
        },
        {
          id: 'tcf-r-4',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Read the recipe:\n\n"Pour faire une omelette : cassez 3 œufs, battez-les, ajoutez du sel et du poivre. Faites chauffer du beurre dans une poêle, versez les œufs, laissez cuire 3 minutes."',
          options: [
            'You need 5 eggs.',
            'You don\'t need butter.',
            'Cooking takes about 3 minutes.',
            'You don\'t need salt.',
          ],
          answer: 2,
          explanation: '"laissez cuire 3 minutes" — cook for 3 minutes.',
        },
        {
          id: 'tcf-r-5',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Read:\n\n"Suite à votre candidature, nous avons le plaisir de vous convier à un entretien le 15 mars à 14h. Merci de confirmer votre présence par retour de mail."',
          options: [
            'The candidate was rejected.',
            'The candidate is invited to an interview on March 15.',
            'The interview will be online.',
            'The candidate has been hired.',
          ],
          answer: 1,
          explanation: '"nous avons le plaisir de vous convier à un entretien le 15 mars" — invited to interview March 15.',
        },
        {
          id: 'tcf-r-6',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Read:\n\n"Le festival de musique de Nice attire chaque année plus de 50 000 visiteurs. Cette année, l\'édition mettra à l\'honneur les artistes méditerranéens du 12 au 15 juillet."',
          options: [
            'The festival is in winter.',
            'The festival features Mediterranean artists.',
            'The festival has 5,000 visitors.',
            'The festival lasts 12 days.',
          ],
          answer: 1,
          explanation: '"l\'édition mettra à l\'honneur les artistes méditerranéens" — features Mediterranean artists.',
        },
        {
          id: 'tcf-r-7',
          type: 'multiple_choice',
          level: 'B2',
          prompt: 'Read:\n\n"Si la France a longtemps été un modèle en matière de protection sociale, son système fait aujourd\'hui face à des défis majeurs. Le vieillissement de la population et la hausse du chômage obligent à repenser le modèle."',
          options: [
            'The French social system is perfect.',
            'The French social system needs to be rethought.',
            'The aging population helps the system.',
            'Unemployment is decreasing.',
          ],
          answer: 1,
          explanation: '"obligent à repenser le modèle" — must rethink the model.',
        },
        {
          id: 'tcf-r-8',
          type: 'multiple_choice',
          level: 'B2',
          prompt: 'Read:\n\n"Longtemps considéré comme un simple loisir, le jardinage est aujourd\'hui reconnu pour ses bienfaits thérapeutiques. Plusieurs hôpitaux l\'utilisent comme traitement complémentaire."',
          options: [
            'Gardening is only a hobby.',
            'Gardening has therapeutic benefits.',
            'Hospitals reject gardening.',
            'Gardening is bad for health.',
          ],
          answer: 1,
          explanation: '"reconnu pour ses bienfaits thérapeutiques" — recognized for therapeutic benefits.',
        },
        {
          id: 'tcf-r-9',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Read:\n\n"À LOUER : Bel appartement 3 pièces, 65m², centre-ville, balcon, parking. 750€/mois charges comprises. Disponible 1er avril. Tél : 04 78 90 12 34."',
          options: [
            'The apartment has no parking.',
            'The apartment is 65 square meters.',
            'Rent is 700€/month.',
            'The apartment is available May 1st.',
          ],
          answer: 1,
          explanation: '"65m²" — 65 square meters.',
        },
        {
          id: 'tcf-r-10',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Read:\n\n"Vu la météo défavorable, la course cycliste prévue dimanche est annulée. Les participants seront remboursés. Une nouvelle date sera communiquée prochainement."',
          options: [
            'The race is postponed but the date is set.',
            'Participants will get their money back.',
            'The race will happen in spite of weather.',
            'No refunds will be given.',
          ],
          answer: 1,
          explanation: '"Les participants seront remboursés." — Participants will be reimbursed.',
        },
      ],
    },
    {
      id: 'listening',
      title: 'Listening Comprehension',
      titleFr: 'Compréhension orale',
      description: 'Listen to audio (use speaker button) and answer questions. Real TCF: 29 questions in 25 minutes.',
      icon: '🎧',
      questionCount: 10,
      durationMinutes: 10,
      questions: [
        {
          id: 'tcf-l-1',
          type: 'multiple_choice',
          level: 'A1',
          prompt: 'Listen:',
          audioText: 'Bonjour, je cherche la pharmacie. Savez-vous où c\'est ?',
          options: [
            'The person is looking for a bakery.',
            'The person is looking for a pharmacy.',
            'The person is at the pharmacy.',
            'The person works at the pharmacy.',
          ],
          answer: 1,
          explanation: '"je cherche la pharmacie" = I\'m looking for the pharmacy.',
        },
        {
          id: 'tcf-l-2',
          type: 'multiple_choice',
          level: 'A1',
          prompt: 'Listen to the question:',
          audioText: 'Quelle heure est-il ? — Il est dix-sept heures.',
          options: ['5:00 AM', '5:00 PM', '7:00 PM', '10:00 AM'],
          answer: 1,
          explanation: '"dix-sept heures" = 17h = 5 PM.',
        },
        {
          id: 'tcf-l-3',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Listen to the conversation:',
          audioText: 'Qu\'est-ce que tu vas faire ce week-end ? — S\'il fait beau, j\'irai à la plage avec mes amis. Et toi ? — Moi, je vais rester à la maison pour réviser mes examens.',
          options: [
            'Both will go to the beach.',
            'One will go to the beach, the other will study.',
            'Both will study.',
            'The weather will be bad.',
          ],
          answer: 1,
          explanation: 'Personne 1 : plage ; Personne 2 : réviser.',
        },
        {
          id: 'tcf-l-4',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Listen:',
          audioText: 'Madame Dubois, votre rendez-vous avec le docteur Martin est confirmé pour jeudi à 16h30. Merci d\'arriver 10 minutes en avance.',
          options: [
            'Appointment is Wednesday at 4:30 PM.',
            'Appointment is Thursday at 4:30 PM.',
            'Patient should arrive at 4:30 PM.',
            'Appointment is cancelled.',
          ],
          answer: 1,
          explanation: '"jeudi à 16h30" = Thursday at 4:30 PM.',
        },
        {
          id: 'tcf-l-5',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Listen to the announcement:',
          audioText: 'En raison de travaux sur la ligne, le métro ligne 4 ne circulera pas entre les stations Châtelet et Gare du Nord ce week-end. Des bus de remplacement sont mis en place.',
          options: [
            'Metro line 4 is closed all weekend.',
            'Metro line 4 is partially closed between Châtelet and Gare du Nord.',
            'Metro line 4 is closed forever.',
            'There is no replacement transport.',
          ],
          answer: 1,
          explanation: '"ne circulera pas entre les stations Châtelet et Gare du Nord" — partial closure.',
        },
        {
          id: 'tcf-l-6',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Listen to the report:',
          audioText: 'Une étude révèle que les Français lisent en moyenne 12 livres par an, contre 15 il y a dix ans. La baisse est surtout marquée chez les jeunes de 15 à 25 ans.',
          options: [
            'French people read more than before.',
            'French people read 12 books per year on average.',
            'Young people read more than before.',
            'Reading has increased overall.',
          ],
          answer: 1,
          explanation: '"les Français lisent en moyenne 12 livres par an".',
        },
        {
          id: 'tcf-l-7',
          type: 'multiple_choice',
          level: 'B2',
          prompt: 'Listen to the interview:',
          audioText: 'Mon métier d\'écrivain me permet d\'explorer des thèmes universels. Mais je dois dire que le plus difficile, ce n\'est pas d\'écrire, c\'est de se faire publier. Le marché est très compétitif aujourd\'hui.',
          options: [
            'The speaker finds writing the hardest part.',
            'The speaker finds publishing the hardest part.',
            'The speaker is a publisher.',
            'The speaker writes about competition.',
          ],
          answer: 1,
          explanation: '"le plus difficile, ce n\'est pas d\'écrire, c\'est de se faire publier" — publishing is hardest.',
        },
        {
          id: 'tcf-l-8',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Listen to the message:',
          audioText: 'Bonjour, c\'est Sophie. Je t\'appelle pour ton anniversaire. On pourrait aller au restaurant vendredi soir ? Appelle-moi !',
          options: [
            'Sophie wants to go to the cinema.',
            'Sophie wants to celebrate a birthday at a restaurant.',
            'Sophie is calling about work.',
            'Sophie is sick.',
          ],
          answer: 1,
          explanation: '"pour ton anniversaire... aller au restaurant" — birthday dinner.',
        },
        {
          id: 'tcf-l-9',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Listen to the news:',
          audioText: 'La mairie de Paris a annoncé hier l\'interdiction des voitures diesel dans le centre-ville à partir de 2025. Cette mesure vise à réduire la pollution de 40% d\'ici cinq ans.',
          options: [
            'Diesel cars will be banned from central Paris from 2025.',
            'All cars will be banned.',
            'Pollution is not a problem.',
            'The measure has no goal.',
          ],
          answer: 0,
          explanation: '"interdiction des voitures diesel dans le centre-ville à partir de 2025."',
        },
        {
          id: 'tcf-l-10',
          type: 'multiple_choice',
          level: 'B2',
          prompt: 'Listen:',
          audioText: 'Contrairement à ce qu\'on pourrait penser, les jeunes Français ne sont pas moins engagés que leurs aînés. Simplement, ils s\'engagent différemment : à travers des associations locales plutôt que des partis politiques.',
          options: [
            'Young French people are not engaged.',
            'Young French people engage differently than their elders.',
            'Young French people prefer political parties.',
            'Older people don\'t engage in associations.',
          ],
          answer: 1,
          explanation: '"ils s\'engagent différemment" — they engage differently.',
        },
      ],
    },
    {
      id: 'vocabulary_grammar',
      title: 'Language Structures',
      titleFr: 'Maîtrise des structures de la langue',
      description: 'Note: In the real TCF, vocabulary-grammar is integrated into reading. We include it here as a focused section.',
      icon: '✏️',
      questionCount: 10,
      durationMinutes: 8,
      questions: [
        {
          id: 'tcf-vg-1',
          type: 'multiple_choice',
          level: 'A1',
          prompt: 'Complete: "Tu _____ un chien ?"',
          options: ['as', 'a', 'est', 'ont'],
          answer: 0,
          explanation: 'Tu + as = you have.',
        },
        {
          id: 'tcf-vg-2',
          type: 'multiple_choice',
          level: 'A1',
          prompt: 'Complete: "Je voudrais _____ pain." (some bread)',
          options: ['du', 'le', 'un', 'des'],
          answer: 0,
          explanation: 'Pain (m) → partitive "du": du pain.',
        },
        {
          id: 'tcf-vg-3',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Complete: "L\'été dernier, nous _____ en Italie."',
          options: ['sommes allés', 'avons allé', 'allions', 'irons'],
          answer: 0,
          explanation: 'Aller + être in passé composé: nous sommes allés.',
        },
        {
          id: 'tcf-vg-4',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Complete: "Avant, j\'_____ à Paris."',
          options: ['habite', 'ai habité', 'habitais', 'habiterai'],
          answer: 2,
          explanation: 'Imparfait for habitual past: j\'habitais.',
        },
        {
          id: 'tcf-vg-5',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Complete: "Je voudrais que tu _____ la vérité."',
          options: ['sais', 'saches', 'savais', 'sache'],
          answer: 1,
          explanation: 'After "vouloir que", use subjunctive: tu saches.',
        },
        {
          id: 'tcf-vg-6',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Complete: "Si tu _____, tu réussirais."',
          options: ['étudies', 'étudiais', 'étudieras', 'étudier'],
          answer: 1,
          explanation: 'Si + imparfait → conditionnel présent: si tu étudiais.',
        },
        {
          id: 'tcf-vg-7',
          type: 'multiple_choice',
          level: 'B2',
          prompt: 'Complete: "Quoiqu\'il _____ tard, on continue."',
          options: ['est', 'soit', 'était', 'sera'],
          answer: 1,
          explanation: 'Quoique + subjunctive: quoiqu\'il soit.',
        },
        {
          id: 'tcf-vg-8',
          type: 'multiple_choice',
          level: 'B2',
          prompt: 'Complete: "Si j\'avais eu le temps, j\'_____ visité le musée."',
          options: ['aurais', 'serais', 'avais', 'ai'],
          answer: 0,
          explanation: 'Visiter uses avoir: conditionnel passé = j\'aurais visité.',
        },
        {
          id: 'tcf-vg-9',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Choose the correct sentence:',
          options: ['Je le vois hier.', 'Je l\'ai vu hier.', 'Je le ai vu hier.', 'Je l\'ai voirs hier.'],
          answer: 1,
          explanation: 'Passé composé with avoir: Je l\'ai vu (le → l\' before ai).',
        },
        {
          id: 'tcf-vg-10',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Complete: "Le livre _____ par l\'écrivain en 1990."',
          options: ['écrit', 'est écrit', 'a écrit', 'écrivait'],
          answer: 1,
          explanation: 'Passive: être + past participle: est écrit (was written).',
        },
      ],
    },
  ],
};
