import type { TestQuestion } from './types';

// TEF — Test d'Évaluation de Français (Expanded Question Bank)
// Administered by CCIP (Paris Île-de-France CCI).
// Real exam: Reading 50Q/60min (3 sections A/B/C), Listening 60Q/40min,
// Vocabulary & Grammar 40Q/15min.
// This expanded bank provides 3 full practice tests per section (135 questions total).

export interface PracticeTest {
  id: string;
  title: string;
  titleFr: string;
  description: string;
  questions: TestQuestion[];
}

export interface ExpandedTestSection {
  id: string; // 'reading' | 'listening' | 'vocabulary_grammar'
  title: string;
  titleFr: string;
  description: string;
  icon: string;
  tests: PracticeTest[];
}

// ---------------------------------------------------------------------------
// READING COMPREHENSION — 3 tests × 15 questions (5 Section A, 5 Section B, 5 Section C)
// ---------------------------------------------------------------------------

const tefReadingTest1: PracticeTest = {
  id: 'tef-reading-test-1',
  title: 'Reading Practice Test 1',
  titleFr: 'Compréhension écrite — Test 1',
  description:
    '15 questions covering Section A (signs & announcements), Section B (short texts) and Section C (longer texts).',
  questions: [
    // -- Section A: Signs, notices, announcements --
    {
      id: 'tef-r1-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Section A — Lisez le panneau et répondez :\n\n« FERMÉ LE LUNDI. Ouvert mardi au samedi : 9h - 19h. Dimanche : 9h - 13h. »',
      promptFr: 'Que dit cette affiche ?',
      options: [
        'Le magasin est ouvert le lundi toute la journée.',
        'Le magasin est fermé le dimanche matin.',
        'Le magasin est ouvert le dimanche matin.',
        'Le magasin ferme à 19h le dimanche.',
      ],
      answer: 2,
      explanation: '"Dimanche : 9h - 13h" indique que le magasin est ouvert le dimanche matin de 9h à 13h.',
    },
    {
      id: 'tef-r1-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Section A — Lisez l\'affiche :\n\n« MUSÉE DU LOUVRE\nEntrée : 17 € — Gratuit le 1er dimanche de chaque mois.\nFermeture des salles à partir de 17h45. »',
      promptFr: 'Que signifie cette affiche ?',
      options: [
        'Le musée est toujours gratuit.',
        'Le musée ferme ses salles à 17h45.',
        'L\'entrée coûte 7 €.',
        'Le musée est fermé les dimanches.',
      ],
      answer: 1,
      explanation: '"Fermeture des salles à partir de 17h45" signifie que les salles commencent à fermer à 17h45.',
    },
    {
      id: 'tef-r1-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Section A — Lisez le panneau à la gare :\n\n« TRAIN N° 6741 à destination de LYON PART-DIEU\nDépart : 14h27 — Voie 12. Retard estimé : 20 minutes. »',
      promptFr: 'Que dit ce panneau ?',
      options: [
        'Le train part à 14h27 à l\'heure.',
        'Le train partira avec environ 20 minutes de retard.',
        'Le train est annulé.',
        'Le train part de la voie 20.',
      ],
      answer: 1,
      explanation: '"Retard estimé : 20 minutes" signifie que le train partira environ 20 min après 14h27.',
    },
    {
      id: 'tef-r1-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Section A — Lisez l\'offre d\'emploi :\n\n« RECHERCHE serveur/se expérimenté(e) pour restaurant italien. Temps plein, week-ends inclus. Début immédiat. Téléphoner au 04 78 90 12 34. »',
      promptFr: 'Que cherche ce restaurant ?',
      options: [
        'Un cuisinier pour la semaine.',
        'Un(e) serveur(se) expérimenté(e), temps plein, week-ends inclus.',
        'Un stagiaire débutant.',
        'Un gérant de restaurant.',
      ],
      answer: 1,
      explanation: 'L\'annonce précise : serveur/se expérimenté(e), temps plein, week-ends inclus, début immédiat.',
    },
    {
      id: 'tef-r1-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Section A — Lisez l\'affiche en bibliothèque :\n\n« SILENCE EXIGÉ. Téléphones portables interdits. Emprunt maximum : 8 ouvrages pour 3 semaines. »',
      promptFr: 'Que doit faire un usager ?',
      options: [
        'Parler à voix haute avec ses amis.',
        'Utiliser son téléphone portable.',
        'Garder le silence et éteindre son téléphone.',
        'Emprunter au maximum 15 livres.',
      ],
      answer: 2,
      explanation: '"Silence exigé" et "téléphones portables interdits" imposent le silence et l\'extinction du téléphone.',
    },
    // -- Section B: Short texts (emails, messages, ads) --
    {
      id: 'tef-r1-6',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Section B — Lisez le message :\n\n« Chère Marie, je ne pourrai pas venir dîner ce soir. J\'ai trop de travail. On se voit samedi ? Bisous, Sophie. »',
      promptFr: 'Que dit Sophie ?',
      options: [
        'Sophie viendra dîner ce soir.',
        'Sophie ne viendra pas dîner ce soir à cause du travail.',
        'Marie ne veut pas dîner avec Sophie.',
        'Sophie est malade.',
      ],
      answer: 1,
      explanation: 'Sophie écrit "je ne pourrai pas venir dîner ce soir. J\'ai trop de travail." Elle propose samedi à la place.',
    },
    {
      id: 'tef-r1-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section B — Lisez l\'invitation :\n\n« Vous êtes invité(e) à l\'anniversaire de Thomas ! Samedi 18 mai à partir de 19h30, au 24 rue des Lilas. Apéritif dinatoire — merci d\'apporter une boisson. RSVP avant le 12 mai. »',
      promptFr: 'Que doivent faire les invités ?',
      options: [
        'Apporter un cadeau coûteux.',
        'Confirmer leur présence avant le 12 mai et apporter une boisson.',
        'Arriver avant 19h30 pour préparer.',
        'Venir le dimanche 19 mai.',
      ],
      answer: 1,
      explanation: 'Les invités doivent RSVP (confirmer) avant le 12 mai et apporter une boisson pour l\'apéritif dinatoire.',
    },
    {
      id: 'tef-r1-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section B — Lisez l\'annonce :\n\n« À LOUER : Appartement T2 de 45 m² au 3e étage avec ascenseur. Cuisine équipée, balcon, parking. Quartier calme proche tramway. Loyer : 720 €/mois charges comprises. Disponible 1er juin. »',
      promptFr: 'Quel est le loyer de l\'appartement ?',
      options: [
        '720 € par mois, charges comprises.',
        '720 € par mois hors charges.',
        '450 € par mois.',
        '720 € par semaine.',
      ],
      answer: 0,
      explanation: '"Loyer : 720 €/mois charges comprises" signifie que les charges sont incluses dans les 720 €.',
    },
    {
      id: 'tef-r1-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section B — Lisez la note :\n\n« Jean est passé à 10h. Il laissera les documents ce soir. Rappelle-le avant 18h, il a besoin de ta réponse pour le contrat. — Karine. »',
      promptFr: 'Que doit faire le destinataire ?',
      options: [
        'Attendre que Jean revienne demain.',
        'Rappeler Jean avant 18h pour le contrat.',
        'Lire les documents ce soir.',
        'Téléphoner à Karine.',
      ],
      answer: 1,
      explanation: 'Karine précise : "Rappelle-le avant 18h, il a besoin de ta réponse pour le contrat."',
    },
    {
      id: 'tef-r1-10',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section B — Lisez la publicité :\n\n« SOLDES D\'HIVER ! Jusqu\'à -50% sur toute la collection homme et femme. Du 8 janvier au 4 février. Profitez-en, stocks limités. Boutique Bonelli, 12 place du Marché. »',
      promptFr: 'Que propose cette publicité ?',
      options: [
        'Une réduction de 50% sur tous les produits pendant un mois.',
        'Une vente privée pour les clients fidèles.',
        'Une nouvelle collection à prix normal.',
        'Des soldes uniquement sur les articles pour enfant.',
      ],
      answer: 0,
      explanation: 'Les soldes vont jusqu\'à -50% sur toute la collection homme/femme du 8 janvier au 4 février.',
    },
    // -- Section C: Longer texts (articles, reports) --
    {
      id: 'tef-r1-11',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section C — Lisez l\'article :\n\n« Selon une étude publiée hier par l\'INSEE, le télétravail a augmenté de 30% en France depuis 2020. Cependant, 45% des employés interrogés regrettent le manque de contacts sociaux et 30% estiment que la frontière entre vie professionnelle et vie privée est devenue floue. »',
      promptFr: 'Quel est le message principal de l\'article ?',
      options: [
        'Le télétravail a baissé depuis 2020.',
        'Tous les employés adorent le télétravail.',
        'Le télétravail a augmenté mais pose des problèmes sociaux et personnels.',
        'Le télétravail est interdit en France.',
      ],
      answer: 2,
      explanation: 'L\'article dit que le télétravail a augmenté de 30%, mais 45% regrettent les contacts sociaux et 30% trouvent la frontière pro/perso floue.',
    },
    {
      id: 'tef-r1-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Section C — Lisez l\'extrait :\n\n« Face à la sécheresse exceptionnelle de cet été, plusieurs communes du sud de la France ont imposé des restrictions d\'eau drastiques. L\'arrosage des jardins est désormais interdit avant 20h, et le remplissage des piscines privées est suspendu jusqu\'à nouvel ordre. Les agriculteurs, eux, réclament des aides pour compenser les pertes. »',
      promptFr: 'Quelle mesure a été prise par les communes ?',
      options: [
        'Interdire l\'arrosage des jardins avant 20h et suspendre le remplissage des piscines privées.',
        'Donner des aides aux propriétaires de piscines.',
        'Interdire totalement l\'usage de l\'eau potable.',
        'Obliger les agriculteurs à fermer.',
      ],
      answer: 0,
      explanation: 'Le texte indique : arrosage interdit avant 20h, remplissage des piscines privées suspendu.',
    },
    {
      id: 'tef-r1-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Section C — Lisez le rapport :\n\n« Le secteur du numérique continue de recruter malgré un contexte économique tendu. Les profils les plus recherchés restent les développeurs, les experts en cybersécurité et les data scientists. Néanmoins, les entreprises soulignent une difficulté croissante à trouver des candidats combinant compétences techniques et soft skills, notamment l\'esprit critique et la communication. »',
      promptFr: 'Que soulignent les entreprises ?',
      options: [
        'Qu\'elles trouvent trop de candidats qualifiés.',
        'Qu\'elles ont du mal à trouver des profils alliant compétences techniques et soft skills.',
        'Que le secteur numérique ne recrute plus.',
        'Que les data scientists ne sont plus recherchés.',
      ],
      answer: 1,
      explanation: 'Les entreprises soulignent "une difficulté croissante à trouver des candidats combinant compétences techniques et soft skills".',
    },
    {
      id: 'tef-r1-14',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Section C — Lisez l\'article de blog :\n\n« Voyager en train à travers l\'Europe redevient populaire. Non seulement ce mode de transport est plus écologique que l\'avion, mais il permet aussi de découvrir des paysages que l\'on ne voit pas depuis les airs. De nombreuses compagnies proposent désormais des pass interrail à prix réduits pour les moins de 27 ans, encourageant ainsi une nouvelle génération à explorer le continent autrement. »',
      promptFr: 'Pourquoi le train redevient-il populaire selon l\'article ?',
      options: [
        'Parce qu\'il est moins cher que l\'avion dans tous les cas.',
        'Parce qu\'il est plus écologique et permet de voir des paysages.',
        'Parce que l\'avion est interdit en Europe.',
        'Parce qu\'il n\'y a plus de pass pour les jeunes.',
      ],
      answer: 1,
      explanation: 'L\'article cite : "plus écologique que l\'avion" et "permet aussi de découvrir des paysages que l\'on ne voit pas depuis les airs".',
    },
    {
      id: 'tef-r1-15',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Section C — Lisez l\'extrait de magazine :\n\n« Dormir moins de six heures par nuit multiplierait par deux le risque de maladies cardiovasculaires, selon une étude parue dans la revue Nature. Les chercheurs insistent toutefois sur le fait que la qualité du sommeil importe autant que sa durée. Ils recommandent de maintenir des horaires réguliers, d\'éviter les écrans une heure avant le coucher et de limiter la caféine en fin de journée. »',
      promptFr: 'Que recommandent les chercheurs ?',
      options: [
        'Dormir moins de six heures par nuit.',
        'Utiliser les écrans avant de dormir.',
        'Maintenir des horaires réguliers et limiter la caféine en fin de journée.',
        'Boire du café pour mieux dormir.',
      ],
      answer: 2,
      explanation: 'Les chercheurs recommandent "des horaires réguliers", "d\'éviter les écrans une heure avant le coucher" et de "limiter la caféine en fin de journée".',
    },
  ],
};

const tefReadingTest2: PracticeTest = {
  id: 'tef-reading-test-2',
  title: 'Reading Practice Test 2',
  titleFr: 'Compréhension écrite — Test 2',
  description:
    '15 questions covering Section A (signs & announcements), Section B (short texts) and Section C (longer texts).',
  questions: [
    // -- Section A --
    {
      id: 'tef-r2-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Section A — Lisez l\'affiche au restaurant :\n\n« MENU DU JOUR 14,50 €\nEntrée + Plat + Dessert\nService en continu de 12h à 22h. »',
      promptFr: 'Que propose ce restaurant ?',
      options: [
        'Un menu à 4,50 € servi uniquement le soir.',
        'Un menu du jour à 14,50 € servi en continu de 12h à 22h.',
        'Un menu sans entrée ni dessert.',
        'Un service uniquement de 12h à 14h.',
      ],
      answer: 1,
      explanation: 'Le menu du jour coûte 14,50 € (entrée + plat + dessert) et le service est continu de 12h à 22h.',
    },
    {
      id: 'tef-r2-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Section A — Lisez le panneau :\n\n« PISCINE MUNICIPALE\nLundi, mercredi, vendredi : 12h - 22h\nMardi, jeudi : 7h - 22h\nWeek-end : 9h - 18h »',
      promptFr: 'Quand la piscine est-elle ouverte tôt le matin ?',
      options: [
        'Le lundi à partir de 7h.',
        'Le mardi et le jeudi à partir de 7h.',
        'Le week-end à partir de 7h.',
        'Tous les jours à partir de 7h.',
      ],
      answer: 1,
      explanation: 'Les jours d\'ouverture à 7h sont le mardi et le jeudi, comme indiqué sur le panneau.',
    },
    {
      id: 'tef-r2-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Section A — Lisez l\'étiquette :\n\n« T-shirt 100% coton bio. Lavable en machine à 30°. Ne pas utiliser de javel. Repasser à basse température. Fabriqué au Portugal. »',
      promptFr: 'Comment faut-il laver ce t-shirt ?',
      options: [
        'À 60° avec de la javel.',
        'À 30° en machine, sans javel.',
        'Uniquement à la main.',
        'Au sèche-linge à haute température.',
      ],
      answer: 1,
      explanation: 'L\'étiquette indique : "Lavable en machine à 30°" et "Ne pas utiliser de javel".',
    },
    {
      id: 'tef-r2-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Section A — Lisez l\'affiche à l\'aéroport :\n\n« DÉPART — Porte B12. Embarquement : 13h45. Fermeture de la porte : 14h05. Merci de vous présenter 30 minutes avant l\'embarquement. »',
      promptFr: 'À quelle heure la porte d\'embarquement ferme-t-elle ?',
      options: [
        'À 13h45.',
        'À 14h05.',
        'À 13h15.',
        'À 14h35.',
      ],
      answer: 1,
      explanation: 'L\'affiche indique : "Fermeture de la porte : 14h05".',
    },
    {
      id: 'tef-r2-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Section A — Lisez le panneau de stationnement :\n\n« STATIONNEMENT INTERDIT le 1er mardi de chaque mois, de 8h à 12h, pour le nettoyage de la voie. »',
      promptFr: 'Quand le stationnement est-il interdit ?',
      options: [
        'Tous les mardis toute la journée.',
        'Le premier mardi du mois, de 8h à 12h.',
        'Le premier lundi du mois.',
        'Tous les jours de 8h à 12h.',
      ],
      answer: 1,
      explanation: 'Le panneau précise : "le 1er mardi de chaque mois, de 8h à 12h".',
    },
    // -- Section B --
    {
      id: 'tef-r2-6',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Section B — Lisez le SMS :\n\n« Salut Léa, je suis en retard, le bus a 15 min de retard. Commence à manger sans moi, j\'arrive vers 19h45. Bises, Théo. »',
      promptFr: 'Pourquoi Théo est-il en retard ?',
      options: [
        'Il travaille tard.',
        'Le bus a 15 minutes de retard.',
        'Il a un rendez-vous.',
        'Il a oublié l\'heure.',
      ],
      answer: 1,
      explanation: 'Théo écrit : "le bus a 15 min de retard".',
    },
    {
      id: 'tef-r2-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section B — Lisez le courriel :\n\n« Bonjour, suite à votre candidature pour le poste de chef de projet, nous vous convions à un entretien le mercredi 12 juin à 10h dans nos locaux. Merci de confirmer votre présence par retour de mail. Cordialement, Service RH — Groupe Lambert. »',
      promptFr: 'Que doit faire le destinataire ?',
      options: [
        'Venir à l\'entretien sans confirmer.',
        'Confirmer sa présence par retour de mail.',
        'Téléphoner au service RH.',
        'Envoyer un nouveau CV.',
      ],
      answer: 1,
      explanation: 'L\'e-mail précise : "Merci de confirmer votre présence par retour de mail."',
    },
    {
      id: 'tef-r2-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section B — Lisez l\'avis :\n\n« Cher client, votre colis sera livré le 15 mars entre 14h et 17h. Veuillez être présent à votre domicile. En cas d\'absence, un avis de passage sera déposé et le colis sera disponible en point relais sous 48h. »',
      promptFr: 'Que se passe-t-il si le client est absent ?',
      options: [
        'Le colis sera renvoyé à l\'expéditeur.',
        'Un avis sera déposé et le colis sera disponible en point relais sous 48h.',
        'Le colis sera livré le lendemain matin.',
        'Le colis sera perdu.',
      ],
      answer: 1,
      explanation: 'En cas d\'absence : "un avis de passage sera déposé et le colis sera disponible en point relais sous 48h".',
    },
    {
      id: 'tef-r2-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section B — Lisez le message :\n\n« Coucou ! On organise une sortie vélo dimanche. Rendez-vous à 9h devant la mairie, prévoyez pique-nique et eau. Si pluie, on reporte au dimanche suivant. Dis-moi si tu viens ! »',
      promptFr: 'Quand la sortie est-elle reportée ?',
      options: [
        'En cas de pluie, au dimanche suivant.',
        'Toujours au dimanche suivant.',
        'En cas de vent.',
        'À 9h le samedi.',
      ],
      answer: 0,
      explanation: 'Le message précise : "Si pluie, on reporte au dimanche suivant."',
    },
    {
      id: 'tef-r2-10',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section B — Lisez l\'annonce :\n\n« DONNE cours de guitare acoustique pour débutants. 1ère leçon offerte ! 25 €/h en groupe, 35 €/h en particulier. Quartier Bellecour. Contact : Antoine, 06 99 88 77 66. »',
      promptFr: 'Que propose Antoine ?',
      options: [
        'Des cours de piano à domicile.',
        'Des cours de guitare avec une première leçon offerte.',
        'La vente d\'une guitare d\'occasion.',
        'Des cours collectifs gratuits.',
      ],
      answer: 1,
      explanation: 'Antoine donne des cours de guitare acoustique pour débutants, avec "1ère leçon offerte".',
    },
    // -- Section C --
    {
      id: 'tef-r2-11',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section C — Lisez l\'article :\n\n« La mairie de Lyon a annoncé hier la création de 30 km de pistes cyclables supplémentaires d\'ici fin 2026. L\'objectif affiché : réduire la pollution et encourager les déplacements doux. Toutefois, plusieurs associations d\'automobilistes dénoncent une réduction importante des places de stationnement en centre-ville. »',
      promptFr: 'Quel est l\'objectif de la mairie ?',
      options: [
        'Augmenter le nombre de places de parking.',
        'Réduire la pollution et encourager les déplacements doux.',
        'Interdire les vélos en centre-ville.',
        'Construire un nouveau métro.',
      ],
      answer: 1,
      explanation: 'L\'objectif affiché par la mairie est "réduire la pollution et encourager les déplacements doux".',
    },
    {
      id: 'tef-r2-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Section C — Lisez l\'extrait :\n\n« Bien que les énergies renouvelables progressent en France, elles ne suffisent pas encore à couvrir la croissance de la demande électrique, notamment liée à la multiplication des data centers et au développement des véhicules électriques. Les experts estiment qu\'une rénovation massive du parc de logements serait tout aussi déterminante que la transition énergétique elle-même. »',
      promptFr: 'Selon les experts, qu\'est-ce qui serait déterminant ?',
      options: [
        'Uniquement le développement des véhicules électriques.',
        'La rénovation massive du parc de logements.',
        'La construction de nouveaux data centers.',
        'La baisse de la demande électrique.',
      ],
      answer: 1,
      explanation: 'Les experts estiment "qu\'une rénovation massive du parc de logements serait tout aussi déterminante".',
    },
    {
      id: 'tef-r2-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Section C — Lisez le rapport :\n\n« Le tourisme en montagne se diversifie. Face à la baisse de l\'enneigement, les stations investissent dans des activités estivales : VTT, randonnée, parcs d\'aventure. Cette stratégie permet d\'étaler la fréquentation sur l\'année et de limiter la dépendance à la saison hivernale, de plus en plus aléatoire. »',
      promptFr: 'Pourquoi les stations investissent-elles dans les activités estivales ?',
      options: [
        'Parce que l\'enneigement augmente chaque hiver.',
        'Face à la baisse de l\'enneigement, pour étaler la fréquentation sur l\'année.',
        'Pour attirer uniquement les skieurs en hiver.',
        'Parce que les touristes ne viennent plus en été.',
      ],
      answer: 1,
      explanation: 'Face à la baisse de l\'enneigement, les stations diversifient leurs activités pour "étaler la fréquentation sur l\'année".',
    },
    {
      id: 'tef-r2-14',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Section C — Lisez l\'article :\n\n« L\'intelligence artificielle transforme progressivement l\'enseignement. Si certains craignent une déshumanisation de la relation pédagogique, d\'autres y voient une opportunité de personnaliser les parcours d\'apprentissage. Plusieurs universités ont ainsi adopté des assistants virtuels capables de répondre aux questions des étudiants à toute heure, sans remplacer pour autant le dialogue avec les enseignants. »',
      promptFr: 'Quel est le sujet principal de l\'article ?',
      options: [
        'L\'interdiction de l\'IA dans les universités.',
        'La transformation de l\'enseignement par l\'IA et le débat qu\'elle suscite.',
        'La disparition des enseignants.',
        'Le coût de l\'IA pour les étudiants.',
      ],
      answer: 1,
      explanation: 'L\'article traite de la transformation de l\'enseignement par l\'IA et du débat entre déshumanisation et personnalisation.',
    },
    {
      id: 'tef-r2-15',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Section C — Lisez l\'extrait :\n\n« La fermentation, technique millénaire, connaît un regain d\'intérêt auprès des chefs étoilés comme des amateurs. Au-delà de la mode, les nutritionnistes soulignent ses bénéfices : meilleure digestibilité, richesse en probiotiques, conservation naturelle sans additifs. Des ateliers se multiplient dans toute la France pour apprendre à fermenter légumes, lait et même céréales. »',
      promptFr: 'Pourquoi la fermentation intéresse-t-elle à nouveau ?',
      options: [
        'Uniquement parce que c\'est une mode passagère.',
        'Pour ses bénéfices nutritionnels et sa conservation naturelle.',
        'Parce qu\'elle est interdite en restauration.',
        'Parce qu\'elle remplace tous les additifs chimiques.',
      ],
      answer: 1,
      explanation: 'Les nutritionnistes soulignent "meilleure digestibilité, richesse en probiotiques, conservation naturelle sans additifs".',
    },
  ],
};

const tefReadingTest3: PracticeTest = {
  id: 'tef-reading-test-3',
  title: 'Reading Practice Test 3',
  titleFr: 'Compréhension écrite — Test 3',
  description:
    '15 questions covering Section A (signs & announcements), Section B (short texts) and Section C (longer texts).',
  questions: [
    // -- Section A --
    {
      id: 'tef-r3-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Section A — Lisez l\'affiche au cinéma :\n\n« SÉANCE 20h30 — Salle 4\nFilm en VO sous-titrée français. Places : 9,50 € — Tarif réduit : 7 €. »',
      promptFr: 'Combien coûte une place à tarif réduit ?',
      options: ['9,50 €', '7 €', '4 €', '20,30 €'],
      answer: 1,
      explanation: 'L\'affiche indique : "Tarif réduit : 7 €".',
    },
    {
      id: 'tef-r3-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Section A — Lisez le panneau à la pharmacie :\n\n« PHARMACIE CENTRALE\nOuverte lundi à vendredi : 8h30 - 19h30\nSamedi : 9h - 18h\nGarde de nuit : appelez le 15. »',
      promptFr: 'Que faut-il faire pour une urgence la nuit ?',
      options: [
        'Venir à la pharmacie.',
        'Appeler le 15.',
        'Attendre le matin.',
        'Appeler le 18.',
      ],
      answer: 1,
      explanation: 'Le panneau précise : "Garde de nuit : appelez le 15."',
    },
    {
      id: 'tef-r3-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Section A — Lisez l\'affiche du marché :\n\n« MARCHÉ DE PLEIN VENT\nTous les dimanches matin, place de la République.\nFruits, légumes, fromages, producteurs locaux. Parking gratuit 2h sur présentation d\'un ticket de marché. »',
      promptFr: 'Que propose le parking du marché ?',
      options: [
        'Un parking payant toute la journée.',
        'Un parking gratuit 2h sur présentation d\'un ticket de marché.',
        'Un parking réservé aux producteurs.',
        'Aucun parking.',
      ],
      answer: 1,
      explanation: 'L\'affiche précise : "Parking gratuit 2h sur présentation d\'un ticket de marché."',
    },
    {
      id: 'tef-r3-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Section A — Lisez l\'étiquette alimentaire :\n\n« YAOURT NATURE — Contenance : 4 × 125 g. À conserver entre +2°C et +6°C. À consommer jusqu\'à la date indiquée sur l\'opercule. »',
      promptFr: 'Comment faut-il conserver ce yaourt ?',
      options: [
        'À température ambiante.',
        'Au congélateur.',
        'Entre +2°C et +6°C.',
        'Au-delà de +6°C.',
      ],
      answer: 2,
      explanation: 'L\'étiquette indique : "À conserver entre +2°C et +6°C".',
    },
    {
      id: 'tef-r3-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Section A — Lisez l\'affiche à l\'hôtel :\n\n« PETIT-DÉJEUNER : servi de 6h30 à 10h en salle, ou par room-service de 7h à 11h (supplément 4 €). WIFI gratuit dans tout l\'établissement. »',
      promptFr: 'Que peut-on dire du petit-déjeuner ?',
      options: [
        'Il est gratuit en room-service.',
        'Il est servi en salle de 6h30 à 10h, et le room-service a un supplément de 4 €.',
        'Il n\'est servi qu\'en salle.',
        'Il commence à 7h en salle.',
      ],
      answer: 1,
      explanation: 'Le petit-déjeuner est servi en salle de 6h30 à 10h ; le room-service coûte un supplément de 4 €.',
    },
    // -- Section B --
    {
      id: 'tef-r3-6',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Section B — Lisez le mot :\n\n« Paul, j\'ai pris ta voiture pour aller chez le garagiste. Je te la ramène ce soir avant 19h. Plein fait ! — Alex. »',
      promptFr: 'Que dit Alex ?',
      options: [
        'Il a vendu la voiture de Paul.',
        'Il a pris la voiture et fera le plein avant de la rendre.',
        'Il a oublié de faire le plein.',
        'Il rendra la voiture demain.',
      ],
      answer: 1,
      explanation: 'Alex a pris la voiture pour le garagiste, "Plein fait !" signifie qu\'il a refait le plein avant de la rendre ce soir.',
    },
    {
      id: 'tef-r3-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section B — Lisez l\'avis d\'un client :\n\n« J\'ai commandé un ordinateur portable le 2 avril. Le colis est arrivé en retard et abîmé. Le service client m\'a proposé un remboursement intégral ou un échange. J\'ai choisi l\'échange : appareil reçu 5 jours plus tard, parfait. »',
      promptFr: 'Quelle solution le client a-t-il choisie ?',
      options: [
        'Le remboursement intégral.',
        'L\'échange de l\'appareil.',
        'Garder l\'appareil abîmé.',
        'Acheter un autre modèle.',
      ],
      answer: 1,
      explanation: 'Le client écrit : "J\'ai choisi l\'échange : appareil reçu 5 jours plus tard, parfait."',
    },
    {
      id: 'tef-r3-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section B — Lisez l\'e-mail professionnel :\n\n« Bonjour, comme convenu, je vous transmets le contrat signé en pièce jointe. Pourriez-vous me renvoyer un exemplaire contresigné avant vendredi ? Je reste à votre disposition pour toute modification. Bien à vous, Sarah Mercier. »',
      promptFr: 'Que demande Sarah ?',
      options: [
        'De renvoyer le contrat contresigné avant vendredi.',
        'De modifier le contrat après vendredi.',
        'De venir signer en personne.',
        'D\'envoyer un nouveau contrat.',
      ],
      answer: 0,
      explanation: 'Sarah demande : "Pourriez-vous me renvoyer un exemplaire contresigné avant vendredi ?"',
    },
    {
      id: 'tef-r3-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section B — Lisez l\'annonce :\n\n« VENDS vélo de route CARBONE, taille M, 12 vitesses Shimano, peu servi, 650 € (facture à l\'appui). À retirer sur Bordeaux. Pas d\'envoi. Premier venu, premier servi. »',
      promptFr: 'Que faut-il savoir sur cette vente ?',
      options: [
        'Le vélo sera expédié partout en France.',
        'Le vélo est à retirer sur Bordeaux, pas d\'envoi.',
        'Le prix est négociable à la hausse.',
        'Plusieurs vélos sont disponibles.',
      ],
      answer: 1,
      explanation: 'L\'annonce précise : "À retirer sur Bordeaux. Pas d\'envoi."',
    },
    {
      id: 'tef-r3-10',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section B — Lisez le message vocal retranscrit :\n\n« Allô, ici le cabinet du Docteur Rousseau. Votre rendez-vous de jeudi 16h est confirmé. Merci d\'arriver 10 minutes avant et d\'apporter votre carte vitale. À jeudi ! »',
      promptFr: 'Que doit faire le patient ?',
      options: [
        'Arriver exactement à 16h.',
        'Arriver 10 minutes avant 16h et apporter sa carte vitale.',
        'Annuler le rendez-vous.',
        'Venir sans carte vitale.',
      ],
      answer: 1,
      explanation: 'Le message demande d\'arriver "10 minutes avant" et d\'apporter la "carte vitale".',
    },
    // -- Section C --
    {
      id: 'tef-r3-11',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Section C — Lisez l\'article :\n\n« Selon une enquête récente, près de 60% des Français déclarent consulter leur smartphone dans les cinq minutes qui suivent leur réveil. Les spécialistes du sommeil s\'inquiètent de cette habitude, qui perturberait la production de cortisol et compliquerait la mise en route de la journée. Ils recommandent de différer la consultation des notifications d\'au moins trente minutes. »',
      promptFr: 'Que recommandent les spécialistes ?',
      options: [
        'De consulter le smartphone immédiatement après le réveil.',
        'De différer la consultation des notifications d\'au moins 30 minutes.',
        'D\'acheter un nouvel smartphone.',
        'De ne plus dormir.',
      ],
      answer: 1,
      explanation: 'Les spécialistes recommandent "de différer la consultation des notifications d\'au moins trente minutes".',
    },
    {
      id: 'tef-r3-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Section C — Lisez l\'extrait :\n\n« La pop-up store, boutique éphémère, séduit de plus en plus de marques. Concept né dans les grandes métropoles, elle permet de tester un produit, un quartier ou une nouvelle clientèle sans s\'engager sur un bail commercial de longue durée. Pour les villes, c\'est aussi un moyen de redynamiser des rues commerciales en perte de vitesse. »',
      promptFr: 'Quel avantage présente la pop-up store pour les marques ?',
      options: [
        'Un bail commercial de très longue durée.',
        'Tester un produit, un quartier ou une clientèle sans engagement long.',
        'Une baisse définitive des impôts.',
        'L\'interdiction de vendre en ligne.',
      ],
      answer: 1,
      explanation: 'La pop-up store "permet de tester un produit, un quartier ou une nouvelle clientèle sans s\'engager sur un bail commercial de longue durée".',
    },
    {
      id: 'tef-r3-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Section C — Lisez le rapport :\n\n« Malgré une hausse continue du nombre d\'étudiants inscrits à l\'université, le taux d\'abandon en première année reste élevé, notamment dans les filières scientifiques. Les causes évoquées sont multiples : manque d\'accompagnement, décalage entre les attentes du lycée et celles de l\'université, contraintes financières. Plusieurs établissements expérimentent des groupes de tutorat réduits pour y remédier. »',
      promptFr: 'Quelle mesure est expérimentée pour réduire les abandons ?',
      options: [
        'L\'augmentation des frais d\'inscription.',
        'Des groupes de tutorat réduits.',
        'La suppression des filières scientifiques.',
        'L\'interdiction de travailler en parallèle.',
      ],
      answer: 1,
      explanation: 'Le rapport précise : "Plusieurs établissements expérimentent des groupes de tutorat réduits pour y remédier."',
    },
    {
      id: 'tef-r3-14',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Section C — Lisez l\'article :\n\n« Les marchés de Noël français attirent chaque année des millions de visiteurs, mais leur modèle économique est de plus en plus contesté. Trop de produits manufacturés importés, dénoncent les artisans locaux, qui réclament des chartes plus strictes garantissant un savoir-faire régional. Certaines villes, comme Strasbourg, ont déjà durci leurs critères de sélection des exposants. »',
      promptFr: 'Que réclament les artisans locaux ?',
      options: [
        'Plus de produits importés.',
        'Des chartes plus strictes garantissant un savoir-faire régional.',
        'La fermeture des marchés de Noël.',
        'Une baisse des prix.',
      ],
      answer: 1,
      explanation: 'Les artisans locaux "réclament des chartes plus strictes garantissant un savoir-faire régional".',
    },
    {
      id: 'tef-r3-15',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Section C — Lisez l\'extrait :\n\n« Le covoiturage courte distance explose en France grâce à une nouvelle aide de l\'État : 100 millions d\'euros pour subventionner les trajets de moins de 80 km. Les critiques fusent toutefois : certains élus ruraux estiment que ces fonds profiteraient surtout aux zones déjà bien desservies, laissant de côté les territoires ruraux les plus isolés. »',
      promptFr: 'Que critique-t-on dans cette aide de l\'État ?',
      options: [
        'Son montant total trop élevé.',
        'Le fait qu\'elle profiterait surtout aux zones déjà bien desservies, oubliant les territoires ruraux isolés.',
        'Le fait qu\'elle ne concerne que les trajets de plus de 80 km.',
        'Le fait qu\'elle soit gérée par les régions.',
      ],
      answer: 1,
      explanation: 'Les élus ruraux estiment que ces fonds "profitreraient surtout aux zones déjà bien desservies, laissant de côté les territoires ruraux les plus isolés".',
    },
  ],
};

// ---------------------------------------------------------------------------
// LISTENING COMPREHENSION — 3 tests × 15 questions (with audioText for TTS)
// ---------------------------------------------------------------------------

const tefListeningTest1: PracticeTest = {
  id: 'tef-listening-test-1',
  title: 'Listening Practice Test 1',
  titleFr: 'Compréhension orale — Test 1',
  description: '15 questions — annonces publiques, conversations, messages téléphoniques, extraits radio.',
  questions: [
    {
      id: 'tef-l1-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Écoutez l\'annonce et répondez : où a lieu la rencontre ?',
      promptFr: 'Où a lieu la rencontre ?',
      audioText: 'Attention, attention. Les passagers du vol AF 1342 à destination de Madrid sont invités à se présenter à la porte d\'embarquement B7. Embarquement immédiat.',
      options: ['À la porte A7', 'À la porte B7', 'À la porte C7', 'Au guichet 7'],
      answer: 1,
      explanation: 'L\'annonce mentionne "porte d\'embarquement B7".',
    },
    {
      id: 'tef-l1-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Écoutez et répondez : quelle est la météo prévue ?',
      promptFr: 'Quelle est la météo prévue ?',
      audioText: 'Bonjour à tous. Aujourd\'hui, sur la région parisienne, le soleil sera au rendez-vous toute la journée, avec des températures autour de 22 degrés. Aucune pluie n\'est attendue avant demain soir.',
      options: ['Pluvieux toute la journée', 'Ensoleillé, environ 22°C', 'Neige', 'Tempêtes'],
      answer: 1,
      explanation: 'L\'annonce indique : "soleil au rendez-vous" et "22 degrés".',
    },
    {
      id: 'tef-l1-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez le message et répondez : quand le médecin reçoit-il ?',
      promptFr: 'Quand le médecin reçoit-il ?',
      audioText: 'Vous êtes bien au cabinet du Docteur Lefèvre. Le cabinet est ouvert du lundi au vendredi, de 9 heures à 18 heures, sans interruption. Pour un rendez-vous, veuillez laisser votre nom, votre numéro de téléphone et le motif de votre appel après le bip sonore.',
      options: [
        'Le mardi et le jeudi seulement',
        'Du lundi au vendredi, de 9h à 18h',
        'Le week-end uniquement',
        'Uniquement le matin',
      ],
      answer: 1,
      explanation: 'Le message indique : "du lundi au vendredi, de 9 heures à 18 heures, sans interruption".',
    },
    {
      id: 'tef-l1-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez et répondez : que propose la vendeuse ?',
      promptFr: 'Que propose la vendeuse ?',
      audioText: 'Bonjour madame, je peux vous aider ? Cette robe est disponible en noir, bleu ou rouge, du 36 au 44. Si vous souhaitez l\'essayer, les cabines sont juste à droite. Nous avons aussi une promotion : le deuxième article à moitié prix.',
      options: [
        'Une robe uniquement en une seule taille',
        'Une robe en trois couleurs, et le 2e article à moitié prix',
        'Une promotion sur les chaussures',
        'Uniquement des soldes en fin de saison',
      ],
      answer: 1,
      explanation: 'La vendeuse propose "noir, bleu ou rouge, du 36 au 44" et "le deuxième article à moitié prix".',
    },
    {
      id: 'tef-l1-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez l\'annonce en gare : que se passe-t-il ?',
      promptFr: 'Que se passe-t-il ?',
      audioText: 'Mesdames et messieurs, en raison d\'un incident technique sur la ligne, le train de 13h12 à destination de Marseille Saint-Charles est supprimé. Le prochain train partira à 14h15 en voie 5. Nous vous présentons nos excuses pour ce contretemps.',
      options: [
        'Le train de 13h12 pour Marseille est supprimé, le prochain à 14h15 voie 5.',
        'Le train de 14h15 est supprimé.',
        'La ligne fonctionne normalement.',
        'Le train partira en avance.',
      ],
      answer: 0,
      explanation: 'L\'annonce précise : "train de 13h12 à destination de Marseille Saint-Charles est supprimé" et "prochain train partira à 14h15 en voie 5".',
    },
    {
      id: 'tef-l1-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez la conversation : que veut la cliente ?',
      promptFr: 'Que veut la cliente ?',
      audioText: '— Bonjour, je voudrais changer ces euros en dollars américains, s\'il vous plaît.\n— Combien souhaitez-vous changer ?\n— Cinq cents euros. Quel est le taux du jour ?\n— Un euro équivaut à un dollar huit. Pour 500 euros, je vous donne 540 dollars, après commission.',
      options: [
        'Changer 500 dollars en euros',
        'Changer 500 euros en dollars américains',
        'Ouvrir un compte bancaire',
        'Retirer 500 euros',
      ],
      answer: 1,
      explanation: 'La cliente dit : "je voudrais changer ces euros en dollars américains" et "Cinq cents euros".',
    },
    {
      id: 'tef-l1-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez le message et répondez : pourquoi Lucas ne peut-il pas venir ?',
      promptFr: 'Pourquoi Lucas ne peut-il pas venir ?',
      audioText: 'Salut c\'est Lucas. Écoute, je suis vraiment désolé mais je ne pourrai pas venir au cinéma ce soir. Ma fille est malade, je dois rester avec elle. On peut se faire ça la semaine prochaine ? Rappelez-moi pour fixer le jour. Bisous !',
      options: [
        'Il est malade.',
        'Sa fille est malade et il doit rester avec elle.',
        'Il a trop de travail.',
        'Il n\'aime pas le cinéma.',
      ],
      answer: 1,
      explanation: 'Lucas dit : "Ma fille est malade, je dois rester avec elle."',
    },
    {
      id: 'tef-l1-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que demande l\'employé ?',
      promptFr: 'Que demande l\'employé ?',
      audioText: 'Patron, je voudrais vous demander deux jours de congé supplémentaires la semaine prochaine, jeudi et vendredi. J\'aimerais accompagner mes parents à un rendez-vous médical important à Lille. Je rattraperai mes heures la semaine d\'après, c\'est promis.',
      options: [
        'Deux jours de congé jeudi et vendredi la semaine prochaine',
        'Une augmentation de salaire',
        'Un changement de poste',
        'Trois semaines de vacances',
      ],
      answer: 0,
      explanation: 'L\'employé demande "deux jours de congé supplémentaires la semaine prochaine, jeudi et vendredi".',
    },
    {
      id: 'tef-l1-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez l\'extrait radio : de quoi parle-t-on ?',
      promptFr: 'De quoi parle-t-on ?',
      audioText: 'Ce soir dans notre magazine culturel : focus sur le festival de cinéma d\'animation qui se tient jusqu\'à dimanche à Annecy. Au programme, plus de deux cents projections, des rencontres avec des réalisateurs du monde entier, et une compétition officielle très relevée cette année.',
      options: [
        'Un festival de musique',
        'Un festival de cinéma d\'animation à Annecy',
        'Une foire commerciale',
        'Une compétition de sport',
      ],
      answer: 1,
      explanation: 'L\'extrait parle "du festival de cinéma d\'animation qui se tient jusqu\'à dimanche à Annecy".',
    },
    {
      id: 'tef-l1-10',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : combien coûte le menu enfant ?',
      promptFr: 'Combien coûte le menu enfant ?',
      audioText: 'Bonjour et bienvenue. Voici notre carte. Le menu du jour est à dix-huit euros, le menu enfant à huit euros cinquante, et la formule midi à douze euros. Souhaitez-vous commencer par une boisson ?',
      options: ['18 €', '12 €', '8,50 €', '4,50 €'],
      answer: 2,
      explanation: 'Le serveur dit : "le menu enfant à huit euros cinquante", soit 8,50 €.',
    },
    {
      id: 'tef-l1-11',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que dit l\'annonce ?',
      promptFr: 'Que dit l\'annonce ?',
      audioText: 'Mesdames et messieurs, en raison d\'un colis abandonné en salle 3, l\'accès à cette salle est temporairement interdit. Nous vous demandons de bien vouloir vous diriger calmement vers la sortie principale. La reprise normale des activités est prévue dans une vingtaine de minutes.',
      options: [
        'La salle 3 est fermée pour un colis abandonné, évacuation calme.',
        'La sortie principale est interdite.',
        'Le bâtiment ferme définitivement.',
        'Aucun changement.',
      ],
      answer: 0,
      explanation: 'L\'annonce parle d\'un "colis abandonné en salle 3" et demande de se diriger "calmement vers la sortie principale".',
    },
    {
      id: 'tef-l1-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : quel est le sujet principal du reportage ?',
      promptFr: 'Quel est le sujet principal du reportage ?',
      audioText: 'Dans notre reportage du jour, nous nous intéressons au retour des foires aux vins dans les supermarchés français. Longtemps délaissées au profit des ventes en ligne, elles séduisent à nouveau une clientèle en quête de conseils. Les cavistes présents sur place jouent un rôle clé : ils aident les clients à composer des caveaux adaptés à leur budget et à leurs goûts.',
      options: [
        'La baisse des ventes de vin en France',
        'Le retour des foires aux vins en supermarché, avec le rôle clé des cavistes',
        'L\'interdiction de l\'alcool en supermarché',
        'La concurrence des ventes en ligne',
      ],
      answer: 1,
      explanation: 'Le reportage porte sur "le retour des foires aux vins dans les supermarchés français" et "le rôle clé" des cavistes.',
    },
    {
      id: 'tef-l1-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : que recommande la nutritionniste ?',
      promptFr: 'Que recommande la nutritionniste ?',
      audioText: 'Beaucoup de mes patients sautent le petit-déjeuner en pensant perdre du poids. C\'est une erreur. Un petit-déjeuner équilibré, riche en fibres et en protéines, permet de tenir jusqu\'au déjeuner sans grignoter. Je conseille par exemple un yaourt nature, un fruit frais et une poignée d\'oléagineux, plutôt que des céréales trop sucrées.',
      options: [
        'Sauter le petit-déjeuner pour maigrir',
        'Manger des céréales très sucrées le matin',
        'Prendre un petit-déjeuner équilibré avec yaourt, fruit et oléagineux',
        'Ne manger que le soir',
      ],
      answer: 2,
      explanation: 'La nutritionniste conseille "un yaourt nature, un fruit frais et une poignée d\'oléagineux, plutôt que des céréales trop sucrées".',
    },
    {
      id: 'tef-l1-14',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : qu\'apprend-on sur le projet ?',
      promptFr: 'Qu\'apprend-on sur le projet ?',
      audioText: 'Le nouveau tramway, dont l\'inauguration est prévue pour septembre, desservira huit quartiers périphériques jusqu\'ici mal connectés au centre-ville. La fréquence annoncée est d\'une rame toutes les six minutes en heure de pointe. Les associations d\'usagers saluent l\'initiative mais regrettent l\'absence de parkings-relais aux terminus.',
      options: [
        'Le tramway sera inauguré en septembre et desservira 8 quartiers périphériques.',
        'Le projet est définitivement abandonné.',
        'Il n\'y aura qu\'une rame toutes les 30 minutes.',
        'Des parkings-relais seront construits aux terminus.',
      ],
      answer: 0,
      explanation: 'Le tramway sera inauguré en septembre et "desservira huit quartiers périphériques".',
    },
    {
      id: 'tef-l1-15',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : quel bilan fait l\'intervenant ?',
      promptFr: 'Quel bilan fait l\'intervenant ?',
      audioText: 'Cette année, notre festival a accueilli près de quarante mille spectateurs, soit une hausse de quinze pour cent par rapport à l\'an dernier. Le bilan financier est positif, même si les coûts de sécurité ont explosé. L\'édition prochaine devrait s\'ouvrir à un pays invité d\'honneur, probablement le Portugal.',
      options: [
        'Le festival a perdu des spectateurs.',
        'Le festival a accueilli environ 40 000 spectateurs, en hausse de 15%.',
        'Le bilan financier est négatif.',
        'Le pays invité 2024 sera l\'Espagne.',
      ],
      answer: 1,
      explanation: 'L\'intervenant indique "près de quarante mille spectateurs, soit une hausse de quinze pour cent".',
    },
  ],
};

const tefListeningTest2: PracticeTest = {
  id: 'tef-listening-test-2',
  title: 'Listening Practice Test 2',
  titleFr: 'Compréhension orale — Test 2',
  description: '15 questions — annonces publiques, conversations, messages téléphoniques, extraits radio.',
  questions: [
    {
      id: 'tef-l2-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Écoutez et répondez : à quelle heure ferme la boulangerie ?',
      promptFr: 'À quelle heure ferme la boulangerie ?',
      audioText: 'Bonjour ! Notre boulangerie est ouverte du mardi au dimanche, de six heures trente à dix-neuf heures, sans interruption. Nous sommes fermés le lundi toute la journée. Passez nous voir !',
      options: ['À 19h', 'À 18h', 'À 20h', 'À 6h30'],
      answer: 0,
      explanation: 'L\'annonce précise : "de six heures trente à dix-neuf heures", soit une fermeture à 19h.',
    },
    {
      id: 'tef-l2-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Écoutez l\'annonce : quel est le numéro de la porte ?',
      promptFr: 'Quel est le numéro de la porte ?',
      audioText: 'Le train à destination de Bordeaux Saint-Jean partira en voie 9. Les voyageurs avec réservation sont invités à se présenter en tête de rame. Attention, départ dans cinq minutes.',
      options: ['Voie 5', 'Voie 9', 'Voie 19', 'Voie 2'],
      answer: 1,
      explanation: 'L\'annonce indique : "voie 9".',
    },
    {
      id: 'tef-l2-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez le message : pourquoi la personne appelle-t-elle ?',
      promptFr: 'Pourquoi la personne appelle-t-elle ?',
      audioText: 'Bonjour, ici la bibliothèque municipale. Le livre que vous aviez réservé, "L\'Étranger" d\'Albert Camus, est disponible au comptoir depuis ce matin. Nous le conservons huit jours. Merci de venir le récupérer muni de votre carte d\'adhérent. Bonne journée !',
      options: [
        'Pour signaler un retard',
        'Pour annoncer qu\'un livre réservé est disponible',
        'Pour annuler une réservation',
        'Pour demander un remboursement',
      ],
      answer: 1,
      explanation: 'Le message annonce : "Le livre que vous aviez réservé... est disponible au comptoir depuis ce matin."',
    },
    {
      id: 'tef-l2-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez la conversation : que commande le client ?',
      promptFr: 'Que commande le client ?',
      audioText: '— Bonjour, je vais prendre un café allongé et un croissant beurre, s\'il vous plaît.\n— Sur place ou à emporter ?\n— Sur place.\n— Très bien, ça fait 4 euros 20. Vous réglez par carte ?\n— Oui, par carte, merci.',
      options: [
        'Un thé et un pain au chocolat',
        'Un café allongé et un croissant beurre, sur place',
        'Deux cafés à emporter',
        'Un café et une salade',
      ],
      answer: 1,
      explanation: 'Le client commande "un café allongé et un croissant beurre" et précise "Sur place".',
    },
    {
      id: 'tef-l2-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez l\'annonce : que doivent faire les passagers ?',
      promptFr: 'Que doivent faire les passagers ?',
      audioText: 'Mesdames et messieurs, le vol AF 1740 à destination de Montréal est retardé d\'une heure en raison de conditions météorologiques. Le nouvel embarquement est fixé à 16h30 en porte D4. Nous vous remercions de votre compréhension.',
      options: [
        'Embarquer immédiatement en porte D4',
        'Attendre le nouvel embarquement à 16h30 en porte D4',
        'Annuler leur vol',
        'Changer de compagnie',
      ],
      answer: 1,
      explanation: 'L\'annonce indique : "Le nouvel embarquement est fixé à 16h30 en porte D4."',
    },
    {
      id: 'tef-l2-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que dit le médecin ?',
      promptFr: 'Que dit le médecin ?',
      audioText: 'Alors, vos analyses sont bonnes dans l\'ensemble. Le cholestérol est un peu élevé, je vous conseille de réduire les graisses saturées : moins de charcuterie, moins de fromage. Et surtout, marchez au moins trente minutes par jour. On refait un point dans trois mois.',
      options: [
        'Manger plus de charcuterie',
        'Réduire les graisses saturées et marcher 30 minutes par jour',
        'Prendre un médicament immédiatement',
        'Arrêter toute activité physique',
      ],
      answer: 1,
      explanation: 'Le médecin conseille de "réduire les graisses saturées" et de "marcher au moins trente minutes par jour".',
    },
    {
      id: 'tef-l2-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez le message : qui appelle ?',
      promptFr: 'Qui appelle ?',
      audioText: 'Bonjour, ici Marie Lenoir, votre voisine du troisième. Je voulais vous signaler que j\'ai retrouvé votre chat dans l\'escalier ce matin. Il est chez moi, en sécurité. Pourriez-vous passer le récupérer quand vous rentrez ? Merci et à bientôt !',
      options: [
        'La factrice',
        'Une voisine qui a retrouvé le chat',
        'Le vétérinaire',
        'La gardienne de l\'immeuble',
      ],
      answer: 1,
      explanation: 'Marie Lenoir se présente comme "votre voisine du troisième" et dit avoir retrouvé le chat.',
    },
    {
      id: 'tef-l2-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que propose l\'agent immobilier ?',
      promptFr: 'Que propose l\'agent immobilier ?',
      audioText: 'J\'ai bien étudié votre demande. Pour un budget de 250 000 euros, j\'ai trois biens à vous proposer : un T3 en centre-ville avec balcon, un T2 rénové proche du tram, et une maison avec jardin en périphérie. Lequel vous tente le plus pour une visite ce week-end ?',
      options: [
        'Aucun bien dans ce budget',
        'Trois biens : un T3 avec balcon, un T2 rénové, une maison avec jardin',
        'Uniquement des studios',
        'Une location saisonnière',
      ],
      answer: 1,
      explanation: 'L\'agent propose "un T3 en centre-ville avec balcon, un T2 rénové proche du tram, et une maison avec jardin".',
    },
    {
      id: 'tef-l2-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez l\'extrait radio : de quoi parle-t-on ?',
      promptFr: 'De quoi parle-t-on ?',
      audioText: 'Aujourd\'hui dans notre émission santé, nous parlons du burn-out parental, un phénomène de plus en plus évoqué par les psychologues. Surcharge mentale, épuisement émotionnel, sentiment de ne jamais en faire assez : les signes sont nombreux. Notre invitée, la docteure Roussel, propose des pistes pour en sortir.',
      options: [
        'Du burn-out professionnel',
        'Du burn-out parental',
        'De la dépression chez les enfants',
        'De l\'obésité infantile',
      ],
      answer: 1,
      explanation: 'L\'émission parle "du burn-out parental, un phénomène de plus en plus évoqué par les psychologues".',
    },
    {
      id: 'tef-l2-10',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : quel billet choisit la cliente ?',
      promptFr: 'Quel billet choisit la cliente ?',
      audioText: '— Bonjour, je voudrais un billet aller simple pour Genève.\n— En 1ère ou 2nde classe ?\n— En 2nde. Et si possible avec une place côté fenêtre.\n— Cela fait 78 euros. Vous réglez comment ?\n— Par carte bancaire, merci.',
      options: [
        'Un aller-retour en 1ère classe',
        'Un aller simple en 2nde classe, place fenêtre, pour 78 €',
        'Un aller simple en 2nde classe pour 178 €',
        'Un billet sans place réservée',
      ],
      answer: 1,
      explanation: 'La cliente choisit "un billet aller simple pour Genève", en "2nde", "côté fenêtre", à 78 €.',
    },
    {
      id: 'tef-l2-11',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que dit l\'annonce ?',
      promptFr: 'Que dit l\'annonce ?',
      audioText: 'Mesdames et messieurs, en raison d\'un mouvement social national, le réseau de bus urbain fonctionnera ce jeudi avec un service réduit, environ un bus sur trois. Les horaires des tramways ne sont pas affectés. Merci de prévoir un délai supplémentaire pour vos trajets.',
      options: [
        'Aucun bus ne circulera jeudi.',
        'Le réseau de bus fonctionnera en service réduit, environ un bus sur trois, mais les tramways ne sont pas affectés.',
        'Les tramways seront supprimés.',
        'Le réseau fonctionne normalement.',
      ],
      answer: 1,
      explanation: 'L\'annonce précise : "service réduit, environ un bus sur trois" et "Les horaires des tramways ne sont pas affectés".',
    },
    {
      id: 'tef-l2-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : quel est le sujet de l\'interview ?',
      promptFr: 'Quel est le sujet de l\'interview ?',
      audioText: 'Aujourd\'hui, nous recevons un chercheur du CNRS spécialiste des algues. Selon lui, ces organismes longtemps négligés pourraient révolutionner notre alimentation, notre agriculture et même nos biocarburants. Il plaide pour une filière française structurée, capable de concurrencer les pays asiatiques déjà très avancés dans ce domaine.',
      options: [
        'La pollution des océans',
        'Le potentiel des algues pour l\'alimentation, l\'agriculture et les biocarburants',
        'La pêche industrielle',
        'Le réchauffement climatique',
      ],
      answer: 1,
      explanation: 'L\'interview porte sur le potentiel des algues pour "l\'alimentation, notre agriculture et même nos biocarburants".',
    },
    {
      id: 'tef-l2-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : que dit le journaliste sur le marché ?',
      promptFr: 'Que dit le journaliste sur le marché ?',
      audioText: 'Le marché de l\'occasion explose en France : voitures, vêtements, meubles, électroménager. Une tendance portée par le pouvoir d\'achat et par la prise de conscience écologique. Les plateformes en ligne voient leur trafic augmenter de plus de 25% sur un an, et les gammes reconditionnées séduisent même les marques historiques.',
      options: [
        'Le marché de l\'occasion baisse.',
        'Le marché de l\'occasion explose, porté par le pouvoir d\'achat et l\'écologie.',
        'Les marques historiques refusent le reconditionné.',
        'Les ventes en ligne baissent.',
      ],
      answer: 1,
      explanation: 'Le journaliste dit que "Le marché de l\'occasion explose en France", porté "par le pouvoir d\'achat et par la prise de conscience écologique".',
    },
    {
      id: 'tef-l2-14',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : que propose le maire ?',
      promptFr: 'Que propose le maire ?',
      audioText: 'Face à la canicule annoncée la semaine prochaine, la municipalité met en place un dispositif renforcé : ouverture de trois salles rafraîchies 24h/24, distribution d\'eau dans les quartiers prioritaires, et numéro vert dédié aux personnes isolées. J\'appelle chacun à la vigilance et à la solidarité envers les plus fragiles.',
      options: [
        'Fermer les salles rafraîchies',
        'Ouvrir trois salles rafraîchies 24h/24, distribuer de l\'eau, numéro vert',
        'Interdire les déplacements',
        'Augmenter les impôts',
      ],
      answer: 1,
      explanation: 'Le maire propose "trois salles rafraîchies 24h/24", "distribution d\'eau" et "numéro vert".',
    },
    {
      id: 'tef-l2-15',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : qu\'explique la directrice ?',
      promptFr: 'Qu\'explique la directrice ?',
      audioText: 'Notre entreprise a décidé de revoir entièrement sa politique de télétravail. À partir de septembre, les salariés devront travailler au moins deux jours par semaine sur site. L\'objectif n\'est pas de punir le télétravail, mais de préserver la culture d\'entreprise et la transmission entre générations de collaborateurs.',
      options: [
        'Le télétravail sera supprimé totalement.',
        'Les salariés devront travailler au moins deux jours par semaine sur site à partir de septembre.',
        'L\'entreprise va licencier.',
        'Le télétravail sera obligatoire 5 jours par semaine.',
      ],
      answer: 1,
      explanation: 'La directrice annonce : "les salariés devront travailler au moins deux jours par semaine sur site" à partir de septembre.',
    },
  ],
};

const tefListeningTest3: PracticeTest = {
  id: 'tef-listening-test-3',
  title: 'Listening Practice Test 3',
  titleFr: 'Compréhension orale — Test 3',
  description: '15 questions — annonces publiques, conversations, messages téléphoniques, extraits radio.',
  questions: [
    {
      id: 'tef-l3-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Écoutez et répondez : quel jour la pharmacie est-elle fermée ?',
      promptFr: 'Quel jour la pharmacie est-elle fermée ?',
      audioText: 'Notre pharmacie est ouverte du lundi au samedi, de huit heures à vingt heures. Nous sommes fermés le dimanche. En cas d\'urgence le dimanche, veuillez contacter la pharmacie de garde au 15.',
      options: ['Le lundi', 'Le samedi', 'Le dimanche', 'Le mercredi'],
      answer: 2,
      explanation: 'L\'annonce indique : "Nous sommes fermés le dimanche."',
    },
    {
      id: 'tef-l3-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Écoutez l\'annonce : combien de places reste-t-il ?',
      promptFr: 'Combien de places reste-t-il ?',
      audioText: 'Attention, il ne reste que cinq places pour la représentation de 20 heures du spectacle "Le Malade imaginaire". Les places sont disponibles au guichet et en ligne. Venez vite !',
      options: ['10 places', '5 places', '20 places', 'Aucune place'],
      answer: 1,
      explanation: 'L\'annonce précise : "il ne reste que cinq places".',
    },
    {
      id: 'tef-l3-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez et répondez : que dit la personne ?',
      promptFr: 'Que dit la personne ?',
      audioText: 'Bonjour, c\'est Julie. Je vous appelle pour annuler notre rendez-vous de demain après-midi. J\'ai un imprévu professionnel et je dois me rendre à Lyon. Pouvons-nous nous voir la semaine prochaine, mardi ou jeudi ? Tenez-moi au courant, merci !',
      options: [
        'Elle confirme le rendez-vous de demain.',
        'Elle annule le rendez-vous de demain et propose mardi ou jeudi prochain.',
        'Elle est malade.',
        'Elle déménage à Lyon.',
      ],
      answer: 1,
      explanation: 'Julie "annule notre rendez-vous de demain" et propose "mardi ou jeudi" la semaine prochaine.',
    },
    {
      id: 'tef-l3-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez la conversation au marché : combien coûtent les pommes ?',
      promptFr: 'Combien coûtent les pommes ?',
      audioText: '— Bonjour, les pommes c\'est combien ?\n— Deux euros le kilo, madame. Aujourd\'hui, trois kilos pour cinq euros.\n— Je vais en prendre trois kilos, s\'il vous plaît.\n— Très bon choix, ce sont des Gala.',
      options: ['2 € le kilo', '5 € les 3 kg', '3 € le kilo', '10 € les 3 kg'],
      answer: 1,
      explanation: 'Le vendeur propose "trois kilos pour cinq euros" et la cliente en prend trois.',
    },
    {
      id: 'tef-l3-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Écoutez l\'annonce à l\'hôtel : à quelle heure est le petit-déjeuner ?',
      promptFr: 'À quelle heure est le petit-déjeuner ?',
      audioText: 'Mesdames et messieurs, bienvenue à l\'hôtel des Pins. Le petit-déjeuner est servi de sept heures à dix heures dans la salle "Aurore", au rez-de-chaussée. Le wifi est gratuit, le code figure sur votre clé. Pour tout renseignement, composez le 9 à la réception.',
      options: [
        'De 7h à 10h',
        'De 6h à 9h',
        'De 8h à 11h',
        'De 7h à 11h',
      ],
      answer: 0,
      explanation: 'L\'annonce indique : "Le petit-déjeuner est servi de sept heures à dix heures".',
    },
    {
      id: 'tef-l3-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que demande l\'employeur ?',
      promptFr: 'Que demande l\'employeur ?',
      audioText: 'Bonjour, c\'est Monsieur Durand, le responsable des ressources humaines. Je vous appelle suite à votre candidature. Pourriez-vous venir jeudi prochain à quatorze heures pour un entretien d\'embauche ? Merci de me confirmer votre présence par téléphone avant mardi midi. À bientôt !',
      options: [
        'Venir jeudi prochain à 14h, confirmer avant mardi midi',
        'Venir mardi à 14h',
        'Confirmer par courrier postal',
        'Envoyer un nouveau CV',
      ],
      answer: 0,
      explanation: 'L\'employeur demande de venir "jeudi prochain à quatorze heures" et de "confirmer votre présence par téléphone avant mardi midi".',
    },
    {
      id: 'tef-l3-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que dit la cliente au retour ?',
      promptFr: 'Que dit la cliente au retour ?',
      audioText: '— Bonjour, je voudrais ramener cette chemise, elle est trop grande.\n— Avez-vous le ticket de caisse ?\n— Oui, voilà. Et le tag est encore dessus.\n— Très bien. Vous préférez un échange ou un remboursement ?\n— Un échange pour une taille M, s\'il vous plaît.',
      options: [
        'Un remboursement',
        'Un échange pour une taille M',
        'Garder la chemise',
        'Acheter une autre chemise',
      ],
      answer: 1,
      explanation: 'La cliente choisit "Un échange pour une taille M".',
    },
    {
      id: 'tef-l3-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez le message du banquier : que propose-t-il ?',
      promptFr: 'Que propose-t-il ?',
      audioText: 'Bonjour, c\'est votre conseiller bancaire. Suite à l\'examen de votre dossier, je vous propose un rendez-vous pour parler de votre projet d\'acquisition immobilière. Je peux vous recevoir jeudi matin ou vendredi après-midi, à votre convenance. Merci de me rappeler rapidement pour fixer la date. Excellente journée !',
      options: [
        'Un refus de prêt',
        'Un rendez-vous pour parler du projet d\'acquisition immobilière, jeudi matin ou vendredi après-midi',
        'Une augmentation de découvert',
        'Une fermeture de compte',
      ],
      answer: 1,
      explanation: 'Le banquier propose "un rendez-vous pour parler de votre projet d\'acquisition immobilière", jeudi matin ou vendredi après-midi.',
    },
    {
      id: 'tef-l3-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez l\'extrait : quel temps fera-t-il ce week-end ?',
      promptFr: 'Quel temps fera-t-il ce week-end ?',
      audioText: 'Voici les prévisions pour le week-end. Samedi, le temps sera nuageux avec quelques averses en fin de journée sur le littoral. Dimanche, le soleil revient en force, avec des températures pouvant atteindre 25 degrés dans l\'intérieur des terres. Vent faible venu de l\'ouest.',
      options: [
        'Samedi nuageux avec averses, dimanche ensoleillé jusqu\'à 25°C',
        'Pluie tout le week-end',
        'Neige dimanche',
        'Canicule dès samedi',
      ],
      answer: 0,
      explanation: 'Samedi "nuageux avec quelques averses", dimanche "le soleil revient en force" avec "25 degrés".',
    },
    {
      id: 'tef-l3-10',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que dit le professeur ?',
      promptFr: 'Que dit le professeur ?',
      audioText: 'Bonjour à tous. Petit rappel : votre devoir sur table de la semaine prochaine est décalé au jeudi 15 au lieu du mardi 13. Pensez à réviser les chapitres 4 à 6. Les calculatrices sont autorisées, mais pas les téléphones. Bon courage pour vos révisions !',
      options: [
        'Le devoir est avancé au mardi 13.',
        'Le devoir est décalé au jeudi 15, calculatrices autorisées mais pas les téléphones.',
        'Le devoir est annulé.',
        'Les téléphones sont autorisés.',
      ],
      answer: 1,
      explanation: 'Le professeur annonce un décalage "au jeudi 15 au lieu du mardi 13" et "calculatrices autorisées, mais pas les téléphones".',
    },
    {
      id: 'tef-l3-11',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Écoutez et répondez : que dit l\'annonce de la SNCF ?',
      promptFr: 'Que dit l\'annonce de la SNCF ?',
      audioText: 'Mesdames et messieurs, votre attention s\'il vous plaît. En raison d\'un accident de personne sur la voie, la circulation des trains est interrompue entre Lyon Part-Dieu et Saint-Étienne jusqu\'à 18 heures. Des bus de remplacement sont mis en place. Nous vous présentons nos sincères excuses.',
      options: [
        'La circulation reprend immédiatement.',
        'Circulation interrompue Lyon–Saint-Étienne jusqu\'à 18h, bus de remplacement en place.',
        'Tous les trains sont supprimés.',
        'Aucune incidence sur les trains.',
      ],
      answer: 1,
      explanation: 'L\'annonce indique : "circulation des trains est interrompue entre Lyon Part-Dieu et Saint-Étienne jusqu\'à 18 heures" et "bus de remplacement".',
    },
    {
      id: 'tef-l3-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : quel phénomène est décrit ?',
      promptFr: 'Quel phénomène est décrit ?',
      audioText: 'Un phénomène inquiétant préoccupe les agriculteurs du sud-ouest : les rendements de maïs chutent pour la troisième année consécutive. La cause principale identifiée par les agronomes : le déficit hydrique estival, de plus en plus marqué. Plusieurs exploitations étudient des variétés plus résistantes à la sécheresse.',
      options: [
        'Une hausse des rendements de maïs',
        'Une baisse des rendements de maïs liée au déficit hydrique',
        'Une invasion d\'insectes',
        'Une surproduction de maïs',
      ],
      answer: 1,
      explanation: 'Le reportage décrit "les rendements de maïs chutent" et identifie "le déficit hydrique estival" comme cause principale.',
    },
    {
      id: 'tef-l3-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : quel est l\'avis de la critique ?',
      promptFr: 'Quel est l\'avis de la critique ?',
      audioText: 'Le dernier film de Céline Sciamma a divisé la critique. Si certains saluent une mise en scène audacieuse et une photographie sublime, d\'autres regrettent un rythme trop lent et un scénario parfois mince. Le public, lui, a tranché : près de 800 000 entrées en une semaine, un vrai succès populaire.',
      options: [
        'La critique est unanime.',
        'La critique est divisée, mais le public plébiscite le film (800 000 entrées en 1 semaine).',
        'Le film est un échec public.',
        'Personne n\'est allé le voir.',
      ],
      answer: 1,
      explanation: 'La critique est "divisée", mais le public a fait un "vrai succès populaire" avec "800 000 entrées en une semaine".',
    },
    {
      id: 'tef-l3-14',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : que dit l\'économie du journaliste ?',
      promptFr: 'Que dit l\'économie du journaliste ?',
      audioText: 'Bonne nouvelle pour l\'économie française : le taux de chômage est repassé sous la barre des 7% au dernier trimestre, un niveau qu\'on n\'avait plus vu depuis 2009. Les créations d\'emplois sont particulièrement dynamiques dans les services et le bâtiment. Reste que le chômage des jeunes reste élevé, autour de 17%.',
      options: [
        'Le chômage a dépassé 7%.',
        'Le chômage est repassé sous 7%, mais celui des jeunes reste élevé (17%).',
        'Le chômage des jeunes a disparu.',
        'Aucune création d\'emploi.',
      ],
      answer: 1,
      explanation: 'Le journaliste indique que le chômage est "repassé sous la barre des 7%" mais que "le chômage des jeunes reste élevé, autour de 17%".',
    },
    {
      id: 'tef-l3-15',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Écoutez et répondez : que dénonce l\'écologue ?',
      promptFr: 'Que dénonce l\'écologue ?',
      audioText: 'Notre océan est en train de s\'acidifier à une vitesse inquiétante. Conséquence directe de l\'absorption du CO2, cette acidification menace les récifs coralliens et les coquillages. Si nous ne réduisons pas drastiquement nos émissions, c\'est toute la chaîne alimentaire marine qui risque de s\'effondrer d\'ici la fin du siècle.',
      options: [
        'L\'océan se refroidit.',
        'L\'océan s\'acidifie à cause du CO2, menaçant coraux et coquillages.',
        'Les coquillages prolifèrent.',
        'La chaîne alimentaire marine est déjà sauvée.',
      ],
      answer: 1,
      explanation: 'L\'écologue dénonce l\'acidification de l\'océan due au CO2, qui menace "les récifs coralliens et les coquillages".',
    },
  ],
};

// ---------------------------------------------------------------------------
// VOCABULARY & GRAMMAR — 3 tests × 15 questions
// ---------------------------------------------------------------------------

const tefVocabTest1: PracticeTest = {
  id: 'tef-vocab-test-1',
  title: 'Vocabulary & Grammar Practice Test 1',
  titleFr: 'Vocabulaire et grammaire — Test 1',
  description: '15 questions — choix du mot ou de la forme correcte.',
  questions: [
    {
      id: 'tef-v1-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Complétez (verbe vivre) : « Je ___ à Paris depuis trois ans. »',
      promptFr: 'Complétez la phrase.',
      options: ['vis', 'vit', 'vivent', 'vivez'],
      answer: 0,
      explanation: 'Avec "je", on conjugue "vivre" en "vis" (je vis, tu vis, il vit, nous vivons, vous vivez, ils vivent).',
    },
    {
      id: 'tef-v1-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Complétez : « Il y a ___ pomme sur la table. »',
      promptFr: 'Complétez la phrase.',
      options: ['une', 'un', 'des', 'le'],
      answer: 0,
      explanation: '"Pomme" est féminin singulier → "une pomme".',
    },
    {
      id: 'tef-v1-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « Hier, nous ___ au cinéma. »',
      promptFr: 'Complétez la phrase.',
      options: ['allons', 'sommes allés', 'irons', 'allions'],
      answer: 1,
      explanation: 'Passé composé avec "être" : "nous sommes allés" (mouvement).',
    },
    {
      id: 'tef-v1-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « Elle parle ___ son ami au téléphone. »',
      promptFr: 'Complétez la phrase.',
      options: ['à', 'avec', 'de', 'par'],
      answer: 0,
      explanation: 'On dit "parler à quelqu\'un". La préposition correcte est "à".',
    },
    {
      id: 'tef-v1-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « C\'est le livre ___ j\'ai acheté hier. »',
      promptFr: 'Complétez la phrase.',
      options: ['que', 'qui', 'dont', 'où'],
      answer: 0,
      explanation: 'COD : "que" (le livre que j\'ai acheté).',
    },
    {
      id: 'tef-v1-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Si j\'avais le temps, je ___ au sport plus souvent. »',
      promptFr: 'Complétez la phrase.',
      options: ['jouerais', 'joue', 'jouerai', 'jouais'],
      answer: 0,
      explanation: 'Hypothèse présente (si + imparfait) → conditionnel présent : "je jouerais".',
    },
    {
      id: 'tef-v1-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Le train est parti ___ l\'heure. »',
      promptFr: 'Complétez la phrase.',
      options: ['à', 'en', 'dans', 'par'],
      answer: 0,
      explanation: 'On dit "à l\'heure" (ponctuel). "En avance/en retard" utilisent "en".',
    },
    {
      id: 'tef-v1-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « La fille ___ tu as parlé est ma cousine. »',
      promptFr: 'Complétez la phrase.',
      options: ['que', 'qui', 'dont', 'où'],
      answer: 2,
      explanation: 'Verbe "parler de" : on utilise "dont" (la fille dont tu as parlé).',
    },
    {
      id: 'tef-v1-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Bien qu\'il ___ fatigué, il est venu travailler. »',
      promptFr: 'Complétez la phrase.',
      options: ['est', 'soit', 'était', 'sera'],
      answer: 1,
      explanation: 'Après "bien que", on emploie le subjonctif : "bien qu\'il soit".',
    },
    {
      id: 'tef-v1-10',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Il faut que tu ___ ton devoir. »',
      promptFr: 'Complétez la phrase.',
      options: ['fais', 'fasses', 'feras', 'faisais'],
      answer: 1,
      explanation: 'Après "il faut que", on emploie le subjonctif : "que tu fasses".',
    },
    {
      id: 'tef-v1-11',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Si j\'avais su, je ___ venir. »',
      promptFr: 'Complétez la phrase.',
      options: ['serais venu', 'viendrai', 'viendrais', 'serai venu'],
      answer: 0,
      explanation: 'Hypothèse passée (si + plus-que-parfait) → conditionnel passé : "je serais venu".',
    },
    {
      id: 'tef-v1-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Cette région est connue ___ ses vins. »',
      promptFr: 'Complétez la phrase.',
      options: ['pour', 'de', 'par', 'avec'],
      answer: 0,
      explanation: '"Être connu pour" = célèbre pour. La préposition correcte est "pour".',
    },
    {
      id: 'tef-v1-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Je doute qu\'il ___ à l\'heure. »',
      promptFr: 'Complétez la phrase.',
      options: ['vient', 'vienne', 'viendra', 'venait'],
      answer: 1,
      explanation: 'Après "douter que", on emploie le subjonctif : "qu\'il vienne".',
    },
    {
      id: 'tef-v1-14',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « ___ ses difficultés, il a réussi son examen. »',
      promptFr: 'Complétez la phrase.',
      options: ['Malgré', 'Grâce à', 'À cause de', 'Pendant'],
      answer: 0,
      explanation: 'On emploie "malgré" pour exprimer l\'opposition. "Grâce à" est positif, "à cause de" négatif.',
    },
    {
      id: 'tef-v1-15',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Je n\'ai ___ vu un tel paysage. »',
      promptFr: 'Complétez la phrase.',
      options: ['jamais', 'toujours', 'déjà', 'encore'],
      answer: 0,
      explanation: 'Avec la négation "ne...jamais" indique "aucune fois dans ma vie". "Je n\'ai jamais vu" = jamais vu.',
    },
  ],
};

const tefVocabTest2: PracticeTest = {
  id: 'tef-vocab-test-2',
  title: 'Vocabulary & Grammar Practice Test 2',
  titleFr: 'Vocabulaire et grammaire — Test 2',
  description: '15 questions — choix du mot ou de la forme correcte.',
  questions: [
    {
      id: 'tef-v2-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Complétez : « Nous ___ français. »',
      promptFr: 'Complétez la phrase.',
      options: ['sommes', 'est', 'sont', 'être'],
      answer: 0,
      explanation: 'Avec "nous", on conjugue "être" en "sommes".',
    },
    {
      id: 'tef-v2-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Complétez : « Elle a ___ chien noir. »',
      promptFr: 'Complétez la phrase.',
      options: ['un', 'une', 'des', 'la'],
      answer: 0,
      explanation: '"Chien" est masculin singulier → "un chien".',
    },
    {
      id: 'tef-v2-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « L\'été dernier, ils ___ en Espagne. »',
      promptFr: 'Complétez la phrase.',
      options: ['vont', 'sont allés', 'iront', 'allaient'],
      answer: 1,
      explanation: 'Passé composé avec "être" : "ils sont allés" (déplacement).',
    },
    {
      id: 'tef-v2-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « Je voudrais ___ café, s\'il vous plaît. »',
      promptFr: 'Complétez la phrase.',
      options: ['un', 'une', 'du', 'de la'],
      answer: 2,
      explanation: '"Café" masculin indéfinissable (non comptable dans ce contexte) → "du café".',
    },
    {
      id: 'tef-v2-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « L\'homme ___ parle est mon professeur. »',
      promptFr: 'Complétez la phrase.',
      options: ['qui', 'que', 'dont', 'où'],
      answer: 0,
      explanation: 'Sujet : "qui" (l\'homme qui parle = l\'homme est sujet de "parle").',
    },
    {
      id: 'tef-v2-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Quand j\'étais petit, je ___ à la montagne chaque hiver. »',
      promptFr: 'Complétez la phrase.',
      options: ['allais', 'vais', 'irai', 'suis allé'],
      answer: 0,
      explanation: 'Habitude passée : imparfait "j\'allais".',
    },
    {
      id: 'tef-v2-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Je partirai dès que j\'___ fini. »',
      promptFr: 'Complétez la phrase.',
      options: ['aurai', 'ai', 'avais', 'aura'],
      answer: 0,
      explanation: 'Futur antérieur pour une action achevée avant une autre : "dès que j\'aurai fini".',
    },
    {
      id: 'tef-v2-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « La maison ___ je rêve est en bord de mer. »',
      promptFr: 'Complétez la phrase.',
      options: ['que', 'qui', 'dont', 'où'],
      answer: 2,
      explanation: 'Verbe "rêver de" : on utilise "dont" (la maison dont je rêve).',
    },
    {
      id: 'tef-v2-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Je voudrais que tu ___ plus sérieux. »',
      promptFr: 'Complétez la phrase.',
      options: ['sois', 'es', 'seras', 'étais'],
      answer: 0,
      explanation: 'Après "je voudrais que", on emploie le subjonctif : "que tu sois".',
    },
    {
      id: 'tef-v2-10',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Il a réussi ___ son examen du premier coup. »',
      promptFr: 'Complétez la phrase.',
      options: ['à', 'de', 'pour', 'par'],
      answer: 0,
      explanation: 'On dit "réussir à quelque chose" : "réussir à son examen".',
    },
    {
      id: 'tef-v2-11',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « S\'il faisait beau, on ___ pique-niquer. »',
      promptFr: 'Complétez la phrase.',
      options: ['pourrait', 'pourra', 'aurait pu', 'peut'],
      answer: 0,
      explanation: 'Hypothèse présente (si + imparfait) → conditionnel présent : "on pourrait".',
    },
    {
      id: 'tef-v2-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Il a commencé à pleuvoir, ___ nous avons rentré les chaises. »',
      promptFr: 'Complétez la phrase.',
      options: ['donc', 'malgré', 'bien que', 'puisque'],
      answer: 0,
      explanation: 'Conséquence logique : "donc". Les autres ne conviennent pas.',
    },
    {
      id: 'tef-v2-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Je regrette qu\'il ___ parti si tôt. »',
      promptFr: 'Complétez la phrase.',
      options: ['soit', 'est', 'était', 'sera'],
      answer: 0,
      explanation: 'Après "regretter que", on emploie le subjonctif : "qu\'il soit".',
    },
    {
      id: 'tef-v2-14',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « ___ la pluie, nous sommes sortis nous promener. »',
      promptFr: 'Complétez la phrase.',
      options: ['Malgré', 'Grâce à', 'Pendant', 'À cause de'],
      answer: 0,
      explanation: 'Opposition : "malgré la pluie" indique qu\'on a fait l\'action malgré le obstacle.',
    },
    {
      id: 'tef-v2-15',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Ce problème est ___ difficile ___ tu le crois. »',
      promptFr: 'Complétez la phrase.',
      options: ['plus... que', 'aussi... que', 'moins... que', 'autant... que'],
      answer: 0,
      explanation: 'Comparaison de supériorité : "plus difficile que".',
    },
  ],
};

const tefVocabTest3: PracticeTest = {
  id: 'tef-vocab-test-3',
  title: 'Vocabulary & Grammar Practice Test 3',
  titleFr: 'Vocabulaire et grammaire — Test 3',
  description: '15 questions — choix du mot ou de la forme correcte.',
  questions: [
    {
      id: 'tef-v3-1',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Complétez : « Tu ___ étudiant ? »',
      promptFr: 'Complétez la phrase.',
      options: ['es', 'est', 'sont', 'être'],
      answer: 0,
      explanation: 'Avec "tu", on conjugue "être" en "es".',
    },
    {
      id: 'tef-v3-2',
      type: 'multiple_choice',
      level: 'A1',
      prompt: 'Complétez : « Il y a ___ livres sur l\'étagère. »',
      promptFr: 'Complétez la phrase.',
      options: ['des', 'un', 'une', 'le'],
      answer: 0,
      explanation: 'Pluriel indéfini : "des livres".',
    },
    {
      id: 'tef-v3-3',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « Demain, je ___ ma grand-mère. »',
      promptFr: 'Complétez la phrase.',
      options: ['visiterai', 'visite', 'visiterais', 'visitais'],
      answer: 0,
      explanation: 'Action future : futur simple "je visiterai".',
    },
    {
      id: 'tef-v3-4',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « Je n\'aime pas ___ café le matin. »',
      promptFr: 'Complétez la phrase.',
      options: ['le', 'la', 'les', 'un'],
      answer: 0,
      explanation: '"Café" masculin singulier défini → "le café".',
    },
    {
      id: 'tef-v3-5',
      type: 'multiple_choice',
      level: 'A2',
      prompt: 'Complétez : « La ville ___ je viens est petite. »',
      promptFr: 'Complétez la phrase.',
      options: ['dont', 'que', 'où', 'qui'],
      answer: 2,
      explanation: 'Lieu : "où" (la ville où je viens).',
    },
    {
      id: 'tef-v3-6',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « En ___ au travail, j\'ai écouté un podcast. »',
      promptFr: 'Complétez la phrase.',
      options: ['venant', 'venir', 'venu', 'viens'],
      answer: 0,
      explanation: 'Gérondif : "en venant" (en + participe présent).',
    },
    {
      id: 'tef-v3-7',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Je te préviendrai dès que le colis ___. »',
      promptFr: 'Complétez la phrase.',
      options: ['arrivera', 'arrive', 'arrivait', 'arrivé'],
      answer: 0,
      explanation: 'Action future postérieure à une autre action future : futur simple "arrivera".',
    },
    {
      id: 'tef-v3-8',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « C\'est le sujet ___ je t\'ai parlé hier. »',
      promptFr: 'Complétez la phrase.',
      options: ['dont', 'que', 'qui', 'où'],
      answer: 0,
      explanation: 'Verbe "parler de" : on utilise "dont" (le sujet dont je t\'ai parlé).',
    },
    {
      id: 'tef-v3-9',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Il est important que chacun ___ son rôle. »',
      promptFr: 'Complétez la phrase.',
      options: ['joue', 'joues', 'jouera', 'jouait'],
      answer: 0,
      explanation: 'Après "il est important que", on emploie le subjonctif. Avec "chacun" (3e pers. sing.) : "que chacun joue".',
    },
    {
      id: 'tef-v3-10',
      type: 'multiple_choice',
      level: 'B1',
      prompt: 'Complétez : « Cette voiture coûte ___ que la mienne. »',
      promptFr: 'Complétez la phrase.',
      options: ['plus cher', 'plus chère', 'plus chers', 'plus chères'],
      answer: 1,
      explanation: '"Voiture" féminin singulier : "plus chère".',
    },
    {
      id: 'tef-v3-11',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Si tu m\'avais prévenu, je ___ venir. »',
      promptFr: 'Complétez la phrase.',
      options: ['serais venu', 'viendrai', 'viendrais', 'serai venu'],
      answer: 0,
      explanation: 'Hypothèse passée (si + plus-que-parfait) → conditionnel passé : "je serais venu".',
    },
    {
      id: 'tef-v3-12',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Je me souviens ___ cet endroit. »',
      promptFr: 'Complétez la phrase.',
      options: ['de', 'à', 'pour', 'sur'],
      answer: 0,
      explanation: 'On dit "se souvenir de" : "Je me souviens de cet endroit".',
    },
    {
      id: 'tef-v3-13',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Il est temps que tu ___ une décision. »',
      promptFr: 'Complétez la phrase.',
      options: ['prennes', 'prends', 'prendras', 'prenais'],
      answer: 0,
      explanation: 'Après "il est temps que", on emploie le subjonctif : "que tu prennes".',
    },
    {
      id: 'tef-v3-14',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « Le voyage a été annulé ___ la grève. »',
      promptFr: 'Complétez la phrase.',
      options: ['à cause de', 'grâce à', 'malgré', 'pendant'],
      answer: 0,
      explanation: 'Cause négative : "à cause de la grève".',
    },
    {
      id: 'tef-v3-15',
      type: 'multiple_choice',
      level: 'B2',
      prompt: 'Complétez : « ___ de ses efforts, il n\'a pas gagné. »',
      promptFr: 'Complétez la phrase.',
      options: ['Malgré', 'Grâce à', 'À cause de', 'Pendant'],
      answer: 0,
      explanation: 'Opposition : "malgré" indique que l\'effort n\'a pas suffi.',
    },
  ],
};

// ---------------------------------------------------------------------------
// EXPORTED SECTIONS
// ---------------------------------------------------------------------------

export const tefExpandedSections: ExpandedTestSection[] = [
  {
    id: 'reading',
    title: 'Reading Comprehension',
    titleFr: 'Compréhension écrite',
    description:
      'TEF Reading: 50 questions in 60 minutes. Section A (signs & announcements), Section B (short texts), Section C (longer texts).',
    icon: '📖',
    tests: [tefReadingTest1, tefReadingTest2, tefReadingTest3],
  },
  {
    id: 'listening',
    title: 'Listening Comprehension',
    titleFr: 'Compréhension orale',
    description:
      'TEF Listening: 60 questions in 40 minutes. Public announcements, conversations, radio extracts (with audioText for TTS).',
    icon: '🎧',
    tests: [tefListeningTest1, tefListeningTest2, tefListeningTest3],
  },
  {
    id: 'vocabulary_grammar',
    title: 'Vocabulary & Grammar',
    titleFr: 'Vocabulaire et structure',
    description:
      'TEF Vocabulary & Grammar: 40 questions in 15 minutes. Fill-in-the-blank, correct word/form, prepositions, conjugation.',
    icon: '✏️',
    tests: [tefVocabTest1, tefVocabTest2, tefVocabTest3],
  },
];

export default tefExpandedSections;
