import type { MockTest } from './types';

// TEF — Test d'Évaluation de Français
// Administered by CCIP (Chambre de Commerce et d'Industrie de Paris)
// Used for: Canada immigration (Express Entry, Quebec), French citizenship, study
// Real test: Reading 60min/50Q, Listening 40min/60Q, Vocabulary-Grammar 15min/40Q,
//            Speaking 15min/2subjects, Writing 60min/2subjects
export const tefTest: MockTest = {
  type: 'TEF',
  name: 'TEF',
  fullName: 'Test d\'Évaluation de Français',
  description:
    "The TEF is an international reference test that measures French language proficiency for non-native speakers. It is officially recognized by Immigration, Refugees and Citizenship Canada (IRCC) for Express Entry and by the French government for citizenship applications.",
  administeredBy: 'Paris Île-de-France CCI (CCIP)',
  usedFor: 'Canada immigration (Express Entry, Quebec CSQ), French citizenship, university admission, professional certification',
  color: '#1D4ED8',
  sections: [
    {
      id: 'reading',
      title: 'Reading Comprehension',
      titleFr: 'Compréhension écrite',
      description: 'Read short texts and answer questions. Real TEF: 50 questions in 60 minutes.',
      icon: '📖',
      questionCount: 10,
      durationMinutes: 12,
      questions: [
        {
          id: 'tef-r-1',
          type: 'multiple_choice',
          level: 'A1',
          prompt: 'Read the message and answer:\n\n"Chère Marie, je ne pourrai pas venir dîner ce soir. J\'ai trop de travail. On se voit samedi ? Bisous, Sophie."',
          promptFr: 'Lisez le message et répondez.',
          options: [
            'Sophie viendra dîner ce soir.',
            'Sophie ne viendra pas dîner ce soir.',
            'Marie ne veut pas dîner avec Sophie.',
            'Sophie dîne samedi soir avec Marie.',
          ],
          answer: 1,
          explanation: 'Sophie dit "je ne pourrai pas venir dîner ce soir" — she will NOT come.',
        },
        {
          id: 'tef-r-2',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Read the sign and answer:\n\n"FERMÉ LE LUNDI. Ouvert mardi au samedi : 9h - 19h. Dimanche : 9h - 13h."',
          options: [
            'Le magasin est ouvert le lundi.',
            'Le magasin ferme à 19h le dimanche.',
            'Le magasin est ouvert le dimanche matin.',
            'Le magasin ferme à 13h le samedi.',
          ],
          answer: 2,
          explanation: 'Dimanche : 9h - 13h means Sunday morning 9 AM to 1 PM.',
        },
        {
          id: 'tef-r-3',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Read and answer:\n\n"RECHERCHE : Appartement 2 pièces à Lyon, max 800€/mois. Parking souhaité. Contacter : Paul, 06 12 34 56 78."',
          options: [
            'Paul vend un appartement à Lyon.',
            'Paul cherche un appartement à Lyon.',
            'Paul a un appartement à louer.',
            'Paul habite à Lyon.',
          ],
          answer: 1,
          explanation: '"RECHERCHE" means looking for. Paul is searching for an apartment.',
        },
        {
          id: 'tef-r-4',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Read the article excerpt:\n\n"Selon une étude publiée hier, le télétravail a augmenté de 30% en France depuis 2020. Cependant, 45% des employés regretteraient le manque de contacts sociaux."',
          options: [
            'Le télétravail a baissé depuis 2020.',
            'Tous les employés aiment le télétravail.',
            'Le télétravail a augmenté mais pose des problèmes sociaux.',
            'Le télétravail a baissé de 45%.',
          ],
          answer: 2,
          explanation: 'Le télétravail a augmenté (30%) mais 45% des employés regrettent le manque de contacts — donc pose problème.',
        },
        {
          id: 'tef-r-5',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Read:\n\n"Cher client, votre colis sera livré le 15 mars entre 14h et 17h. Veuillez être présent à votre domicile. En cas d\'absence, un avis de passage sera déposé."',
          options: [
            'Le colis sera livré le matin.',
            'Si le client est absent, le colis sera perdu.',
            'Le client doit être présent le 15 mars après-midi.',
            'Le colis sera livré sans rendez-vous.',
          ],
          answer: 2,
          explanation: 'Livré entre 14h et 17h = l\'après-midi. Le client doit être présent.',
        },
        {
          id: 'tef-r-6',
          type: 'multiple_choice',
          level: 'B2',
          prompt: 'Read:\n\n"Malgré les critiques, la réforme des retraites a été adoptée. Le gouvernement affirme qu\'elle est nécessaire à la pérennité du système, tandis que les syndicats dénoncent une injustice sociale."',
          options: [
            'Tout le monde est d\'accord sur la réforme.',
            'Le gouvernement et les syndicats ont des opinions opposées.',
            'Les syndicats soutiennent la réforme.',
            'La réforme a été rejetée.',
          ],
          answer: 1,
          explanation: 'Le gouvernement soutient ; les syndicats dénoncent = opinions opposées.',
        },
        {
          id: 'tef-r-7',
          type: 'multiple_choice',
          level: 'B2',
          prompt: 'Read:\n\n"L\'intelligence artificielle, longtemps confinée aux laboratoires, s\'infiltre désormais dans notre quotidien. Si elle facilite certaines tâches, elle soulève aussi des questions éthiques majeures."',
          options: [
            'L\'IA reste dans les laboratoires.',
            'L\'IA ne pose aucun problème éthique.',
            'L\'IA a des avantages et des inconvénients.',
            'L\'IA est rejetée par le public.',
          ],
          answer: 2,
          explanation: '"facilite certaines tâches" (avantages) + "soulève des questions éthiques" (inconvénients).',
        },
        {
          id: 'tef-r-8',
          type: 'multiple_choice',
          level: 'A1',
          prompt: 'Read:\n\n"Bonjour, je m\'appelle Lucas. J\'ai 25 ans. Je suis étudiant à l\'université de Lyon. J\'habite dans un petit appartement avec mon chat."',
          options: [
            'Lucas a 20 ans.',
            'Lucas travaille à Lyon.',
            'Lucas est étudiant.',
            'Lucas habite avec un chien.',
          ],
          answer: 2,
          explanation: 'Le texte dit "Je suis étudiant à l\'université de Lyon."',
        },
        {
          id: 'tef-r-9',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Read:\n\n"MÉTÉO : Demain, temps nuageux avec quelques averses le matin. L\'après-midi, le soleil fera son apparition. Températures : 15°C le matin, 22°C l\'après-midi."',
          options: [
            'Il pleuvra toute la journée.',
            'Il fera beau toute la journée.',
            'Le soleil apparaîtra l\'après-midi.',
            'Les températures seront négatives.',
          ],
          answer: 2,
          explanation: '"L\'après-midi, le soleil fera son apparition."',
        },
        {
          id: 'tef-r-10',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Read:\n\n"Pour louer un vélo en libre-service : 1) Téléchargez l\'application. 2) Créez un compte. 3) Scannez le QR code du vélo. 4) Roulez ! Le premier quart d\'heure est gratuit."',
          options: [
            'La location de vélo est payante dès la première minute.',
            'Il faut créer un compte avant de louer.',
            'Les 30 premières minutes sont gratuites.',
            'Il n\'y a pas d\'application pour louer.',
          ],
          answer: 1,
          explanation: 'Étape 2 : "Créez un compte" avant de scanner le QR code.',
        },
      ],
    },
    {
      id: 'listening',
      title: 'Listening Comprehension',
      titleFr: 'Compréhension orale',
      description: 'Listen to short audio clips (use the speaker button to hear each prompt) and answer.',
      icon: '🎧',
      questionCount: 10,
      durationMinutes: 10,
      questions: [
        {
          id: 'tef-l-1',
          type: 'multiple_choice',
          level: 'A1',
          prompt: 'You will hear a short message. What does the person want?',
          audioText: 'Bonjour, je voudrais un café et un croissant, s\'il vous plaît.',
          options: ['A tea and a cake', 'A coffee and a croissant', 'A glass of water', 'A sandwich'],
          answer: 1,
          explanation: '"un café et un croissant" = a coffee and a croissant.',
        },
        {
          id: 'tef-l-2',
          type: 'multiple_choice',
          level: 'A1',
          prompt: 'Listen and identify the time:',
          audioText: 'Excusez-moi, vous avez l\'heure ? Il est exactement quinze heures trente.',
          options: ['3:30 AM', '3:30 PM', '5:30 PM', '15:00'],
          answer: 1,
          explanation: '"Quinze heures trente" = 15h30 = 3:30 PM.',
        },
        {
          id: 'tef-l-3',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Listen and answer:',
          audioText: 'Pardon, pour aller à la gare, s\'il vous plaît ? — Allez tout droit, puis tournez à droite. C\'est à cinq minutes à pied.',
          options: [
            'La gare est très loin.',
            'La gare est à cinq minutes à pied.',
            'La gare est à gauche.',
            'La gare est en face.',
          ],
          answer: 1,
          explanation: '"C\'est à cinq minutes à pied."',
        },
        {
          id: 'tef-l-4',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Listen to the announcement:',
          audioText: 'Le train à destination de Lyon Part-Dieu va partir en voie 5. Veuillez embarquer immédiatement.',
          options: [
            'The train is arriving from Lyon.',
            'The train to Lyon is leaving from platform 5.',
            'The train is delayed.',
            'The train goes to Paris.',
          ],
          answer: 1,
          explanation: '"Le train à destination de Lyon... voie 5" — Train to Lyon, platform 5.',
        },
        {
          id: 'tef-l-5',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Listen to the conversation:',
          audioText: 'Tu as passé un bon week-end ? — Oui, je suis allée au cinéma avec mes amis. On a vu un film français très intéressant. Et toi ? — Moi, je suis resté à la maison, j\'ai lu un livre.',
          options: [
            'Les deux personnes sont sorties.',
            'Une personne est allée au cinéma.',
            'Les deux ont vu un film.',
            'Personne n\'a aimé son week-end.',
          ],
          answer: 1,
          explanation: 'La première personne est allée au cinéma ; la deuxième est restée à la maison.',
        },
        {
          id: 'tef-l-6',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Listen to the news:',
          audioText: 'Selon une enquête récente, 60% des Français considèrent que le télétravail améliore leur qualité de vie. Cependant, 30% se sentent parfois isolés.',
          options: [
            'Most French people hate remote work.',
            '60% of French people think remote work improves their quality of life.',
            '30% prefer to work from office always.',
            'No one feels isolated when working from home.',
          ],
          answer: 1,
          explanation: '"60% des Français considèrent que le télétravail améliore leur qualité de vie."',
        },
        {
          id: 'tef-l-7',
          type: 'multiple_choice',
          level: 'B2',
          prompt: 'Listen to the debate:',
          audioText: 'D\'une part, l\'intelligence artificielle nous fait gagner du temps. D\'autre part, elle pose des questions éthiques importantes. Il faudrait donc réguler son usage.',
          options: [
            'The speaker opposes AI completely.',
            'The speaker sees both advantages and disadvantages of AI.',
            'The speaker thinks AI should not be regulated.',
            'The speaker thinks AI is perfect.',
          ],
          answer: 1,
          explanation: '"D\'une part... d\'autre part" — speaker presents both sides.',
        },
        {
          id: 'tef-l-8',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Listen to the weather forecast:',
          audioText: 'Demain, le temps sera ensoleillé dans le sud de la France, mais des nuages apparaîtront dans le nord. Les températures atteindront 25 degrés à Marseille.',
          options: [
            'Il fera beau partout.',
            'Il pleuvra dans le sud.',
            'Il fera 25°C à Marseille.',
            'Il fera froid dans le nord.',
          ],
          answer: 2,
          explanation: '"Les températures atteindront 25 degrés à Marseille."',
        },
        {
          id: 'tef-l-9',
          type: 'multiple_choice',
          level: 'A1',
          prompt: 'Listen to the introduction:',
          audioText: 'Bonjour, je m\'appelle Marie. J\'habite à Bordeaux et je suis professeure. J\'ai deux enfants.',
          options: [
            'Marie is a doctor.',
            'Marie has two children.',
            'Marie lives in Paris.',
            'Marie has no children.',
          ],
          answer: 1,
          explanation: '"J\'ai deux enfants." — Marie has two children.',
        },
        {
          id: 'tef-l-10',
          type: 'multiple_choice',
          level: 'B2',
          prompt: 'Listen to the interview:',
          audioText: 'Quand j\'étais enfant, je voulais devenir écrivain. Finalement, j\'ai choisi le journalisme, qui me permet d\'écrire tout en restant au contact de la réalité.',
          options: [
            'The speaker wanted to be a writer but became a journalist.',
            'The speaker always wanted to be a journalist.',
            'The speaker became an writer.',
            'The speaker hates writing.',
          ],
          answer: 0,
          explanation: '"je voulais devenir écrivain" → "j\'ai choisi le journalisme".',
        },
      ],
    },
    {
      id: 'vocabulary_grammar',
      title: 'Vocabulary & Grammar',
      titleFr: 'Lexique et structure',
      description: 'Choose the correct word or grammatical form to complete sentences.',
      icon: '✏️',
      questionCount: 10,
      durationMinutes: 8,
      questions: [
        {
          id: 'tef-vg-1',
          type: 'multiple_choice',
          level: 'A1',
          prompt: 'Complete: "Je _____ français."',
          options: ['est', 'suis', 'es', 'être'],
          answer: 1,
          explanation: 'Je + suis = I am.',
        },
        {
          id: 'tef-vg-2',
          type: 'multiple_choice',
          level: 'A1',
          prompt: 'Complete: "_____ livre est sur la table." (the book)',
          options: ['Le', 'La', 'Les', 'Un'],
          answer: 0,
          explanation: 'Livre is masculine singular → le.',
        },
        {
          id: 'tef-vg-3',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Complete: "Hier, je _____ au cinéma."',
          options: ['suis allé', 'suis aller', 'ai allé', 'allais'],
          answer: 0,
          explanation: 'Aller uses être in passé composé: je suis allé.',
        },
        {
          id: 'tef-vg-4',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Complete: "Quand j\'_____ enfant, j\'aimais les bonbons."',
          options: ['étais', 'étais', 'ai été', 'serai'],
          answer: 0,
          explanation: 'Imparfait of être: j\'étais.',
        },
        {
          id: 'tef-vg-5',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Complete: "Il faut que tu _____ maintenant."',
          options: ['pars', 'partes', 'partir', 'partis'],
          answer: 1,
          explanation: 'After "il faut que", use subjunctive: tu partes.',
        },
        {
          id: 'tef-vg-6',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Complete: "Si j\'_____ riche, j\'achèterais une maison."',
          options: ['suis', 'serais', 'étais', 'étais'],
          answer: 2,
          explanation: 'Si + imparfait → conditionnel présent: si j\'étais riche.',
        },
        {
          id: 'tef-vg-7',
          type: 'multiple_choice',
          level: 'B2',
          prompt: 'Complete: "Bien qu\'il _____ fatigué, il a fini son travail."',
          options: ['est', 'soit', 'était', 'sera'],
          answer: 1,
          explanation: 'Bien que + subjunctive: bien qu\'il soit.',
        },
        {
          id: 'tef-vg-8',
          type: 'multiple_choice',
          level: 'B2',
          prompt: 'Complete: "Si j\'avais su, je _____ venu."',
          options: ['serais', 'avais', 'suis', 'aurais'],
          answer: 0,
          explanation: 'Venir uses être: conditionnel passé = je serais venu.',
        },
        {
          id: 'tef-vg-9',
          type: 'multiple_choice',
          level: 'A2',
          prompt: 'Which is the direct object pronoun in "Je les vois"?',
          options: ['Je', 'les', 'vois', 'there is none'],
          answer: 1,
          explanation: '"les" is the direct object pronoun (them).',
        },
        {
          id: 'tef-vg-10',
          type: 'multiple_choice',
          level: 'B1',
          prompt: 'Complete: "Le livre _____ par Marie." (passive)',
          options: ['écrit', 'est écrit', 'a écrit', 'écrit'],
          answer: 1,
          explanation: 'Passive = être + past participle: est écrit.',
        },
      ],
    },
  ],
};
