from .types import *

# ============================================================
# A1 Course — Complete with all units and lessons
# ============================================================

a1_units = [
    # UNIT 0: Starter
    Unit(
        id='a1-u0', title='Starter Unit — Discover French', titleFr='Unité 0 — Découvrez !',
        theme='First contact with French', description='Greetings, the alphabet, numbers, and an introduction to France.',
        lessons=[
            Lesson(id='a1-u0-l1', title='Greetings and Polite Expressions', titleFr='Saluer',
                description='Learn to greet people, say goodbye, and use polite expressions in French.',
                objectives=['Greet someone using bonjour, bonsoir, salut', 'Say goodbye with au revoir, à bientôt', "Use merci, s'il vous plaît, pardon", 'Distinguish tu and vous'],
                vocabulary=[
                    VocabItem(fr='Bonjour', en='Hello / Good morning', ipa='/bɔ̃.ʒuʁ/', example='Bonjour, comment ça va ?', category='greetings'),
                    VocabItem(fr='Bonsoir', en='Good evening', ipa='/bɔ̃.swaʁ/', example='Bonsoir, madame.', category='greetings'),
                    VocabItem(fr='Salut', en='Hi / Bye (informal)', ipa='/sa.ly/', example='Salut Marie !', category='greetings'),
                    VocabItem(fr='Au revoir', en='Goodbye', ipa='/o.ʁə.vwaʁ/', example='Au revoir, à demain !', category='greetings'),
                    VocabItem(fr='À bientôt', en='See you soon', ipa='/a.bjɛ̃.to/', example='Merci, à bientôt !', category='greetings'),
                    VocabItem(fr='Bonne nuit', en='Good night', ipa='/bɔn.nɥi/', example='Bonne nuit, fais de beaux rêves.', category='greetings'),
                    VocabItem(fr='Merci', en='Thank you', ipa='/mɛʁ.si/', example='Merci beaucoup !', category='politeness'),
                    VocabItem(fr='De rien', en="You're welcome", ipa='/də.ʁjɛ̃/', example='— Merci ! — De rien !', category='politeness'),
                    VocabItem(fr="S'il vous plaît", en='Please (formal)', ipa='/sil.vu.plɛ/', example="Un café, s'il vous plaît.", category='politeness'),
                    VocabItem(fr='Pardon', en='Excuse me / Sorry', ipa='/paʁ.dɔ̃/', example='Pardon, où sont les toilettes ?', category='politeness'),
                    VocabItem(fr='Monsieur', en='Sir / Mr.', ipa='/mə.sjø/', example='Bonjour, monsieur.', category='titles'),
                    VocabItem(fr='Madame', en='Madam / Mrs.', ipa='/ma.dam/', example='Bonjour, madame.', category='titles'),
                    VocabItem(fr='Oui', en='Yes', ipa='/wi/', example="Oui, je suis d'accord.", category='basics'),
                    VocabItem(fr='Non', en='No', ipa='/nɔ̃/', example='Non, merci.', category='basics'),
                ],
                grammar=[
                    GrammarRule(title='Tu vs. Vous', explanation="French has two words for 'you'. Use 'tu' with friends/family. Use 'vous' with strangers/professionals.", examples=[GrammarExample(fr='Tu es étudiant ?', en='Are you a student? (friend)'), GrammarExample(fr='Vous êtes étudiant ?', en='Are you a student? (formal)')]),
                    GrammarRule(title='Time-based greetings', explanation="'Bonjour' from morning to ~6PM. 'Bonsoir' in the evening. 'Bonne nuit' only at bedtime.", examples=[GrammarExample(fr='Bonjour ! (morning)', en='Hello'), GrammarExample(fr='Bonsoir ! (evening)', en='Good evening'), GrammarExample(fr='Bonne nuit ! (bedtime)', en='Good night')]),
                ],
                conjugation=ConjugationData(verbs=[ConjugationVerb(infinitive='être', translation='to be', tense='Présent', conjugations=[{'pronoun': 'je', 'form': 'suis'}, {'pronoun': 'tu', 'form': 'es'}, {'pronoun': 'il/elle', 'form': 'est'}, {'pronoun': 'nous', 'form': 'sommes'}, {'pronoun': 'vous', 'form': 'êtes'}, {'pronoun': 'ils/elles', 'form': 'sont'}], sentenceRule='Subject + être + adjective/noun/profession.', sentenceExamples=[GrammarExample(fr='Je suis étudiant.', en='I am a student.'), GrammarExample(fr='Tu es français ?', en='Are you French?')])]),
                dialogue=[
                    DialogueLine(speaker='A', name='Thomas', fr="Bonjour ! Je m'appelle Thomas. Et vous ?", en='Hello! My name is Thomas. And you?'),
                    DialogueLine(speaker='B', name='Sophie', fr="Bonjour, monsieur. Je m'appelle Sophie.", en='Hello, sir. My name is Sophie.'),
                    DialogueLine(speaker='A', name='Thomas', fr='Enchanté ! Vous êtes française ?', en='Nice to meet you! Are you French?'),
                    DialogueLine(speaker='B', name='Sophie', fr='Oui, je suis française. Et vous ?', en='Yes, I am French. And you?'),
                    DialogueLine(speaker='A', name='Thomas', fr="Moi, je suis canadien. J'habite à Montréal.", en='Me, I am Canadian. I live in Montreal.'),
                    DialogueLine(speaker='B', name='Sophie', fr='Au revoir, monsieur. À bientôt !', en='Goodbye, sir. See you soon!'),
                ],
                exercises=[
                    Exercise(id='a1-u0-l1-e1', type='multiple_choice', prompt='What is the polite way to greet a stranger in the morning?', options=['Salut', 'Bonjour', 'Bonne nuit', 'Au revoir'], answer=1),
                    Exercise(id='a1-u0-l1-e2', type='multiple_choice', prompt='Which pronoun do you use to address your best friend?', options=['Vous', 'Tu', 'Il', 'Nous'], answer=1),
                    Exercise(id='a1-u0-l1-e3', type='true_false', prompt='"Bonsoir" is used to greet someone in the evening.', options=['True', 'False'], answer=0),
                    Exercise(id='a1-u0-l1-e4', type='translate_to_fr', prompt='Translate: "Thank you very much."', answer='Merci beaucoup', acceptable=['merci beaucoup']),
                    Exercise(id='a1-u0-l1-e5', type='fill_blank', prompt='Complete: "_____ nuit, fais de beaux rêves."', answer='Bonne'),
                ],
                activities=[
                    Exercise(id='a1-u0-l1-a1', type='word_bank', prompt='Build: "Hello, my name is Marie."', wordBank=['Bonjour', 'je', "m'appelle", 'Marie', 'merci'], answer="Bonjour je m'appelle Marie"),
                    Exercise(id='a1-u0-l1-a2', type='dictation', prompt='Listen and type what you hear.', audioText='Bonjour, comment ça va ?', answer='Bonjour, comment ça va ?', acceptable=['bonjour comment ca va']),
                ],
                culturalNote="In France, it is impolite to enter a shop without saying 'Bonjour' first.",
                estimatedMinutes=30),
            Lesson(id='a1-u0-l2', title='The Alphabet and Spelling', titleFr='Épeler',
                description='Learn the French alphabet and how to spell your name.',
                objectives=['Recite the French alphabet', 'Spell your name', "Use \"Comment ça s'écrit ?\""],
                vocabulary=[
                    VocabItem(fr='G (jé)', en='G (zhay sound)', example='G comme Gabriel', category='alphabet'),
                    VocabItem(fr='J (ji)', en='J (zhgee sound)', example='J comme Julien', category='alphabet'),
                    VocabItem(fr='R (erre)', en='R (gargled)', example='R comme Robert', category='alphabet'),
                    VocabItem(fr='U (u)', en='U (tight, rounded)', example='U comme Ursule', category='alphabet'),
                    VocabItem(fr="Comment ça s'écrit ?", en='How is it spelled?', category='spelling'),
                ],
                grammar=[GrammarRule(title='The French alphabet', explanation="26 letters, same as English, but pronounced differently. G=/ʒe/, J=/ʒi/, R=gargled, U=tight rounded.", examples=[GrammarExample(fr='G = /ʒe/', en='Same as English soft G')])],
                dialogue=[
                    DialogueLine(speaker='A', name='Réceptionniste', fr="Comment ça s'écrit, votre nom ?", en='How is your name spelled?'),
                    DialogueLine(speaker='B', name='Client', fr="Ça s'écrit L-E-C-L-E-R-C.", en="It's spelled L-E-C-L-E-R-C."),
                    DialogueLine(speaker='A', name='Réceptionniste', fr='Pardon, vous pouvez répéter ?', en='Sorry, can you repeat?'),
                    DialogueLine(speaker='B', name='Client', fr='L comme Louis, E, C comme Céline, L, E, R, C.', en='L as in Louis, E, C as in Céline, L, E, R, C.'),
                ],
                exercises=[
                    Exercise(id='a1-u0-l2-e1', type='multiple_choice', prompt='How is the letter "G" pronounced in French?', options=['Like English G', 'Like "zhay"', 'Like "jay"', 'Like "gee"'], answer=1),
                    Exercise(id='a1-u0-l2-e2', type='multiple_choice', prompt='What does "Comment ça s\'écrit ?" mean?', options=['How do you say it?', 'How is it spelled?', 'What does it mean?'], answer=1),
                ],
                culturalNote="The Académie française, founded in 1635, is the official authority on the French language.",
                estimatedMinutes=30),
            Lesson(id='a1-u0-l3', title='Numbers 0–20', titleFr='Compter',
                description='Learn to count from 0 to 20 in French.',
                objectives=['Count from 0 to 20', 'Express age with avoir'],
                vocabulary=[
                    VocabItem(fr='zéro', en='zero', category='numbers'), VocabItem(fr='un', en='one', category='numbers'),
                    VocabItem(fr='deux', en='two', category='numbers'), VocabItem(fr='trois', en='three', category='numbers'),
                    VocabItem(fr='quatre', en='four', category='numbers'), VocabItem(fr='cinq', en='five', category='numbers'),
                    VocabItem(fr='six', en='six', category='numbers'), VocabItem(fr='sept', en='seven', category='numbers'),
                    VocabItem(fr='huit', en='eight', category='numbers'), VocabItem(fr='neuf', en='nine', category='numbers'),
                    VocabItem(fr='dix', en='ten', category='numbers'), VocabItem(fr='onze', en='eleven', category='numbers'),
                    VocabItem(fr='douze', en='twelve', category='numbers'), VocabItem(fr='treize', en='thirteen', category='numbers'),
                    VocabItem(fr='quatorze', en='fourteen', category='numbers'), VocabItem(fr='quinze', en='fifteen', category='numbers'),
                    VocabItem(fr='seize', en='sixteen', category='numbers'), VocabItem(fr='dix-sept', en='seventeen', category='numbers'),
                    VocabItem(fr='dix-huit', en='eighteen', category='numbers'), VocabItem(fr='dix-neuf', en='nineteen', category='numbers'),
                    VocabItem(fr='vingt', en='twenty', category='numbers'),
                ],
                grammar=[GrammarRule(title='Numbers 0–20', explanation='Essential for prices, ages, phone numbers.', examples=[GrammarExample(fr="J'ai vingt ans.", en='I am twenty years old.')])],
                conjugation=ConjugationData(verbs=[ConjugationVerb(infinitive='avoir', translation='to have', tense='Présent', conjugations=[{'pronoun': "j'", 'form': 'ai'}, {'pronoun': 'tu', 'form': 'as'}, {'pronoun': 'il/elle', 'form': 'a'}, {'pronoun': 'nous', 'form': 'avons'}, {'pronoun': 'vous', 'form': 'avez'}, {'pronoun': 'ils/elles', 'form': 'ont'}], sentenceRule="Subject + avoir + noun. Used for possession, age (J'ai 20 ans).")]),
                dialogue=[
                    DialogueLine(speaker='A', name='Lucas', fr='Tu as quel âge ?', en='How old are you?'),
                    DialogueLine(speaker='B', name='Mia', fr="J'ai dix-huit ans. Et toi ?", en='I am eighteen. And you?'),
                    DialogueLine(speaker='A', name='Lucas', fr="Moi, j'ai vingt ans.", en='Me, I am twenty.'),
                ],
                exercises=[
                    Exercise(id='a1-u0-l3-e1', type='multiple_choice', prompt='How do you say "15" in French?', options=['quatorze', 'quinze', 'seize', 'treize'], answer=1),
                    Exercise(id='a1-u0-l3-e2', type='fill_blank', prompt='Complete: "J\'ai _____ ans." (I am 20 years old.)', answer='vingt'),
                    Exercise(id='a1-u0-l3-e3', type='true_false', prompt='"Dix-neuf" means 19.', options=['True', 'False'], answer=0),
                ],
                estimatedMinutes=25),
            Lesson(id='a1-u0-l4', title='France and the Francophone World', titleFr='La France et la francophonie',
                description='Discover France, French-speaking countries, and basic nationalities.',
                objectives=['Name major French-speaking countries', 'Say your nationality with être', 'Use prepositions with countries'],
                vocabulary=[
                    VocabItem(fr='la France', en='France', example='Je vis en France.', category='countries'),
                    VocabItem(fr='le Canada', en='Canada', example='Il habite au Canada.', category='countries'),
                    VocabItem(fr='la Belgique', en='Belgium', category='countries'),
                    VocabItem(fr='la Suisse', en='Switzerland', category='countries'),
                    VocabItem(fr='le Maroc', en='Morocco', category='countries'),
                    VocabItem(fr='français(e)', en='French', example='Je suis français.', category='nationalities'),
                    VocabItem(fr='la francophonie', en='the French-speaking world', category='culture'),
                ],
                grammar=[
                    GrammarRule(title='Prepositions with countries', explanation="Feminine countries: en. Masculine: au. Plural: aux.", examples=[GrammarExample(fr='en France, en Italie', en='Feminine: en'), GrammarExample(fr='au Canada, au Maroc', en='Masculine: au')]),
                    GrammarRule(title='Nationality adjectives', explanation="Agree with gender. Add -e for feminine. NOT capitalized.", examples=[GrammarExample(fr='Il est français. Elle est française.', en='He is French. She is French.')]),
                ],
                dialogue=[
                    DialogueLine(speaker='A', name='Léa', fr="Tu viens d'où ?", en='Where are you from?'),
                    DialogueLine(speaker='B', name='Karim', fr='Je viens du Maroc. Et toi ?', en="I'm from Morocco. And you?"),
                    DialogueLine(speaker='A', name='Léa', fr="Moi, je suis belge. J'habite à Bruxelles.", en="Me, I'm Belgian. I live in Brussels."),
                ],
                exercises=[
                    Exercise(id='a1-u0-l4-e1', type='multiple_choice', prompt='Which preposition: "Je vais _____ France."', options=['au', 'en', 'aux', 'à la'], answer=1),
                    Exercise(id='a1-u0-l4-e2', type='fill_blank', prompt='Complete: "Je suis _____ ." (French, female)', answer='française', acceptable=['francaise']),
                ],
                culturalNote="French is the official language in 29 countries — second only to English.",
                estimatedMinutes=30),
        ]),
    # UNIT 1
    Unit(
        id='a1-u1', title='Get in Touch', titleFr='Unité 1 — Entrez en contact !',
        theme='Introducing yourself and exchanging information', description='Learn to introduce yourself, exchange personal information, and communicate in the classroom.',
        lessons=[
            Lesson(id='a1-u1-l1', title='Introducing Yourself', titleFr='Se présenter',
                description='Introduce yourself with name, nationality, profession, and the verb être.',
                objectives=['Conjugate être in present', 'Say your name, nationality, profession', 'Use subject pronouns'],
                vocabulary=[
                    VocabItem(fr='je suis', en='I am', category='verbs'), VocabItem(fr='tu es', en='you are', category='verbs'),
                    VocabItem(fr='il est', en='he is', category='verbs'), VocabItem(fr='elle est', en='she is', category='verbs'),
                    VocabItem(fr='nous sommes', en='we are', category='verbs'), VocabItem(fr='vous êtes', en='you are (formal)', category='verbs'),
                    VocabItem(fr='un étudiant', en='a student (m)', category='professions'),
                    VocabItem(fr='un professeur', en='a teacher (m)', category='professions'),
                    VocabItem(fr='un médecin', en='a doctor', category='professions'),
                    VocabItem(fr='Enchanté(e)', en='Nice to meet you', category='politeness'),
                ],
                grammar=[
                    GrammarRule(title='The verb être — to be', explanation="Irregular verb used for identity, nationality, profession, location. Professions take NO article.", examples=[GrammarExample(fr='Je suis français.', en='I am French.'), GrammarExample(fr='Il est médecin.', en='He is a doctor.')]),
                    GrammarRule(title='Subject pronouns', explanation='je, tu, il/elle, nous, vous, ils/elles', examples=[GrammarExample(fr='Je suis étudiant.', en='I am a student.')]),
                ],
                conjugation=ConjugationData(verbs=[ConjugationVerb(infinitive='être', translation='to be', tense='Présent', conjugations=[{'pronoun': 'je', 'form': 'suis'}, {'pronoun': 'tu', 'form': 'es'}, {'pronoun': 'il/elle', 'form': 'est'}, {'pronoun': 'nous', 'form': 'sommes'}, {'pronoun': 'vous', 'form': 'êtes'}, {'pronoun': 'ils/elles', 'form': 'sont'}])]),
                dialogue=[
                    DialogueLine(speaker='A', name='Marc', fr="Bonjour, je m'appelle Marc. Et vous ?", en='Hello, my name is Marc. And you?'),
                    DialogueLine(speaker='B', name='Anna', fr="Bonjour. Je m'appelle Anna.", en='Hello. My name is Anna.'),
                    DialogueLine(speaker='A', name='Marc', fr='Enchanté ! Vous êtes étudiante ?', en='Nice to meet you! Are you a student?'),
                    DialogueLine(speaker='B', name='Anna', fr='Oui, je suis étudiante. Et vous ?', en='Yes, I am a student. And you?'),
                    DialogueLine(speaker='A', name='Marc', fr='Je suis professeur.', en='I am a teacher.'),
                ],
                exercises=[
                    Exercise(id='a1-u1-l1-e1', type='multiple_choice', prompt='What is the correct form: "Je _____ étudiant."', options=['es', 'est', 'suis', 'sommes'], answer=2),
                    Exercise(id='a1-u1-l1-e2', type='conjugation', prompt='Conjugate "être" for "tu":', answer='es', acceptable=['es']),
                    Exercise(id='a1-u1-l1-e3', type='fill_blank', prompt='Complete: "Elle _____ française."', answer='est'),
                ],
                estimatedMinutes=35),
            Lesson(id='a1-u1-l2', title='Personal Information', titleFr='Échanger des informations',
                description='Exchange contact information, express age, and make negative sentences.',
                objectives=['Give your email, phone, address', 'Express age with avoir', 'Use ne...pas negation'],
                vocabulary=[
                    VocabItem(fr="J'ai ___ ans", en='I am ___ years old', category='expressions'),
                    VocabItem(fr="C'est mon adresse e-mail", en="It's my email address", category='contact'),
                    VocabItem(fr='mon numéro de téléphone', en='my phone number', category='contact'),
                    VocabItem(fr="Je n'ai pas", en="I don't have", category='negation'),
                ],
                grammar=[
                    GrammarRule(title='The verb avoir — to have', explanation='Used for possession, age, and expressions (avoir faim, avoir soif).', examples=[GrammarExample(fr="J'ai vingt ans.", en='I am twenty.'), GrammarExample(fr="J'ai un frère.", en='I have a brother.')]),
                    GrammarRule(title='Negative sentences', explanation='ne + verb + pas', examples=[GrammarExample(fr="Je ne parle pas français.", en="I don't speak French."), GrammarExample(fr="Il n'a pas de voiture.", en="He doesn't have a car.")]),
                ],
                dialogue=[
                    DialogueLine(speaker='A', name='Camille', fr='Tu as quel âge ?', en='How old are you?'),
                    DialogueLine(speaker='B', name='Léa', fr="J'ai vingt-deux ans.", en='I am twenty-two.'),
                    DialogueLine(speaker='A', name='Camille', fr="C'est quoi ton adresse e-mail ?", en="What's your email?"),
                    DialogueLine(speaker='B', name='Léa', fr="C'est lea@email.com.", en="It's lea@email.com."),
                ],
                exercises=[
                    Exercise(id='a1-u1-l2-e1', type='fill_blank', prompt='Complete: "J\'_____ vingt ans."', answer='ai'),
                    Exercise(id='a1-u1-l2-e2', type='translate_to_fr', prompt='Translate: "I don\'t have a car."', answer="Je n'ai pas de voiture", acceptable=["je n ai pas de voiture"]),
                ],
                estimatedMinutes=35),
            Lesson(id='a1-u1-l3', title='In the Classroom', titleFr='Communiquer en classe',
                description='Name classroom objects, understand instructions, learn gender of nouns.',
                objectives=['Name classroom objects', 'Understand teacher instructions', 'Learn masculine/feminine'],
                vocabulary=[
                    VocabItem(fr='le cahier', en='notebook', category='classroom'), VocabItem(fr='le stylo', en='pen', category='classroom'),
                    VocabItem(fr='le livre', en='book', category='classroom'), VocabItem(fr='la table', en='table', category='classroom'),
                    VocabItem(fr='la chaise', en='chair', category='classroom'), VocabItem(fr='le tableau', en='board', category='classroom'),
                    VocabItem(fr='le professeur', en='teacher', category='people'), VocabItem(fr="l'élève", en='student', category='people'),
                ],
                grammar=[
                    GrammarRule(title='Gender of nouns', explanation='Masculine (le) and feminine (la). Learn with the article.', examples=[GrammarExample(fr='le cahier (m)', en='the notebook'), GrammarExample(fr='la table (f)', en='the table')]),
                    GrammarRule(title='Definite and indefinite articles', explanation='le/la/les (the) vs un/une/des (a/some)', examples=[GrammarExample(fr='le livre', en='the book'), GrammarExample(fr='un stylo', en='a pen')]),
                ],
                dialogue=[
                    DialogueLine(speaker='A', name='Professeur', fr='Ouvrez vos cahiers, s\'il vous plaît.', en='Open your notebooks, please.'),
                    DialogueLine(speaker='B', name='Élève', fr='Professeur, je n\'ai pas de stylo.', en="Teacher, I don't have a pen."),
                    DialogueLine(speaker='A', name='Professeur', fr='Prenez celui-ci.', en='Take this one.'),
                ],
                exercises=[
                    Exercise(id='a1-u1-l3-e1', type='multiple_choice', prompt='Is "la chaise" masculine or feminine?', options=['Masculine', 'Feminine'], answer=1),
                    Exercise(id='a1-u1-l3-e2', type='article_choice', prompt='Choose: _____ cahier', options=['le', 'la', 'les', 'un'], answer=0),
                ],
                estimatedMinutes=35),
            Lesson(id='a1-u1-l4', title='Asking Questions', titleFr='Poser des questions',
                description='Learn three ways to ask questions in French.',
                objectives=['Ask questions with intonation', 'Use est-ce que', 'Use inversion'],
                vocabulary=[
                    VocabItem(fr='qui', en='who', category='question words'), VocabItem(fr='que', en='what', category='question words'),
                    VocabItem(fr='où', en='where', category='question words'), VocabItem(fr='quand', en='when', category='question words'),
                    VocabItem(fr='comment', en='how', category='question words'), VocabItem(fr='pourquoi', en='why', category='question words'),
                    VocabItem(fr='combien', en='how many/much', category='question words'),
                ],
                grammar=[
                    GrammarRule(title='Three ways to ask questions', explanation='1. Intonation (voice goes up)\n2. Est-ce que\n3. Inversion (formal)', examples=[GrammarExample(fr='Tu es français ? (intonation)', en='Are you French?'), GrammarExample(fr='Est-ce que tu es français ? (est-ce que)', en='Are you French?'), GrammarExample(fr='Es-tu français ? (inversion)', en='Are you French? (formal)')]),
                ],
                dialogue=[
                    DialogueLine(speaker='A', name='Paul', fr='Comment tu t\'appelles ?', en='What is your name?'),
                    DialogueLine(speaker='B', name='Anna', fr="Je m'appelle Anna.", en='My name is Anna.'),
                    DialogueLine(speaker='A', name='Paul', fr='D\'où viens-tu ?', en='Where are you from?'),
                    DialogueLine(speaker='B', name='Anna', fr='Je viens d\'Italie.', en='I come from Italy.'),
                    DialogueLine(speaker='A', name='Paul', fr='Tu parles français ?', en='Do you speak French?'),
                    DialogueLine(speaker='B', name='Anna', fr='Oui, je parle un peu français.', en='Yes, I speak a little French.'),
                ],
                exercises=[
                    Exercise(id='a1-u1-l4-e1', type='multiple_choice', prompt='Which question word means "where"?', options=['qui', 'où', 'comment', 'pourquoi'], answer=1),
                    Exercise(id='a1-u1-l4-e2', type='translate_to_fr', prompt='Translate: "Where are you from?"', answer="D'où viens-tu ?", acceptable=["d'où viens-tu", "d ou viens-tu"]),
                ],
                estimatedMinutes=35),
        ]),
    # UNIT 2
    Unit(
        id='a1-u2', title='Get to Know Each Other', titleFr='Unité 2 — Faites connaissance !',
        theme='Family, descriptions, and tastes', description='Talk about your family, describe people, and express likes and dislikes.',
        lessons=[
            Lesson(id='a1-u2-l1', title='My Family', titleFr='Parler de la famille',
                description='Learn family vocabulary and possessive adjectives.',
                objectives=['Name family members', 'Use possessive adjectives'],
                vocabulary=[
                    VocabItem(fr='le père', en='father', category='family'), VocabItem(fr='la mère', en='mother', category='family'),
                    VocabItem(fr='le frère', en='brother', category='family'), VocabItem(fr='la sœur', en='sister', category='family'),
                    VocabItem(fr='le fils', en='son', category='family'), VocabItem(fr='la fille', en='daughter', category='family'),
                    VocabItem(fr='le grand-père', en='grandfather', category='family'), VocabItem(fr='la grand-mère', en='grandmother', category='family'),
                    VocabItem(fr='mon/ma/mes', en='my', category='possessives'), VocabItem(fr='ton/ta/tes', en='your (informal)', category='possessives'),
                    VocabItem(fr='son/sa/ses', en='his/her/its', category='possessives'),
                ],
                grammar=[GrammarRule(title='Possessive adjectives', explanation='Agree with the GENDER of the NOUN, not the owner.', examples=[GrammarExample(fr='mon père (m)', en='my father'), GrammarExample(fr='ma mère (f)', en='my mother'), GrammarExample(fr='mes frères (pl)', en='my brothers')])],
                dialogue=[
                    DialogueLine(speaker='A', name='Hugo', fr='Tu as des frères et sœurs ?', en='Do you have brothers and sisters?'),
                    DialogueLine(speaker='B', name='Emma', fr='Oui, j\'ai un frère et deux sœurs.', en='Yes, I have a brother and two sisters.'),
                    DialogueLine(speaker='A', name='Hugo', fr='Et tes parents, ils habitent où ?', en='And your parents, where do they live?'),
                    DialogueLine(speaker='B', name='Emma', fr='Mes parents habitent à Lyon.', en='My parents live in Lyon.'),
                ],
                exercises=[
                    Exercise(id='a1-u2-l1-e1', type='multiple_choice', prompt='Which possessive for "mère" (feminine)?', options=['mon', 'ma', 'mes', 'sa'], answer=1),
                    Exercise(id='a1-u2-l1-e2', type='fill_blank', prompt='Complete: "_____ frère est grand."', answer='Mon', acceptable=['mon']),
                ],
                estimatedMinutes=30),
            Lesson(id='a1-u2-l2', title='Describing People', titleFr='Décrire une personne',
                description='Describe physical appearance and personality.',
                objectives=['Use adjectives for appearance', 'Understand adjective agreement'],
                vocabulary=[
                    VocabItem(fr='grand(e)', en='tall/big', category='physical'), VocabItem(fr='petit(e)', en='short/small', category='physical'),
                    VocabItem(fr='blond(e)', en='blond', category='physical'), VocabItem(fr='brun(e)', en='brown-haired', category='physical'),
                    VocabItem(fr='sympa', en='nice/friendly', category='personality'), VocabItem(fr='drôle', en='funny', category='personality'),
                    VocabItem(fr='intelligent(e)', en='intelligent', category='personality'), VocabItem(fr='gentil(le)', en='kind', category='personality'),
                    VocabItem(fr='timide', en='shy', category='personality'),
                ],
                grammar=[GrammarRule(title='Adjective agreement', explanation='Adjectives agree in gender and number with the noun. Add -e for feminine, -s for plural.', examples=[GrammarExample(fr='Il est grand. Elle est grande.', en='He is tall. She is tall.'), GrammarExample(fr='Ils sont grands. Elles sont grandes.', en='They are tall.')])],
                dialogue=[
                    DialogueLine(speaker='A', name='Léa', fr='Comment est ton frère ?', en='What is your brother like?'),
                    DialogueLine(speaker='B', name='Tom', fr='Il est grand et blond. Il est très sympa.', en='He is tall and blond. He is very nice.'),
                ],
                exercises=[
                    Exercise(id='a1-u2-l2-e1', type='fill_blank', prompt='Complete: "Elle est _____ ." (tall, feminine)', answer='grande'),
                    Exercise(id='a1-u2-l2-e2', type='matching', prompt='Match French to English.', pairs=[{'left': 'grand', 'right': 'tall'}, {'left': 'sympa', 'right': 'nice'}, {'left': 'timide', 'right': 'shy'}], answer={}),
                ],
                estimatedMinutes=30),
            Lesson(id='a1-u2-l3', title='Likes and Dislikes', titleFr='Échanger sur vos goûts',
                description='Express what you like and dislike with aimer, adorer, détester.',
                objectives=['Use aimer/adorer/détester', 'Talk about hobbies and food'],
                vocabulary=[
                    VocabItem(fr='aimer', en='to like/love', category='verbs'), VocabItem(fr='adorer', en='to love/adore', category='verbs'),
                    VocabItem(fr='détester', en='to hate', category='verbs'),
                    VocabItem(fr='le chocolat', en='chocolate', category='food'), VocabItem(fr='le café', en='coffee', category='food'),
                    VocabItem(fr='le sport', en='sports', category='hobbies'), VocabItem(fr='la musique', en='music', category='hobbies'),
                    VocabItem(fr='le cinéma', en='cinema', category='hobbies'), VocabItem(fr='lire', en='to read', category='hobbies'),
                    VocabItem(fr='voyager', en='to travel', category='hobbies'), VocabItem(fr='cuisiner', en='to cook', category='hobbies'),
                ],
                grammar=[GrammarRule(title='Regular -er verbs (aimer)', explanation='Drop -er and add: -e, -es, -e, -ons, -ez, -ent', examples=[GrammarExample(fr="J'aime le chocolat.", en='I like chocolate.'), GrammarExample(fr='Nous aimons voyager.', en='We like to travel.')])],
                dialogue=[
                    DialogueLine(speaker='A', name='Sarah', fr='Tu aimes le sport ?', en='Do you like sports?'),
                    DialogueLine(speaker='B', name='Marc', fr="Oui, j'adore le tennis. Et toi ?", en='Yes, I love tennis. And you?'),
                    DialogueLine(speaker='A', name='Sarah', fr="J'aime la musique, mais je déteste le sport.", en='I like music, but I hate sports.'),
                ],
                exercises=[
                    Exercise(id='a1-u2-l3-e1', type='conjugation', prompt='Conjugate aimer for "je":', answer="j'aime", acceptable=["j'aime", "j aime"]),
                    Exercise(id='a1-u2-l3-e2', type='translate_to_fr', prompt='Translate: "I love travel."', answer='J\'adore voyager', acceptable=["j adore voyager"]),
                ],
                estimatedMinutes=30),
            Lesson(id='a1-u2-l4', title='Regular -er Verbs', titleFr='Les verbes en -er',
                description='Master regular -er verb conjugation with common verbs.',
                objectives=['Conjugate regular -er verbs', 'Understand spelling changes'],
                vocabulary=[
                    VocabItem(fr='parler', en='to speak', category='verbs'), VocabItem(fr='habiter', en='to live', category='verbs'),
                    VocabItem(fr='travailler', en='to work', category='verbs'), VocabItem(fr='manger', en='to eat', category='verbs'),
                    VocabItem(fr='étudier', en='to study', category='verbs'), VocabItem(fr='écouter', en='to listen', category='verbs'),
                    VocabItem(fr='regarder', en='to watch', category='verbs'), VocabItem(fr='jouer', en='to play', category='verbs'),
                    VocabItem(fr='danser', en='to dance', category='verbs'), VocabItem(fr='chanter', en='to sing', category='verbs'),
                ],
                grammar=[GrammarRule(title='Regular -er verb pattern', explanation='Drop -er, add endings: -e, -es, -e, -ons, -ez, -ent', examples=[GrammarExample(fr='je parle, tu parles, il parle', en='I speak, you speak, he speaks'), GrammarExample(fr='nous parlons, vous parlez, ils parlent', en='we speak, you speak, they speak')])],
                dialogue=[
                    DialogueLine(speaker='A', name='Sophie', fr='Qu\'est-ce que tu fais le week-end ?', en='What do you do on weekends?'),
                    DialogueLine(speaker='B', name='Luc', fr='J\'habite à Paris. Je travaille et j\'étudie.', en='I live in Paris. I work and I study.'),
                    DialogueLine(speaker='A', name='Sophie', fr='Tu parles français ?', en='Do you speak French?'),
                    DialogueLine(speaker='B', name='Luc', fr='Oui, je parle un peu français.', en='Yes, I speak a little French.'),
                ],
                exercises=[
                    Exercise(id='a1-u2-l4-e1', type='conjugation', prompt='Conjugate parler for "nous":', answer='parlons', acceptable=['parlons']),
                    Exercise(id='a1-u2-l4-e2', type='fill_blank', prompt='Complete: "Ils _____ français." (speak)', answer='parlent'),
                ],
                estimatedMinutes=30),
        ]),
    # UNIT 3
    Unit(
        id='a1-u3', title='Daily Life', titleFr='Unité 3 — Au quotidien',
        theme='Time, routine, and going out', description='Tell time, talk about your routine, and make suggestions.',
        lessons=[
            Lesson(id='a1-u3-l1', title='Telling Time', titleFr='Quelle heure est-il ?',
                description='Tell time in French using 12h and 24h systems.',
                objectives=['Ask and tell the time', 'Use time expressions'],
                vocabulary=[
                    VocabItem(fr='Quelle heure est-il ?', en='What time is it?', category='time'), VocabItem(fr="Il est une heure", en="It's one o'clock", category='time'),
                    VocabItem(fr='et demie', en='half past', category='time'), VocabItem(fr='et quart', en='quarter past', category='time'),
                    VocabItem(fr='moins le quart', en='quarter to', category='time'), VocabItem(fr='midi', en='noon', category='time'),
                    VocabItem(fr='minuit', en='midnight', category='time'), VocabItem(fr='le matin', en='in the morning', category='time'),
                    VocabItem(fr="l'après-midi", en='in the afternoon', category='time'), VocabItem(fr='le soir', en='in the evening', category='time'),
                ],
                grammar=[GrammarRule(title='Telling time', explanation="Il est + hour. Use 12h (une heure) or 24h (treize heures) systems.", examples=[GrammarExample(fr="Il est trois heures.", en="It's 3 o'clock."), GrammarExample(fr="Il est trois heures et demie.", en="It's 3:30.")])],
                dialogue=[
                    DialogueLine(speaker='A', name='Sarah', fr='Quelle heure est-il ?', en='What time is it?'),
                    DialogueLine(speaker='B', name='Marc', fr="Il est quinze heures trente.", en="It's 3:30 PM."),
                ],
                exercises=[
                    Exercise(id='a1-u3-l1-e1', type='multiple_choice', prompt='What time is "Il est midi"?', options=['12:00 AM', '12:00 PM', '6:00 PM', '9:00 AM'], answer=1),
                ],
                estimatedMinutes=25),
            Lesson(id='a1-u3-l2', title='The Verb aller', titleFr='Le verbe aller',
                description='Learn the verb aller (to go) and the near future.',
                objectives=['Conjugate aller', 'Use aller + infinitive for future', 'Use prepositions with places'],
                vocabulary=[
                    VocabItem(fr='je vais', en='I go / I am going', category='verbs'), VocabItem(fr='tu vas', en='you go', category='verbs'),
                    VocabItem(fr='il/elle va', en='he/she goes', category='verbs'), VocabItem(fr='nous allons', en='we go', category='verbs'),
                    VocabItem(fr='vous allez', en='you go (formal)', category='verbs'), VocabItem(fr='ils/elles vont', en='they go', category='verbs'),
                ],
                grammar=[
                    GrammarRule(title='The verb aller', explanation='Irregular verb meaning "to go". Used for movement and near future (aller + infinitive).', examples=[GrammarExample(fr='Je vais à Paris.', en='I am going to Paris.'), GrammarExample(fr='Je vais manger.', en='I am going to eat.')]),
                    GrammarRule(title='Prepositions with places', explanation='à + city. au (à + le) for masculine countries. à la for feminine. aux for plural.', examples=[GrammarExample(fr='à Paris', en='to Paris'), GrammarExample(fr='au Japon', en='to Japan'), GrammarExample(fr='en France', en='to France')]),
                ],
                conjugation=ConjugationData(verbs=[ConjugationVerb(infinitive='aller', translation='to go', tense='Présent', conjugations=[{'pronoun': 'je', 'form': 'vais'}, {'pronoun': 'tu', 'form': 'vas'}, {'pronoun': 'il/elle', 'form': 'va'}, {'pronoun': 'nous', 'form': 'allons'}, {'pronoun': 'vous', 'form': 'allez'}, {'pronoun': 'ils/elles', 'form': 'vont'}])]),
                dialogue=[
                    DialogueLine(speaker='A', name='Léa', fr='Qu\'est-ce que tu vas faire ce week-end ?', en='What are you going to do this weekend?'),
                    DialogueLine(speaker='B', name='Marc', fr='Je vais aller au cinéma.', en='I am going to go to the cinema.'),
                    DialogueLine(speaker='A', name='Léa', fr='Super ! Je vais aller au parc.', en='Great! I am going to go to the park.'),
                ],
                exercises=[
                    Exercise(id='a1-u3-l2-e1', type='conjugation', prompt='Conjugate aller for "je":', answer='vais', acceptable=['vais']),
                    Exercise(id='a1-u3-l2-e2', type='fill_blank', prompt='Complete: "Nous _____ au cinéma."', answer='allons'),
                ],
                estimatedMinutes=30),
            Lesson(id='a1-u3-l3', title='The Imperative', titleFr="L'impératif",
                description='Learn to give commands and instructions.',
                objectives=['Form the imperative', 'Give commands', 'Use irregular imperatives'],
                vocabulary=[
                    VocabItem(fr='Regarde !', en='Look!', category='commands'), VocabItem(fr='Écoute !', en='Listen!', category='commands'),
                    VocabItem(fr='Répète !', en='Repeat!', category='commands'), VocabItem(fr='Ouvre !', en='Open!', category='commands'),
                    VocabItem(fr='Ferme !', en='Close!', category='commands'), VocabItem(fr='Sois !', en='Be! (irregular)', category='commands'),
                ],
                grammar=[GrammarRule(title='The imperative mood', explanation='Drop the subject pronoun. For -er verbs, also drop the -s in tu form.', examples=[GrammarExample(fr='Tu parles → Parle !', en='Speak!'), GrammarExample(fr='Tu écoutes → Écoute !', en='Listen!')])],
                dialogue=[
                    DialogueLine(speaker='A', name='Mère', fr='Léa, ouvre ton cahier, s\'il te plaît.', en='Léa, open your notebook, please.'),
                    DialogueLine(speaker='B', name='Léa', fr='Oui, maman.', en='Yes, mom.'),
                    DialogueLine(speaker='A', name='Mère', fr='Maintenant, répète après moi.', en='Now, repeat after me.'),
                ],
                exercises=[
                    Exercise(id='a1-u3-l3-e1', type='fill_blank', prompt='Imperative of "parler" (tu): _____', answer='Parle', acceptable=['parle']),
                ],
                estimatedMinutes=25),
            Lesson(id='a1-u3-l4', title='Suggesting an Outing', titleFr='Proposer une sortie',
                description='Make suggestions and respond to them.',
                objectives=['Make suggestions with "on"', 'Accept or decline invitations', 'Know days of the week'],
                vocabulary=[
                    VocabItem(fr='On va...', en='We are going to...', category='suggestions'), VocabItem.fr='Tu veux... ?' if False else VocabItem(fr='Ça te dit ?', en='How about it?', category='suggestions'),
                    VocabItem(fr='D\'accord', en='OK / Agreed', category='responses'), VocabItem(fr='Avec plaisir', en='With pleasure', category='responses'),
                    VocabItem(fr='Désolé(e)', en='Sorry', category='responses'), VocabItem(fr='lundi', en='Monday', category='days'),
                    VocabItem(fr='mardi', en='Tuesday', category='days'), VocabItem(fr='mercredi', en='Wednesday', category='days'),
                    VocabItem(fr='jeudi', en='Thursday', category='days'), VocabItem(fr='vendredi', en='Friday', category='days'),
                    VocabItem(fr='samedi', en='Saturday', category='days'), VocabItem(fr='dimanche', en='Sunday', category='days'),
                ],
                grammar=[
                    GrammarRule(title='The pronoun "on"', explanation='On = we (informal). Very common in spoken French.', examples=[GrammarExample(fr='On va au cinéma ?', en='Shall we go to the cinema?')]),
                    GrammarRule(title='Days of the week', explanation='Not capitalized in French.', examples=[GrammarExample(fr='lundi, mardi, mercredi...', en='Monday, Tuesday, Wednesday...')]),
                ],
                dialogue=[
                    DialogueLine(speaker='A', name='Camille', fr='On va au cinéma samedi ?', en='Shall we go to the cinema Saturday?'),
                    DialogueLine(speaker='B', name='Lucas', fr='Avec plaisir ! Quel film ?', en='With pleasure! What movie?'),
                    DialogueLine(speaker='A', name='Camille', fr='On va voir un film français.', en='We are going to see a French movie.'),
                ],
                exercises=[
                    Exercise(id='a1-u3-l4-e1', type='multiple_choice', prompt='Which day is "vendredi"?', options=['Monday', 'Wednesday', 'Friday', 'Sunday'], answer=2),
                ],
                estimatedMinutes=30),
        ]),
    # UNIT 4
    Unit(
        id='a1-u4', title='At the Café', titleFr='Unité 4 — Au café',
        theme='Food, drinks, and ordering', description='Order at a café, learn about prices, and talk about food.',
        lessons=[
            Lesson(id='a1-u4-l1', title='Ordering at the Café', titleFr='Commander au café',
                description='Order drinks and food at a café using polite expressions.',
                objectives=['Order food and drinks', 'Use vouloir and prendre', 'Understand partitive articles'],
                vocabulary=[
                    VocabItem(fr='le café', en='coffee', category='drinks'), VocabItem(fr='le thé', en='tea', category='drinks'),
                    VocabItem(fr="le jus d'orange", en='orange juice', category='drinks'), VocabItem(fr='la bière', en='beer', category='drinks'),
                    VocabItem(fr='le croissant', en='croissant', category='food'), VocabItem(fr='le pain au chocolat', en='chocolate pastry', category='food'),
                    VocabItem(fr="l'addition", en='the bill', category='restaurant'), VocabItem(fr='je voudrais', en='I would like', category='restaurant'),
                    VocabItem(fr='je vais prendre', en='I am going to take', category='restaurant'), VocabItem(fr='sur place', en='here (to eat)', category='restaurant'),
                    VocabItem(fr='à emporter', en='to take away', category='restaurant'),
                ],
                grammar=[
                    GrammarRule(title='Partitive articles', explanation='du (m), de la (f), des (pl) — "some"', examples=[GrammarExample(fr='Je voudrais du café.', en='I would like some coffee.'), GrammarExample(fr='Je voudrais de la limonade.', en='I would like some lemonade.')]),
                    GrammarRule(title='The verb vouloir', explanation='To want. Irregular: je veux, tu veux, il veut, nous voulons, vous voulez, ils veulent.', examples=[GrammarExample(fr='Je voudrais un café.', en='I would like a coffee.')]),
                ],
                dialogue=[
                    DialogueLine(speaker='A', name='Serveur', fr='Bonjour, qu\'est-ce que vous prenez ?', en='Hello, what are you having?'),
                    DialogueLine(speaker='B', name='Client', fr='Je voudrais un café, s\'il vous plaît.', en='I would like a coffee, please.'),
                    DialogueLine(speaker='A', name='Serveur', fr='Et pour manger ?', en='And to eat?'),
                    DialogueLine(speaker='B', name='Client', fr='Un croissant, s\'il vous plaît.', en='A croissant, please.'),
                    DialogueLine(speaker='A', name='Serveur', fr='Très bien. Autre chose ?', en='Very well. Anything else?'),
                    DialogueLine(speaker='B', name='Client', fr='Non, c\'est tout. C\'est combien ?', en="No, that's all. How much is it?"),
                ],
                exercises=[
                    Exercise(id='a1-u4-l1-e1', type='multiple_choice', prompt='How do you say "I would like" politely?', options=['Je veux', 'Je voudrais', 'J\'ai besoin', 'Je prends'], answer=1),
                    Exercise(id='a1-u4-l1-e2', type='article_choice', prompt='Choose: "Je voudrais _____ café."', options=['du', 'de la', 'le', 'un'], answer=0),
                ],
                estimatedMinutes=35),
            Lesson(id='a1-u4-l2', title='Prices and Numbers 20–100', titleFr='Les prix et les nombres',
                description='Learn numbers 20-100 and ask about prices.',
                objectives=['Count from 20 to 100', 'Ask about prices', 'Understand the vigesimal system'],
                vocabulary=[
                    VocabItem(fr='vingt', en='twenty', category='numbers'), VocabItem(fr='trente', en='thirty', category='numbers'),
                    VocabItem(fr='quarante', en='forty', category='numbers'), VocabItem(fr='cinquante', en='fifty', category='numbers'),
                    VocabItem(fr='soixante', en='sixty', category='numbers'), VocabItem(fr='soixante-dix', en='seventy (60+10)', category='numbers'),
                    VocabItem(fr='quatre-vingts', en='eighty (4×20)', category='numbers'), VocabItem(fr='quatre-vingt-dix', en='ninety (80+10)', category='numbers'),
                    VocabItem(fr='cent', en='hundred', category='numbers'),
                    VocabItem(fr='Combien ça coûte ?', en='How much does it cost?', category='shopping'),
                    VocabItem(fr='cher', en='expensive', category='shopping'), VocabItem(fr='pas cher', en='cheap', category='shopping'),
                ],
                grammar=[GrammarRule(title='Numbers 20–100', explanation='French uses a vigesimal system for 70-99. 70=soixante-dix (60+10), 80=quatre-vingts (4×20), 90=quatre-vingt-dix (80+10).', examples=[GrammarExample(fr='70 = soixante-dix', en='60 + 10'), GrammarExample(fr='80 = quatre-vingts', en='4 × 20'), GrammarExample(fr='90 = quatre-vingt-dix', en='80 + 10')])],
                dialogue=[
                    DialogueLine(speaker='A', name='Client', fr='Combien coûte le croissant ?', en='How much is the croissant?'),
                    DialogueLine(speaker='B', name='Vendeur', fr='Un euro cinquante.', en='One euro fifty.'),
                    DialogueLine(speaker='A', name='Client', fr='C\'est un peu cher. Vous avez des prix moins chers ?', en="It's a bit expensive. Do you have cheaper prices?"),
                ],
                exercises=[
                    Exercise(id='a1-u4-l2-e1', type='multiple_choice', prompt='How do you say 80 in French?', options=['huitante', 'octante', 'quatre-vingts', 'quatre-vingt'], answer=2),
                    Exercise(id='a1-u4-l2-e2', type='fill_blank', prompt='Complete: "70 = soixante-_____"', answer='dix'),
                ],
                estimatedMinutes=30),
            Lesson(id='a1-u4-l3', title='Food and Meals', titleFr='La nourriture et les repas',
                description='Talk about food, meals, and healthy eating.',
                objectives=['Name common foods', 'Discuss meals', 'Use partitive articles with food'],
                vocabulary=[
                    VocabItem(fr='le petit-déjeuner', en='breakfast', category='meals'), VocabItem(fr='le déjeuner', en='lunch', category='meals'),
                    VocabItem(fr='le dîner', en='dinner', category='meals'),
                    VocabItem(fr='la pomme', en='apple', category='food'), VocabItem(fr='l\'orange', en='orange', category='food'),
                    VocabItem(fr='la banane', en='banana', category='food'), VocabItem(fr='la tomate', en='tomato', category='food'),
                    VocabItem(fr='le poulet', en='chicken', category='food'), VocabItem(fr='le bœuf', en='beef', category='food'),
                    VocabItem(fr='le poisson', en='fish', category='food'), VocabItem(fr='le fromage', en='cheese', category='food'),
                    VocabItem(fr='le pain', en='bread', category='food'), VocabItem(fr='le riz', en='rice', category='food'),
                    VocabItem(fr='les pâtes', en='pasta', category='food'),
                ],
                grammar=[GrammarRule(title='The verb manger', explanation='Regular -er verb. je mange, tu manges, il mange, nous mangeons, vous mangez, ils mangent.', examples=[GrammarExample(fr='Je mange une pomme.', en='I eat an apple.'), GrammarExample(fr='Nous mangeons au restaurant.', en='We eat at the restaurant.')])],
                dialogue=[
                    DialogueLine(speaker='A', name='Paul', fr='Qu\'est-ce que tu manges pour le déjeuner ?', en='What do you eat for lunch?'),
                    DialogueLine(speaker='B', name='Anna', fr='Je mange une salade avec du poulet et du riz.', en='I eat a salad with chicken and rice.'),
                ],
                exercises=[
                    Exercise(id='a1-u4-l3-e1', type='multiple_choice', prompt='Which meal is "le dîner"?', options=['Breakfast', 'Lunch', 'Dinner', 'Snack'], answer=2),
                ],
                estimatedMinutes=30),
            Lesson(id='a1-u4-l4', title='Regular -ir and -re Verbs', titleFr='Les verbes en -ir et -re',
                description='Learn verbs ending in -ir and -re, including faire and prendre.',
                objectives=['Conjugate -ir and -re verbs', 'Learn common expressions with faire'],
                vocabulary=[
                    VocabItem(fr='finir', en='to finish', category='verbs'), VocabItem(fr='choisir', en='to choose', category='verbs'),
                    VocabItem(fr='répondre', en='to answer', category='verbs'), VocabItem(fr='vendre', en='to sell', category='verbs'),
                    VocabItem(fr='faire', en='to do/make', category='verbs'), VocabItem(fr='prendre', en='to take', category='verbs'),
                    VocabItem(fr='faire du sport', en='to do sports', category='expressions'),
                    VocabItem(fr='faire la cuisine', en='to cook', category='expressions'),
                    VocabItem(fr='faire attention', en='to be careful', category='expressions'),
                ],
                grammar=[
                    GrammarRule(title='The verb faire', explanation='Very irregular. je fais, tu fais, il fait, nous faisons, vous faites, ils font.', examples=[GrammarExample(fr='Je fais du sport.', en='I do sports.'), GrammarExample(fr='Elle fait la cuisine.', en='She cooks.')]),
                    GrammarRule(title='The verb prendre', explanation='Irregular. je prends, tu prends, il prend, nous prenons, vous prenez, ils prennent.', examples=[GrammarExample(fr='Je prends le train.', en='I take the train.')]),
                ],
                dialogue=[
                    DialogueLine(speaker='A', name='Marc', fr='Qu\'est-ce que tu fais ce week-end ?', en='What are you doing this weekend?'),
                    DialogueLine(speaker='B', name='Léa', fr='Je vais faire du sport et prendre le petit-déjeuner au café.', en='I am going to do sports and have breakfast at the café.'),
                ],
                exercises=[
                    Exercise(id='a1-u4-l4-e1', type='conjugation', prompt='Conjugate faire for "ils":', answer='font', acceptable=['font']),
                    Exercise(id='a1-u4-l4-e2', type='fill_blank', prompt='Complete: "Nous _____ du sport."', answer='faisons'),
                ],
                estimatedMinutes=30),
        ]),
    # UNIT 5
    Unit(
        id='a1-u5', title='In the City', titleFr='Unité 5 — En ville',
        theme='City, directions, and transportation', description='Navigate the city, ask for directions, and talk about transportation.',
        lessons=[
            Lesson(id='a1-u5-l1', title='Places in the City', titleFr='Les lieux de la ville',
                description='Name places in the city and ask for directions.',
                objectives=['Name city locations', 'Ask for and give directions', 'Use prepositions of location'],
                vocabulary=[
                    VocabItem(fr='la boulangerie', en='bakery', category='places'), VocabItem(fr='la pharmacie', en='pharmacy', category='places'),
                    VocabItem(fr='la gare', en='train station', category='places'), VocabItem(fr='le musée', en='museum', category='places'),
                    VocabItem(fr='le restaurant', en='restaurant', category='places'), VocabItem(fr='la banque', en='bank', category='places'),
                    VocabItem(fr='la poste', en='post office', category='places'), VocabItem(fr="l'hôtel", en='hotel', category='places'),
                    VocabItem(fr="l'école", en='school', category='places'), VocabItem(fr='le supermarché', en='supermarket', category='places'),
                    VocabItem(fr='à gauche', en='to the left', category='directions'), VocabItem(fr='à droite', en='to the right', category='directions'),
                    VocabItem(fr='tout droit', en='straight ahead', category='directions'), VocabItem(fr='à côté de', en='next to', category='directions'),
                    VocabItem(fr='en face de', en='across from', category='directions'), VocabItem(fr='près de', en='near', category='directions'),
                ],
                grammar=[GrammarRule(title='Asking for directions', explanation='Où est...? / Où se trouve...? / Pour aller à... ?', examples=[GrammarExample(fr='Où est la gare ?', en='Where is the train station?'), GrammarExample(fr='Pour aller à la pharmacie ?', en='How to get to the pharmacy?')])],
                dialogue=[
                    DialogueLine(speaker='A', name='Touriste', fr='Excusez-moi, où est la gare ?', en='Excuse me, where is the train station?'),
                    DialogueLine(speaker='B', name='Local', fr='Allez tout droit, puis tournez à droite.', en='Go straight ahead, then turn right.'),
                    DialogueLine(speaker='A', name='Touriste', fr='C\'est loin ?', en='Is it far?'),
                    DialogueLine(speaker='B', name='Local', fr='Non, c\'est à côté de la banque.', en='No, it\'s next to the bank.'),
                ],
                exercises=[
                    Exercise(id='a1-u5-l1-e1', type='multiple_choice', prompt='What does "à gauche" mean?', options=['To the right', 'To the left', 'Straight ahead', 'Nearby'], answer=1),
                    Exercise(id='a1-u5-l1-e2', type='matching', prompt='Match French to English.', pairs=[{'left': 'à gauche', 'right': 'to the left'}, {'left': 'à droite', 'right': 'to the right'}, {'left': 'tout droit', 'right': 'straight ahead'}], answer={}),
                ],
                estimatedMinutes=30),
            Lesson(id='a1-u5-l2', title='Transportation', titleFr='Les transports',
                description='Talk about transportation methods and buy tickets.',
                objectives=['Name transportation types', 'Buy a ticket', 'Use prepositions with transport'],
                vocabulary=[
                    VocabItem(fr='le métro', en='subway', category='transport'), VocabItem(fr='le bus', en='bus', category='transport'),
                    VocabItem(fr='le train', en='train', category='transport'), VocabItem(fr='le vélo', en='bicycle', category='transport'),
                    VocabItem(fr='la voiture', en='car', category='transport'), VocabItem(fr="l'avion", en='airplane', category='transport'),
                    VocabItem(fr='le billet', en='ticket', category='tickets'), VocabItem.fr='un aller simple' if False else VocabItem(fr='un aller simple', en='one-way ticket', category='tickets'),
                    VocabItem(fr='un aller-retour', en='round-trip ticket', category='tickets'),
                    VocabItem(fr='en métro', en='by subway', category='transport'), VocabItem(fr='à pied', en='on foot', category='transport'),
                    VocabItem(fr='en voiture', en='by car', category='transport'), VocabItem(fr='à vélo', en='by bicycle', category='transport'),
                ],
                grammar=[GrammarRule(title='Prepositions with transport', explanation='Use "en" + vehicle (en bus, en train). Use "à" for à pied, à vélo.', examples=[GrammarExample(fr='Je vais en métro.', en='I go by subway.'), GrammarExample(fr='Je vais à pied.', en='I go on foot.')])],
                dialogue=[
                    DialogueLine(speaker='A', name='Client', fr='Un billet pour Paris, s\'il vous plaît.', en='A ticket to Paris, please.'),
                    DialogueLine(speaker='B', name='Guichetier', fr='Un aller simple ou un aller-retour ?', en='One-way or round-trip?'),
                    DialogueLine(speaker='A', name='Client', fr='Un aller-retour, s\'il vous plaît.', en='Round-trip, please.'),
                ],
                exercises=[
                    Exercise(id='a1-u5-l2-e1', type='multiple_choice', prompt='How do you say "by bus" in French?', options=['à bus', 'en bus', 'par bus', 'au bus'], answer=1),
                ],
                estimatedMinutes=30),
            Lesson(id='a1-u5-l3', title='Hobbies and Free Time', titleFr='Loisirs et temps libre',
                description='Talk about hobbies and free time activities.',
                objectives=['Name sports and hobbies', 'Use faire de vs jouer à'],
                vocabulary=[
                    VocabItem(fr='le tennis', en='tennis', category='sports'), VocabItem(fr='le football', en='football', category='sports'),
                    VocabItem(fr='la natation', en='swimming', category='sports'), VocabItem(fr='le yoga', en='yoga', category='sports'),
                    VocabItem(fr='la lecture', en='reading', category='hobbies'), VocabItem(fr='le piano', en='piano', category='instruments'),
                    VocabItem(fr='la guitare', en='guitar', category='instruments'), VocabItem(fr='les jeux vidéo', en='video games', category='hobbies'),
                ],
                grammar=[GrammarRule(title='faire de vs. jouer à/de', explanation='faire de + sport (faire du tennis). Jouer à + sport/game (jouer au football). Jouer de + instrument (jouer du piano).', examples=[GrammarExample(fr='Je fais du tennis.', en='I play tennis.'), GrammarExample(fr='Je joue au football.', en='I play football.'), GrammarExample(fr='Elle joue du piano.', en='She plays piano.')])],
                dialogue=[
                    DialogueLine(speaker='A', name='Thomas', fr='Quels sont tes hobbies ?', en='What are your hobbies?'),
                    DialogueLine(speaker='B', name='Léa', fr='J\'aime la musique et la lecture. Et toi ?', en='I like music and reading. And you?'),
                    DialogueLine(speaker='A', name='Thomas', fr='Je fais du football et je joue de la guitare.', en='I play football and I play guitar.'),
                ],
                exercises=[
                    Exercise(id='a1-u5-l3-e1', type='multiple_choice', prompt='Which is correct for "I play tennis"?', options=["Joue du tennis", "Fais du tennis", "Joue au tennis", "Fais le tennis"], answer=1),
                ],
                estimatedMinutes=30),
            Lesson(id='a1-u5-l4', title='Weather and Seasons', titleFr='Le temps et les saisons',
                description='Talk about weather and seasons.',
                objectives=['Describe weather', 'Name seasons and months', 'Use weather expressions'],
                vocabulary=[
                    VocabItem(fr='Il fait beau', en='The weather is nice', category='weather'), VocabItem(fr='Il fait chaud', en='It is hot', category='weather'),
                    VocabItem(fr='Il fait froid', en='It is cold', category='weather'), VocabItem(fr='Il pleut', en='It is raining', category='weather'),
                    VocabItem(fr='Il neige', en='It is snowing', category='weather'), VocabItem(fr='Il y a du soleil', en='It is sunny', category='weather'),
                    VocabItem(fr='Il y a du vent', en='It is windy', category='weather'),
                    VocabItem(fr='le printemps', en='spring', category='seasons'), VocabItem(fr="l'été", en='summer', category='seasons'),
                    VocabItem(fr="l'automne", en='autumn', category='seasons'), VocabItem(fr="l'hiver", en='winter', category='seasons'),
                ],
                grammar=[GrammarRule(title='Weather expressions', explanation='Use "il fait" + adjective, "il pleut/neige" (verb), or "il y a" + noun.', examples=[GrammarExample(fr='Il fait beau aujourd\'hui.', en='The weather is nice today.'), GrammarExample(fr='Il pleut demain.', en='It will rain tomorrow.')])],
                dialogue=[
                    DialogueLine(speaker='A', name='Marc', fr='Quel temps fait-il ?', en='What\'s the weather like?'),
                    DialogueLine(speaker='B', name='Anna', fr='Il fait beau et il y a du soleil.', en='It\'s nice and sunny.'),
                    DialogueLine(speaker='A', name='Marc', fr='Parfait pour aller au parc !', en='Perfect for going to the park!'),
                ],
                exercises=[
                    Exercise(id='a1-u5-l4-e1', type='multiple_choice', prompt='What does "Il neige" mean?', options=['It is raining', 'It is snowing', 'It is windy', 'It is sunny'], answer=1),
                ],
                estimatedMinutes=30),
        ]),
    ],
]

a1_course = Course(
    level='A1', title='A1 — Débutant', book='Parlez A1',
    description="Complete beginner course. 8 units covering greetings, introductions, family, daily life, food, travel, housing, and more. Each lesson includes vocabulary, grammar, dialogues, exercises, and activities.",
    cefrDescription='Can understand and use familiar everyday expressions and very basic phrases. Can introduce themselves and ask and answer questions about personal details.',
    color='#2D6A4F', units=a1_units,
)
