from .types import *

# ============================================================
# Parlez A1 — Original beginner French course
# ============================================================
# Aligned to CEFR A1, DELF A1, TCF, and TEF frameworks.
# All content (titles, dialogues, vocabulary, examples, exercises,
# cultural notes) is original and not derived from any textbook.
# ============================================================

a1_course = Course(
    level='A1',
    title='A1 — Débutant',
    book='Parlez A1',
    description='Original beginner French course. Eight modules covering personal contact, identity, family, daily life, city life, food, home, and future plans. Aligned to CEFR A1 and DELF A1.',
    cefrDescription='Can understand and use familiar everyday expressions and very basic phrases aimed at the satisfaction of needs of a concrete type. Can introduce themselves and others and can ask and answer questions about personal details.',
    color='#2D6A4F',
    units=[
        # ============================================================
        # Module 1 — Premiers contacts
        # ============================================================
        Unit(
            id='a1-m1',
            title='Module 1 — Premiers contacts',
            titleFr='Module 1 — Premiers contacts',
            theme='First contact with French',
            description='Greet people, introduce yourself, use the alphabet, and count to 20.',
            lessons=[
                Lesson(
                    id='a1-m1-l1',
                    title='Saying Hello and Goodbye',
                    titleFr='Dire bonjour et au revoir',
                    description='Learn to greet people, say goodbye, and use polite expressions in French.',
                    objectives=[
                        'Greet someone using appropriate expressions',
                        'Say goodbye in formal and informal situations',
                        'Use polite words such as please, thank you, and sorry',
                        'Choose between formal and informal address',
                    ],
                    vocabulary=[
                        VocabItem(fr='Bonjour', en='Hello / Good morning', ipa='/bɔ̃.ʒuʁ/', example='Bonjour, comment allez-vous ?', exampleEn='Hello, how are you?', category='greetings'),
                        VocabItem(fr='Bonsoir', en='Good evening', ipa='/bɔ̃.swaʁ/', example='Bonsoir, madame.', exampleEn='Good evening, madam.', category='greetings'),
                        VocabItem(fr='Salut', en='Hi / Bye (informal)', ipa='/sa.ly/', example='Salut, Paul !', exampleEn='Hi, Paul!', category='greetings'),
                        VocabItem(fr='Au revoir', en='Goodbye', ipa='/o ʁə.vwaʁ/', example='Au revoir, à bientôt.', exampleEn='Goodbye, see you soon.', category='greetings'),
                        VocabItem(fr='À bientôt', en='See you soon', ipa='/a bjɛ̃.to/', example='À bientôt, Marie.', exampleEn='See you soon, Marie.', category='greetings'),
                        VocabItem(fr='À demain', en='See you tomorrow', ipa='/a də.mɛ̃/', example='À demain, professeur.', exampleEn='See you tomorrow, teacher.', category='greetings'),
                        VocabItem(fr='Bonne nuit', en='Good night', ipa='/bɔn nɥi/', example='Bonne nuit, les enfants.', exampleEn='Good night, children.', category='greetings'),
                        VocabItem(fr='Bonne journée', en='Have a nice day', ipa='/bɔn ʒuʁ.ne/', example='Bonne journée, monsieur.', exampleEn='Have a nice day, sir.', category='greetings'),
                        VocabItem(fr='Merci', en='Thank you', ipa='/mɛʁ.si/', example='Merci beaucoup.', exampleEn='Thank you very much.', category='politeness'),
                        VocabItem(fr='De rien', en="You're welcome", ipa='/də ʁjɛ̃/', example='— Merci. — De rien.', exampleEn="— Thanks. — You're welcome.", category='politeness'),
                        VocabItem(fr="S'il vous plaît", en='Please (formal)', ipa='/sil vu plɛ/', example='Un café, s\'il vous plaît.', exampleEn='A coffee, please.', category='politeness'),
                        VocabItem(fr="S'il te plaît", en='Please (informal)', ipa='/sil tə plɛ/', example='Passe-moi le sel, s\'il te plaît.', exampleEn='Pass me the salt, please.', category='politeness'),
                        VocabItem(fr='Pardon', en='Excuse me / Sorry', ipa='/paʁ.dɔ̃/', example='Pardon, où est la sortie ?', exampleEn='Excuse me, where is the exit?', category='politeness'),
                        VocabItem(fr='Monsieur', en='Sir / Mr.', ipa='/mə.sjø/', example='Bonjour, monsieur.', exampleEn='Hello, sir.', category='titles'),
                        VocabItem(fr='Madame', en='Madam / Mrs.', ipa='/ma.dam/', example='Bonjour, madame.', exampleEn='Hello, madam.', category='titles'),
                        VocabItem(fr='Oui', en='Yes', ipa='/wi/', example='Oui, je comprends.', exampleEn='Yes, I understand.', category='basics'),
                        VocabItem(fr='Non', en='No', ipa='/nɔ̃/', example='Non, merci.', exampleEn='No, thank you.', category='basics'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Tu vs. Vous',
                            explanation='French uses two forms of "you". Use tu with friends, family, children, and people your age. Use vous with strangers, older people, in professional settings, or to show respect. When unsure, start with vous.',
                            examples=[
                                GrammarExample(fr='Tu vas bien ?', en='Are you doing well? (informal)'),
                                GrammarExample(fr='Vous allez bien ?', en='Are you doing well? (formal or plural)'),
                                GrammarExample(fr='Comment tu t\'appelles ?', en='What is your name? (informal)'),
                                GrammarExample(fr='Comment vous appelez-vous ?', en='What is your name? (formal)'),
                            ],
                            tip='A group of people is always vous, even if they are friends.',
                        ),
                        GrammarRule(
                            title='Greetings by time of day',
                            explanation='Choose the greeting according to the time of day. Bonjour is used during the day. Bonsoir begins in the late afternoon or evening. Bonne nuit is only used when someone is going to sleep.',
                            examples=[
                                GrammarExample(fr='Bonjour ! (le matin et l\'après-midi)', en='Hello! (morning and afternoon)'),
                                GrammarExample(fr='Bonsoir ! (le soir)', en='Good evening! (evening)'),
                                GrammarExample(fr='Bonne nuit ! (au coucher)', en='Good night! (at bedtime)'),
                            ],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[
                                    {'pronoun': 'je', 'form': 'suis'},
                                    {'pronoun': 'tu', 'form': 'es'},
                                    {'pronoun': 'il/elle', 'form': 'est'},
                                    {'pronoun': 'nous', 'form': 'sommes'},
                                    {'pronoun': 'vous', 'form': 'êtes'},
                                    {'pronoun': 'ils/elles', 'form': 'sont'},
                                ],
                                sentenceRule='Use être to identify, describe, or locate. Professions and nationalities do not need an article after être.',
                                sentenceExamples=[
                                    GrammarExample(fr='Je suis étudiant.', en='I am a student.'),
                                    GrammarExample(fr='Elle est française.', en='She is French.'),
                                    GrammarExample(fr='Nous sommes à Lyon.', en='We are in Lyon.'),
                                ],
                            ),
                        ],
                        practice=[
                            Exercise(id='a1-m1-l1-conj-1', type='conjugation', prompt='Conjugate être for "je":', answer='suis', explanation='je suis'),
                            Exercise(id='a1-m1-l1-conj-2', type='multiple_choice', prompt='Complete: "il/elle _____" with être.', answer='', options=['est', 'es', 'sommes', 'êtes'], explanation='il/elle est'),
                            Exercise(id='a1-m1-l1-conj-3', type='fill_blank', prompt='Fill in: "Je _____ professeur."', answer='suis', explanation='The correct form is suis.'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Marc', fr='Bonjour ! Je m\'appelle Marc. Et vous ?', en='Hello! My name is Marc. And you?'),
                        DialogueLine(speaker='B', name='Léa', fr='Bonjour, monsieur. Je m\'appelle Léa Martin.', en='Hello, sir. My name is Léa Martin.'),
                        DialogueLine(speaker='A', name='Marc', fr='Enchanté, madame Martin. Vous êtes française ?', en='Pleased to meet you, Mrs. Martin. Are you French?'),
                        DialogueLine(speaker='B', name='Léa', fr='Oui, je suis française. Et vous, monsieur ?', en='Yes, I am French. And you, sir?'),
                        DialogueLine(speaker='A', name='Marc', fr='Moi, je suis belge. J\'habite à Bruxelles.', en='Me, I am Belgian. I live in Brussels.'),
                        DialogueLine(speaker='B', name='Léa', fr='Au revoir, monsieur. À bientôt !', en='Goodbye, sir. See you soon!'),
                        DialogueLine(speaker='A', name='Marc', fr='Au revoir, madame. Bonne journée !', en='Goodbye, madam. Have a nice day!'),
                    ],
                    exercises=[
                        Exercise(id='a1-m1-l1-e1', type='multiple_choice', prompt='What is the polite way to greet a stranger in the morning?', options=['Salut', 'Bonjour', 'Bonne nuit', 'Au revoir'], answer=1, explanation='Bonjour is the polite daytime greeting.'),
                        Exercise(id='a1-m1-l1-e2', type='multiple_choice', prompt='Which pronoun do you use with your best friend?', options=['Vous', 'Tu', 'Il', 'Nous'], answer=1, explanation='Tu is informal.'),
                        Exercise(id='a1-m1-l1-e3', type='true_false', prompt='"Bonne nuit" is an evening greeting.', options=['True', 'False'], answer=1, explanation='Bonne nuit is only used when someone goes to bed.'),
                        Exercise(id='a1-m1-l1-e4', type='translate_to_fr', prompt='Translate: "Thank you very much."', answer='Merci beaucoup', explanation='Merci beaucoup.'),
                        Exercise(id='a1-m1-l1-e5', type='fill_blank', prompt='Complete: "_____ nuit, fais de beaux rêves."', answer='Bonne', explanation='Bonne nuit.'),
                    ],
                    activities=[
                        Exercise(id='a1-m1-l1-a1', type='word_bank', prompt='Build: "Hello, my name is Sophie."', wordBank=['Bonjour', 'je', "m'appelle", 'Sophie', 'suis', 'Je'], answer="Bonjour, je m'appelle Sophie.", explanation='Bonjour + je + m\'appelle + name.'),
                        Exercise(id='a1-m1-l1-a2', type='reorder', prompt='Reorder: "madame / Bonsoir / entrez / s\'il vous plaît"', words=['madame', 'Bonsoir', 'entrez', 's\'il', 'vous', 'plaît'], answer="Bonsoir madame, entrez s'il vous plaît.", explanation='Polite evening greeting + invitation.'),
                        Exercise(id='a1-m1-l1-a3', type='multiple_choice', prompt='Someone says "Merci". What is the polite response?', options=['Bonjour', 'De rien', 'Au revoir', 'Pardon'], answer=1, explanation='De rien = You\'re welcome.'),
                    ],
                    culturalNote='In France, it is considered impolite to enter a small shop without saying "Bonjour" first. A simple greeting is often more important than the words that follow.',
                    estimatedMinutes=30,
                ),
                Lesson(
                    id='a1-m1-l2',
                    title='The French Alphabet',
                    titleFr="L'alphabet français",
                    description='Learn the French alphabet, key pronunciation differences, and how to spell words.',
                    objectives=[
                        'Name the letters of the French alphabet',
                        'Recognise letters that differ from English',
                        'Spell simple words and names',
                        'Identify common accented letters',
                    ],
                    vocabulary=[
                        VocabItem(fr='A (ah)', en='A', ipa='/a/', example='A comme Arthur', exampleEn='A as in Arthur', category='alphabet'),
                        VocabItem(fr='B (bé)', en='B', ipa='/be/', example='B comme Béatrice', exampleEn='B as in Béatrice', category='alphabet'),
                        VocabItem(fr='C (cé)', en='C', ipa='/se/', example='C comme Camille', exampleEn='C as in Camille', category='alphabet'),
                        VocabItem(fr='G (jé)', en='G', ipa='/ʒe/', example='G comme Gabriel', exampleEn='G as in Gabriel', category='alphabet'),
                        VocabItem(fr='J (jii)', en='J', ipa='/ʒi/', example='J comme Juliette', exampleEn='J as in Juliette', category='alphabet'),
                        VocabItem(fr='R (erre)', en='R', ipa='/ɛʁ/', example='R comme Raphaël', exampleEn='R as in Raphaël', category='alphabet'),
                        VocabItem(fr='U (u)', en='U', ipa='/y/', example='U comme Ursule', exampleEn='U as in Ursule', category='alphabet'),
                        VocabItem(fr='W (double vé)', en='W', ipa='/dubləve/', example='W comme William', exampleEn='W as in William', category='alphabet'),
                        VocabItem(fr='Y (i grec)', en='Y', ipa='/i gʁɛk/', example='Y comme Yasmine', exampleEn='Y as in Yasmine', category='alphabet'),
                        VocabItem(fr='Comment ça s\'écrit ?', en='How is it written?', ipa='/kɔ.mɑ̃ sa se.kʁi/', example='Comment ça s\'écrit, votre nom ?', exampleEn='How is your name written?', category='spelling'),
                        VocabItem(fr='Répétez, s\'il vous plaît', en='Please repeat', ipa='/ʁe.pe.te sil vu plɛ/', example='Répétez, s\'il vous plaît.', exampleEn='Please repeat.', category='spelling'),
                        VocabItem(fr='Plus lentement', en='More slowly', ipa='/ply lɑ̃t.mɑ̃/', example='Plus lentement, s\'il vous plaît.', exampleEn='More slowly, please.', category='spelling'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Key pronunciation differences',
                            explanation='Several French letters sound different from English. G sounds like the s in "measure". J sounds like "zhjee". U is a tight rounded vowel. R is made in the throat.',
                            examples=[
                                GrammarExample(fr='G = /ʒe/', en='Like the s in "measure"'),
                                GrammarExample(fr='J = /ʒi/', en='Like "zhjee"'),
                                GrammarExample(fr='U = /y/', en='Say "ee" with rounded lips'),
                                GrammarExample(fr='R = /ɛʁ/', en='A soft gargled sound'),
                            ],
                            tip='When spelling, French speakers often use first names: "A comme Arthur".',
                        ),
                        GrammarRule(
                            title='Common accents',
                            explanation='Accents change pronunciation or meaning. É sounds like "ay". È sounds like "eh". Ç makes C soft before A, O, or U.',
                            examples=[
                                GrammarExample(fr='café /ka.fe/', en='coffee (acute accent)'),
                                GrammarExample(fr='mère /mɛʁ/', en='mother (grave accent)'),
                                GrammarExample(fr='français /fʁɑ̃.sɛ/', en='French (cedilla)'),
                            ],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[
                                    {'pronoun': 'je', 'form': 'ai'},
                                    {'pronoun': 'tu', 'form': 'as'},
                                    {'pronoun': 'il/elle', 'form': 'a'},
                                    {'pronoun': 'nous', 'form': 'avons'},
                                    {'pronoun': 'vous', 'form': 'avez'},
                                    {'pronoun': 'ils/elles', 'form': 'ont'},
                                ],
                                sentenceRule='Use avoir to express possession, age, and many physical states.',
                                sentenceExamples=[
                                    GrammarExample(fr="J'ai un chat.", en='I have a cat.'),
                                    GrammarExample(fr='Tu as vingt ans.', en='You are twenty years old.'),
                                    GrammarExample(fr='Elle a froid.', en='She is cold.'),
                                ],
                            ),
                        ],
                        practice=[
                            Exercise(id='a1-m1-l2-conj-1', type='conjugation', prompt='Conjugate avoir for "nous":', answer='avons', explanation='nous avons'),
                            Exercise(id='a1-m1-l2-conj-2', type='multiple_choice', prompt='Complete: "Elle _____ un livre." with avoir.', answer='', options=['a', 'ai', 'as', 'ont'], explanation='elle a'),
                            Exercise(id='a1-m1-l2-conj-3', type='fill_blank', prompt='Fill in: "Tu _____ quinze ans."', answer='as', explanation='tu as'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Réceptionniste', fr='Bonjour. Comment ça s\'écrit, votre nom ?', en='Hello. How is your name written?'),
                        DialogueLine(speaker='B', name='Client', fr='Ça s\'écrit L-E-C-L-E-R-C.', en='It is written L-E-C-L-E-R-C.'),
                        DialogueLine(speaker='A', name='Réceptionniste', fr='Pardon, vous pouvez répéter ?', en='Sorry, can you repeat?'),
                        DialogueLine(speaker='B', name='Client', fr='Oui. L comme Luc, E, C comme Camille, L, E, R, C.', en='Yes. L as in Luc, E, C as in Camille, L, E, R, C.'),
                    ],
                    exercises=[
                        Exercise(id='a1-m1-l2-e1', type='multiple_choice', prompt='How is the letter G pronounced in French?', options=['Like English G', 'Like the s in "measure"', 'Like English J', 'Silent'], answer=1, explanation='French G = /ʒe/.'),
                        Exercise(id='a1-m1-l2-e2', type='multiple_choice', prompt='Which accent makes a soft "s" sound before A, O, or U?', options=['é', 'è', 'ê', 'ç'], answer=3, explanation='The cedilla: garçon, français.'),
                        Exercise(id='a1-m1-l2-e3', type='true_false', prompt='The French R is pronounced in the back of the throat.', options=['True', 'False'], answer=0, explanation='True.'),
                        Exercise(id='a1-m1-l2-e4', type='fill_blank', prompt='Spell L using a name: "L comme _____"', answer='Luc', explanation='L comme Luc.'),
                        Exercise(id='a1-m1-l2-e5', type='multiple_choice', prompt='What does "Comment ça s\'écrit ?" mean?', options=['How do you say it?', 'How is it written?', 'What does it mean?', 'Where is it?'], answer=1, explanation='How is it written?'),
                    ],
                    activities=[
                        Exercise(id='a1-m1-l2-a1', type='dictation', prompt='Listen and type the letter.', audioText='J', answer='J', explanation='J = /ʒi/.'),
                        Exercise(id='a1-m1-l2-a2', type='dictation', prompt='Listen and type the word.', audioText='café', answer='café', explanation='Notice the acute accent.'),
                        Exercise(id='a1-m1-l2-a3', type='fill_blank', prompt='Complete: "J\'_____ un chien." (avoir)', answer='ai', explanation='J\'ai = I have.'),
                    ],
                    culturalNote='The Académie française watches over the French language. In recent years it has accepted simpler spellings for some words, but accents remain essential for pronunciation and meaning.',
                    estimatedMinutes=30,
                ),
                Lesson(
                    id='a1-m1-l3',
                    title='Counting to Twenty',
                    titleFr="Compter jusqu'à vingt",
                    description='Learn numbers from 0 to 20 and how to use them in simple contexts.',
                    objectives=[
                        'Count from 0 to 20',
                        'Ask for and give a phone number',
                        'Say how old you are',
                        'Use numbers in everyday shopping',
                    ],
                    vocabulary=[
                        VocabItem(fr='zéro', en='zero', ipa='/ze.ʁo/', example='zéro euro', exampleEn='zero euros', category='numbers'),
                        VocabItem(fr='un', en='one', ipa='/œ̃/', example='un livre', exampleEn='one book', category='numbers'),
                        VocabItem(fr='deux', en='two', ipa='/dø/', example='deux amis', exampleEn='two friends', category='numbers'),
                        VocabItem(fr='trois', en='three', ipa='/tʁwa/', example='trois chats', exampleEn='three cats', category='numbers'),
                        VocabItem(fr='quatre', en='four', ipa='/katʁ/', example='quatre stylos', exampleEn='four pens', category='numbers'),
                        VocabItem(fr='cinq', en='five', ipa='/sɛ̃k/', example='cinq minutes', exampleEn='five minutes', category='numbers'),
                        VocabItem(fr='six', en='six', ipa='/sis/', example='six personnes', exampleEn='six people', category='numbers'),
                        VocabItem(fr='sept', en='seven', ipa='/sɛt/', example='sept jours', exampleEn='seven days', category='numbers'),
                        VocabItem(fr='huit', en='eight', ipa='/ɥit/', example='huit euros', exampleEn='eight euros', category='numbers'),
                        VocabItem(fr='neuf', en='nine', ipa='/nœf/', example='neuf mois', exampleEn='nine months', category='numbers'),
                        VocabItem(fr='dix', en='ten', ipa='/dis/', example='dix minutes', exampleEn='ten minutes', category='numbers'),
                        VocabItem(fr='onze', en='eleven', ipa='/ɔ̃z/', example='onze élèves', exampleEn='eleven pupils', category='numbers'),
                        VocabItem(fr='douze', en='twelve', ipa='/duz/', example='douze mois', exampleEn='twelve months', category='numbers'),
                        VocabItem(fr='treize', en='thirteen', ipa='/tʁɛz/', example='treize ans', exampleEn='thirteen years', category='numbers'),
                        VocabItem(fr='quatorze', en='fourteen', ipa='/ka.tɔʁz/', example='quatorze jours', exampleEn='fourteen days', category='numbers'),
                        VocabItem(fr='quinze', en='fifteen', ipa='/kɛ̃z/', example='quinze euros', exampleEn='fifteen euros', category='numbers'),
                        VocabItem(fr='seize', en='sixteen', ipa='/sɛz/', example='seize personnes', exampleEn='sixteen people', category='numbers'),
                        VocabItem(fr='dix-sept', en='seventeen', ipa='/di.sɛt/', example='dix-sept minutes', exampleEn='seventeen minutes', category='numbers'),
                        VocabItem(fr='dix-huit', en='eighteen', ipa='/di.zɥit/', example='dix-huit ans', exampleEn='eighteen years', category='numbers'),
                        VocabItem(fr='dix-neuf', en='nineteen', ipa='/di.nœf/', example='dix-neuf euros', exampleEn='nineteen euros', category='numbers'),
                        VocabItem(fr='vingt', en='twenty', ipa='/vɛ̃/', example='vingt minutes', exampleEn='twenty minutes', category='numbers'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Numbers and gender',
                            explanation='The number one has a masculine and feminine form: un livre, une table. Other numbers do not change.',
                            examples=[
                                GrammarExample(fr='un chat', en='one cat (masculine)'),
                                GrammarExample(fr='une chaise', en='one chair (feminine)'),
                                GrammarExample(fr='deux chats / deux chaises', en='two cats / two chairs'),
                            ],
                        ),
                        GrammarRule(
                            title='Age with avoir',
                            explanation='In French, you say "to have" a number of years. Use avoir, not être.',
                            examples=[
                                GrammarExample(fr='J\'ai vingt ans.', en='I am twenty years old.'),
                                GrammarExample(fr='Il a quinze ans.', en='He is fifteen years old.'),
                                GrammarExample(fr='Quel âge as-tu ?', en='How old are you? (informal)'),
                            ],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[
                                    {'pronoun': 'je', 'form': 'suis'},
                                    {'pronoun': 'tu', 'form': 'es'},
                                    {'pronoun': 'il/elle', 'form': 'est'},
                                    {'pronoun': 'nous', 'form': 'sommes'},
                                    {'pronoun': 'vous', 'form': 'êtes'},
                                    {'pronoun': 'ils/elles', 'form': 'sont'},
                                ],
                                sentenceRule='Review être for identity and location.',
                                sentenceExamples=[
                                    GrammarExample(fr='Je suis ici.', en='I am here.'),
                                    GrammarExample(fr='Nous sommes prêts.', en='We are ready.'),
                                ],
                            ),
                        ],
                        practice=[
                            Exercise(id='a1-m1-l3-conj-1', type='conjugation', prompt='Conjugate être for "vous":', answer='êtes', explanation='vous êtes'),
                            Exercise(id='a1-m1-l3-conj-2', type='fill_blank', prompt='Fill in: "Ils _____ étudiants."', answer='sont', explanation='ils sont'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Amir', fr='Salut ! Quel âge as-tu ?', en='Hi! How old are you?'),
                        DialogueLine(speaker='B', name='Clara', fr='J\'ai dix-huit ans. Et toi ?', en='I am eighteen. And you?'),
                        DialogueLine(speaker='A', name='Amir', fr='Moi, j\'ai vingt ans. Quel est ton numéro de téléphone ?', en='Me, I am twenty. What is your phone number?'),
                        DialogueLine(speaker='B', name='Clara', fr='C\'est le zé six, douze, trente-quatre, cinquante-six, vingt.', en='It is zero six, twelve, thirty-four, fifty-six, twenty.'),
                    ],
                    exercises=[
                        Exercise(id='a1-m1-l3-e1', type='multiple_choice', prompt='How do you say "15"?', options=['cinq', 'quinze', 'seize', 'vingt'], answer=1, explanation='quinze'),
                        Exercise(id='a1-m1-l3-e2', type='multiple_choice', prompt='Which is the feminine form of "one"?', options=['un', 'une', 'deux', 'des'], answer=1, explanation='une'),
                        Exercise(id='a1-m1-l3-e3', type='translate_to_fr', prompt='Translate: "I am twenty years old."', answer="J'ai vingt ans", explanation="J'ai vingt ans."),
                        Exercise(id='a1-m1-l3-e4', type='fill_blank', prompt='Complete: "J\'_____ dix-sept ans."', answer='ai', explanation='J\'ai dix-sept ans.'),
                        Exercise(id='a1-m1-l3-e5', type='reorder', prompt='Reorder: "ans / ai / seize / J\'"', words=["J'", 'ai', 'seize', 'ans'], answer="J'ai seize ans.", explanation='Age uses avoir.'),
                    ],
                    activities=[
                        Exercise(id='a1-m1-l3-a1', type='dictation', prompt='Listen and type the number.', audioText='douze', answer='douze', explanation='douze = 12'),
                        Exercise(id='a1-m1-l3-a2', type='dictation', prompt='Listen and type the number.', audioText='vingt', answer='vingt', explanation='vingt = 20'),
                        Exercise(id='a1-m1-l3-a3', type='multiple_choice', prompt='What comes after dix-neuf?', options=['dix', 'vingt', 'quinze', 'dix-huit'], answer=1, explanation='vingt = 20'),
                    ],
                    culturalNote='In France, phone numbers are usually read two digits at a time: 06 12 34 56 78 becomes "zéro six, douze, trente-quatre, cinquante-six, soixante-dix-huit". This takes practice for learners.',
                    estimatedMinutes=30,
                ),
            ],
        ),
        # ============================================================
        # Module 2 — Mon identité
        # ============================================================
        Unit(
            id='a1-m2',
            title='Module 2 — Mon identité',
            titleFr='Module 2 — Mon identité',
            theme='Personal identity',
            description='Talk about your name, origin, nationality, languages, age, and profession.',
            lessons=[
                Lesson(
                    id='a1-m2-l1',
                    title='My Name and Origin',
                    titleFr='Mon nom et mes origines',
                    description='Introduce yourself, say where you come from, and ask simple questions.',
                    objectives=[
                        'Introduce yourself with name and origin',
                        'Ask where someone is from',
                        'Use question words such as qui, où, comment, and d\'où',
                        'Name countries and nationalities',
                    ],
                    vocabulary=[
                        VocabItem(fr='je m\'appelle', en='my name is', ipa='/ʒə ma.pɛl/', example='Je m\'appelle Sophie.', exampleEn='My name is Sophie.', category='identity'),
                        VocabItem(fr='tu t\'appelles', en='your name is (informal)', ipa='/ty ta.pɛl/', example='Comment tu t\'appelles ?', exampleEn='What is your name?', category='identity'),
                        VocabItem(fr='il s\'appelle', en='his name is', ipa='/il sa.pɛl/', example='Il s\'appelle Lucas.', exampleEn='His name is Lucas.', category='identity'),
                        VocabItem(fr='elle s\'appelle', en='her name is', ipa='/ɛl sa.pɛl/', example='Elle s\'appelle Emma.', exampleEn='Her name is Emma.', category='identity'),
                        VocabItem(fr='je viens de', en='I come from', ipa='/ʒə vjɛ̃ də/', example='Je viens du Canada.', exampleEn='I come from Canada.', category='origin'),
                        VocabItem(fr='j\'habite à', en='I live in', ipa='/ʒa.bit a/', example='J\'habite à Paris.', exampleEn='I live in Paris.', category='origin'),
                        VocabItem(fr='nationalité', en='nationality', ipa='/na.sjɔ.na.li.te/', example='Quelle est votre nationalité ?', exampleEn='What is your nationality?', category='identity'),
                        VocabItem(fr='français / française', en='French', ipa='/fʁɑ̃.sɛ/ /fʁɑ̃.sɛz/', example='Je suis français.', exampleEn='I am French.', category='nationalities'),
                        VocabItem(fr='canadien / canadienne', en='Canadian', ipa='/ka.na.djɛ̃/ /ka.na.djɛn/', example='Elle est canadienne.', exampleEn='She is Canadian.', category='nationalities'),
                        VocabItem(fr='belge', en='Belgian', ipa='/bɛlʒ/', example='Il est belge.', exampleEn='He is Belgian.', category='nationalities'),
                        VocabItem(fr='suisse', en='Swiss', ipa='/sɥis/', example='Je suis suisse.', exampleEn='I am Swiss.', category='nationalities'),
                        VocabItem(fr='algérien / algérienne', en='Algerian', ipa='/al.ʒe.ʁjɛ̃/ /al.ʒe.ʁjɛn/', example='Elle est algérienne.', exampleEn='She is Algerian.', category='nationalities'),
                        VocabItem(fr='marocain / marocaine', en='Moroccan', ipa='/ma.ʁɔ.kɛ̃/ /ma.ʁɔ.kɛn/', example='Il est marocain.', exampleEn='He is Moroccan.', category='nationalities'),
                        VocabItem(fr='Quel / Quelle', en='Which / What', ipa='/kɛl/ /kɛl/', example='Quelle est ta nationalité ?', exampleEn='What is your nationality?', category='questions'),
                        VocabItem(fr='Qui', en='Who', ipa='/ki/', example='Qui est-ce ?', exampleEn='Who is it?', category='questions'),
                        VocabItem(fr='Où', en='Where', ipa='/u/', example='Où habites-tu ?', exampleEn='Where do you live?', category='questions'),
                        VocabItem(fr='D\'où', en='From where', ipa='/du/', example='D\'où viens-tu ?', exampleEn='Where are you from?', category='questions'),
                        VocabItem(fr='Comment', en='How', ipa='/kɔ.mɑ̃/', example='Comment ça va ?', exampleEn='How are you?', category='questions'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Subject pronouns',
                            explanation='French subject pronouns replace the subject of a sentence. Je, tu, il/elle, nous, vous, ils/elles are the basic forms.',
                            examples=[
                                GrammarExample(fr='Je suis étudiant.', en='I am a student.'),
                                GrammarExample(fr='Tu parles français.', en='You speak French.'),
                                GrammarExample(fr='Elle habite à Lyon.', en='She lives in Lyon.'),
                                GrammarExample(fr='Nous venons du Maroc.', en='We come from Morocco.'),
                            ],
                        ),
                        GrammarRule(
                            title='Prepositions with countries',
                            explanation='Use à before cities (no article) and en, au, or aux before countries. Feminine countries use en; masculine countries use au; plural countries use aux.',
                            examples=[
                                GrammarExample(fr='J\'habite à Paris.', en='I live in Paris.'),
                                GrammarExample(fr='Je viens de France.', en='I come from France.'),
                                GrammarExample(fr='Je viens du Canada.', en='I come from Canada.'),
                                GrammarExample(fr='Je viens des États-Unis.', en='I come from the United States.'),
                            ],
                            tip='Du = de + le; des = de + les.',
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='venir',
                                translation='to come',
                                tense='Présent',
                                conjugations=[
                                    {'pronoun': 'je', 'form': 'viens'},
                                    {'pronoun': 'tu', 'form': 'viens'},
                                    {'pronoun': 'il/elle', 'form': 'vient'},
                                    {'pronoun': 'nous', 'form': 'venons'},
                                    {'pronoun': 'vous', 'form': 'venez'},
                                    {'pronoun': 'ils/elles', 'form': 'viennent'},
                                ],
                                sentenceRule='Use venir de + place to say where you come from.',
                                sentenceExamples=[
                                    GrammarExample(fr='Je viens de Suisse.', en='I come from Switzerland.'),
                                    GrammarExample(fr='Tu viens d\'où ?', en='Where do you come from?'),
                                    GrammarExample(fr='Ils viennent d\'Algérie.', en='They come from Algeria.'),
                                ],
                            ),
                        ],
                        practice=[
                            Exercise(id='a1-m2-l1-conj-1', type='conjugation', prompt='Conjugate venir for "nous":', answer='venons', explanation='nous venons'),
                            Exercise(id='a1-m2-l1-conj-2', type='multiple_choice', prompt='Complete: "Elle _____ de Belgique."', answer='', options=['viens', 'venons', 'vient', 'viennent'], explanation='elle vient'),
                            Exercise(id='a1-m2-l1-conj-3', type='fill_blank', prompt='Fill in: "Je _____ de France."', answer='viens', explanation='je viens'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Inès', fr='Bonjour ! Comment tu t\'appelles ?', en='Hello! What is your name?'),
                        DialogueLine(speaker='B', name='Noah', fr='Salut ! Je m\'appelle Noah. Et toi ?', en='Hi! My name is Noah. And you?'),
                        DialogueLine(speaker='A', name='Inès', fr='Je m\'appelle Inès. Tu viens d\'où ?', en='My name is Inès. Where are you from?'),
                        DialogueLine(speaker='B', name='Noah', fr='Je viens du Sénégal. J\'habite à Dakar.', en='I come from Senegal. I live in Dakar.'),
                        DialogueLine(speaker='A', name='Inès', fr='Ah, tu es sénégalais ?', en='Ah, you are Senegalese?'),
                        DialogueLine(speaker='B', name='Noah', fr='Oui, et toi ?', en='Yes, and you?'),
                        DialogueLine(speaker='A', name='Inès', fr='Moi, je suis française. J\'habite à Marseille.', en='Me, I am French. I live in Marseille.'),
                    ],
                    exercises=[
                        Exercise(id='a1-m2-l1-e1', type='multiple_choice', prompt='How do you ask "What is your name?" informally?', options=["Comment vous appelez-vous ?", "Comment tu t\'appelles ?", "Qui es-tu ?", "Où habites-tu ?"], answer=1, explanation='Comment tu t\'appelles?'),
                        Exercise(id='a1-m2-l1-e2', type='multiple_choice', prompt='Which preposition do you use with a feminine country?', options=['au', 'en', 'aux', 'à'], answer=1, explanation='Use en for feminine countries: en France.'),
                        Exercise(id='a1-m2-l1-e3', type='translate_to_fr', prompt='Translate: "Where do you come from?" (informal)', answer='D\'où viens-tu ?', explanation='D\'où viens-tu?'),
                        Exercise(id='a1-m2-l1-e4', type='fill_blank', prompt='Complete: "Elle _____ d\'Algérie."', answer='vient', explanation='elle vient'),
                        Exercise(id='a1-m2-l1-e5', type='matching', prompt='Match the question word to its meaning.', pairs=[{"left": "Qui", "right": "Who"}, {"left": "Où", "right": "Where"}, {"left": "Comment", "right": "How"}, {"left": "Quel", "right": "What/Which"}], answer=None, explanation=''),
                    ],
                    activities=[
                        Exercise(id='a1-m2-l1-a1', type='word_bank', prompt='Build: "My name is Inès and I come from France."', wordBank=["Je", "m\'appelle", "Inès", "et", "je", "viens", "de", "France", "du"], answer="Je m'appelle Inès et je viens de France.", explanation='je m\'appelle + et + je viens de + country.'),
                        Exercise(id='a1-m2-l1-a2', type='reorder', prompt='Reorder: "Marseille / j\'habite / à"', words=["j'", 'habite', 'à', 'Marseille'], answer="J'habite à Marseille.", explanation='Subject + habite à + city.'),
                        Exercise(id='a1-m2-l1-a3', type='multiple_choice', prompt='What does "Je viens du Canada" mean?', options=['I go to Canada', 'I come from Canada', 'I live in Canada', 'I like Canada'], answer=1, explanation='Je viens de = I come from.'),
                    ],
                    culturalNote='In many French-speaking African countries, such as Senegal and Côte d\'Ivoire, people often greet with a handshake and ask about family before discussing business. This warmth is part of everyday French-speaking cultures.',
                    estimatedMinutes=35,
                ),
                Lesson(
                    id='a1-m2-l2',
                    title='Age and Profession',
                    titleFr='Âge et profession',
                    description='Say how old you are, talk about your job, and ask others about theirs.',
                    objectives=[
                        'Ask and answer questions about age',
                        'Name common professions',
                        'Use professions without an article after être',
                        'Count from 21 to 60',
                    ],
                    vocabulary=[
                        VocabItem(fr='un étudiant / une étudiante', en='student', ipa='/e.ty.djɑ̃/ /e.ty.djɑ̃t/', example='Je suis étudiant.', exampleEn='I am a student.', category='professions'),
                        VocabItem(fr='un professeur', en='teacher', ipa='/pʁɔ.fe.sœʁ/', example='Elle est professeur.', exampleEn='She is a teacher.', category='professions'),
                        VocabItem(fr='un médecin', en='doctor', ipa='/med.sɛ̃/', example='Il est médecin.', exampleEn='He is a doctor.', category='professions'),
                        VocabItem(fr='un infirmier / une infirmière', en='nurse', ipa='/ɛ̃.fiʁ.mje/ /ɛ̃.fiʁ.mjɛʁ/', example='Elle est infirmière.', exampleEn='She is a nurse.', category='professions'),
                        VocabItem(fr='un ingénieur', en='engineer', ipa='/ɛ̃.ʒe.njœʁ/', example='Il est ingénieur.', exampleEn='He is an engineer.', category='professions'),
                        VocabItem(fr='un serveur / une serveuse', en='waiter / waitress', ipa='/sɛʁ.vœʁ/ /sɛʁ.vøz/', example='Il est serveur.', exampleEn='He is a waiter.', category='professions'),
                        VocabItem(fr='un cuisinier / une cuisinière', en='cook', ipa='/kɥi.zi.nje/ /kɥi.zi.njɛʁ/', example='Elle est cuisinière.', exampleEn='She is a cook.', category='professions'),
                        VocabItem(fr='un vendeur / une vendeuse', en='salesperson', ipa='/vɑ̃.dœʁ/ /vɑ̃.døz/', example='Il est vendeur.', exampleEn='He is a salesperson.', category='professions'),
                        VocabItem(fr='un artiste', en='artist', ipa='/aʁ.tist/', example='Elle est artiste.', exampleEn='She is an artist.', category='professions'),
                        VocabItem(fr='un employé / une employée', en='employee', ipa='/ɑ̃.plwa.je/ /ɑ̃.plwa.je/', example='Il est employé.', exampleEn='He is an employee.', category='professions'),
                        VocabItem(fr='Quel âge as-tu ?', en='How old are you? (informal)', ipa='/kɛl ɑʒ a ty/', example='Quel âge as-tu ?', exampleEn='How old are you?', category='age'),
                        VocabItem(fr='J\'ai ... ans', en='I am ... years old', ipa='/ʒe ɑ̃/', example='J\'ai vingt-cinq ans.', exampleEn='I am twenty-five years old.', category='age'),
                        VocabItem(fr='vingt et un', en='twenty-one', ipa='/vɛ̃.te.œ̃/', example='vingt et un ans', exampleEn='twenty-one years', category='numbers'),
                        VocabItem(fr='trente', en='thirty', ipa='/tʁɑ̃t/', example='trente minutes', exampleEn='thirty minutes', category='numbers'),
                        VocabItem(fr='quarante', en='forty', ipa='/ka.ʁɑ̃t/', example='quarante euros', exampleEn='forty euros', category='numbers'),
                        VocabItem(fr='cinquante', en='fifty', ipa='/sɛ̃.kɑ̃t/', example='cinquante personnes', exampleEn='fifty people', category='numbers'),
                        VocabItem(fr='soixante', en='sixty', ipa='/swa.sɑ̃t/', example='soixante secondes', exampleEn='sixty seconds', category='numbers'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Professions without an article',
                            explanation='After être, professions do not use an article. Say Je suis professeur, not Je suis un professeur.',
                            examples=[
                                GrammarExample(fr='Je suis médecin.', en='I am a doctor.'),
                                GrammarExample(fr='Elle est artiste.', en='She is an artist.'),
                                GrammarExample(fr='Ils sont étudiants.', en='They are students.'),
                            ],
                        ),
                        GrammarRule(
                            title='Indefinite articles',
                            explanation='Use un before masculine nouns and une before feminine nouns. Use des before plural nouns.',
                            examples=[
                                GrammarExample(fr='un livre', en='a book (masculine)'),
                                GrammarExample(fr='une table', en='a table (feminine)'),
                                GrammarExample(fr='des amis', en='some friends (plural)'),
                            ],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[
                                    {'pronoun': 'je', 'form': 'ai'},
                                    {'pronoun': 'tu', 'form': 'as'},
                                    {'pronoun': 'il/elle', 'form': 'a'},
                                    {'pronoun': 'nous', 'form': 'avons'},
                                    {'pronoun': 'vous', 'form': 'avez'},
                                    {'pronoun': 'ils/elles', 'form': 'ont'},
                                ],
                                sentenceRule='Use avoir to express age.',
                                sentenceExamples=[
                                    GrammarExample(fr="J'ai vingt-deux ans.", en='I am twenty-two.'),
                                    GrammarExample(fr='Tu as trente ans.', en='You are thirty.'),
                                    GrammarExample(fr='Elle a quarante ans.', en='She is forty.'),
                                ],
                            ),
                        ],
                        practice=[
                            Exercise(id='a1-m2-l2-conj-1', type='conjugation', prompt='Conjugate avoir for "ils/elles":', answer='ont', explanation='ils/elles ont'),
                            Exercise(id='a1-m2-l2-conj-2', type='fill_blank', prompt='Fill in: "Vous _____ cinquante ans."', answer='avez', explanation='vous avez'),
                            Exercise(id='a1-m2-l2-conj-3', type='multiple_choice', prompt='Complete: "Nous _____ vingt ans."', answer='', options=['ai', 'as', 'a', 'avons'], explanation='nous avons'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Fatima', fr='Bonjour, monsieur. Vous êtes professeur ?', en='Hello, sir. Are you a teacher?'),
                        DialogueLine(speaker='B', name='Thomas', fr='Oui, je suis professeur de français. Et vous, vous êtes étudiante ?', en='Yes, I am a French teacher. And you, are you a student?'),
                        DialogueLine(speaker='A', name='Fatima', fr='Oui, je suis étudiante. J\'ai vingt-trois ans.', en='Yes, I am a student. I am twenty-three.'),
                        DialogueLine(speaker='B', name='Thomas', fr='Moi, j\'ai quarante-deux ans. Vous parlez anglais ?', en='Me, I am forty-two. Do you speak English?'),
                        DialogueLine(speaker='A', name='Fatima', fr='Un peu. J\'apprends le français.', en='A little. I am learning French.'),
                    ],
                    exercises=[
                        Exercise(id='a1-m2-l2-e1', type='multiple_choice', prompt='Which sentence is correct for "She is a nurse"?', options=['Elle est une infirmière.', 'Elle est infirmière.', 'Elle a infirmière.', 'Elle fait infirmière.'], answer=1, explanation='Professions do not use an article after être.'),
                        Exercise(id='a1-m2-l2-e2', type='multiple_choice', prompt='How do you say "fifty"?', options=['quarante', 'cinquante', 'soixante', 'trente'], answer=1, explanation='cinquante'),
                        Exercise(id='a1-m2-l2-e3', type='translate_to_fr', prompt='Translate: "I am thirty years old."', answer="J'ai trente ans", explanation="J'ai trente ans."),
                        Exercise(id='a1-m2-l2-e4', type='fill_blank', prompt='Complete: "Il est _____." (engineer)', answer='ingénieur', explanation='Il est ingénieur.'),
                        Exercise(id='a1-m2-l2-e5', type='true_false', prompt='You say "Je suis un médecin" for "I am a doctor."', options=['True', 'False'], answer=1, explanation='False. No article after être for professions.'),
                    ],
                    activities=[
                        Exercise(id='a1-m2-l2-a1', type='word_bank', prompt='Build: "She is a student and she is twenty years old."', wordBank=['Elle', 'est', 'étudiante', 'et', 'elle', 'a', 'vingt', 'ans'], answer='Elle est étudiante et elle a vingt ans.', explanation='elle est + profession + et + elle a + age.'),
                        Exercise(id='a1-m2-l2-a2', type='dictation', prompt='Listen and type the number.', audioText='quarante-deux', answer='quarante-deux', explanation='quarante-deux = 42'),
                        Exercise(id='a1-m2-l2-a3', type='multiple_choice', prompt='Which article goes with "table" (feminine)?', options=['un', 'une', 'des', 'le'], answer=1, explanation='une table'),
                    ],
                    culturalNote='In France, asking someone\'s profession is common in conversation, but asking about salary is considered rude. Age is acceptable among friends but can be sensitive with strangers.',
                    estimatedMinutes=35,
                ),
                Lesson(
                    id='a1-m2-l3',
                    title='The Languages I Speak',
                    titleFr='Les langues que je parle',
                    description='Talk about the languages you speak and how well you speak them.',
                    objectives=[
                        'Name languages in French',
                        'Say how well you speak a language',
                        'Use the verb parler',
                        'Form simple negative sentences',
                    ],
                    vocabulary=[
                        VocabItem(fr='français', en='French (language)', ipa='/fʁɑ̃.sɛ/', example='Je parle français.', exampleEn='I speak French.', category='languages'),
                        VocabItem(fr='anglais', en='English', ipa='/ɑ̃.glɛ/', example='Je parle anglais.', exampleEn='I speak English.', category='languages'),
                        VocabItem(fr='espagnol', en='Spanish', ipa='/ɛs.pa.ɲɔl/', example='Elle parle espagnol.', exampleEn='She speaks Spanish.', category='languages'),
                        VocabItem(fr='allemand', en='German', ipa='/al.mɑ̃/', example='Il parle allemand.', exampleEn='He speaks German.', category='languages'),
                        VocabItem(fr='italien', en='Italian', ipa='/i.ta.ljɛ̃/', example='Je parle un peu italien.', exampleEn='I speak a little Italian.', category='languages'),
                        VocabItem(fr='arabe', en='Arabic', ipa='/a.ʁab/', example='Elle parle arabe.', exampleEn='She speaks Arabic.', category='languages'),
                        VocabItem(fr='chinois', en='Chinese', ipa='/ʃi.nwa/', example='Il parle chinois.', exampleEn='He speaks Chinese.', category='languages'),
                        VocabItem(fr='portugais', en='Portuguese', ipa='/pɔʁ.ty.gɛ/', example='Elle parle portugais.', exampleEn='She speaks Portuguese.', category='languages'),
                        VocabItem(fr='je parle', en='I speak', ipa='/ʒə paʁl/', example='Je parle français.', exampleEn='I speak French.', category='verbs'),
                        VocabItem(fr='tu parles', en='you speak (informal)', ipa='/ty paʁl/', example='Tu parles anglais ?', exampleEn='Do you speak English?', category='verbs'),
                        VocabItem(fr='il/elle parle', en='he/she speaks', ipa='/il paʁl/ /ɛl paʁl/', example='Elle parle espagnol.', exampleEn='She speaks Spanish.', category='verbs'),
                        VocabItem(fr='nous parlons', en='we speak', ipa='/nu paʁ.lɔ̃/', example='Nous parlons français.', exampleEn='We speak French.', category='verbs'),
                        VocabItem(fr='un peu', en='a little', ipa='/œ̃ pø/', example='Je parle un peu français.', exampleEn='I speak a little French.', category='fluency'),
                        VocabItem(fr='bien', en='well', ipa='/bjɛ̃/', example='Je parle bien anglais.', exampleEn='I speak English well.', category='fluency'),
                        VocabItem(fr='couramment', en='fluently', ipa='/ku.ʁa.mɑ̃/', example='Elle parle couramment allemand.', exampleEn='She speaks German fluently.', category='fluency'),
                        VocabItem(fr='pas du tout', en='not at all', ipa='/pa dy tu/', example='Je ne parle pas du tout chinois.', exampleEn='I do not speak Chinese at all.', category='fluency'),
                        VocabItem(fr='comprendre', en='to understand', ipa='/kɔ̃.pʁɑ̃.dʁ/', example='Je comprends un peu.', exampleEn='I understand a little.', category='verbs'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='The verb parler',
                            explanation='Parler is a regular -er verb. Drop the -er and add the endings: -e, -es, -e, -ons, -ez, -ent.',
                            examples=[
                                GrammarExample(fr='Je parle français.', en='I speak French.'),
                                GrammarExample(fr='Tu parles anglais.', en='You speak English.'),
                                GrammarExample(fr='Nous parlons allemand.', en='We speak German.'),
                                GrammarExample(fr='Ils parlent espagnol.', en='They speak Spanish.'),
                            ],
                        ),
                        GrammarRule(
                            title='Negation with ne...pas',
                            explanation='To make a sentence negative, put ne before the verb and pas after it. With a vowel, ne becomes n\'.',
                            examples=[
                                GrammarExample(fr='Je ne parle pas allemand.', en='I do not speak German.'),
                                GrammarExample(fr="Je n'ai pas vingt ans.", en='I am not twenty years old.'),
                                GrammarExample(fr='Elle ne comprend pas.', en='She does not understand.'),
                            ],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='parler',
                                translation='to speak',
                                tense='Présent',
                                conjugations=[
                                    {'pronoun': 'je', 'form': 'parle'},
                                    {'pronoun': 'tu', 'form': 'parles'},
                                    {'pronoun': 'il/elle', 'form': 'parle'},
                                    {'pronoun': 'nous', 'form': 'parlons'},
                                    {'pronoun': 'vous', 'form': 'parlez'},
                                    {'pronoun': 'ils/elles', 'form': 'parlent'},
                                ],
                                sentenceRule='Use parler + language to say what language you speak.',
                                sentenceExamples=[
                                    GrammarExample(fr='Je parle français.', en='I speak French.'),
                                    GrammarExample(fr='Tu parles anglais ?', en='Do you speak English?'),
                                    GrammarExample(fr='Nous parlons italien.', en='We speak Italian.'),
                                ],
                            ),
                        ],
                        practice=[
                            Exercise(id='a1-m2-l3-conj-1', type='conjugation', prompt='Conjugate parler for "vous":', answer='parlez', explanation='vous parlez'),
                            Exercise(id='a1-m2-l3-conj-2', type='fill_blank', prompt='Fill in: "Ils _____ français."', answer='parlent', explanation='ils parlent'),
                            Exercise(id='a1-m2-l3-conj-3', type='multiple_choice', prompt='Complete: "Nous _____ anglais."', answer='', options=['parle', 'parles', 'parlons', 'parlent'], explanation='nous parlons'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Lucas', fr='Tu parles français ?', en='Do you speak French?'),
                        DialogueLine(speaker='B', name='Mei', fr='Oui, un peu. Je parle aussi anglais et chinois.', en='Yes, a little. I also speak English and Chinese.'),
                        DialogueLine(speaker='A', name='Lucas', fr='Tu parles couramment chinois ?', en='Do you speak Chinese fluently?'),
                        DialogueLine(speaker='B', name='Mei', fr='Oui, je parle couramment chinois. Et toi ?', en='Yes, I speak Chinese fluently. And you?'),
                        DialogueLine(speaker='A', name='Lucas', fr='Moi, je ne parle pas chinois. Je parle français et anglais.', en='Me, I do not speak Chinese. I speak French and English.'),
                    ],
                    exercises=[
                        Exercise(id='a1-m2-l3-e1', type='multiple_choice', prompt='What is the correct form for "we speak"?', options=['parle', 'parles', 'parlons', 'parlent'], answer=2, explanation='nous parlons'),
                        Exercise(id='a1-m2-l3-e2', type='multiple_choice', prompt='How do you say "I do not speak German"?', options=['Je parle allemand.', 'Je ne parle pas allemand.', "Je n'ai pas allemand.", 'Je suis pas allemand.'], answer=1, explanation='Je ne parle pas allemand.'),
                        Exercise(id='a1-m2-l3-e3', type='translate_to_fr', prompt='Translate: "She speaks Spanish fluently."', answer='Elle parle couramment espagnol.', explanation='Elle parle couramment espagnol.'),
                        Exercise(id='a1-m2-l3-e4', type='fill_blank', prompt='Complete: "Nous _____ français et anglais."', answer='parlons', explanation='nous parlons'),
                        Exercise(id='a1-m2-l3-e5', type='true_false', prompt='Languages use an article after parler.', options=['True', 'False'], answer=1, explanation='False. Je parle français, not je parle le français.'),
                    ],
                    activities=[
                        Exercise(id='a1-m2-l3-a1', type='word_bank', prompt='Build: "I speak a little French."', wordBank=['Je', 'parle', 'un', 'peu', 'français', 'le'], answer='Je parle un peu français.', explanation='Je parle + un peu + language.'),
                        Exercise(id='a1-m2-l3-a2', type='reorder', prompt='Reorder: "pas / allemand / ne / parle / Je"', words=['Je', 'ne', 'parle', 'pas', 'allemand'], answer='Je ne parle pas allemand.', explanation='Ne + verb + pas.'),
                        Exercise(id='a1-m2-l3-a3', type='multiple_choice', prompt='Which word means "fluently"?', options=['bien', 'un peu', 'couramment', 'pas du tout'], answer=2, explanation='couramment'),
                    ],
                    culturalNote='French is spoken on every continent. Countries like Canada, Belgium, Switzerland, Senegal, Côte d\'Ivoire, and Lebanon each have their own accents and expressions. This diversity makes French a truly global language.',
                    estimatedMinutes=35,
                ),
            ],
        ),
        # ============================================================
        # Module 3 — Ma famille et mes proches
        # ============================================================
        Unit(
            id='a1-m3',
            title='Module 3 — Ma famille et mes proches',
            titleFr='Module 3 — Ma famille et mes proches',
            theme='Family and close ones',
            description='Talk about your family, describe people, and discuss pets and animals.',
            lessons=[
                Lesson(
                    id='a1-m3-l1',
                    title='My Family',
                    titleFr='Ma famille',
                    description='Learn vocabulary for family members and how to talk about your family and marital status.',
                    objectives=[
                        'Name close family members in French',
                        'Talk about your marital status',
                        'Use possessive adjectives to show relationships',
                        'Ask simple questions about someone\'s family',
                    ],
                    vocabulary=[
                        VocabItem(fr='la famille', en='the family', ipa='/la fa.mij/', example='Ma famille est grande.', exampleEn='My family is big.', category='family'),
                        VocabItem(fr='le père', en='father', ipa='/lə pɛʁ/', example='Mon père est professeur.', exampleEn='My father is a teacher.', category='family'),
                        VocabItem(fr='la mère', en='mother', ipa='/la mɛʁ/', example='Ma mère est médecin.', exampleEn='My mother is a doctor.', category='family'),
                        VocabItem(fr='le frère', en='brother', ipa='/lə fʁɛʁ/', example='J\'ai un frère.', exampleEn='I have a brother.', category='family'),
                        VocabItem(fr='la sœur', en='sister', ipa='/la sœʁ/', example='Elle a une sœur.', exampleEn='She has a sister.', category='family'),
                        VocabItem(fr='le fils', en='son', ipa='/lə fis/', example='Il a un fils.', exampleEn='He has a son.', category='family'),
                        VocabItem(fr='la fille', en='daughter', ipa='/la fij/', example='Ma fille a dix ans.', exampleEn='My daughter is ten years old.', category='family'),
                        VocabItem(fr='les parents', en='parents', ipa='/le pa.ʁɑ̃/', example='Mes parents habitent à Lyon.', exampleEn='My parents live in Lyon.', category='family'),
                        VocabItem(fr='le grand-père', en='grandfather', ipa='/lə gʁɑ̃ pɛʁ/', example='Mon grand-père a quatre-vingts ans.', exampleEn='My grandfather is eighty years old.', category='family'),
                        VocabItem(fr='la grand-mère', en='grandmother', ipa='/la gʁɑ̃ mɛʁ/', example='Ma grand-mère cuisine bien.', exampleEn='My grandmother cooks well.', category='family'),
                        VocabItem(fr='le mari', en='husband', ipa='/lə ma.ʁi/', example='Son mari est ingénieur.', exampleEn='Her husband is an engineer.', category='family'),
                        VocabItem(fr='la femme', en='wife', ipa='/la fam/', example='Sa femme est artiste.', exampleEn='His wife is an artist.', category='family'),
                        VocabItem(fr='célibataire', en='single', ipa='/se.li.bi.tɛʁ/', example='Je suis célibataire.', exampleEn='I am single.', category='status'),
                        VocabItem(fr='marié / mariée', en='married', ipa='/ma.ʁje/ /ma.ʁje/', example='Elle est mariée.', exampleEn='She is married.', category='status'),
                        VocabItem(fr='divorcé / divorcée', en='divorced', ipa='/di.vɔʁ.se/ /di.vɔʁ.se/', example='Il est divorcé.', exampleEn='He is divorced.', category='status'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Possessive adjectives: mon, ma, mes',
                            explanation='Possessive adjectives agree with the noun they describe, not with the owner. Use mon before a masculine noun, ma before a feminine noun, and mes before plural nouns.',
                            examples=[
                                GrammarExample(fr='mon père', en='my father (masculine)'),
                                GrammarExample(fr='ma mère', en='my mother (feminine)'),
                                GrammarExample(fr='mes parents', en='my parents (plural)'),
                                GrammarExample(fr='mon amie', en='my friend (feminine, but starts with a vowel)'),
                            ],
                        ),
                        GrammarRule(
                            title='Possessive adjectives: ton/ta/tes and son/sa/ses',
                            explanation='Use ton, ta, tes for "your" and son, sa, ses for "his/her". They also agree with the noun, not the person who owns it.',
                            examples=[
                                GrammarExample(fr='ton frère', en='your brother'),
                                GrammarExample(fr='ta sœur', en='your sister'),
                                GrammarExample(fr='ses enfants', en='his/her children'),
                                GrammarExample(fr='son mari', en='her husband'),
                            ],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[
                                    {'pronoun': 'je', 'form': 'ai'},
                                    {'pronoun': 'tu', 'form': 'as'},
                                    {'pronoun': 'il/elle', 'form': 'a'},
                                    {'pronoun': 'nous', 'form': 'avons'},
                                    {'pronoun': 'vous', 'form': 'avez'},
                                    {'pronoun': 'ils/elles', 'form': 'ont'},
                                ],
                                sentenceRule='Use avoir to talk about the people in your family.',
                                sentenceExamples=[
                                    GrammarExample(fr="J'ai deux sœurs.", en='I have two sisters.'),
                                    GrammarExample(fr='Il a un frère.', en='He has a brother.'),
                                    GrammarExample(fr='Nous avons une grande famille.', en='We have a big family.'),
                                ],
                            ),
                        ],
                        practice=[
                            Exercise(id='a1-m3-l1-conj-1', type='conjugation', prompt='Conjugate avoir for "je":', answer='ai', explanation="j'ai"),
                            Exercise(id='a1-m3-l1-conj-2', type='multiple_choice', prompt='Complete: "Elle _____ un fils."', answer='', options=['ai', 'as', 'a', 'ont'], explanation='elle a'),
                            Exercise(id='a1-m3-l1-conj-3', type='fill_blank', prompt='Fill in: "Nous _____ une grande famille."', answer='avons', explanation='nous avons'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Sofia', fr='Tu as des frères et sœurs ?', en='Do you have brothers and sisters?'),
                        DialogueLine(speaker='B', name='Tom', fr='Oui, j\'ai un frère et deux sœurs.', en='Yes, I have one brother and two sisters.'),
                        DialogueLine(speaker='A', name='Sofia', fr='Tes parents habitent où ?', en='Where do your parents live?'),
                        DialogueLine(speaker='B', name='Tom', fr='Mes parents habitent à Nice. Et toi, tu es mariée ?', en='My parents live in Nice. And you, are you married?'),
                        DialogueLine(speaker='A', name='Sofia', fr='Non, je suis célibataire. Ma sœur est mariée.', en='No, I am single. My sister is married.'),
                        DialogueLine(speaker='B', name='Tom', fr='Elle a des enfants ?', en='Does she have children?'),
                        DialogueLine(speaker='A', name='Sofia', fr='Oui, elle a un fils et une fille.', en='Yes, she has a son and a daughter.'),
                    ],
                    exercises=[
                        Exercise(id='a1-m3-l1-e1', type='multiple_choice', prompt='Which possessive adjective goes with "mère"?', options=['mon', 'ma', 'mes', 'ton'], answer=1, explanation='ma mère (feminine)'),
                        Exercise(id='a1-m3-l1-e2', type='multiple_choice', prompt='How do you say "my parents"?', options=['mon parent', 'ma parent', 'mes parents', 'ton parents'], answer=2, explanation='mes parents (plural)'),
                        Exercise(id='a1-m3-l1-e3', type='translate_to_fr', prompt='Translate: "She is married."', answer='Elle est mariée.', explanation='Elle est mariée.'),
                        Exercise(id='a1-m3-l1-e4', type='fill_blank', prompt='Complete: "_____ frère a quinze ans." (my)', answer='Mon', explanation='Mon frère (masculine)'),
                        Exercise(id='a1-m3-l1-e5', type='true_false', prompt='Possessive adjectives agree with the owner.', options=['True', 'False'], answer=1, explanation='They agree with the noun, not the owner.'),
                    ],
                    activities=[
                        Exercise(id='a1-m3-l1-a1', type='word_bank', prompt='Build: "My sister is married."', wordBank=['Ma', 'sœur', 'est', 'mariée', 'mon', 'mari'], answer='Ma sœur est mariée.', explanation='Ma sœur + est + mariée.'),
                        Exercise(id='a1-m3-l1-a2', type='reorder', prompt='Reorder: "famille / j\'ai / grande / une / Je"', words=["J'", 'ai', 'une', 'grande', 'famille'], answer="J'ai une grande famille.", explanation='Subject + ai + une grande famille.'),
                        Exercise(id='a1-m3-l1-a3', type='multiple_choice', prompt='What does "Mes parents habitent à Paris" mean?', options=['My parents work in Paris', 'My parents live in Paris', 'My parents visit Paris', 'My parents are from Paris'], answer=1, explanation='habiter = to live'),
                    ],
                    culturalNote='In France, family is important, and Sunday lunches with extended family are a tradition in many regions. It is common to ask someone if they have brothers or sisters when getting to know them.',
                    estimatedMinutes=35,
                ),
                Lesson(
                    id='a1-m3-l2',
                    title='Describing Someone',
                    titleFr='Décrire quelqu\'un',
                    description='Learn how to describe physical appearance, character, and colours in French.',
                    objectives=[
                        'Describe height, age, and hair colour',
                        'Describe someone\'s character',
                        'Make adjectives agree with the noun',
                        'Place adjectives correctly before or after the noun',
                    ],
                    vocabulary=[
                        VocabItem(fr='grand / grande', en='tall / big', ipa='/gʁɑ̃/ /gʁɑ̃d/', example='Il est grand.', exampleEn='He is tall.', category='appearance'),
                        VocabItem(fr='petit / petite', en='short / small', ipa='/pə.ti/ /pə.tit/', example='Elle est petite.', exampleEn='She is short.', category='appearance'),
                        VocabItem(fr='beau / belle', en='handsome / beautiful', ipa='/bo/ /bɛl/', example='C\'est une belle femme.', exampleEn='She is a beautiful woman.', category='appearance'),
                        VocabItem(fr='jeune', en='young', ipa='/ʒœn/', example='Il est jeune.', exampleEn='He is young.', category='appearance'),
                        VocabItem(fr='vieux / vieille', en='old', ipa='/vjø/ /vjɛj/', example='Mon grand-père est vieux.', exampleEn='My grandfather is old.', category='appearance'),
                        VocabItem(fr='brun / brune', en='brown-haired / brunette', ipa='/bʁœ̃/ /bʁyn/', example='Elle est brune.', exampleEn='She is brunette.', category='appearance'),
                        VocabItem(fr='blond / blonde', en='blond', ipa='/blɔ̃/ /blɔ̃d/', example='Il est blond.', exampleEn='He is blond.', category='appearance'),
                        VocabItem(fr='les cheveux', en='hair', ipa='/le ʃə.vø/', example='Elle a les cheveux longs.', exampleEn='She has long hair.', category='appearance'),
                        VocabItem(fr='les yeux', en='eyes', ipa='/le zjø/', example='Il a les yeux bleus.', exampleEn='He has blue eyes.', category='appearance'),
                        VocabItem(fr='bleu / bleue', en='blue', ipa='/blø/ /blø/', example='Des yeux bleus.', exampleEn='Blue eyes.', category='colours'),
                        VocabItem(fr='vert / verte', en='green', ipa='/vɛʁ/ /vɛʁt/', example='Des yeux verts.', exampleEn='Green eyes.', category='colours'),
                        VocabItem(fr='marron', en='brown', ipa='/ma.ʁɔ̃/', example='Des yeux marron.', exampleEn='Brown eyes.', category='colours'),
                        VocabItem(fr='gentil / gentille', en='kind', ipa='/ʒɑ̃.ti/ /ʒɑ̃.tij/', example='Elle est très gentille.', exampleEn='She is very kind.', category='character'),
                        VocabItem(fr='sympa', en='nice', ipa='/sɛ̃.pa/', example='Il est sympa.', exampleEn='He is nice.', category='character'),
                        VocabItem(fr='drôle', en='funny', ipa='/dʁol/', example='Elle est drôle.', exampleEn='She is funny.', category='character'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Adjective agreement',
                            explanation='Most French adjectives add -e to form the feminine and -s to form the plural. Some have irregular forms.',
                            examples=[
                                GrammarExample(fr='un garçon petit', en='a small boy (masculine)'),
                                GrammarExample(fr='une fille petite', en='a small girl (feminine)'),
                                GrammarExample(fr='des garçons petits', en='small boys (plural)'),
                                GrammarExample(fr='une belle femme', en='a beautiful woman (irregular)'),
                            ],
                        ),
                        GrammarRule(
                            title='Position of adjectives',
                            explanation='Most adjectives come after the noun. A few common adjectives, such as beau, jeune, vieux, grand, petit, gentil, and bon, usually come before.',
                            examples=[
                                GrammarExample(fr='un petit chat', en='a small cat'),
                                GrammarExample(fr='une belle maison', en='a beautiful house'),
                                GrammarExample(fr='des yeux bleus', en='blue eyes'),
                                GrammarExample(fr='des cheveux blonds', en='blond hair'),
                            ],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[
                                    {'pronoun': 'je', 'form': 'suis'},
                                    {'pronoun': 'tu', 'form': 'es'},
                                    {'pronoun': 'il/elle', 'form': 'est'},
                                    {'pronoun': 'nous', 'form': 'sommes'},
                                    {'pronoun': 'vous', 'form': 'êtes'},
                                    {'pronoun': 'ils/elles', 'form': 'sont'},
                                ],
                                sentenceRule='Use être to describe people. Remember to make the adjective agree.',
                                sentenceExamples=[
                                    GrammarExample(fr='Je suis grand.', en='I am tall. (masculine)'),
                                    GrammarExample(fr='Elle est gentille.', en='She is kind. (feminine)'),
                                    GrammarExample(fr='Ils sont drôles.', en='They are funny. (plural)'),
                                ],
                            ),
                        ],
                        practice=[
                            Exercise(id='a1-m3-l2-conj-1', type='conjugation', prompt='Conjugate être for "elles":', answer='sont', explanation='elles sont'),
                            Exercise(id='a1-m3-l2-conj-2', type='multiple_choice', prompt='Complete: "Nous _____ amusants."', answer='', options=['suis', 'es', 'sommes', 'sont'], explanation='nous sommes'),
                            Exercise(id='a1-m3-l2-conj-3', type='fill_blank', prompt='Fill in: "Tu _____ très sympa."', answer='es', explanation='tu es'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Amina', fr='Comment est ton frère ?', en='What is your brother like?'),
                        DialogueLine(speaker='B', name='Luc', fr='Il est grand et blond. Il a les yeux bleus.', en='He is tall and blond. He has blue eyes.'),
                        DialogueLine(speaker='A', name='Amina', fr='Et ta mère, comment est-elle ?', en='And your mother, what is she like?'),
                        DialogueLine(speaker='B', name='Luc', fr='Elle est petite et brune. Elle est très gentille.', en='She is short and brunette. She is very kind.'),
                        DialogueLine(speaker='A', name='Amina', fr='Ta sœur est drôle, non ?', en='Your sister is funny, right?'),
                        DialogueLine(speaker='B', name='Luc', fr='Oui, elle est très drôle.', en='Yes, she is very funny.'),
                    ],
                    exercises=[
                        Exercise(id='a1-m3-l2-e1', type='multiple_choice', prompt='Which is the feminine form of "beau"?', options=['beau', 'belle', 'beaux', 'bel'], answer=1, explanation='belle'),
                        Exercise(id='a1-m3-l2-e2', type='multiple_choice', prompt='Where does "bleu" go in "des yeux _____"?', options=['before the noun', 'after the noun', 'it does not change', 'before the verb'], answer=1, explanation='Most colour adjectives go after the noun: des yeux bleus.'),
                        Exercise(id='a1-m3-l2-e3', type='translate_to_fr', prompt='Translate: "She is kind."', answer='Elle est gentille.', explanation='Elle est gentille.'),
                        Exercise(id='a1-m3-l2-e4', type='fill_blank', prompt='Complete: "Il est grand et _____." (blond)', answer='blond', explanation='masculine singular'),
                        Exercise(id='a1-m3-l2-e5', type='true_false', prompt='All French adjectives come before the noun.', options=['True', 'False'], answer=1, explanation='Most come after the noun.'),
                    ],
                    activities=[
                        Exercise(id='a1-m3-l2-a1', type='word_bank', prompt='Build: "She has blue eyes."', wordBank=['Elle', 'a', 'les', 'yeux', 'bleus', 'vert'], answer='Elle a les yeux bleus.', explanation='Elle a + les yeux + adjective agreeing.'),
                        Exercise(id='a1-m3-l2-a2', type='reorder', prompt='Reorder: "mère / ma / gentille / est / Très"', words=['Ma', 'mère', 'est', 'très', 'gentille'], answer='Ma mère est très gentille.', explanation='Possessive + noun + est + très + adjective.'),
                        Exercise(id='a1-m3-l2-a3', type='multiple_choice', prompt='Which adjective usually comes before the noun?', options=['bleu', 'vert', 'grand', 'marron'], answer=2, explanation='grand usually comes before the noun'),
                    ],
                    culturalNote='French people often compliment each other on appearance or style, but they tend to be more reserved with strangers than in some other cultures. A simple "Vous êtes très sympa" is a safe and kind compliment.',
                    estimatedMinutes=35,
                ),
                Lesson(
                    id='a1-m3-l3',
                    title='Pets and Animals',
                    titleFr='Les animaux de compagnie',
                    description='Learn vocabulary for common animals, pets, and how to talk about taking care of them.',
                    objectives=[
                        'Name common animals and pets',
                        'Talk about basic pet care',
                        'Use definite articles le, la, and les',
                        'Recognize the partitive articles du and des',
                    ],
                    vocabulary=[
                        VocabItem(fr='un animal', en='animal', ipa='/œ̃ ni.mal/', example='C\'est un animal.', exampleEn='It is an animal.', category='animals'),
                        VocabItem(fr='un chien', en='dog', ipa='/œ̃ ʃjɛ̃/', example='J\'ai un chien.', exampleEn='I have a dog.', category='pets'),
                        VocabItem(fr='un chat', en='cat', ipa='/œ̃ ʃa/', example='Elle a un chat.', exampleEn='She has a cat.', category='pets'),
                        VocabItem(fr='un oiseau', en='bird', ipa='/œ̃ nwa.zo/', example='Il a un oiseau.', exampleEn='He has a bird.', category='pets'),
                        VocabItem(fr='un poisson', en='fish', ipa='/œ̃ pwa.sɔ̃/', example='Nous avons un poisson.', exampleEn='We have a fish.', category='pets'),
                        VocabItem(fr='un lapin', en='rabbit', ipa='/œ̃ la.pɛ̃/', example='C\'est un lapin blanc.', exampleEn='It is a white rabbit.', category='pets'),
                        VocabItem(fr='une souris', en='mouse', ipa='/yn su.ʁi/', example='Elle a une souris grise.', exampleEn='She has a grey mouse.', category='pets'),
                        VocabItem(fr='une tortue', en='turtle', ipa='/yn tɔʁ.ty/', example='J\'ai une tortue.', exampleEn='I have a turtle.', category='pets'),
                        VocabItem(fr='un cheval', en='horse', ipa='/œ̃ ʃə.val/', example='Il aime les chevaux.', exampleEn='He likes horses.', category='animals'),
                        VocabItem(fr='une vache', en='cow', ipa='/yn vaʃ/', example='Les vaches mangent de l\'herbe.', exampleEn='Cows eat grass.', category='animals'),
                        VocabItem(fr='un mouton', en='sheep', ipa='/œ̃ mu.tɔ̃/', example='Il y a un mouton.', exampleEn='There is a sheep.', category='animals'),
                        VocabItem(fr='un cochon', en='pig', ipa='/œ̃ kɔ.ʃɔ̃/', example='Le cochon est rose.', exampleEn='The pig is pink.', category='animals'),
                        VocabItem(fr='la nourriture', en='food', ipa='/la nu.ʁi.tyʁ/', example='La nourriture du chat.', exampleEn='The cat\'s food.', category='care'),
                        VocabItem(fr='l\'eau', en='water', ipa='/lo/', example='Le chien boit de l\'eau.', exampleEn='The dog drinks water.', category='care'),
                        VocabItem(fr='une promenade', en='walk', ipa='/yn pʁɔ.ma.nad/', example='Je fais une promenade avec mon chien.', exampleEn='I go for a walk with my dog.', category='care'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Definite articles: le, la, les',
                            explanation='Use le before a masculine singular noun, la before a feminine singular noun, and les before plural nouns. Use l\' before a vowel or silent h.',
                            examples=[
                                GrammarExample(fr='le chien', en='the dog (masculine)'),
                                GrammarExample(fr='la tortue', en='the turtle (feminine)'),
                                GrammarExample(fr='les animaux', en='the animals (plural)'),
                                GrammarExample(fr="l'oiseau", en='the bird (vowel)'),
                            ],
                        ),
                        GrammarRule(
                            title='Partitive articles: du and des',
                            explanation='Use du (de + le) with masculine nouns and des with plural nouns to express an unspecified quantity. Use de l\' before a vowel.',
                            examples=[
                                GrammarExample(fr='Le chien mange du pain.', en='The dog eats (some) bread.'),
                                GrammarExample(fr='Le chat mange des croquettes.', en='The cat eats (some) kibble.'),
                                GrammarExample(fr="Il boit de l'eau.", en='He drinks water.'),
                            ],
                            tip='This is just a preview. You will learn more about partitive articles later.',
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='aimer',
                                translation='to like / to love',
                                tense='Présent',
                                conjugations=[
                                    {'pronoun': 'je', 'form': 'aime'},
                                    {'pronoun': 'tu', 'form': 'aimes'},
                                    {'pronoun': 'il/elle', 'form': 'aime'},
                                    {'pronoun': 'nous', 'form': 'aimons'},
                                    {'pronoun': 'vous', 'form': 'aimez'},
                                    {'pronoun': 'ils/elles', 'form': 'aiment'},
                                ],
                                sentenceRule='Use aimer to talk about pets and animals you like.',
                                sentenceExamples=[
                                    GrammarExample(fr="J'aime les chiens.", en='I like dogs.'),
                                    GrammarExample(fr='Tu aimes les chats ?', en='Do you like cats?'),
                                    GrammarExample(fr='Elle aime son lapin.', en='She loves her rabbit.'),
                                ],
                            ),
                        ],
                        practice=[
                            Exercise(id='a1-m3-l3-conj-1', type='conjugation', prompt='Conjugate aimer for "nous":', answer='aimons', explanation='nous aimons'),
                            Exercise(id='a1-m3-l3-conj-2', type='multiple_choice', prompt='Complete: "Vous _____ les animaux."', answer='', options=['aime', 'aimes', 'aimons', 'aimez'], explanation='vous aimez'),
                            Exercise(id='a1-m3-l3-conj-3', type='fill_blank', prompt='Fill in: "Elle _____ son chien."', answer='aime', explanation='elle aime'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Nora', fr='Tu as un animal de compagnie ?', en='Do you have a pet?'),
                        DialogueLine(speaker='B', name='Max', fr='Oui, j\'ai un chien. Il s\'appelle Milou.', en='Yes, I have a dog. His name is Milou.'),
                        DialogueLine(speaker='A', name='Nora', fr='Tu l\'aimes beaucoup ?', en='Do you like him a lot?'),
                        DialogueLine(speaker='B', name='Max', fr='Oui, j\'aime mon chien. Je fais une promenade avec lui tous les jours.', en='Yes, I love my dog. I go for a walk with him every day.'),
                        DialogueLine(speaker='A', name='Nora', fr='Il mange quoi ?', en='What does he eat?'),
                        DialogueLine(speaker='B', name='Max', fr='Il mange des croquettes et il boit de l\'eau.', en='He eats kibble and drinks water.'),
                    ],
                    exercises=[
                        Exercise(id='a1-m3-l3-e1', type='multiple_choice', prompt='Which definite article goes with "tortue"?', options=['le', 'la', 'les', 'l\''], answer=1, explanation='la tortue (feminine)'),
                        Exercise(id='a1-m3-l3-e2', type='multiple_choice', prompt='Which partitive article goes with "pain" (masculine)?', options=['de la', 'du', 'des', 'l\''], answer=1, explanation='du pain'),
                        Exercise(id='a1-m3-l3-e3', type='translate_to_fr', prompt='Translate: "I like cats."', answer="J'aime les chats.", explanation="J'aime les chats."),
                        Exercise(id='a1-m3-l3-e4', type='fill_blank', prompt='Complete: "Le chat boit _____ eau."', answer="de l'", explanation='de l\'eau (vowel)'),
                        Exercise(id='a1-m3-l3-e5', type='true_false', prompt='Use "les" before a singular feminine noun.', options=['True', 'False'], answer=1, explanation='les is plural.'),
                    ],
                    activities=[
                        Exercise(id='a1-m3-l3-a1', type='word_bank', prompt='Build: "The dog eats kibble."', wordBank=['Le', 'chien', 'mange', 'des', 'croquettes', 'du', 'pain'], answer='Le chien mange des croquettes.', explanation='Le chien + mange + des croquettes.'),
                        Exercise(id='a1-m3-l3-a2', type='reorder', prompt='Reorder: "avec / chien / fais / mon / Je / une / promenade"', words=['Je', 'fais', 'une', 'promenade', 'avec', 'mon', 'chien'], answer='Je fais une promenade avec mon chien.', explanation='Subject + fais + une promenade + avec mon chien.'),
                        Exercise(id='a1-m3-l3-a3', type='multiple_choice', prompt='What does "Elle aime son lapin" mean?', options=['She has her rabbit', 'She likes her rabbit', 'She feeds her rabbit', 'She walks her rabbit'], answer=1, explanation='aime = likes/loves'),
                    ],
                    culturalNote='Many French households have pets, and dogs are often welcomed in cafés with outdoor seating in cities. It is common to see people walking their dogs in parks and along boulevards in the evening.',
                    estimatedMinutes=35,
                ),
            ],
        ),
    ],
)
