from .types import *

# A2 Course
a2_course = Course(
    level='A2',
    title='A2 — Élémentaire',
    book='Parlez A2',
    description='Continue your journey. You\'ll master the passé composé and imparfait to talk about past events, express opinions, navigate social situations, and discuss memories, travel, health, and housing.',
    cefrDescription='Can understand sentences and frequently used expressions related to areas of most immediate relevance. Can communicate in simple and routine tasks requiring a simple and direct exchange of information on familiar and routine matters.',
    color='#C19A4B',
    units=[
        Unit(
            id='a2-u1',
            title='Memories and the Past',
            titleFr='Souvenirs',
            theme='Passé composé & childhood',
            description='Talk about what you did yesterday, last week, or in your childhood.',
            lessons=[
                Lesson(
                    id='a2-u1-l1',
                    title='The Passé Composé',
                    titleFr='Le passé composé',
                    description='Learn the main French past tense — used to talk about completed actions in the past.',
                    objectives=["Form the pass\u00e9 compos\u00e9 with avoir and \u00eatre", "Conjugate regular -er, -ir, -re verbs in the past", "Use common irregular past participles", "Talk about what you did yesterday"],
                    vocabulary=[
                        VocabItem(fr='hier', en='yesterday', ipa='', example='Hier, je suis allé au cinéma.', exampleEn='Yesterday, I went to the movies.', category='time'),
                        VocabItem(fr='la semaine dernière', en='last week', ipa='', example='La semaine dernière, j\\', exampleEn='Last week, I traveled.', category='time'),
                        VocabItem(fr='le mois dernier', en='last month', ipa='', example='Le mois dernier, il a neigé.', exampleEn='Last month, it snowed.', category='time'),
                        VocabItem(fr='l\\', en='last year', ipa='', example='L\\', exampleEn='Last year, we went to Italy.', category='time'),
                        VocabItem(fr='avant', en='before', ipa='', example='Avant, j\\', exampleEn='Before, I lived in Lyon.', category='time'),
                        VocabItem(fr='mon enfance', en='my childhood', ipa='', example='Dans mon enfance, je jouais au parc.', exampleEn='In my childhood, I played in the park.', category='life'),
                        VocabItem(fr='un souvenir', en='a memory', ipa='', example='J\\', exampleEn='I have a good memory of that time.', category='life'),
                        VocabItem(fr='se souvenir de', en='to remember', ipa='', example='Je me souviens de toi.', exampleEn='I remember you.', category='verbs'),
                        VocabItem(fr='oublier', en='to forget', ipa='', example='J\\', exampleEn='I forgot my umbrella.', category='verbs'),
                        VocabItem(fr='raconter', en='to tell (a story)', ipa='', example='Raconte-moi ton voyage !', exampleEn='Tell me about your trip!', category='verbs'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Forming the passé composé',
                            explanation='The passé composé is the main past tense in spoken French. It is formed with an auxiliary (avoir or être) + past participle. Most verbs use avoir; about 14 verbs of motion/reflexive use être.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "J\\", "en": "Avoir + mang\u00e9 (past participle of manger)."}, {"fr": "Je suis all\u00e9. (I went)", "en": "\u00catre + all\u00e9. Note: agreement with subject for \u00eatre verbs."}, {"fr": "Nous avons fini. (We finished)", "en": "Avoir + fini (past participle of finir)."}]],
                            tip='With être, the past participle agrees with the subject: elle est allée (f), ils sont venus (m pl), elles sont venues (f pl).',
                        ),
                        GrammarRule(
                            title='The "Dr. & Mrs. Vandertramp" verbs (être)',
                            explanation='These 14 verbs (and their compounds) use être as their auxiliary in the passé composé. Most are verbs of motion: aller, venir, arriver, partir, entrer, sortir, monter, descendre, naître, mourir, rester, tomber, retourner, devenir, plus reflexive verbs.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Je suis all\u00e9 au cin\u00e9ma.", "en": "I went to the cinema."}, {"fr": "Elle est venue \u00e0 la f\u00eate.", "en": "She came to the party."}, {"fr": "Ils sont partis \u00e0 8h.", "en": "They left at 8."}, {"fr": "Nous sommes rest\u00e9s \u00e0 la maison.", "en": "We stayed at home."}]],
                            tip='A mnemonic: Dr. Mrs. Vandertramp — each letter is the start of an être verb.',
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "suis"}, {"pronoun": "tu", "form": "es"}, {"pronoun": "il/elle", "form": "est"}, {"pronoun": "nous", "form": "sommes"}, {"pronoun": "vous", "form": "\u00eates"}, {"pronoun": "ils/elles", "form": "sont"}],
                                sentenceRule='Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je suis \u00e9tudiant.", "en": "I am a student."}, {"fr": "Tu es fran\u00e7ais ?", "en": "Are you French?"}, {"fr": "Nous sommes \u00e0 Paris.", "en": "We are in Paris."}]],
                            ),
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "ai"}, {"pronoun": "tu", "form": "as"}, {"pronoun": "il/elle", "form": "a"}, {"pronoun": "nous", "form": "avons"}, {"pronoun": "vous", "form": "avez"}, {"pronoun": "ils/elles", "form": "ont"}],
                                sentenceRule='Subject + avoir + noun. Used for possession, age (J\\',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "J\\", "en": "I have a brother."}, {"fr": "Tu as vingt ans.", "en": "You are twenty."}, {"fr": "Il a faim.", "en": "He is hungry."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='a2-u1-l1-conj-0-1', type='conjugation', prompt='Conjugate "être" for "je":', answer='suis', options=None, explanation='je suis — correct form of "être".'),
                            Exercise(id='a2-u1-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "être".', answer='', options=['est', 'suis', 'es', 'sommes'], explanation='il/elle est — correct conjugation of "être".'),
                            Exercise(id='a2-u1-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"', answer='suis', options=None, explanation='The correct form is "suis".'),
                            Exercise(id='a2-u1-l1-conj-1-1', type='conjugation', prompt='Conjugate "avoir" for "tu":', answer='as', options=None, explanation='tu as — correct form of "avoir".'),
                            Exercise(id='a2-u1-l1-conj-1-2', type='multiple_choice', prompt='Complete: "nous _____" with the correct form of "avoir".', answer='', options=['avons', 'ai', 'as', 'a'], explanation='nous avons — correct conjugation of "avoir".'),
                            Exercise(id='a2-u1-l1-conj-1-3', type='fill_blank', prompt='Fill in the blank: "Tu _____ vingt ans." (You are twenty.) — form of "avoir"', answer='as', options=None, explanation='The correct form is "as".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Lucas', fr='Tu as fait quoi hier, Marie ?', en='What did you do yesterday, Marie?'),
                        DialogueLine(speaker='B', name='Marie', fr='Hier, je suis allée au musée avec ma sœur. Nous avons vu une exposition sur Picasso.', en='Yesterday, I went to the museum with my sister. We saw a Picasso exhibition.'),
                        DialogueLine(speaker='A', name='Lucas', fr='Super ! Et le soir, qu\\', en='Great! And in the evening, what did you do?'),
                        DialogueLine(speaker='B', name='Marie', fr='Le soir, nous avons dîné dans un petit restaurant italien. J\\', en='In the evening, we had dinner in a small Italian restaurant. I had delicious pasta.'),
                        DialogueLine(speaker='A', name='Lucas', fr='Moi, je suis resté à la maison. J\\', en='Me, I stayed home. I watched a movie.'),
                        DialogueLine(speaker='B', name='Marie', fr='Quel film tu as vu ?', en='What movie did you watch?'),
                        DialogueLine(speaker='A', name='Lucas', fr='J\\', en='I saw "Amélie". It\\'),
                    ],
                    exercises=[
                        Exercise(id='a2-u1-l1-e1', type='multiple_choice', prompt='Which auxiliary does "aller" use in the passé composé?', options=['avoir', 'être', 'faire', 'both'], answer=1, explanation='Aller is a motion verb — it uses être: je suis allé(e).'),
                        Exercise(id='a2-u1-l2-e2', type='fill_blank', prompt='Complete: "Hier, j\\', options=None, answer='ai', explanation='J\\'),
                        Exercise(id='a2-u1-l3-e3', type='multiple_choice', prompt='What is the past participle of "prendre"?', options=['prendu', 'pris', 'prendi', 'prendre'], answer=1, explanation='Prendre → pris (irregular). Like: apprendre → appris, comprendre → compris.'),
                        Exercise(id='a2-u1-l4-e4', type='translate_to_fr', prompt='Translate: "We went to Italy last year."', options=None, answer='Nous sommes allés en Italie l\\', explanation='Aller + être. Nous (m) → allés. En Italie (countries).'),
                        Exercise(id='a2-u1-l5-e5', type='true_false', prompt='With être verbs, the past participle agrees with the subject in gender and number.', options=['True', 'False'], answer=0, explanation='True. Elle est allée (f), ils sont venus (m pl), elles sont venues (f pl).'),
                    ],
                    culturalNote='The French love to \'raconter\' (tell stories). A typical French dinner can last 2-3 hours, with everyone sharing stories about their day, week, or trips. Asking \'Qu\\\'est-ce que tu as fait ce week-end ?\' is a classic Monday morning question at work.',
                    estimatedMinutes=35,
                ),
                Lesson(
                    id='a2-u1-l2',
                    title='The Imparfait',
                    titleFr='L\\',
                    description='Learn the imperfect tense — used for descriptions, habits, and ongoing past actions.',
                    objectives=["Form the imparfait from the nous form", "Use imparfait for descriptions and habits", "Distinguish imparfait from pass\u00e9 compos\u00e9", "Describe your childhood"],
                    vocabulary=[
                        VocabItem(fr='quand j\\', en='when I was little', ipa='', example='Quand j\\', exampleEn='When I was little, I loved candy.', category='childhood'),
                        VocabItem(fr='avant', en='before / in the past', ipa='', example='Avant, j\\', exampleEn='Before, I lived in the countryside.', category='time'),
                        VocabItem(fr='tous les jours', en='every day', ipa='', example='Tous les jours, je marchais à l\\', exampleEn='Every day, I walked to school.', category='habit'),
                        VocabItem(fr='souvent', en='often', ipa='', example='Je jouais souvent au parc.', exampleEn='I often played in the park.', category='frequency'),
                        VocabItem(fr='parfois', en='sometimes', ipa='', example='Parfois, nous allions à la mer.', exampleEn='Sometimes, we went to the sea.', category='frequency'),
                        VocabItem(fr='la campagne', en='the countryside', ipa='', example='J\\', exampleEn='I liked the countryside.', category='places'),
                        VocabItem(fr='la mer', en='the sea', ipa='', example='Nous allions à la mer en été.', exampleEn='We went to the sea in summer.', category='places'),
                        VocabItem(fr='l\\', en='school', ipa='', example='À l\\', exampleEn='At school, I was good at math.', category='education'),
                        VocabItem(fr='les copains', en='friends (informal)', ipa='', example='Je jouais avec mes copains.', exampleEn='I played with my friends.', category='people'),
                        VocabItem(fr='grandir', en='to grow up', ipa='', example='J\\', exampleEn='I grew up in Lyon.', category='verbs'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Forming the imparfait',
                            explanation='The imparfait is formed from the nous form of the present tense: drop the -ons ending and add -ais, -ais, -ait, -ions, -iez, -aient. The only exception is être, whose stem is \'ét-\'.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "parler \u2192 nous parlons \u2192 je parlais", "en": "I was speaking / I used to speak"}, {"fr": "finir \u2192 nous finissons \u2192 je finissais", "en": "I was finishing / I used to finish"}, {"fr": "\u00eatre \u2192 j\\", "en": "I was (being)"}]],
                            tip='All forms have the same sound (é /ɛ/), except nous (-jɔ̃) and vous (-je).',
                        ),
                        GrammarRule(
                            title='Imparfait vs. Passé Composé',
                            explanation='Use the imparfait for: descriptions, ongoing actions, habits (\'I used to...\'), and background. Use the passé composé for: completed actions, specific events, and actions that moved the story forward.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Il pleuvait (imparfait) quand je suis sorti (pass\u00e9 compos\u00e9).", "en": "It was raining when I went out."}, {"fr": "Quand j\\", "en": "When I was a child, I went to the sea every summer (habit)."}, {"fr": "Hier, j\\", "en": "Yesterday, I met Sophie (specific event)."}]],
                            tip='Imparfait = setting the scene; Passé composé = what happened.',
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "ai"}, {"pronoun": "tu", "form": "as"}, {"pronoun": "il/elle", "form": "a"}, {"pronoun": "nous", "form": "avons"}, {"pronoun": "vous", "form": "avez"}, {"pronoun": "ils/elles", "form": "ont"}],
                                sentenceRule='Subject + avoir + noun. Used for possession, age (J\\',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "J\\", "en": "I have a brother."}, {"fr": "Tu as vingt ans.", "en": "You are twenty."}, {"fr": "Il a faim.", "en": "He is hungry."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='a2-u1-l2-conj-0-1', type='conjugation', prompt='Conjugate "avoir" for "j\\', answer='ai', options=None, explanation='j\\'),
                            Exercise(id='a2-u1-l2-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "avoir".', answer='', options=['a', 'ai', 'as', 'avons'], explanation='il/elle a — correct conjugation of "avoir".'),
                            Exercise(id='a2-u1-l2-conj-0-3', type='fill_blank', prompt='Fill in the blank: "J\\', answer='ai', options=None, explanation='The correct form is "ai".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Paul', fr='Tu étais comment quand tu étais enfant, Léa ?', en='What were you like when you were a child, Léa?'),
                        DialogueLine(speaker='B', name='Léa', fr='J\\', en='I was very shy. I spoke little, but I read a lot.'),
                        DialogueLine(speaker='A', name='Paul', fr='Tu habitais où à ce moment-là ?', en='Where did you live at that time?'),
                        DialogueLine(speaker='B', name='Léa', fr='J\\', en='I lived in Nantes, near the Loire. Every weekend, we went walking along the river.'),
                        DialogueLine(speaker='A', name='Paul', fr='C\\', en='That\\'),
                        DialogueLine(speaker='B', name='Léa', fr='Oui, j\\', en='Yes, I had two best friends. We played together every day after school.'),
                        DialogueLine(speaker='A', name='Paul', fr='Tu les vois encore ?', en='Do you still see them?'),
                        DialogueLine(speaker='B', name='Léa', fr='Malheureusement non. L\\', en='Unfortunately no. One lives in Canada now.'),
                    ],
                    exercises=[
                        Exercise(id='a2-u1-l2-e1', type='multiple_choice', prompt='What is the imparfait stem of "finir" (nous finissons)?', options=['fin-', 'finiss-', 'fini-', 'finiss-'], answer=1, explanation='Drop -ons from nous finissons → finiss-. Then add -ais: je finissais.'),
                        Exercise(id='a2-u1-l2-e2', type='fill_blank', prompt='Complete: "Quand j\\', options=None, answer='étais', explanation='Être in imparfait: j\\'),
                        Exercise(id='a2-u1-l2-e3', type='multiple_choice', prompt='Which tense for "I used to play tennis every Sunday"?', options=['Passé composé', 'Imparfait', 'Présent', 'Futur'], answer=1, explanation='Habitual past actions use imparfait: Je jouais au tennis tous les dimanches.'),
                        Exercise(id='a2-u1-l2-e4', type='translate_to_fr', prompt='Translate: "When I was little, I lived in Lyon."', options=None, answer='Quand j\\', explanation='Imparfait for both: j\\'),
                        Exercise(id='a2-u1-l2-e5', type='true_false', prompt='The imparfait is used for completed, specific past events.', options=['True', 'False'], answer=1, explanation='False. The imparfait is for descriptions and habits. Passé composé is for completed events.'),
                    ],
                    culturalNote='French schools have a long tradition of \'la rédaction\' (essay writing). Children are encouraged from a young age to write stories about their weekends, holidays, and childhood memories. This cultural emphasis on storytelling shapes the way French people converse — anecdotes and detailed narratives are highly valued.',
                    estimatedMinutes=35,
                ),
            ],
        ),
        Unit(
            id='a2-u2',
            title='Travel and Discovery',
            titleFr='Voyages',
            theme='Future, travel & transportation',
            description='Plan future trips, talk about transportation, and use the futur proche.',
            lessons=[
                Lesson(
                    id='a2-u2-l1',
                    title='Planning the Future',
                    titleFr='Planifier l\\',
                    description='Use aller + infinitive to talk about what you are going to do.',
                    objectives=["Form the futur proche (aller + infinitif)", "Talk about future plans and intentions", "Use travel vocabulary", "Book a hotel and a train ticket"],
                    vocabulary=[
                        VocabItem(fr='le voyage', en='the trip', ipa='', example='Je vais faire un voyage.', exampleEn='I\\', category='travel'),
                        VocabItem(fr='le billet', en='the ticket', ipa='', example='Je vais acheter un billet de train.', exampleEn='I\\', category='travel'),
                        VocabItem(fr='la valise', en='the suitcase', ipa='', example='Je vais faire ma valise.', exampleEn='I\\', category='travel'),
                        VocabItem(fr='l\\', en='the plane', ipa='', example='Nous allons prendre l\\', exampleEn='We\\', category='transport'),
                        VocabItem(fr='le train', en='the train', ipa='', example='Le train arrive à 14h.', exampleEn='The train arrives at 2 PM.', category='transport'),
                        VocabItem(fr='la voiture', en='the car', ipa='', example='Je vais louer une voiture.', exampleEn='I\\', category='transport'),
                        VocabItem(fr='l\\', en='the hotel', ipa='', example='Nous allons réserver un hôtel.', exampleEn='We\\', category='travel'),
                        VocabItem(fr='la plage', en='the beach', ipa='', example='Nous allons à la plage.', exampleEn='We\\', category='places'),
                        VocabItem(fr='la montagne', en='the mountain', ipa='', example='Ils vont à la montagne.', exampleEn='They\\', category='places'),
                        VocabItem(fr='réserver', en='to book / reserve', ipa='', example='Je vais réserver une chambre.', exampleEn='I\\', category='verbs'),
                        VocabItem(fr='partir', en='to leave', ipa='', example='Nous allons partir demain.', exampleEn='We\\', category='verbs'),
                        VocabItem(fr='visiter', en='to visit (a place)', ipa='', example='Je vais visiter Paris.', exampleEn='I\\', category='verbs'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Futur proche — aller + infinitif',
                            explanation='The futur proche (near future) is the easiest way to talk about the future in French. It is formed with the present tense of \'aller\' + the infinitive of the main verb. It is used for plans, intentions, and near-future events.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Je vais manger.", "en": "I am going to eat."}, {"fr": "Tu vas voyager.", "en": "You are going to travel."}, {"fr": "Nous allons partir demain.", "en": "We are going to leave tomorrow."}]],
                            tip='The futur proche is more common in spoken French than the futur simple, especially for near-future plans.',
                        ),
                        GrammarRule(
                            title='Prepositions with countries and cities',
                            explanation='Prepositions change depending on the gender of the country and whether it\'s a city. Cities always take \'à\'. Countries take \'en\' (feminine) or \'au\' (masculine).',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "\u00e0 Paris, \u00e0 Lyon, \u00e0 Tokyo", "en": "Cities always use \u00e0."}, {"fr": "en France, en Italie, en Chine", "en": "Feminine countries use en."}, {"fr": "au Canada, au Japon, au Maroc", "en": "Masculine countries use au."}, {"fr": "aux \u00c9tats-Unis, aux Pays-Bas", "en": "Plural countries use aux."}]],
                            tip='Most countries ending in -e are feminine (la France, l\'Italie). Exceptions: le Mexique, le Mozambique, le Cambodge, le Zimbabwe.',
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "ai"}, {"pronoun": "tu", "form": "as"}, {"pronoun": "il/elle", "form": "a"}, {"pronoun": "nous", "form": "avons"}, {"pronoun": "vous", "form": "avez"}, {"pronoun": "ils/elles", "form": "ont"}],
                                sentenceRule='Subject + avoir + noun. Used for possession, age (J\\',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "J\\", "en": "I have a brother."}, {"fr": "Tu as vingt ans.", "en": "You are twenty."}, {"fr": "Il a faim.", "en": "He is hungry."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='a2-u2-l1-conj-0-1', type='conjugation', prompt='Conjugate "avoir" for "j\\', answer='ai', options=None, explanation='j\\'),
                            Exercise(id='a2-u2-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "avoir".', answer='', options=['a', 'ai', 'as', 'avons'], explanation='il/elle a — correct conjugation of "avoir".'),
                            Exercise(id='a2-u2-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "J\\', answer='ai', options=None, explanation='The correct form is "ai".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Camille', fr='Qu\\', en='What are you going to do this summer, Thomas?'),
                        DialogueLine(speaker='B', name='Thomas', fr='Je vais voyager en Italie avec ma copine. Nous allons visiter Rome et Florence.', en='I\\'),
                        DialogueLine(speaker='A', name='Camille', fr='Super ! Comment vous allez y aller ? En avion ?', en='Great! How are you going to go? By plane?'),
                        DialogueLine(speaker='B', name='Thomas', fr='Non, nous allons prendre le train. C\\', en='No, we\\'),
                        DialogueLine(speaker='A', name='Camille', fr='Vous allez réserver un hôtel ?', en='Are you going to book a hotel?'),
                        DialogueLine(speaker='B', name='Thomas', fr='Oui, nous allons réserver un petit hôtel à Rome. Et toi, tu vas partir en vacances ?', en='Yes, we\\'),
                        DialogueLine(speaker='A', name='Camille', fr='Je vais aller au Maroc avec ma famille. Nous allons rester deux semaines.', en='I\\'),
                    ],
                    exercises=[
                        Exercise(id='a2-u2-l1-e1', type='multiple_choice', prompt='How do you say "I am going to travel" in French?', options=['Je voyage', 'Je vais voyager', 'Je voyagerai', 'Je voyageais'], answer=1, explanation='Futur proche = aller (present) + infinitive: je vais voyager.'),
                        Exercise(id='a2-u2-l1-e2', type='fill_blank', prompt='Complete: "Nous _____ partir demain." (We are going to leave tomorrow.)', options=None, answer='allons', explanation='Nous + allons + infinitive: nous allons partir.'),
                        Exercise(id='a2-u2-l1-e3', type='multiple_choice', prompt='Which preposition: "Je vais _____ Italie." (I am going to Italy.)', options=['à l\\', ', ', ', ', ', '], answer=2, explanation='Italie is feminine → en Italie.'),
                        Exercise(id='a2-u2-l1-e4', type='translate_to_fr', prompt='Translate: "We are going to take the train."', options=None, answer='Nous allons prendre le train', explanation='Nous allons + prendre (infinitive) + le train.'),
                        Exercise(id='a2-u2-l1-e5', type='true_false', prompt='The futur proche is more common in spoken French than the futur simple.', options=['True', 'False'], answer=0, explanation='True. The futur proche (aller + infinitif) is the most natural way to talk about near-future plans.'),
                    ],
                    culturalNote='France has an extensive high-speed train network called TGV (Train à Grande Vitesse). The TGV can reach 320 km/h and connects Paris to Marseille in just 3 hours. The SNCF (French national railway) is the main operator — booking in advance can save you up to 70% on tickets.',
                    estimatedMinutes=35,
                ),
            ],
        ),
        Unit(
            id='a2-u3',
            title='Health and Body',
            titleFr='Santé',
            theme='Body, illness & advice',
            description='Talk about your body, describe symptoms, and give advice using devoir.',
            lessons=[
                Lesson(
                    id='a2-u3-l1',
                    title='At the Doctor',
                    titleFr='Chez le médecin',
                    description='Describe symptoms, talk to a doctor, and understand medical advice.',
                    objectives=["Name body parts", "Describe common symptoms", "Use devoir for advice (tu dois...)", "Understand basic medical instructions"],
                    vocabulary=[
                        VocabItem(fr='le corps', en='the body', ipa='', example='Le corps humain est fascinant.', exampleEn='The human body is fascinating.', category='body'),
                        VocabItem(fr='la tête', en='the head', ipa='', example='J\\', exampleEn='I have a headache.', category='body'),
                        VocabItem(fr='le ventre', en='the stomach', ipa='', example='J\\', exampleEn='I have a stomach ache.', category='body'),
                        VocabItem(fr='le dos', en='the back', ipa='', example='J\\', exampleEn='My back hurts.', category='body'),
                        VocabItem(fr='la gorge', en='the throat', ipa='', example='J\\', exampleEn='My throat hurts.', category='body'),
                        VocabItem(fr='le bras', en='the arm', ipa='', example='Mon bras me fait mal.', exampleEn='My arm hurts.', category='body'),
                        VocabItem(fr='la jambe', en='the leg', ipa='', example='Ma jambe est cassée.', exampleEn='My leg is broken.', category='body'),
                        VocabItem(fr='avoir mal à', en='to have pain in', ipa='', example='J\\', exampleEn='I have a headache.', category='medical'),
                        VocabItem(fr='la fièvre', en='the fever', ipa='', example='J\\', exampleEn='I have a fever.', category='medical'),
                        VocabItem(fr='la toux', en='the cough', ipa='', example='J\\', exampleEn='I have a dry cough.', category='medical'),
                        VocabItem(fr='le rhume', en='the cold', ipa='', example='J\\', exampleEn='I caught a cold.', category='medical'),
                        VocabItem(fr='le médicament', en='the medicine', ipa='', example='Prenez ce médicament trois fois par jour.', exampleEn='Take this medicine three times a day.', category='medical'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Expression: avoir mal à',
                            explanation='To express pain, French uses \'avoir mal à\' + body part. The preposition \'à\' changes to \'au\' (m), \'à la\' (f), or \'à l\\\'\' (vowel).',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "J\\", "en": "I have a headache."}, {"fr": "J\\", "en": "I have a stomach ache."}, {"fr": "J\\", "en": "My feet hurt."}, {"fr": "J\\", "en": "My ear hurts."}]],
                            tip='Avoir mal à + definite article + body part. Always use the article, even though English doesn\\',
                        ),
                        GrammarRule(
                            title='Devoir — must / should / have to',
                            explanation='Devoir is used to express obligation, necessity, or advice. The meaning changes with the tense: present = must/should, conditional = ought to (softer advice).',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Tu dois voir un m\u00e9decin.", "en": "You must see a doctor."}, {"fr": "Vous devez vous reposer.", "en": "You must rest."}, {"fr": "Tu ne dois pas fumer.", "en": "You must not smoke."}]],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "suis"}, {"pronoun": "tu", "form": "es"}, {"pronoun": "il/elle", "form": "est"}, {"pronoun": "nous", "form": "sommes"}, {"pronoun": "vous", "form": "\u00eates"}, {"pronoun": "ils/elles", "form": "sont"}],
                                sentenceRule='Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je suis \u00e9tudiant.", "en": "I am a student."}, {"fr": "Tu es fran\u00e7ais ?", "en": "Are you French?"}, {"fr": "Nous sommes \u00e0 Paris.", "en": "We are in Paris."}]],
                            ),
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "ai"}, {"pronoun": "tu", "form": "as"}, {"pronoun": "il/elle", "form": "a"}, {"pronoun": "nous", "form": "avons"}, {"pronoun": "vous", "form": "avez"}, {"pronoun": "ils/elles", "form": "ont"}],
                                sentenceRule='Subject + avoir + noun. Used for possession, age (J\\',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "J\\", "en": "I have a brother."}, {"fr": "Tu as vingt ans.", "en": "You are twenty."}, {"fr": "Il a faim.", "en": "He is hungry."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='a2-u3-l1-conj-0-1', type='conjugation', prompt='Conjugate "être" for "je":', answer='suis', options=None, explanation='je suis — correct form of "être".'),
                            Exercise(id='a2-u3-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "être".', answer='', options=['est', 'suis', 'es', 'sommes'], explanation='il/elle est — correct conjugation of "être".'),
                            Exercise(id='a2-u3-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"', answer='suis', options=None, explanation='The correct form is "suis".'),
                            Exercise(id='a2-u3-l1-conj-1-1', type='conjugation', prompt='Conjugate "avoir" for "tu":', answer='as', options=None, explanation='tu as — correct form of "avoir".'),
                            Exercise(id='a2-u3-l1-conj-1-2', type='multiple_choice', prompt='Complete: "nous _____" with the correct form of "avoir".', answer='', options=['avons', 'ai', 'as', 'a'], explanation='nous avons — correct conjugation of "avoir".'),
                            Exercise(id='a2-u3-l1-conj-1-3', type='fill_blank', prompt='Fill in the blank: "Tu _____ vingt ans." (You are twenty.) — form of "avoir"', answer='as', options=None, explanation='The correct form is "as".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Médecin', fr='Bonjour, qu\\', en='Hello, what\\'),
                        DialogueLine(speaker='B', name='Patient', fr='Bonjour, docteur. J\\', en='Hello, doctor. My throat hurts and I\\'),
                        DialogueLine(speaker='A', name='Médecin', fr='Vous avez aussi de la toux ?', en='Do you also have a cough?'),
                        DialogueLine(speaker='B', name='Patient', fr='Oui, une toux sèche. Et j\\', en='Yes, a dry cough. And I have a headache.'),
                        DialogueLine(speaker='A', name='Médecin', fr='C\\', en='It\\'),
                        DialogueLine(speaker='B', name='Patient', fr='Je dois prendre des médicaments ?', en='Should I take medicine?'),
                        DialogueLine(speaker='A', name='Médecin', fr='Oui, prenez ce sirop deux fois par jour. Et buvez beaucoup d\\', en='Yes, take this syrup twice a day. And drink plenty of water.'),
                        DialogueLine(speaker='B', name='Patient', fr='Merci, docteur. Au revoir.', en='Thank you, doctor. Goodbye.'),
                    ],
                    exercises=[
                        Exercise(id='a2-u3-l1-e1', type='multiple_choice', prompt='How do you say "I have a headache"?', options=['J\\', ', ', 'ai mal à la tête', 'J\\', ', '], answer=1, explanation='Avoir mal à la tête = to have a headache. Tête is feminine → à la.'),
                        Exercise(id='a2-u3-l1-e2', type='fill_blank', prompt='Complete: "Tu _____ voir un médecin." (You must see a doctor.)', options=None, answer='dois', explanation='Tu + dois + infinitive: tu dois voir.'),
                        Exercise(id='a2-u3-l1-e3', type='multiple_choice', prompt='Which body part is "le ventre"?', options=['The head', 'The stomach', 'The back', 'The throat'], answer=1, explanation='Le ventre = the stomach/belly. J\\'),
                        Exercise(id='a2-u3-l1-e4', type='translate_to_fr', prompt='Translate: "I have a fever."', options=None, answer='J\\', explanation='Avoir + de la (partitive) + fièvre.'),
                        Exercise(id='a2-u3-l1-e5', type='true_false', prompt='"Devoir" can express advice or obligation.', options=['True', 'False'], answer=0, explanation='True. Tu dois (you must) is stronger; tu devrais (you should) is softer advice.'),
                    ],
                    culturalNote='In France, healthcare is largely public and very affordable. The \'Sécurité Sociale\' covers about 70% of medical costs, and most people have \'mutuelle\' insurance for the rest. A standard doctor visit (consultation) costs 25€. The emergency number for medical help is 15 (SAMU).',
                    estimatedMinutes=30,
                ),
            ],
        ),
        Unit(
            id='a2-u4',
            title='Housing and Home',
            titleFr='Logement',
            theme='House, furniture & pronouns',
            description='Describe your home, talk about rooms and furniture, and use direct object pronouns.',
            lessons=[
                Lesson(
                    id='a2-u4-l1',
                    title='Describing Your Home',
                    titleFr='Décrire sa maison',
                    description='Name rooms and furniture, use direct object pronouns (le, la, les).',
                    objectives=["Name rooms (chambre, cuisine, salon)", "Describe furniture", "Use direct object pronouns (le, la, les)", "Talk about where you live"],
                    vocabulary=[
                        VocabItem(fr='la maison', en='the house', ipa='', example='J\\', exampleEn='I live in a house.', category='housing'),
                        VocabItem(fr='l\\', en='the apartment', ipa='', example='Mon appartement est petit.', exampleEn='My apartment is small.', category='housing'),
                        VocabItem(fr='la chambre', en='the bedroom', ipa='', example='Ma chambre est à l\\', exampleEn='My bedroom is upstairs.', category='rooms'),
                        VocabItem(fr='la cuisine', en='the kitchen', ipa='', example='La cuisine est grande.', exampleEn='The kitchen is big.', category='rooms'),
                        VocabItem(fr='le salon', en='the living room', ipa='', example='Nous mangeons dans le salon.', exampleEn='We eat in the living room.', category='rooms'),
                        VocabItem(fr='la salle de bain', en='the bathroom', ipa='', example='La salle de bain a une baignoire.', exampleEn='The bathroom has a bathtub.', category='rooms'),
                        VocabItem(fr='les toilettes', en='the toilet(s)', ipa='', example='Où sont les toilettes ?', exampleEn='Where are the toilets?', category='rooms'),
                        VocabItem(fr='le lit', en='the bed', ipa='', example='Mon lit est confortable.', exampleEn='My bed is comfortable.', category='furniture'),
                        VocabItem(fr='la table', en='the table', ipa='', example='La table est en bois.', exampleEn='The table is wooden.', category='furniture'),
                        VocabItem(fr='le canapé', en='the sofa', ipa='', example='Le canapé est gris.', exampleEn='The sofa is grey.', category='furniture'),
                        VocabItem(fr='l\\', en='the wardrobe', ipa='', example='Mes vêtements sont dans l\\', exampleEn='My clothes are in the wardrobe.', category='furniture'),
                        VocabItem(fr='le balcon', en='the balcony', ipa='', example='J\\', exampleEn='I have plants on the balcony.', category='housing'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Direct object pronouns — le, la, les',
                            explanation='Direct object pronouns replace a direct object (a noun that receives the action directly). They go BEFORE the verb. \'le\' = him/it (m), \'la\' = her/it (f), \'les\' = them.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Je vois le chat. \u2192 Je le vois.", "en": "I see the cat. \u2192 I see it."}, {"fr": "Je vois la table. \u2192 Je la vois.", "en": "I see the table. \u2192 I see it."}, {"fr": "Je vois les livres. \u2192 Je les vois.", "en": "I see the books. \u2192 I see them."}, {"fr": "Tu aimes Marie ? \u2192 Oui, je l\\", "en": "You like Marie? \u2192 Yes, I like her."}]],
                            tip='Before a vowel, le/la become l\\',
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "suis"}, {"pronoun": "tu", "form": "es"}, {"pronoun": "il/elle", "form": "est"}, {"pronoun": "nous", "form": "sommes"}, {"pronoun": "vous", "form": "\u00eates"}, {"pronoun": "ils/elles", "form": "sont"}],
                                sentenceRule='Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je suis \u00e9tudiant.", "en": "I am a student."}, {"fr": "Tu es fran\u00e7ais ?", "en": "Are you French?"}, {"fr": "Nous sommes \u00e0 Paris.", "en": "We are in Paris."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='a2-u4-l1-conj-0-1', type='conjugation', prompt='Conjugate "être" for "je":', answer='suis', options=None, explanation='je suis — correct form of "être".'),
                            Exercise(id='a2-u4-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "être".', answer='', options=['est', 'suis', 'es', 'sommes'], explanation='il/elle est — correct conjugation of "être".'),
                            Exercise(id='a2-u4-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"', answer='suis', options=None, explanation='The correct form is "suis".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Sophie', fr='Tu habites où maintenant, Marc ?', en='Where do you live now, Marc?'),
                        DialogueLine(speaker='B', name='Marc', fr='J\\', en='I live in an apartment in Lyon. It has three rooms.'),
                        DialogueLine(speaker='A', name='Sophie', fr='C\\', en='Is it big? Do you have a balcony?'),
                        DialogueLine(speaker='B', name='Marc', fr='Oui, j\\', en='Yes, I have a balcony with a nice view. And I have a big living room with a comfortable sofa.'),
                        DialogueLine(speaker='A', name='Sophie', fr='Tu l\\', en='Do you like your apartment?'),
                        DialogueLine(speaker='B', name='Marc', fr='Oui, je l\\', en='Yes, I love it! And you, do you still live in your house?'),
                        DialogueLine(speaker='A', name='Sophie', fr='Oui, on l\\', en='Yes, we like it a lot. But we\\'),
                    ],
                    exercises=[
                        Exercise(id='a2-u4-l1-e1', type='multiple_choice', prompt='Replace the object: "Je vois Marie." → "Je _____ vois."', options=['le', 'la', 'les', 'lui'], answer=1, explanation='Marie is feminine singular → la. Je la vois.'),
                        Exercise(id='a2-u4-l1-e2', type='fill_blank', prompt='Complete: "Tu aimes les livres ? Oui, je _____ aime."', options=None, answer='les', explanation='Livres is plural → les. Je les aime.'),
                        Exercise(id='a2-u4-l1-e3', type='multiple_choice', prompt='Where do direct object pronouns go in French?', options=['After the verb', 'Before the verb', 'At the end', 'They don\\'], answer=1, explanation='In French, direct object pronouns go BEFORE the verb: Je le vois (not Je vois le).'),
                        Exercise(id='a2-u4-l1-e4', type='translate_to_fr', prompt='Translate: "I love it." (referring to "le livre", masculine)', options=None, answer='Je l\\', explanation='Le livre → le → l\\'),
                        Exercise(id='a2-u4-l1-e5', type='true_false', prompt='In French, direct object pronouns are placed before the conjugated verb.', options=['True', 'False'], answer=0, explanation='True. Je le vois = I see him/it. (Pronoun before verb.)'),
                    ],
                    culturalNote='In French cities, most people live in apartments, not houses. The typical French apartment has a \'salon\' (living room), \'cuisine\' (kitchen — often separate), \'chambres\' (bedrooms), and \'salle de bain\' (bathroom). The toilets (\'les WC\') are often in a separate tiny room! Rent in Paris is among the highest in Europe.',
                    estimatedMinutes=30,
                ),
            ],
        ),
        Unit(
            id='a2-u5',
            title='Food and Cooking',
            titleFr='Nourriture et cuisine',
            theme='Food vocabulary, recipes & pronouns Y/EN',
            description='Talk about food, follow a recipe, and use the pronouns y and en.',
            lessons=[
                Lesson(
                    id='a2-u5-l1',
                    title='In the Kitchen',
                    titleFr='Dans la cuisine',
                    description='Learn food vocabulary, kitchen verbs, and follow a simple recipe.',
                    objectives=["Name common foods (fruits, vegetables, meat, dairy)", "Use kitchen verbs (couper, m\u00e9langer, cuire)", "Follow a simple recipe in French", "Use the pronoun ", " for quantities"],
                    vocabulary=[
                        VocabItem(fr='la pomme', en='the apple', ipa='', example='Je mange une pomme.', exampleEn='I eat an apple.', category='fruits'),
                        VocabItem(fr='la banane', en='the banana', ipa='', example='Une banane mûre.', exampleEn='A ripe banana.', category='fruits'),
                        VocabItem(fr='l\\', en='the orange', ipa='', example='Un jus d\\', exampleEn='An orange juice.', category='fruits'),
                        VocabItem(fr='la fraise', en='the strawberry', ipa='', example='Des fraises avec de la crème.', exampleEn='Strawberries with cream.', category='fruits'),
                        VocabItem(fr='le citron', en='the lemon', ipa='', example='Un citron pressé.', exampleEn='A squeezed lemon.', category='fruits'),
                        VocabItem(fr='la tomate', en='the tomato', ipa='', example='Une salade de tomates.', exampleEn='A tomato salad.', category='vegetables'),
                        VocabItem(fr='la carotte', en='the carrot', ipa='', example='Des carottes râpées.', exampleEn='Grated carrots.', category='vegetables'),
                        VocabItem(fr='la pomme de terre', en='the potato', ipa='', example='Purée de pommes de terre.', exampleEn='Mashed potatoes.', category='vegetables'),
                        VocabItem(fr='l\'oignon', en='the onion', ipa='', example='Coupez l\\', exampleEn='Cut the onion.', category='vegetables'),
                        VocabItem(fr='l\'ail', en='the garlic', ipa='', example='Une gousse d\\', exampleEn='A clove of garlic.', category='vegetables'),
                        VocabItem(fr='la salade', en='the salad / lettuce', ipa='', example='Une salade verte.', exampleEn='A green salad.', category='vegetables'),
                        VocabItem(fr='le poulet', en='the chicken', ipa='', example='Du poulet rôti.', exampleEn='Roast chicken.', category='meat'),
                        VocabItem(fr='le bœuf', en='the beef', ipa='', example='Un steak de bœuf.', exampleEn='A beef steak.', category='meat'),
                        VocabItem(fr='le porc', en='the pork', ipa='', example='Du porc grillé.', exampleEn='Grilled pork.', category='meat'),
                        VocabItem(fr='le poisson', en='the fish', ipa='', example='Un poisson frais.', exampleEn='A fresh fish.', category='meat'),
                        VocabItem(fr='le fromage', en='the cheese', ipa='', example='Un plateau de fromages.', exampleEn='A cheese platter.', category='dairy'),
                        VocabItem(fr='le lait', en='the milk', ipa='', example='Un verre de lait.', exampleEn='A glass of milk.', category='dairy'),
                        VocabItem(fr='le beurre', en='the butter', ipa='', example='Du beurre sur la tartine.', exampleEn='Butter on the bread.', category='dairy'),
                        VocabItem(fr='la crème', en='the cream', ipa='', example='De la crème fraîche.', exampleEn='Fresh cream.', category='dairy'),
                        VocabItem(fr='les œufs', en='the eggs', ipa='', example='Trois œufs.', exampleEn='Three eggs.', category='dairy'),
                        VocabItem(fr='couper', en='to cut', ipa='', example='Coupez les tomates.', exampleEn='Cut the tomatoes.', category='verbs'),
                        VocabItem(fr='mélanger', en='to mix', ipa='', example='Mélangez le sucre et la farine.', exampleEn='Mix the sugar and flour.', category='verbs'),
                        VocabItem(fr='cuire', en='to cook', ipa='', example='Cuire au four 30 minutes.', exampleEn='Bake for 30 minutes.', category='verbs'),
                        VocabItem(fr='ajouter', en='to add', ipa='', example='Ajoutez du sel.', exampleEn='Add some salt.', category='verbs'),
                        VocabItem(fr='verser', en='to pour', ipa='', example='Versez le lait.', exampleEn='Pour the milk.', category='verbs'),
                        VocabItem(fr='la farine', en='the flour', ipa='', example='De la farine pour le gâteau.', exampleEn='Flour for the cake.', category='pantry'),
                        VocabItem(fr='le sucre', en='the sugar', ipa='', example='Du sucre dans le café.', exampleEn='Sugar in coffee.', category='pantry'),
                        VocabItem(fr='le sel', en='the salt', ipa='', example='Une pincée de sel.', exampleEn='A pinch of salt.', category='pantry'),
                        VocabItem(fr='le poivre', en='the pepper', ipa='', example='Du poivre noir.', exampleEn='Black pepper.', category='pantry'),
                        VocabItem(fr='l\'huile', en='the oil', ipa='', example='De l\'huile d\'olive.', exampleEn='Olive oil.', category='pantry'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='The pronoun "en" — for quantities',
                            explanation='The pronoun \'en\' replaces quantities and partitive articles. Use it to avoid repeating a noun. \'En\' generally goes before the verb.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Tu veux du pain ? \u2014 Oui, j\\", "en": "Do you want bread? \u2014 Yes, I want some (of it)."}, {"fr": "Tu as combien de pommes ? \u2014 J\\", "en": "How many apples do you have? \u2014 I have three (of them)."}, {"fr": "Tu ach\u00e8tes du fromage ? \u2014 J\\", "en": "Are you buying cheese? \u2014 I\\"}]],
                            tip='"En" replaces "du/de la/des + noun" or "number + de + noun". Always placed before the verb.',
                        ),
                        GrammarRule(
                            title='The pronoun "y" — for places',
                            explanation='The pronoun \'y\' replaces a place introduced by \'à\' (or another preposition of place). It means \'there\' in English. It goes before the verb.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Tu vas \u00e0 Paris ? \u2014 Oui, j\\", "en": "Are you going to Paris? \u2014 Yes, I\\"}, {"fr": "Tu es chez toi ? \u2014 Oui, j\\", "en": "Are you at home? \u2014 Yes, I\\"}, {"fr": "Tu vas au mus\u00e9e ? \u2014 J\\", "en": "Are you going to the museum? \u2014 I\\"}]],
                            tip='Y replaces à + place. Always placed before the verb. Common in everyday conversation.',
                        ),
                        GrammarRule(
                            title='Imperative in recipes',
                            explanation='French recipes use the imperative mood — the verb without a subject. For -er verbs, drop the -s in the tu form: \'tu manges\' → \'mange !\' (eat!).',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Coupez les tomates. (vous/both)", "en": "Cut the tomatoes."}, {"fr": "Ajoutez du sel. (vous/both)", "en": "Add salt."}, {"fr": "M\u00e9lange bien ! (tu, informal)", "en": "Mix well!"}]],
                            tip='Recipes typically use the \'vous\' form of imperative (coupez, ajoutez, mélangez) — even for one person — because it sounds more formal/standard.',
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='aller',
                                translation='to go',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "vais"}, {"pronoun": "tu", "form": "vas"}, {"pronoun": "il/elle", "form": "va"}, {"pronoun": "nous", "form": "allons"}, {"pronoun": "vous", "form": "allez"}, {"pronoun": "ils/elles", "form": "vont"}],
                                sentenceRule='Subject + aller + preposition + place. à + le = au, à + les = aux. Also: aller + infinitive = near future (Je vais manger).',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je vais au cin\u00e9ma.", "en": "I go to the cinema."}, {"fr": "Nous allons \u00e0 Paris.", "en": "We go to Paris."}, {"fr": "Je vais manger.", "en": "I am going to eat."}]],
                            ),
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "suis"}, {"pronoun": "tu", "form": "es"}, {"pronoun": "il/elle", "form": "est"}, {"pronoun": "nous", "form": "sommes"}, {"pronoun": "vous", "form": "\u00eates"}, {"pronoun": "ils/elles", "form": "sont"}],
                                sentenceRule='Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je suis \u00e9tudiant.", "en": "I am a student."}, {"fr": "Tu es fran\u00e7ais ?", "en": "Are you French?"}, {"fr": "Nous sommes \u00e0 Paris.", "en": "We are in Paris."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='a2-u5-l1-conj-0-1', type='conjugation', prompt='Conjugate "aller" for "je":', answer='vais', options=None, explanation='je vais — correct form of "aller".'),
                            Exercise(id='a2-u5-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "aller".', answer='', options=['va', 'vais', 'vas', 'allons'], explanation='il/elle va — correct conjugation of "aller".'),
                            Exercise(id='a2-u5-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "Je _____ au cinéma." (I go to the cinema.) — form of "aller"', answer='vais', options=None, explanation='The correct form is "vais".'),
                            Exercise(id='a2-u5-l1-conj-1-1', type='conjugation', prompt='Conjugate "être" for "tu":', answer='es', options=None, explanation='tu es — correct form of "être".'),
                            Exercise(id='a2-u5-l1-conj-1-2', type='multiple_choice', prompt='Complete: "nous _____" with the correct form of "être".', answer='', options=['sommes', 'suis', 'es', 'est'], explanation='nous sommes — correct conjugation of "être".'),
                            Exercise(id='a2-u5-l1-conj-1-3', type='fill_blank', prompt='Fill in the blank: "Tu _____ français ?" (Are you French?) — form of "être"', answer='es', options=None, explanation='The correct form is "es".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Marie', fr='Tu veux m\\', en='Do you want to help me make a cake?'),
                        DialogueLine(speaker='B', name='Luc', fr='Bien sûr ! Qu\\', en='Of course! What are we making?'),
                        DialogueLine(speaker='A', name='Marie', fr='Un gâteau au chocolat. D\\', en='A chocolate cake. First, crack three eggs into a bowl.'),
                        DialogueLine(speaker='B', name='Luc', fr='Ensuite ?', en='Then?'),
                        DialogueLine(speaker='A', name='Marie', fr='Ajoute 100 grammes de sucre et mélange bien. Puis, ajoute la farine et le chocolat fondu.', en='Add 100 grams of sugar and mix well. Then, add the flour and melted chocolate.'),
                        DialogueLine(speaker='B', name='Luc', fr='On cuit combien de temps ?', en='How long do we bake it?'),
                        DialogueLine(speaker='A', name='Marie', fr='On cuit 30 minutes à 180 degrés. Tu veux goûter la pâte ?', en='We bake for 30 minutes at 180 degrees. Do you want to taste the batter?'),
                        DialogueLine(speaker='B', name='Luc', fr='Oui, j\\', en='Yes, I want some! (using en)'),
                    ],
                    exercises=[
                        Exercise(id='a2-u5-l1-e1', type='multiple_choice', prompt='Complete with the pronoun "en": "Tu veux du pain ? — Oui, j\\', options=['y', 'en', 'le', 'la'], answer=1, explanation='En replaces "du pain" (partitive + noun).'),
                        Exercise(id='a2-u5-l1-e2', type='multiple_choice', prompt='Complete with "y": "Tu vas à Paris ? — Oui, j\\', options=['y', 'en', 'le', 'y en'], answer=0, explanation='Y replaces "à Paris" (place preposition + location).'),
                        Exercise(id='a2-u5-l1-e3', type='fill_blank', prompt='Complete: "Tu as combien de pommes ? — J\\', options=None, answer='en', explanation='En replaces "de pommes" after a quantity.'),
                        Exercise(id='a2-u5-l1-e4', type='matching', prompt='Match each food to its French name.', options=None, answer=None, explanation=''),
                        Exercise(id='a2-u5-l1-e5', type='true_false', prompt='"En" is used to replace quantities and partitive articles.', options=['True', 'False'], answer=0, explanation='True. En replaces "du/de la/des + noun" or quantities.'),
                        Exercise(id='a2-u5-l1-e6', type='translate_to_fr', prompt='Translate (using en): "I want some." (referring to "du fromage")', options=None, answer="J'en veux", explanation='En replaces "du fromage". J\\'),
                        Exercise(id='a2-u5-l1-e7', type='multiple_choice', prompt='What does "Cuire au four" mean?', options=['Cut the oven', 'Bake in the oven', 'Open the oven', 'Clean the oven'], answer=1, explanation='Cuire = to cook. Au four = in the oven. So "bake in the oven".'),
                    ],
                    activities=[
                        Exercise(id='a2-u5-l1-a1', type='word_bank', prompt='Build: "I eat an apple."', options=None, answer='Je mange une pomme', explanation='Standard subject + verb + article + noun.'),
                        Exercise(id='a2-u5-l1-a2', type='dictation', prompt='Listen and type what you hear.', options=None, answer='Ajoutez du sel et du poivre.', explanation='A typical recipe instruction.'),
                        Exercise(id='a2-u5-l1-a3', type='pronoun_replace', prompt='Replace the underlined noun with "en": "Tu veux _____du fromage_____ ?" → "Oui, j\\', options=None, answer='en', explanation='En replaces du fromage.'),
                        Exercise(id='a2-u5-l1-a4', type='reorder', prompt='Reorder the recipe instruction: "sel / ajoutez / du"', options=None, answer='Ajoutez du sel.', explanation='Imperative form: Ajoutez + du + sel.'),
                        Exercise(id='a2-u5-l1-a5', type='matching', prompt='Match each kitchen verb to its English meaning.', options=None, answer=None, explanation=''),
                        Exercise(id='a2-u5-l1-a6', type='fill_blank', prompt='Complete with "en": "Tu achètes du pain ? — Oui, j\\', options=None, answer='en', explanation='En replaces "du pain".'),
                    ],
                    culturalNote='French cuisine is famously listed as an Intangible Cultural Heritage by UNESCO. The traditional French meal has 4 courses: entrée (starter), plat principal (main dish), fromage (cheese), and dessert. The baguette is so important that French law defines what can be called a \'baguette de tradition française\' — only flour, water, salt, and yeast, no additives. The average French person eats 30 kg of cheese per year — the highest in the world!',
                    estimatedMinutes=40,
                ),
            ],
        ),
        Unit(
            id='a2-u6',
            title='Shopping and Clothing',
            titleFr='Les achats et les vêtements',
            theme='Clothing vocabulary, comparisons & shopping',
            description='Shop for clothes, ask for sizes, and use comparative and superlative forms.',
            lessons=[
                Lesson(
                    id='a2-u6-l1',
                    title='Buying Clothes',
                    titleFr='Acheter des vêtements',
                    description='Learn clothing vocabulary, ask for sizes, and use comparatives.',
                    objectives=["Name clothing items (chemise, pantalon, robe)", "Ask for sizes and colors", "Use comparatives (plus...que, moins...que, aussi...que)", "Use superlatives (le plus, le moins)"],
                    vocabulary=[
                        VocabItem(fr='le vêtement', en='the clothing item', ipa='', example='Un vêtement chaud.', exampleEn='A warm clothing item.', category='clothing'),
                        VocabItem(fr='la chemise', en='the shirt', ipa='', example='Une chemise blanche.', exampleEn='A white shirt.', category='clothing'),
                        VocabItem(fr='le pantalon', en='the pants', ipa='', example='Un pantalon noir.', exampleEn='Black pants.', category='clothing'),
                        VocabItem(fr='la robe', en='the dress', ipa='', example='Une robe rouge.', exampleEn='A red dress.', category='clothing'),
                        VocabItem(fr='la jupe', en='the skirt', ipa='', example='Une jupe longue.', exampleEn='A long skirt.', category='clothing'),
                        VocabItem(fr='le pull', en='the sweater', ipa='', example='Un pull en laine.', exampleEn='A wool sweater.', category='clothing'),
                        VocabItem(fr='le t-shirt', en='the t-shirt', ipa='', example='Un t-shirt bleu.', exampleEn='A blue t-shirt.', category='clothing'),
                        VocabItem(fr='la veste', en='the jacket', ipa='', example='Une veste en cuir.', exampleEn='A leather jacket.', category='clothing'),
                        VocabItem(fr='le manteau', en='the coat', ipa='', example='Un manteau d\\', exampleEn='A winter coat.', category='clothing'),
                        VocabItem(fr='les chaussures', en='the shoes', ipa='', example='Des chaussures noires.', exampleEn='Black shoes.', category='clothing'),
                        VocabItem(fr='les baskets', en='the sneakers', ipa='', example='Des baskets blanches.', exampleEn='White sneakers.', category='clothing'),
                        VocabItem(fr='les chaussettes', en='the socks', ipa='', example='Une paire de chaussettes.', exampleEn='A pair of socks.', category='clothing'),
                        VocabItem(fr='le chapeau', en='the hat', ipa='', example='Un chapeau noir.', exampleEn='A black hat.', category='clothing'),
                        VocabItem(fr='les lunettes', en='the glasses', ipa='', example='Des lunettes de soleil.', exampleEn='Sunglasses.', category='clothing'),
                        VocabItem(fr='la taille', en='the size (clothing)', ipa='', example='Quelle est votre taille ?', exampleEn='What is your size?', category='shopping'),
                        VocabItem(fr='la pointure', en='the size (shoes)', ipa='', example='Quelle est votre pointure ?', exampleEn='What is your shoe size?', category='shopping'),
                        VocabItem(fr='petit(e)', en='small', ipa='', example='Une petite taille.', exampleEn='A small size.', category='sizes'),
                        VocabItem(fr='moyen(ne)', en='medium', ipa='', example='Une taille moyenne.', exampleEn='A medium size.', category='sizes'),
                        VocabItem(fr='grand(e)', en='large / big', ipa='', example='Une grande taille.', exampleEn='A large size.', category='sizes'),
                        VocabItem(fr='essayer', en='to try on', ipa='', example='Je voudrais essayer.', exampleEn='I would like to try on.', category='verbs'),
                        VocabItem(fr='ça va', en='it fits', ipa='', example='Ça va, cette chemise ?', exampleEn='Does this shirt fit?', category='shopping'),
                        VocabItem(fr='ça ne va pas', en='it doesn\\', ipa='', example='Ça ne va pas.', exampleEn='It doesn\\', category='shopping'),
                        VocabItem(fr='trop petit', en='too small', ipa='', example='C\\', exampleEn='It\\', category='sizes'),
                        VocabItem(fr='trop grand', en='too big', ipa='', example='C\\', exampleEn='It\\', category='sizes'),
                        VocabItem(fr='rouge', en='red', ipa='', example='Une robe rouge.', exampleEn='A red dress.', category='colors'),
                        VocabItem(fr='bleu(e)', en='blue', ipa='', example='Un t-shirt bleu.', exampleEn='A blue t-shirt.', category='colors'),
                        VocabItem(fr='vert(e)', en='green', ipa='', example='Une veste verte.', exampleEn='A green jacket.', category='colors'),
                        VocabItem(fr='noir(e)', en='black', ipa='', example='Un pantalon noir.', exampleEn='Black pants.', category='colors'),
                        VocabItem(fr='blanc(he)', en='white', ipa='', example='Une chemise blanche.', exampleEn='A white shirt.', category='colors'),
                        VocabItem(fr='jaune', en='yellow', ipa='', example='Un pull jaune.', exampleEn='A yellow sweater.', category='colors'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Comparatives — plus / moins / aussi...que',
                            explanation='To compare two things in French, use \'plus...que\' (more...than), \'moins...que\' (less...than), or \'aussi...que\' (as...as). The adjective goes between plus/moins/aussi and que.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Cette robe est plus ch\u00e8re que celle-ci.", "en": "This dress is more expensive than this one."}, {"fr": "Ce pantalon est moins cher que l\\", "en": "These pants are less expensive than the other."}, {"fr": "Cette chemise est aussi belle que celle-l\u00e0.", "en": "This shirt is as beautiful as that one."}]],
                            tip='The adjective agrees in gender/number with the noun it describes: cher → chère (f), chers (m pl), chères (f pl).',
                        ),
                        GrammarRule(
                            title='Superlatives — le plus / le moins',
                            explanation='For the superlative (the most, the least), use \'le/la/les plus\' or \'le/la/les moins\' before the adjective.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "C\\", "en": "It\\"}, {"fr": "C\\", "en": "It\\"}, {"fr": "Ce sont les meilleures chaussures.", "en": "These are the best shoes. (bon \u2192 meilleur, irregular)"}]],
                            tip='Good → meilleur (better), best → le meilleur. Bad → pire (worse), worst → le pire. These are irregular.',
                        ),
                        GrammarRule(
                            title='Demonstrative adjectives — ce, cet, cette, ces',
                            explanation='Demonstrative adjectives point out specific things: \'this/that/these/those\'. Use \'ce\' for masculine singular, \'cet\' for masculine singular before a vowel, \'cette\' for feminine singular, \'ces\' for plural (both genders).',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "ce pull (m)", "en": "this sweater"}, {"fr": "cet imperm\u00e9able (m, vowel)", "en": "this raincoat"}, {"fr": "cette robe (f)", "en": "this dress"}, {"fr": "ces chaussures (pl)", "en": "these shoes"}]],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "ai"}, {"pronoun": "tu", "form": "as"}, {"pronoun": "il/elle", "form": "a"}, {"pronoun": "nous", "form": "avons"}, {"pronoun": "vous", "form": "avez"}, {"pronoun": "ils/elles", "form": "ont"}],
                                sentenceRule='Subject + avoir + noun. Used for possession, age (J\\',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "J\\", "en": "I have a brother."}, {"fr": "Tu as vingt ans.", "en": "You are twenty."}, {"fr": "Il a faim.", "en": "He is hungry."}]],
                            ),
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "suis"}, {"pronoun": "tu", "form": "es"}, {"pronoun": "il/elle", "form": "est"}, {"pronoun": "nous", "form": "sommes"}, {"pronoun": "vous", "form": "\u00eates"}, {"pronoun": "ils/elles", "form": "sont"}],
                                sentenceRule='Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je suis \u00e9tudiant.", "en": "I am a student."}, {"fr": "Tu es fran\u00e7ais ?", "en": "Are you French?"}, {"fr": "Nous sommes \u00e0 Paris.", "en": "We are in Paris."}]],
                            ),
                            ConjugationVerb(
                                infinitive='aller',
                                translation='to go',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "vais"}, {"pronoun": "tu", "form": "vas"}, {"pronoun": "il/elle", "form": "va"}, {"pronoun": "nous", "form": "allons"}, {"pronoun": "vous", "form": "allez"}, {"pronoun": "ils/elles", "form": "vont"}],
                                sentenceRule='Subject + aller + preposition + place. à + le = au, à + les = aux. Also: aller + infinitive = near future (Je vais manger).',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je vais au cin\u00e9ma.", "en": "I go to the cinema."}, {"fr": "Nous allons \u00e0 Paris.", "en": "We go to Paris."}, {"fr": "Je vais manger.", "en": "I am going to eat."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='a2-u6-l1-conj-0-1', type='conjugation', prompt='Conjugate "avoir" for "j\\', answer='ai', options=None, explanation='j\\'),
                            Exercise(id='a2-u6-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "avoir".', answer='', options=['a', 'ai', 'as', 'avons'], explanation='il/elle a — correct conjugation of "avoir".'),
                            Exercise(id='a2-u6-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "J\\', answer='ai', options=None, explanation='The correct form is "ai".'),
                            Exercise(id='a2-u6-l1-conj-1-1', type='conjugation', prompt='Conjugate "être" for "tu":', answer='es', options=None, explanation='tu es — correct form of "être".'),
                            Exercise(id='a2-u6-l1-conj-1-2', type='multiple_choice', prompt='Complete: "nous _____" with the correct form of "être".', answer='', options=['sommes', 'suis', 'es', 'est'], explanation='nous sommes — correct conjugation of "être".'),
                            Exercise(id='a2-u6-l1-conj-1-3', type='fill_blank', prompt='Fill in the blank: "Tu _____ français ?" (Are you French?) — form of "être"', answer='es', options=None, explanation='The correct form is "es".'),
                            Exercise(id='a2-u6-l1-conj-2-1', type='conjugation', prompt='Conjugate "aller" for "il/elle":', answer='va', options=None, explanation='il/elle va — correct form of "aller".'),
                            Exercise(id='a2-u6-l1-conj-2-2', type='multiple_choice', prompt='Complete: "vous _____" with the correct form of "aller".', answer='', options=['allez', 'vais', 'vas', 'va'], explanation='vous allez — correct conjugation of "aller".'),
                            Exercise(id='a2-u6-l1-conj-2-3', type='fill_blank', prompt='Fill in the blank: "Je _____ manger." (I am going to eat.) — form of "aller"', answer='vais', options=None, explanation='The correct form is "vais".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Vendeur', fr='Bonjour, je peux vous aider ?', en='Hello, can I help you?'),
                        DialogueLine(speaker='B', name='Cliente', fr='Oui, je cherche une chemise blanche.', en='Yes, I\\'),
                        DialogueLine(speaker='A', name='Vendeur', fr='Quelle taille ?', en='What size?'),
                        DialogueLine(speaker='B', name='Cliente', fr='Taille M. Et je voudrais essayer.', en='Size M. And I\\'),
                        DialogueLine(speaker='A', name='Vendeur', fr='Voici. La cabine est par là.', en='Here you go. The fitting room is over there.'),
                        DialogueLine(speaker='B', name='Cliente', fr='Cette chemise est trop petite. Vous avez une taille plus grande ?', en='This shirt is too small. Do you have a bigger size?'),
                        DialogueLine(speaker='A', name='Vendeur', fr='Oui, voici la taille L. C\\', en='Yes, here\\'),
                        DialogueLine(speaker='B', name='Cliente', fr='Parfait, elle me va. Combien ça coûte ?', en='Perfect, it fits me. How much does it cost?'),
                    ],
                    exercises=[
                        Exercise(id='a2-u6-l1-e1', type='multiple_choice', prompt='Complete: "Cette robe est _____ chère que celle-ci." (more expensive)', options=['plus', 'moins', 'aussi', 'très'], answer=0, explanation='Plus...que = more...than.'),
                        Exercise(id='a2-u6-l1-e2', type='fill_blank', prompt='Complete: "Ce pantalon est _____ cher que l\\', options=None, answer='moins', explanation='Moins...que = less...than.'),
                        Exercise(id='a2-u6-l1-e3', type='multiple_choice', prompt='Which demonstrative: "_____ robe" (this dress, feminine)?', options=['ce', 'cet', 'cette', 'ces'], answer=2, explanation='Robe is feminine singular → cette.'),
                        Exercise(id='a2-u6-l1-e4', type='multiple_choice', prompt='Which demonstrative: "_____ imperméable" (this raincoat, masculine starting with vowel)?', options=['ce', 'cet', 'cette', 'ces'], answer=1, explanation='Before a vowel, ce becomes cet (even for masculine).'),
                        Exercise(id='a2-u6-l1-e5', type='true_false', prompt='"Le meilleur" means "the best".', options=['True', 'False'], answer=0, explanation='True. Bon → meilleur (better), le meilleur (the best) — irregular comparative/superlative.'),
                        Exercise(id='a2-u6-l1-e6', type='matching', prompt='Match each clothing item to its French name.', options=None, answer=None, explanation=''),
                        Exercise(id='a2-u6-l1-e7', type='translate_to_fr', prompt='Translate: "It\\', options=None, answer="C'est trop petit", explanation='C\\'),
                    ],
                    activities=[
                        Exercise(id='a2-u6-l1-a1', type='word_bank', prompt='Build: "I am looking for a white shirt."', options=None, answer='Je cherche une chemise blanche', explanation='Chercher = to look for. Blanche agrees with chemise (f).'),
                        Exercise(id='a2-u6-l1-a2', type='dictation', prompt='Listen and type what you hear.', options=None, answer='Cette chemise est trop petite.', explanation='A common fitting-room comment.'),
                        Exercise(id='a2-u6-l1-a3', type='transformation', prompt='Make comparative: "Cette robe est belle." → "Cette robe est _____ belle _____ l\\', options=None, answer='aussi, que', explanation='aussi...que = as...as.'),
                        Exercise(id='a2-u6-l1-a4', type='fill_blank', prompt='Complete: "C\\', options=None, answer='la', explanation='Superlative: la plus belle (la + plus + adjective).'),
                        Exercise(id='a2-u6-l1-a5', type='matching', prompt='Match each color to its French name.', options=None, answer=None, explanation=''),
                        Exercise(id='a2-u6-l1-a6', type='reorder', prompt='Reorder: "vous / quelle / taille / ?"', options=None, answer='Quelle taille êtes-vous ?', explanation='Actually the more common form is "Quelle est votre taille ?"'),
                    ],
                    culturalNote='French fashion is world-famous — Paris is one of the fashion capitals of the world along with Milan, London, and New York. Famous French brands include Chanel, Dior, Louis Vuitton, Hermès, and Saint Laurent. The French \'soldes\' (sales) happen twice a year — in January-February and June-July — by law. Outside of these periods, shops cannot discount items as much. This is unique to France!',
                    estimatedMinutes=40,
                ),
            ],
        ),
    ],
)