from .types import *

# B1 Course
b1_course = Course(
    level='B1',
    title='B1 — Intermédiaire',
    book='Parlez B1',
    description='Step into the intermediate level. You\'ll learn to express opinions, defend arguments, use the subjunctive and conditional, and engage with real-world French media — news, debates, films, and literature.',
    cefrDescription='Can understand the main points of clear standard input on familiar matters regularly encountered in work, school, leisure, etc. Can deal with most situations likely to arise while traveling. Can produce simple connected text on topics that are familiar or of personal interest.',
    color='#B45309',
    units=[
        Unit(
            id='b1-u1',
            title='Opinions and Arguments',
            titleFr='Opinions et arguments',
            theme='Expressing opinions & logical connectors',
            description='Express nuanced opinions, agree and disagree, and use logical connectors.',
            lessons=[
                Lesson(
                    id='b1-u1-l1',
                    title='Expressing Your Opinion',
                    titleFr='Exprimer son opinion',
                    description='Use structures like "à mon avis", "je pense que", "il me semble que" to express opinions.',
                    objectives=["Express opinions formally and informally", "Agree and disagree politely", "Use logical connectors (cependant, n\u00e9anmoins, en revanche)", "Structure a short argument"],
                    vocabulary=[
                        VocabItem(fr='à mon avis', en='in my opinion', ipa='', example='À mon avis, il faut agir maintenant.', exampleEn='In my opinion, we must act now.', category='opinion'),
                        VocabItem(fr='je pense que', en='I think that', ipa='', example='Je pense que c\\', exampleEn='I think it\\', category='opinion'),
                        VocabItem(fr='il me semble que', en='it seems to me that', ipa='', example='Il me semble qu\\', exampleEn='It seems to me he\\', category='opinion'),
                        VocabItem(fr='selon moi', en='according to me', ipa='', example='Selon moi, le projet est viable.', exampleEn='According to me, the project is viable.', category='opinion'),
                        VocabItem(fr='je suis d\\', en='I agree', ipa='', example='Je suis d\\', exampleEn='I agree with you.', category='agreement'),
                        VocabItem(fr='je ne suis pas d\\', en='I disagree', ipa='', example='Je ne suis pas d\\', exampleEn='I disagree.', category='agreement'),
                        VocabItem(fr='c\\', en='it\\', ipa='', example='C\\', exampleEn='It\\', category='agreement'),
                        VocabItem(fr='cependant', en='however', ipa='', example='C\\', exampleEn='It\\', category='connectors'),
                        VocabItem(fr='néanmoins', en='nevertheless', ipa='', example='Il pleut ; néanmoins, je sors.', exampleEn='It\\', category='connectors'),
                        VocabItem(fr='en revanche', en='on the other hand', ipa='', example='Il est intelligent ; en revanche, il est paresseux.', exampleEn='He\\', category='connectors'),
                        VocabItem(fr='par conséquent', en='consequently', ipa='', example='Il a neigé ; par conséquent, les routes sont fermées.', exampleEn='It snowed; consequently, roads are closed.', category='connectors'),
                        VocabItem(fr='en effet', en='indeed / in fact', ipa='', example='Il est fatigué. En effet, il a beaucoup travaillé.', exampleEn='He\\', category='connectors'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Structuring an argument',
                            explanation='A good argument in French follows a clear structure: introduce the topic, state your opinion, give reasons with examples, acknowledge the counter-argument, and conclude. Logical connectors help guide the reader/listener.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "\u00c0 mon avis, le t\u00e9l\u00e9travail est positif. D\\", "en": "In my opinion, remote work is positive. First, it saves time. Then, it reduces stress. However, it can isolate. In conclusion, it\\"}]],
                            tip='When you disagree, soften it: "Je comprends ton point de vue, mais..." (I understand your point, but...).',
                        ),
                        GrammarRule(
                            title='Il me semble que + indicatif ou subjonctif ?',
                            explanation='\'Il me semble que\' is followed by the indicative when expressing your own perception: \'Il me semble qu\\\'il est tard.\' But \'Il ne me semble pas que\' (negative) takes the subjunctive: \'Il ne me semble pas qu\\\'il soit tard.\'',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Il me semble qu\\", "en": "It seems to me he\\"}, {"fr": "Il me semble qu\\", "en": "It seems to me she\\"}]],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "suis"}, {"pronoun": "tu", "form": "es"}, {"pronoun": "il/elle", "form": "est"}, {"pronoun": "nous", "form": "sommes"}, {"pronoun": "vous", "form": "\u00eates"}, {"pronoun": "ils/elles", "form": "sont"}],
                                sentenceRule='Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je suis \u00e9tudiant.", "en": "I am a student."}, {"fr": "Tu es fran\u00e7ais ?", "en": "Are you French?"}, {"fr": "Nous sommes \u00e0 Paris.", "en": "We are in Paris."}]],
                            ),
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "ai"}, {"pronoun": "tu", "form": "as"}, {"pronoun": "il/elle", "form": "a"}, {"pronoun": "nous", "form": "avons"}, {"pronoun": "vous", "form": "avez"}, {"pronoun": "ils/elles", "form": "ont"}],
                                sentenceRule='Subject + avoir + noun. Used for possession, age (J\\',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "J\\", "en": "I have a brother."}, {"fr": "Tu as vingt ans.", "en": "You are twenty."}, {"fr": "Il a faim.", "en": "He is hungry."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='b1-u1-l1-conj-0-1', type='conjugation', prompt='Conjugate "être" for "je":', answer='suis', options=None, explanation='je suis — correct form of "être".'),
                            Exercise(id='b1-u1-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "être".', answer='', options=['est', 'suis', 'es', 'sommes'], explanation='il/elle est — correct conjugation of "être".'),
                            Exercise(id='b1-u1-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"', answer='suis', options=None, explanation='The correct form is "suis".'),
                            Exercise(id='b1-u1-l1-conj-1-1', type='conjugation', prompt='Conjugate "avoir" for "tu":', answer='as', options=None, explanation='tu as — correct form of "avoir".'),
                            Exercise(id='b1-u1-l1-conj-1-2', type='multiple_choice', prompt='Complete: "nous _____" with the correct form of "avoir".', answer='', options=['avons', 'ai', 'as', 'a'], explanation='nous avons — correct conjugation of "avoir".'),
                            Exercise(id='b1-u1-l1-conj-1-3', type='fill_blank', prompt='Fill in the blank: "Tu _____ vingt ans." (You are twenty.) — form of "avoir"', answer='as', options=None, explanation='The correct form is "as".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Claire', fr='À mon avis, le télétravail devrait devenir la norme. Qu\\', en='In my opinion, remote work should become the norm. What do you think?'),
                        DialogueLine(speaker='B', name='Antoine', fr='Je ne suis pas d\\', en='I disagree. According to me, in-person work favors creativity and social ties.'),
                        DialogueLine(speaker='A', name='Claire', fr='C\\', en='It\\'),
                        DialogueLine(speaker='B', name='Antoine', fr='Je comprends ton point de vue. Néanmoins, beaucoup de personnes se sentent isolées chez elles.', en='I understand your point. Nevertheless, many people feel isolated at home.'),
                        DialogueLine(speaker='A', name='Claire', fr='En effet, c\\', en='Indeed, that\\'),
                        DialogueLine(speaker='B', name='Antoine', fr='Là, je suis tout à fait d\\', en='There, I completely agree with you! It\\'),
                    ],
                    exercises=[
                        Exercise(id='b1-u1-l1-e1', type='multiple_choice', prompt='Which expression means "in my opinion"?', options=['En effet', 'À mon avis', 'Par conséquent', 'En revanche'], answer=1, explanation='À mon avis = in my opinion. Other options: en effet (indeed), par conséquent (consequently), en revanche (on the other hand).'),
                        Exercise(id='b1-u1-l1-e2', type='fill_blank', prompt='Complete: "Il pleut ; _____, je prends mon parapluie." (therefore)', options=None, answer='par conséquent', explanation='Par conséquent = consequently/therefore. "Donc" also works.'),
                        Exercise(id='b1-u1-l1-e3', type='multiple_choice', prompt='Which connector expresses opposition?', options=['De plus', 'Ensuite', 'Cependant', 'Donc'], answer=2, explanation='Cependant = however. De plus (addition), Ensuite (sequence), Donc (consequence).'),
                        Exercise(id='b1-u1-l1-e4', type='translate_to_fr', prompt='Translate: "However, I disagree."', options=None, answer='Cependant, je ne suis pas d\\', explanation='Cependant / néanmoins / en revanche = however. Je ne suis pas d\\'),
                        Exercise(id='b1-u1-l1-e5', type='true_false', prompt='"En revanche" is used to introduce an opposing idea.', options=['True', 'False'], answer=0, explanation='True. En revanche = on the other hand / however.'),
                    ],
                    culturalNote='The French love debate (\'le débat\'). It is a national sport — discussions about politics, philosophy, food, or cinema can last hours. The French school system trains students in \'la dissertation\' (structured essay with thesis, antithesis, synthesis) from age 15. Don\'t be surprised if a casual dinner turns into a passionate debate!',
                    estimatedMinutes=35,
                ),
                Lesson(
                    id='b1-u1-l2',
                    title='The Subjunctive Mood',
                    titleFr='Le subjonctif présent',
                    description='Learn when and how to use the subjunctive — essential for expressing doubt, emotion, and necessity.',
                    objectives=["Form the present subjunctive of regular verbs", "Recognize common irregular subjunctives", "Use the subjunctive after expressions of necessity", "Use the subjunctive after expressions of emotion"],
                    vocabulary=[
                        VocabItem(fr='il faut que', en='it is necessary that', ipa='', example='Il faut que tu viennes.', exampleEn='It\\', category='subjunctive triggers'),
                        VocabItem(fr='je veux que', en='I want that', ipa='', example='Je veux que tu saches la vérité.', exampleEn='I want you to know the truth.', category='subjunctive triggers'),
                        VocabItem(fr='j\\', en='I\\', ipa='', example='J\\', exampleEn='I\\', category='subjunctive triggers'),
                        VocabItem(fr='je suis content que', en='I\\', ipa='', example='Je suis content que tu sois là.', exampleEn='I\\', category='subjunctive triggers'),
                        VocabItem(fr='bien que', en='although', ipa='', example='Bien qu\\', exampleEn='Although he\\', category='subjunctive triggers'),
                        VocabItem(fr='pour que', en='so that', ipa='', example='Je t\\', exampleEn='I explain so that you understand.', category='subjunctive triggers'),
                        VocabItem(fr='avant que', en='before', ipa='', example='Avant qu\\', exampleEn='Before he arrives, finish your work.', category='subjunctive triggers'),
                        VocabItem(fr='sans que', en='without', ipa='', example='Il est parti sans qu\\', exampleEn='He left without anyone seeing him.', category='subjunctive triggers'),
                        VocabItem(fr='douter que', en='to doubt that', ipa='', example='Je doute qu\\', exampleEn='I doubt he\\', category='subjunctive triggers'),
                        VocabItem(fr='il est important que', en='it is important that', ipa='', example='Il est important que nous parlions.', exampleEn='It\\', category='subjunctive triggers'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Forming the present subjunctive',
                            explanation='Take the ils/elles form of the present indicative, drop the -ent ending, and add the subjunctive endings: -e, -es, -e, -ions, -iez, -ent. For -er verbs, the subjunctive looks identical to the present indicative (except nous and vous).',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "parler \u2192 ils parlent \u2192 parl- \u2192 que je parle", "en": "to speak \u2192 that I speak"}, {"fr": "finir \u2192 ils finissent \u2192 finiss- \u2192 que je finisse", "en": "to finish \u2192 that I finish"}, {"fr": "attendre \u2192 ils attendent \u2192 attend- \u2192 que j\\", "en": "to wait \u2192 that I wait"}]],
                            tip='The nous and vous forms are always different from the present indicative — they take -ions and -iez.',
                        ),
                        GrammarRule(
                            title='Common irregular subjunctives',
                            explanation='Some verbs have irregular subjunctive stems. The most common: être, avoir, aller, faire, pouvoir, savoir, vouloir.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "\u00eatre \u2192 que je sois, que tu sois, qu\\", "en": "that I am"}, {"fr": "avoir \u2192 que j\\", "en": "that I have"}, {"fr": "faire \u2192 que je fasse, que tu fasses, qu\\", "en": "that I do"}, {"fr": "pouvoir \u2192 que je puisse, que tu puisses...", "en": "that I can"}, {"fr": "savoir \u2192 que je sache, que tu saches...", "en": "that I know"}]],
                            tip='For être, the stem is "soi-". For avoir, the stem is "ai-". These must be memorized.',
                        ),
                        GrammarRule(
                            title='When to use the subjunctive',
                            explanation='The subjunctive is used after expressions of: necessity (il faut que), wish/desire (je veux que), emotion (je suis content que), doubt (je doute que), and certain conjunctions (bien que, pour que, avant que). The subjunctive expresses subjectivity, not facts.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Il faut que tu partes maintenant.", "en": "You must leave now."}, {"fr": "Je suis ravi que vous soyez venus.", "en": "I\\"}, {"fr": "Bien qu\\", "en": "Although he\\"}]],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "ai"}, {"pronoun": "tu", "form": "as"}, {"pronoun": "il/elle", "form": "a"}, {"pronoun": "nous", "form": "avons"}, {"pronoun": "vous", "form": "avez"}, {"pronoun": "ils/elles", "form": "ont"}],
                                sentenceRule='Subject + avoir + noun. Used for possession, age (J\\',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "J\\", "en": "I have a brother."}, {"fr": "Tu as vingt ans.", "en": "You are twenty."}, {"fr": "Il a faim.", "en": "He is hungry."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='b1-u1-l2-conj-0-1', type='conjugation', prompt='Conjugate "avoir" for "j\\', answer='ai', options=None, explanation='j\\'),
                            Exercise(id='b1-u1-l2-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "avoir".', answer='', options=['a', 'ai', 'as', 'avons'], explanation='il/elle a — correct conjugation of "avoir".'),
                            Exercise(id='b1-u1-l2-conj-0-3', type='fill_blank', prompt='Fill in the blank: "J\\', answer='ai', options=None, explanation='The correct form is "ai".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Mère', fr='Il faut que tu fasses tes devoirs avant de sortir !', en='You must do your homework before going out!'),
                        DialogueLine(speaker='B', name='Fils', fr='Mais maman, je veux que mes amis m\\', en='But mom, I want my friends to wait for me!'),
                        DialogueLine(speaker='A', name='Mère', fr='Bien que tu sois pressé, les devoirs sont importants. Il faut que tu les finisses.', en='Although you\\'),
                        DialogueLine(speaker='B', name='Fils', fr='D\\', en='OK. But I doubt I can finish before 6 PM.'),
                        DialogueLine(speaker='A', name='Mère', fr='Je suis contente que tu comprennes. Fais de ton mieux !', en='I\\'),
                        DialogueLine(speaker='B', name='Fils', fr='D\\', en='OK mom. So that you\\'),
                    ],
                    exercises=[
                        Exercise(id='b1-u1-l2-e1', type='multiple_choice', prompt='Complete: "Il faut que tu _____." (you must come)', options=['viens', 'viennes', 'venir', 'venirs'], answer=1, explanation='After "il faut que", use subjunctive: tu viennes.'),
                        Exercise(id='b1-u1-l2-e2', type='fill_blank', prompt='Subjunctive of "être": "Je suis content que tu _____ là."', options=None, answer='sois', explanation='Subjunctive of être: que je sois, que tu sois, qu\\'),
                        Exercise(id='b1-u1-l2-e3', type='multiple_choice', prompt='Which expression does NOT trigger the subjunctive?', options=['Il faut que', 'Je pense que', 'Bien que', 'Pour que'], answer=1, explanation='Je pense que takes the indicative (it expresses belief, not doubt).'),
                        Exercise(id='b1-u1-l2-e4', type='translate_to_fr', prompt='Translate: "I want you to know." (use vouloir + savoir)', options=None, answer='Je veux que tu saches', explanation='Je veux que + subjunctive of savoir: que tu saches.'),
                        Exercise(id='b1-u1-l2-e5', type='true_false', prompt='The subjunctive is used after "bien que" (although).', options=['True', 'False'], answer=0, explanation='True. Bien que + subjunctive: Bien qu\\'),
                    ],
                    culturalNote='The subjunctive is fading in casual spoken French — many young speakers simplify it. However, in formal writing, journalism, and literature, it remains essential. A famous French joke: \'Le subjonctif, c\\\'est comme la grammaire : on l\\\'apprend à l\\\'école et on l\\\'oublie après.\' (The subjunctive is like grammar: you learn it at school and forget it after.)',
                    estimatedMinutes=40,
                ),
            ],
        ),
        Unit(
            id='b1-u2',
            title='Media and News',
            titleFr='Médias et actualité',
            theme='News, conditionals & reported speech',
            description='Understand French news, use the conditional mood, and report what others say.',
            lessons=[
                Lesson(
                    id='b1-u2-l1',
                    title='The Conditional Mood',
                    titleFr='Le conditionnel',
                    description='Use the conditional to express hypotheses, politeness, and reported information.',
                    objectives=["Form the present conditional", "Use ", " clauses with conditionals", "Express politeness with the conditional", "Recognize the conditional as ", ""],
                    vocabulary=[
                        VocabItem(fr='si', en='if', ipa='', example='Si j\\', exampleEn='If I had time, I would travel.', category='condition'),
                        VocabItem(fr='je voudrais', en='I would like', ipa='', example='Je voudrais un café.', exampleEn='I would like a coffee.', category='politeness'),
                        VocabItem(fr='je pourrais', en='I could', ipa='', example='Je pourrais t\\', exampleEn='I could help you.', category='conditional'),
                        VocabItem(fr='il faudrait', en='one should / it would be necessary', ipa='', example='Il faudrait partir tôt.', exampleEn='We should leave early.', category='conditional'),
                        VocabItem(fr='à condition que', en='on condition that', ipa='', example='Je viendrai à condition qu\\', exampleEn='I\\', category='condition'),
                        VocabItem(fr='au cas où', en='in case', ipa='', example='Prends un parapluie au cas où il pleuvrait.', exampleEn='Take an umbrella in case it rains.', category='condition'),
                        VocabItem(fr='selon les journalistes', en='according to journalists', ipa='', example='Selon les journalistes, le projet est annulé.', exampleEn='According to journalists, the project is canceled.', category='media'),
                        VocabItem(fr='les informations', en='the news', ipa='', example='Je regarde les informations à 20h.', exampleEn='I watch the news at 8 PM.', category='media'),
                        VocabItem(fr='le journal', en='the newspaper / the news', ipa='', example='Le journal de 20h.', exampleEn='The 8 PM news.', category='media'),
                        VocabItem(fr='un journaliste', en='a journalist', ipa='', example='La journaliste interviewe le ministre.', exampleEn='The journalist is interviewing the minister.', category='media'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Forming the present conditional',
                            explanation='The conditional is formed with the futur stem + imparfait endings (-ais, -ais, -ait, -ions, -iez, -aient). It is used for hypotheses, polite requests, and reported future events (\'future in the past\').',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "parler \u2192 parler- \u2192 je parlerais (I would speak)", "en": "Stem of futur simple + imparfait endings."}, {"fr": "finir \u2192 finir- \u2192 je finirais (I would finish)", "en": "Same pattern."}, {"fr": "\u00eatre \u2192 ser- \u2192 je serais (I would be)", "en": "Irregular stem (same as futur)."}, {"fr": "avoir \u2192 aur- \u2192 j\\", "en": "Irregular stem."}]],
                            tip='The conditional uses the same stems as the futur simple — only the endings differ (-ai → -ais for je).',
                        ),
                        GrammarRule(
                            title='Si clauses — hypothetical sentences',
                            explanation='French uses three types of \'si\' clauses: (1) Si + présent → futur (real possibility), (2) Si + imparfait → conditionnel (hypothetical), (3) Si + plus-que-parfait → conditionnel passé (unreal past).',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Si tu \u00e9tudies, tu r\u00e9ussiras.", "en": "If you study, you will succeed. (real)"}, {"fr": "Si tu \u00e9tudiais, tu r\u00e9ussirais.", "en": "If you studied, you would succeed. (hypothetical)"}, {"fr": "Si tu avais \u00e9tudi\u00e9, tu aurais r\u00e9ussi.", "en": "If you had studied, you would have succeeded. (unreal past)"}]],
                            tip='In the hypothetical si clause, the imparfait is used (not the conditional). NEVER say "Si je serais" — it\\',
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "ai"}, {"pronoun": "tu", "form": "as"}, {"pronoun": "il/elle", "form": "a"}, {"pronoun": "nous", "form": "avons"}, {"pronoun": "vous", "form": "avez"}, {"pronoun": "ils/elles", "form": "ont"}],
                                sentenceRule='Subject + avoir + noun. Used for possession, age (J\\',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "J\\", "en": "I have a brother."}, {"fr": "Tu as vingt ans.", "en": "You are twenty."}, {"fr": "Il a faim.", "en": "He is hungry."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='b1-u2-l1-conj-0-1', type='conjugation', prompt='Conjugate "avoir" for "j\\', answer='ai', options=None, explanation='j\\'),
                            Exercise(id='b1-u2-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "avoir".', answer='', options=['a', 'ai', 'as', 'avons'], explanation='il/elle a — correct conjugation of "avoir".'),
                            Exercise(id='b1-u2-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "J\\', answer='ai', options=None, explanation='The correct form is "ai".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Journaliste', fr='Selon nos informations, le gouvernement annoncerait une réforme la semaine prochaine.', en='According to our information, the government would announce a reform next week.'),
                        DialogueLine(speaker='B', name='Invité', fr='Si c\\', en='If that were true, it would be good news for citizens.'),
                        DialogueLine(speaker='A', name='Journaliste', fr='Que feriez-vous si vous étiez au gouvernement ?', en='What would you do if you were in government?'),
                        DialogueLine(speaker='B', name='Invité', fr='Si j\\', en='If I were minister, I would invest more in education. It would also be necessary to reduce taxes.'),
                        DialogueLine(speaker='A', name='Journaliste', fr='Mais si le budget était limité, comment feriez-vous ?', en='But if the budget were limited, how would you do it?'),
                        DialogueLine(speaker='B', name='Invité', fr='Je pourrais trouver des économies ailleurs. Au cas où le budget augmenterait, je créerais plus de places à l\\', en='I could find savings elsewhere. In case the budget increased, I would create more university places.'),
                    ],
                    exercises=[
                        Exercise(id='b1-u2-l1-e1', type='multiple_choice', prompt='Complete: "Si j\\', options=['vais', 'irais', 'allais', 'irai'], answer=1, explanation='Si + imparfait → conditionnel présent. Aller → j\\'),
                        Exercise(id='b1-u2-l1-e2', type='fill_blank', prompt='Conditional of "être": "Si j\\', options=None, answer='serais', explanation='Conditional of être: je serais, tu serais, il serait.'),
                        Exercise(id='b1-u2-l1-e3', type='multiple_choice', prompt='Which sentence is grammatically correct?', options=['Si je serais riche, j\\', ', ', 'étais riche, j\\', ', ', 'achète une maison', 'Si j\\', 'achèterai une maison'], answer=1, explanation='After si, NEVER use the conditional. Use imparfait: Si j\\'),
                        Exercise(id='b1-u2-l1-e4', type='translate_to_fr', prompt='Translate: "I would like a coffee, please." (polite)', options=None, answer='Je voudrais un café, s\\', explanation='Vouloir in conditional = polite form: je voudrais.'),
                        Exercise(id='b1-u2-l1-e5', type='true_false', prompt='The conditional is used in journalism to report unconfirmed information.', options=['True', 'False'], answer=0, explanation='True. "Le gouvernement annoncerait..." = "The government would announce..." (unconfirmed).'),
                    ],
                    culturalNote='French TV news (\'le journal de 20h\') on TF1 and France 2 is a national ritual, watched by millions every evening. France has a strong tradition of investigative journalism, with magazines like \'Le Canard Enchaîné\' (satirical/investigative) and \'Mediapart\' (online). The press is largely subsidized by the state to ensure pluralism.',
                    estimatedMinutes=40,
                ),
            ],
        ),
        Unit(
            id='b1-u3',
            title='Work and Career',
            titleFr='Travail et carrière',
            theme='Professional life & plus-que-parfait',
            description='Talk about your career, write a CV, and use the plus-que-parfait.',
            lessons=[
                Lesson(
                    id='b1-u3-l1',
                    title='Professional Life',
                    titleFr='La vie professionnelle',
                    description='Use professional vocabulary, talk about your career path, and use the plus-que-parfait.',
                    objectives=["Use professional French vocabulary", "Describe your career and education", "Form the plus-que-parfait", "Talk about a sequence of past events"],
                    vocabulary=[
                        VocabItem(fr='le travail', en='work / job', ipa='', example='Je cherche du travail.', exampleEn='I\\', category='work'),
                        VocabItem(fr='le métier', en='profession / trade', ipa='', example='Quel est votre métier ?', exampleEn='What is your profession?', category='work'),
                        VocabItem(fr='la carrière', en='career', ipa='', example='Il a une belle carrière.', exampleEn='He has a beautiful career.', category='work'),
                        VocabItem(fr='l\\', en='company', ipa='', example='Je travaille dans une petite entreprise.', exampleEn='I work in a small company.', category='work'),
                        VocabItem(fr='le patron', en='boss', ipa='', example='Mon patron est sympa.', exampleEn='My boss is nice.', category='work'),
                        VocabItem(fr='les collègues', en='colleagues', ipa='', example='Mes collègues sont gentils.', exampleEn='My colleagues are kind.', category='work'),
                        VocabItem(fr='le salaire', en='salary', ipa='', example='Mon salaire a augmenté.', exampleEn='My salary increased.', category='work'),
                        VocabItem(fr='un entretien d\\', en='a job interview', ipa='', example='J\\', exampleEn='I have a job interview tomorrow.', category='work'),
                        VocabItem(fr='le CV', en='CV / résumé', ipa='', example='J\\', exampleEn='I sent my CV.', category='work'),
                        VocabItem(fr='démissionner', en='to resign', ipa='', example='Il a démissionné hier.', exampleEn='He resigned yesterday.', category='work'),
                        VocabItem(fr='être embauché(e)', en='to be hired', ipa='', example='Elle a été embauchée.', exampleEn='She was hired.', category='work'),
                        VocabItem(fr='le chômage', en='unemployment', ipa='', example='Le chômage baisse.', exampleEn='Unemployment is decreasing.', category='work'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Plus-que-parfait — the past of the past',
                            explanation='The plus-que-parfait is used to describe an action that happened BEFORE another past action. It is formed with the imparfait of avoir/être + past participle.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Quand je suis arriv\u00e9, le train \u00e9tait d\u00e9j\u00e0 parti.", "en": "When I arrived, the train had already left."}, {"fr": "Elle avait fini son travail quand j\\", "en": "She had finished her work when I called."}, {"fr": "J\\", "en": "I had eaten before he arrived."}]],
                            tip='Think of it as the "past before the past" — used to set background for the passé composé.',
                        ),
                        GrammarRule(
                            title='Sequence of past events',
                            explanation='When telling a story, the plus-que-parfait establishes what had already happened, the imparfait describes the scene, and the passé composé moves the action forward.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "J\\", "en": "I had prepared dinner. It was raining. When he arrived, we ate."}]],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "suis"}, {"pronoun": "tu", "form": "es"}, {"pronoun": "il/elle", "form": "est"}, {"pronoun": "nous", "form": "sommes"}, {"pronoun": "vous", "form": "\u00eates"}, {"pronoun": "ils/elles", "form": "sont"}],
                                sentenceRule='Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je suis \u00e9tudiant.", "en": "I am a student."}, {"fr": "Tu es fran\u00e7ais ?", "en": "Are you French?"}, {"fr": "Nous sommes \u00e0 Paris.", "en": "We are in Paris."}]],
                            ),
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "ai"}, {"pronoun": "tu", "form": "as"}, {"pronoun": "il/elle", "form": "a"}, {"pronoun": "nous", "form": "avons"}, {"pronoun": "vous", "form": "avez"}, {"pronoun": "ils/elles", "form": "ont"}],
                                sentenceRule='Subject + avoir + noun. Used for possession, age (J\\',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "J\\", "en": "I have a brother."}, {"fr": "Tu as vingt ans.", "en": "You are twenty."}, {"fr": "Il a faim.", "en": "He is hungry."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='b1-u3-l1-conj-0-1', type='conjugation', prompt='Conjugate "être" for "je":', answer='suis', options=None, explanation='je suis — correct form of "être".'),
                            Exercise(id='b1-u3-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "être".', answer='', options=['est', 'suis', 'es', 'sommes'], explanation='il/elle est — correct conjugation of "être".'),
                            Exercise(id='b1-u3-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"', answer='suis', options=None, explanation='The correct form is "suis".'),
                            Exercise(id='b1-u3-l1-conj-1-1', type='conjugation', prompt='Conjugate "avoir" for "tu":', answer='as', options=None, explanation='tu as — correct form of "avoir".'),
                            Exercise(id='b1-u3-l1-conj-1-2', type='multiple_choice', prompt='Complete: "nous _____" with the correct form of "avoir".', answer='', options=['avons', 'ai', 'as', 'a'], explanation='nous avons — correct conjugation of "avoir".'),
                            Exercise(id='b1-u3-l1-conj-1-3', type='fill_blank', prompt='Fill in the blank: "Tu _____ vingt ans." (You are twenty.) — form of "avoir"', answer='as', options=None, explanation='The correct form is "as".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Recruteur', fr='Bonjour. Vous avez quelles expériences professionnelles ?', en='Hello. What professional experience do you have?'),
                        DialogueLine(speaker='B', name='Candidat', fr='J\\', en='I had worked three years in a start-up before applying here. Before that, I had done an internship in a big company.'),
                        DialogueLine(speaker='A', name='Recruteur', fr='Et pourquoi avez-vous quitté votre précédent poste ?', en='And why did you leave your previous position?'),
                        DialogueLine(speaker='B', name='Candidat', fr='J\\', en='I had reached the ceiling in that company. I was looking for new challenges.'),
                        DialogueLine(speaker='A', name='Recruteur', fr='Quel salaire espériez-vous ?', en='What salary were you hoping for?'),
                        DialogueLine(speaker='B', name='Candidat', fr='J\\', en='I was hoping for a salary around 35,000 euros, with possibilities for advancement.'),
                        DialogueLine(speaker='A', name='Recruteur', fr='C\\', en='That\\'),
                    ],
                    exercises=[
                        Exercise(id='b1-u3-l1-e1', type='multiple_choice', prompt='What is the plus-que-parfait of "manger" for "j\\', options=['j\\', ', ', 'avais mangé', 'j\\', ', '], answer=1, explanation='Imparfait of avoir + past participle: j\\'),
                        Exercise(id='b1-u3-l1-e2', type='fill_blank', prompt='Complete: "Quand je suis arrivé, le train _____ déjà parti."', options=None, answer='était', explanation='Partir uses être. Plus-que-parfait: était parti.'),
                        Exercise(id='b1-u3-l1-e3', type='multiple_choice', prompt='When do you use the plus-que-parfait?', options=['For recent past', 'For future past', 'For an action before another past action', 'For present habits'], answer=2, explanation='The plus-que-parfait describes an action that happened before another past action.'),
                        Exercise(id='b1-u3-l1-e4', type='translate_to_fr', prompt='Translate: "I had finished my work."', options=None, answer="J'avais fini mon travail", explanation='Imparfait of avoir + past participle of finir: j\\'),
                        Exercise(id='b1-u3-l1-e5', type='true_false', prompt='The plus-que-parfait is formed with imparfait of avoir/être + past participle.', options=['True', 'False'], answer=0, explanation='True. Ex: j\\'),
                    ],
                    culturalNote='In France, the legal work week is 35 hours. Workers have 5 weeks of paid vacation per year — among the highest in the world. The French CV is typically 1-2 pages, with a photo (optional but common), and includes personal details like age and marital status that would be unusual in American CVs.',
                    estimatedMinutes=35,
                ),
            ],
        ),
        Unit(
            id='b1-u4',
            title='Environment and Society',
            titleFr='Environnement et société',
            theme='Environment, cause & consequence',
            description='Discuss environmental issues, use cause-and-effect structures.',
            lessons=[
                Lesson(
                    id='b1-u4-l1',
                    title='Talking About the Environment',
                    titleFr='Parler de l\\',
                    description='Use vocabulary for climate issues and express cause and consequence.',
                    objectives=["Use environmental vocabulary", "Express cause (\u00e0 cause de, gr\u00e2ce \u00e0)", "Express consequence (donc, par cons\u00e9quent)", "Form the passive voice"],
                    vocabulary=[
                        VocabItem(fr='l\\', en='the environment', ipa='', example='Il faut protéger l\\', exampleEn='We must protect the environment.', category='environment'),
                        VocabItem(fr='le climat', en='the climate', ipa='', example='Le climat change.', exampleEn='The climate is changing.', category='environment'),
                        VocabItem(fr='la pollution', en='pollution', ipa='', example='La pollution de l\\', exampleEn='Air pollution is serious.', category='environment'),
                        VocabItem(fr='le réchauffement', en='warming', ipa='', example='Le réchauffement climatique.', exampleEn='Global warming.', category='environment'),
                        VocabItem(fr='les déchets', en='waste / trash', ipa='', example='Trier les déchets est important.', exampleEn='Sorting waste is important.', category='environment'),
                        VocabItem(fr='recycler', en='to recycle', ipa='', example='Je recycle le plastique.', exampleEn='I recycle plastic.', category='environment'),
                        VocabItem(fr='l\\', en='renewable energy', ipa='', example='Les énergies renouvelables progressent.', exampleEn='Renewable energies are progressing.', category='environment'),
                        VocabItem(fr='à cause de', en='because of (negative)', ipa='', example='À cause de la pollution, l\\', exampleEn='Because of pollution, the air is bad.', category='cause'),
                        VocabItem(fr='grâce à', en='thanks to (positive)', ipa='', example='Grâce à l\\', exampleEn='Thanks to green electricity, we pollute less.', category='cause'),
                        VocabItem(fr='en raison de', en='due to (neutral)', ipa='', example='En raison du vent, l\\', exampleEn='Due to wind, the plane is late.', category='cause'),
                        VocabItem(fr='donc', en='therefore', ipa='', example='Il pleut, donc je reste.', exampleEn='It\\', category='consequence'),
                        VocabItem(fr='par conséquent', en='consequently', ipa='', example='Il est malade ; par conséquent, il ne vient pas.', exampleEn='He\\', category='consequence'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Cause expressions: à cause de vs. grâce à',
                            explanation='\'À cause de\' introduces a negative cause (something bad). \'Grâce à\' introduces a positive cause (something good). \'En raison de\' is neutral, used in formal contexts.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "\u00c0 cause de la gr\u00e8ve, le train est annul\u00e9.", "en": "Because of the strike (bad), the train is canceled."}, {"fr": "Gr\u00e2ce \u00e0 ton aide, j\\", "en": "Thanks to your help (good), I succeeded."}, {"fr": "En raison de travaux, la route est ferm\u00e9e.", "en": "Due to road works (neutral), the road is closed."}]],
                            tip='All three are followed by a NOUN, not a sentence. For a sentence, use "parce que".',
                        ),
                        GrammarRule(
                            title='The passive voice',
                            explanation='The passive voice is formed with être + past participle. It is used when the action is more important than who did it. The agent (who did it) is introduced with \'par\'.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "La maison est construite par des ouvriers.", "en": "The house is built by workers."}, {"fr": "Le pain est fait avec de la farine.", "en": "Bread is made with flour."}, {"fr": "Ce livre a \u00e9t\u00e9 \u00e9crit en 1950.", "en": "This book was written in 1950."}]],
                            tip='French uses the passive less than English. Often, "on" + active verb replaces it: "On a construit la maison" (They built the house / The house was built).',
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='vouloir',
                                translation='to want',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "veux"}, {"pronoun": "tu", "form": "veux"}, {"pronoun": "il/elle", "form": "veut"}, {"pronoun": "nous", "form": "voulons"}, {"pronoun": "vous", "form": "voulez"}, {"pronoun": "ils/elles", "form": "veulent"}],
                                sentenceRule='Subject + vouloir + noun/infinitive. Je voudrais (conditional) = I would like — polite form for ordering. Irregular.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je veux un caf\u00e9.", "en": "I want a coffee."}, {"fr": "Tu veux venir ?", "en": "Do you want to come?"}, {"fr": "Je voudrais un th\u00e9.", "en": "I would like a tea."}]],
                            ),
                            ConjugationVerb(
                                infinitive='prendre',
                                translation='to take',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "prends"}, {"pronoun": "tu", "form": "prends"}, {"pronoun": "il/elle", "form": "prend"}, {"pronoun": "nous", "form": "prenons"}, {"pronoun": "vous", "form": "prenez"}, {"pronoun": "ils/elles", "form": "prennent"}],
                                sentenceRule='Subject + prendre + transport (Je prends le métro). Also: prendre un café, prendre le petit-déjeuner. Irregular -re verb.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je prends le bus.", "en": "I take the bus."}, {"fr": "Tu prends un caf\u00e9 ?", "en": "Will you have a coffee?"}, {"fr": "Nous prenons le train.", "en": "We take the train."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='b1-u4-l1-conj-0-1', type='conjugation', prompt='Conjugate "vouloir" for "je":', answer='veux', options=None, explanation='je veux — correct form of "vouloir".'),
                            Exercise(id='b1-u4-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "vouloir".', answer='', options=['veut', 'veux', 'veux', 'voulons'], explanation='il/elle veut — correct conjugation of "vouloir".'),
                            Exercise(id='b1-u4-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "Je _____ un café." (I want a coffee.) — form of "vouloir"', answer='veux', options=None, explanation='The correct form is "veux".'),
                            Exercise(id='b1-u4-l1-conj-1-1', type='conjugation', prompt='Conjugate "prendre" for "tu":', answer='prends', options=None, explanation='tu prends — correct form of "prendre".'),
                            Exercise(id='b1-u4-l1-conj-1-2', type='multiple_choice', prompt='Complete: "nous _____" with the correct form of "prendre".', answer='', options=['prenons', 'prends', 'prends', 'prend'], explanation='nous prenons — correct conjugation of "prendre".'),
                            Exercise(id='b1-u4-l1-conj-1-3', type='fill_blank', prompt='Fill in the blank: "Tu _____ un café ?" (Will you have a coffee?) — form of "prendre"', answer='prends', options=None, explanation='The correct form is "prends".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Léa', fr='À cause du réchauffement climatique, les étés sont de plus en plus chauds.', en='Because of global warming, summers are getting hotter and hotter.'),
                        DialogueLine(speaker='B', name='Tom', fr='C\\', en='True. Fortunately, thanks to renewable energies, we\\'),
                        DialogueLine(speaker='A', name='Léa', fr='Mais est-ce que c\\', en='But is it enough? Consequently, we would need stricter laws.'),
                        DialogueLine(speaker='B', name='Tom', fr='Tu as raison. Le recyclage est important, mais il ne suffit pas.', en='You\\'),
                        DialogueLine(speaker='A', name='Léa', fr='En raison de l\\', en='Due to the urgency, everyone must act.'),
                        DialogueLine(speaker='B', name='Tom', fr='Tout à fait. Chaque geste compte.', en='Absolutely. Every action counts.'),
                    ],
                    exercises=[
                        Exercise(id='b1-u4-l1-e1', type='multiple_choice', prompt='Which expression has a NEGATIVE connotation?', options=['Grâce à', 'À cause de', 'En raison de', 'Donc'], answer=1, explanation='À cause de introduces a negative cause. Grâce à is positive.'),
                        Exercise(id='b1-u4-l1-e2', type='fill_blank', prompt='Complete: "_____ ton aide, j\\', options=None, answer='Grâce à', explanation='Grâce à = thanks to (positive).'),
                        Exercise(id='b1-u4-l1-e3', type='multiple_choice', prompt='Which is the passive form of "On construit la maison"?', options=['La maison construit', 'La maison est construite', 'La maison a construit', 'La maison construire'], answer=1, explanation='Passive = être + past participle: La maison est construite.'),
                        Exercise(id='b1-u4-l1-e4', type='translate_to_fr', prompt='Translate: "Because of the strike, the train is canceled."', options=None, answer='À cause de la grève, le train est annulé', explanation='À cause de + noun (negative cause).'),
                        Exercise(id='b1-u4-l1-e5', type='true_false', prompt='"Grâce à" introduces a positive cause.', options=['True', 'False'], answer=0, explanation='True. Grâce à = thanks to (something positive).'),
                    ],
                    culturalNote='France is a leader in low-carbon electricity thanks to nuclear power (about 70% of production). The country has banned single-use plastic packaging for many fruits and vegetables since 2022. The \'mairie\' (city hall) of Paris has launched ambitious programs to reduce car traffic and plant trees — by 2030, Paris aims to be carbon-neutral.',
                    estimatedMinutes=35,
                ),
            ],
        ),
        Unit(
            id='I am tired.',
            title='Technology and Modern Life',
            titleFr='Technologie et vie moderne',
            theme='Technology, internet & indirect speech',
            description='Discuss technology, report what others say, and use indirect questions.',
            lessons=[
                Lesson(
                    id='I am tired.',
                    title='In the Digital Age',
                    titleFr='À l\\',
                    description='Talk about technology, social media, and report what others say.',
                    objectives=["Use technology vocabulary (ordinateur, smartphone, r\u00e9seau social)", "Form indirect questions (Il demande si...)", "Report speech with ", "", "Discuss pros and cons of technology"],
                    vocabulary=[
                        VocabItem(fr='l\'ordinateur', en='the computer', ipa='', example='Mon ordinateur est en panne.', exampleEn='My computer is broken.', category='tech'),
                        VocabItem(fr='le smartphone', en='the smartphone', ipa='', example='Je ne peux pas vivre sans smartphone.', exampleEn='I can\\', category='tech'),
                        VocabItem(fr='l\'internet', en='the internet', ipa='', example='Une connexion internet rapide.', exampleEn='A fast internet connection.', category='tech'),
                        VocabItem(fr='le réseau social', en='the social network', ipa='', example='Les réseaux sociaux sont populaires.', exampleEn='Social networks are popular.', category='tech'),
                        VocabItem(fr='l\'application (app)', en='the app', ipa='', example='J\\', exampleEn='I downloaded a new app.', category='tech'),
                        VocabItem(fr='le courriel (email)', en='the email', ipa='', example='Je vais envoyer un courriel.', exampleEn='I\\', category='tech'),
                        VocabItem(fr='le message', en='the message', ipa='', example='Un message texte.', exampleEn='A text message.', category='tech'),
                        VocabItem(fr='télécharger', en='to download', ipa='', example='J\\', exampleEn='I downloaded a movie.', category='verbs'),
                        VocabItem(fr='partager', en='to share', ipa='', example='Elle a partagé une photo.', exampleEn='She shared a photo.', category='verbs'),
                        VocabItem(fr='se connecter', en='to log in / connect', ipa='', example='Connecte-toi à ton compte.', exampleEn='Log into your account.', category='verbs'),
                        VocabItem(fr='se déconnecter', en='to log out', ipa='', example='Déconnecte-toi après usage.', exampleEn='Log out after use.', category='verbs'),
                        VocabItem(fr='le mot de passe', en='the password', ipa='', example='Quel est ton mot de passe ?', exampleEn='What is your password?', category='tech'),
                        VocabItem(fr='l\'écran', en='the screen', ipa='', example='Un grand écran.', exampleEn='A large screen.', category='tech'),
                        VocabItem(fr='le clavier', en='the keyboard', ipa='', example='Tape sur le clavier.', exampleEn='Type on the keyboard.', category='tech'),
                        VocabItem(fr='la souris', en='the mouse (computer)', ipa='', example='Une souris sans fil.', exampleEn='A wireless mouse.', category='tech'),
                        VocabItem(fr='les données', en='the data', ipa='', example='La protection des données.', exampleEn='Data protection.', category='tech'),
                        VocabItem(fr='le pirate', en='the hacker', ipa='', example='Les pirates informatiques.', exampleEn='Computer hackers.', category='tech'),
                        VocabItem(fr='la intelligence artificielle', en='the artificial intelligence', ipa='', example='L\'IA transforme le monde.', exampleEn='AI is transforming the world.', category='tech'),
                        VocabItem(fr='l\'algorithme', en='the algorithm', ipa='', example='Un algorithme complexe.', exampleEn='A complex algorithm.', category='tech'),
                        VocabItem(fr='addictif', en='addictive', ipa='', example='Les réseaux sont addictifs.', exampleEn='Networks are addictive.', category='adjectives'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Indirect questions',
                            explanation='Indirect questions report a question without using quotation marks. They are introduced by \'si\' (if/whether) for yes/no questions, or by a question word (qui, que, où, quand, comment, pourquoi, ce que) for wh-questions. The subject usually comes BEFORE the verb (no inversion).',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Il demande si tu viens.", "en": "He asks if you are coming."}, {"fr": "Je ne sais pas quand il arrive.", "en": "I don\\"}, {"fr": "Elle veut savoir o\u00f9 tu habites.", "en": "She wants to know where you live."}, {"fr": "Dis-moi ce que tu penses.", "en": "Tell me what you think."}]],
                            tip='After \'si\' (if/whether), use statement word order: \'si tu viens\' (not \'si viens-tu\').',
                        ),
                        GrammarRule(
                            title='Reported speech with dire que',
                            explanation='To report what someone said, use \'dire que\' + statement. The tense often shifts: present → imparfait, passé composé → plus-que-parfait.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Il dit : \u00ab Je suis fatigu\u00e9. \u00bb \u2192 Il dit qu\\", "en": "He says: \"I am tired.\" \u2192 He says (that) he is tired."}, {"fr": "Il a dit : \u00ab Je suis fatigu\u00e9. \u00bb \u2192 Il a dit qu\\", "en": "He said: \"I am tired.\" \u2192 He said (that) he was tired."}]],
                            tip='In French, "que" is required (unlike English where "that" can be dropped): "Il dit qu\\',
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='aller',
                                translation='to go',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "vais"}, {"pronoun": "tu", "form": "vas"}, {"pronoun": "il/elle", "form": "va"}, {"pronoun": "nous", "form": "allons"}, {"pronoun": "vous", "form": "allez"}, {"pronoun": "ils/elles", "form": "vont"}],
                                sentenceRule='Subject + aller + preposition + place. à + le = au, à + les = aux. Also: aller + infinitive = near future (Je vais manger).',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je vais au cin\u00e9ma.", "en": "I go to the cinema."}, {"fr": "Nous allons \u00e0 Paris.", "en": "We go to Paris."}, {"fr": "Je vais manger.", "en": "I am going to eat."}]],
                            ),
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "suis"}, {"pronoun": "tu", "form": "es"}, {"pronoun": "il/elle", "form": "est"}, {"pronoun": "nous", "form": "sommes"}, {"pronoun": "vous", "form": "\u00eates"}, {"pronoun": "ils/elles", "form": "sont"}],
                                sentenceRule='Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je suis \u00e9tudiant.", "en": "I am a student."}, {"fr": "Tu es fran\u00e7ais ?", "en": "Are you French?"}, {"fr": "Nous sommes \u00e0 Paris.", "en": "We are in Paris."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='b1-u5-l1-conj-0-1', type='conjugation', prompt='Conjugate "aller" for "je":', answer='vais', options=None, explanation='je vais — correct form of "aller".'),
                            Exercise(id='b1-u5-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "aller".', answer='', options=['va', 'vais', 'vas', 'allons'], explanation='il/elle va — correct conjugation of "aller".'),
                            Exercise(id='b1-u5-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "Je _____ au cinéma." (I go to the cinema.) — form of "aller"', answer='vais', options=None, explanation='The correct form is "vais".'),
                            Exercise(id='b1-u5-l1-conj-1-1', type='conjugation', prompt='Conjugate "être" for "tu":', answer='es', options=None, explanation='tu es — correct form of "être".'),
                            Exercise(id='b1-u5-l1-conj-1-2', type='multiple_choice', prompt='Complete: "nous _____" with the correct form of "être".', answer='', options=['sommes', 'suis', 'es', 'est'], explanation='nous sommes — correct conjugation of "être".'),
                            Exercise(id='b1-u5-l1-conj-1-3', type='fill_blank', prompt='Fill in the blank: "Tu _____ français ?" (Are you French?) — form of "être"', answer='es', options=None, explanation='The correct form is "es".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Clara', fr='Tu as vu ? Marc a dit qu\\', en='Did you see? Marc said he\\'),
                        DialogueLine(speaker='B', name='Tom', fr='Vraiment ? Je me demande pourquoi.', en='Really? I wonder why.'),
                        DialogueLine(speaker='A', name='Clara', fr='Il a dit que c\\', en='He said it was because of stress. Do you know if he has another project?'),
                        DialogueLine(speaker='B', name='Tom', fr='Je ne sais pas. Je vais lui demander s\\', en='I don\\'),
                        DialogueLine(speaker='A', name='Clara', fr='Tu penses que les réseaux sociaux ont changé notre façon de travailler ?', en='Do you think social media has changed how we work?'),
                        DialogueLine(speaker='B', name='Tom', fr='Certainement. D\\', en='Certainly. On one hand, it\\'),
                        DialogueLine(speaker='A', name='Clara', fr='Tu sais combien de temps on passe sur notre smartphone par jour ?', en='Do you know how much time we spend on our smartphone per day?'),
                        DialogueLine(speaker='B', name='Tom', fr='Je crois que c\\', en='I think it\\'),
                    ],
                    exercises=[
                        Exercise(id='b1-u5-l1-e1', type='multiple_choice', prompt='Transform to indirect question: "Viens-tu ?" → "Je me demande _____ tu viens."', options=['si', 'que', 'ce que', 'est-ce que'], answer=0, explanation='For yes/no questions, use "si": Je me demande si tu viens.'),
                        Exercise(id='b1-u5-l1-e2', type='fill_blank', prompt='Complete: "Il a dit _____ il était fatigué." (that)', options=None, answer='que', explanation='Reported speech uses "dire que": il a dit qu\\'),
                        Exercise(id='b1-u5-l1-e3', type='multiple_choice', prompt='Which sentence is correct for "I don\\', options=['Je ne sais pas où vit-il.', 'Je ne sais pas où il vit.', 'Je ne sais pas où vit il.', 'Je ne sais pas où est-il.'], answer=1, explanation='Indirect questions use statement word order: où il vit (not où vit-il).'),
                        Exercise(id='b1-u5-l1-e4', type='translate_to_fr', prompt='Translate: "She asks if I am hungry."', options=None, answer='Elle demande si j\\', explanation='Indirect question with si: Elle demande si + subject + verb.'),
                        Exercise(id='b1-u5-l1-e5', type='true_false', prompt='In indirect questions, you keep the inversion (e.g. "Je me demande où vas-tu").', options=['True', 'False'], answer=1, explanation='False. Indirect questions use statement order: "Je me demande où tu vas".'),
                        Exercise(id='b1-u5-l1-e6', type='matching', prompt='Match each tech term to its French name.', options=None, answer=None, explanation=''),
                        Exercise(id='b1-u5-l1-e7', type='multiple_choice', prompt='What does "se connecter" mean?', options=['To disconnect', 'To log in / connect', 'To download', 'To share'], answer=1, explanation='Se connecter = to log in / to connect. Se déconnecter = to log out.'),
                    ],
                    activities=[
                        Exercise(id='b1-u5-l1-a1', type='transformation', prompt='Transform to indirect question: "Où habites-tu ?" → "Je veux savoir _____ "', options=None, answer='où tu habites', explanation='Statement word order: où tu habites (no inversion).'),
                        Exercise(id='b1-u5-l1-a2', type='transformation', prompt='Report this speech: Il dit : « Je suis malade. » → Il dit qu\\', options=None, answer='il est malade', explanation='que + il + est malade. Subject-verb order, present tense stays if main verb is present.'),
                        Exercise(id='b1-u5-l1-a3', type='dictation', prompt='Listen and type what you hear.', options=None, answer='Je ne sais pas quand il arrive.', explanation='An indirect question with "quand".'),
                        Exercise(id='b1-u5-l1-a4', type='word_bank', prompt='Build: "I downloaded a new app."', options=None, answer="J'ai téléchargé une nouvelle application", explanation='Passé composé: J\\'),
                        Exercise(id='b1-u5-l1-a5', type='fill_blank', prompt='Complete: "Je me demande _____ il viendra." (whether)', options=None, answer='si', explanation='For yes/no indirect questions, use "si".'),
                        Exercise(id='b1-u5-l1-a6', type='reorder', prompt='Reorder: "demander / je / si / vais / je / lui / viendra / il"', options=None, answer='Je vais lui demander si il viendra.', explanation='"si il" contracts to "s\\'),
                    ],
                    culturalNote='France has a strong tradition of tech skepticism alongside tech adoption. The \'Loi Hadopi\' (2009) tried to combat illegal downloading with fines, but was widely mocked. France created the world\'s first digital ministry in 2017. The CNIL (Commission Nationale de l\'Informatique et des Libertés) is one of Europe\'s strictest data protection agencies — they fined Google €150 million in 2021 for privacy violations. Paris has become a major European AI hub, with Meta\'s FAIR lab and many startups.',
                    estimatedMinutes=40,
                ),
            ],
        ),
    ],
)