from .types import *

# B2 Course
b2_course = Course(
    level='B2',
    title='B2 — Avancé',
    book='Parlez B2',
    description='Master the upper-intermediate level. You\'ll defend complex viewpoints, debate like a native, understand literary and journalistic texts, and master advanced structures like the subjunctive in all contexts, discourse markers, and registers of language.',
    cefrDescription='Can understand the main ideas of complex text on both concrete and abstract topics, including technical discussions in their field of specialization. Can interact with a degree of fluency and spontaneity that makes regular interaction with native speakers quite possible without strain for either party.',
    color='#7C2D3F',
    units=[
        Unit(
            id='b2-u1',
            title='Identities and Cultures',
            titleFr='Identités et cultures',
            theme='Cultural nuances & language registers',
            description='Explore francophone identities and master formal vs. informal registers.',
            lessons=[
                Lesson(
                    id='b2-u1-l1',
                    title='Registers of Language',
                    titleFr='Les registres de langue',
                    description='Distinguish formal, standard, and informal registers; know when to use each.',
                    objectives=["Identify formal (soutenu), standard (courant), and informal (familier) registers", "Use appropriate register in different social contexts", "Recognize slang (argot) and verlan", "Adapt language to audience"],
                    vocabulary=[
                        VocabItem(fr='le registre soutenu', en='formal register', ipa='', example='Je vous saurais gré de bien vouloir...', exampleEn='I would be grateful if you would...', category='register'),
                        VocabItem(fr='le registre courant', en='standard register', ipa='', example='Est-ce que vous pourriez...', exampleEn='Could you...', category='register'),
                        VocabItem(fr='le registre familier', en='informal register', ipa='', example='Tu peux...', exampleEn='Can you...', category='register'),
                        VocabItem(fr='l\\', en='slang', ipa='', example='C\\', exampleEn='That\\', category='register'),
                        VocabItem(fr='le verlan', en='verlan (reversed syllables)', ipa='', example='Une meuf (= femme)', exampleEn='A girl/woman', category='register'),
                        VocabItem(fr='boulot', en='job (informal)', ipa='', example='Je vais au boulot.', exampleEn='I\\', category='informal'),
                        VocabItem(fr='fric', en='money (informal)', ipa='', example='Il a beaucoup de fric.', exampleEn='He has a lot of money.', category='informal'),
                        VocabItem(fr='bagnole', en='car (informal)', ipa='', example='Ma bagnole est en panne.', exampleEn='My car broke down.', category='informal'),
                        VocabItem(fr='la bouffe', en='food (informal)', ipa='', example='On va manger de la bouffe.', exampleEn='We\\', category='informal'),
                        VocabItem(fr='un potes', en='a buddy', ipa='', example='Je sors avec mes potes.', exampleEn='I\\', category='informal'),
                        VocabItem(fr='je vous saurais gré', en='I would be grateful (very formal)', ipa='', example='Je vous saurais gré de m\\', exampleEn='I would be grateful for your help.', category='formal'),
                        VocabItem(fr='il convient de', en='it is appropriate to (formal)', ipa='', example='Il convient de noter que...', exampleEn='It should be noted that...', category='formal'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Three registers of French',
                            explanation='French has three main registers: soutenu (formal, written, speeches), courant (standard, used in most situations), and familier (informal, with friends). The choice depends on context, audience, and relationship. Using the wrong register can sound rude or pretentious.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Soutenu: Je vous saurais gr\u00e9 de bien vouloir m\\", "en": "I would be grateful if you would help me."}, {"fr": "Courant: Pourriez-vous m\\", "en": "Could you help me, please?"}, {"fr": "Familier: Tu peux m\\", "en": "Can you help me?"}]],
                            tip='When in doubt, use the courant register. Better to be slightly formal than rude.',
                        ),
                        GrammarRule(
                            title='Verlan — French slang reversal',
                            explanation='Verlan (from \'l\\\'envers\' reversed) is a slang that reverses syllables. Common examples: femme → meuf, fou → ouf, arabe → beur. It originated in the banlieues (suburbs) and is now widely understood.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "femme \u2192 meuf", "en": "woman"}, {"fr": "fou \u2192 ouf", "en": "crazy"}, {"fr": "arabe \u2192 beur", "en": "Arab (reclaimed)"}, {"fr": "pourri \u2192 ripou", "en": "corrupt (cop)"}]],
                            tip='Verlan is informal — don\'t use it in professional contexts.',
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "suis"}, {"pronoun": "tu", "form": "es"}, {"pronoun": "il/elle", "form": "est"}, {"pronoun": "nous", "form": "sommes"}, {"pronoun": "vous", "form": "\u00eates"}, {"pronoun": "ils/elles", "form": "sont"}],
                                sentenceRule='Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je suis \u00e9tudiant.", "en": "I am a student."}, {"fr": "Tu es fran\u00e7ais ?", "en": "Are you French?"}, {"fr": "Nous sommes \u00e0 Paris.", "en": "We are in Paris."}]],
                            ),
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "ai"}, {"pronoun": "tu", "form": "as"}, {"pronoun": "il/elle", "form": "a"}, {"pronoun": "nous", "form": "avons"}, {"pronoun": "vous", "form": "avez"}, {"pronoun": "ils/elles", "form": "ont"}],
                                sentenceRule='Subject + avoir + noun. Used for possession, age (J\\',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "J\\", "en": "I have a brother."}, {"fr": "Tu as vingt ans.", "en": "You are twenty."}, {"fr": "Il a faim.", "en": "He is hungry."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='b2-u1-l1-conj-0-1', type='conjugation', prompt='Conjugate "être" for "je":', answer='suis', options=None, explanation='je suis — correct form of "être".'),
                            Exercise(id='b2-u1-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "être".', answer='', options=['est', 'suis', 'es', 'sommes'], explanation='il/elle est — correct conjugation of "être".'),
                            Exercise(id='b2-u1-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"', answer='suis', options=None, explanation='The correct form is "suis".'),
                            Exercise(id='b2-u1-l1-conj-1-1', type='conjugation', prompt='Conjugate "avoir" for "tu":', answer='as', options=None, explanation='tu as — correct form of "avoir".'),
                            Exercise(id='b2-u1-l1-conj-1-2', type='multiple_choice', prompt='Complete: "nous _____" with the correct form of "avoir".', answer='', options=['avons', 'ai', 'as', 'a'], explanation='nous avons — correct conjugation of "avoir".'),
                            Exercise(id='b2-u1-l1-conj-1-3', type='fill_blank', prompt='Fill in the blank: "Tu _____ vingt ans." (You are twenty.) — form of "avoir"', answer='as', options=None, explanation='The correct form is "as".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Lucas', fr='Salut mec, ça va ? T\\', en='Hey man, you OK? Did you see the girl over there, that\\'),
                        DialogueLine(speaker='B', name='Antoine', fr='Lucas, on est dans un entretien, là ! Il faut parler correctement.', en='Lucas, we\\'),
                        DialogueLine(speaker='A', name='Lucas', fr='Oh pardon, monsieur. Je vous prie de m\\', en='Oh sorry, sir. I beg you to excuse my inappropriate register.'),
                        DialogueLine(speaker='B', name='Antoine', fr='Ce n\\', en='No need to exaggerate either. Standard language is enough.'),
                        DialogueLine(speaker='A', name='Lucas', fr='Je comprends. Pourriez-vous me redonner une chance ?', en='I understand. Could you give me another chance?'),
                        DialogueLine(speaker='B', name='Antoine', fr='Bien sûr. Mais à l\\', en='Of course. But in the future, it should be noted that register matters as much as content.'),
                    ],
                    exercises=[
                        Exercise(id='b2-u1-l1-e1', type='multiple_choice', prompt='Which is the formal (soutenu) way to say "I don\\', options=['J\\', ', ', ', ', 'ignore', 'No idea'], answer=2, explanation='Je l\\'),
                        Exercise(id='b2-u1-l1-e2', type='fill_blank', prompt='Verlan of "femme" = _____', options=None, answer='meuf', explanation='Verlan reverses syllables: femme → meuf.'),
                        Exercise(id='b2-u1-l1-e3', type='multiple_choice', prompt='Which word is informal for "car"?', options=['Voiture', 'Véhicule', 'Bagnole', 'Automobile'], answer=2, explanation='Bagnole is informal. Voiture is standard. Véhicule/automobile are formal.'),
                        Exercise(id='b2-u1-l1-e4', type='translate_to_fr', prompt='Translate (formal): "I would be grateful if you would help me."', options=None, answer='Je vous saurais gré de bien vouloir m\\', explanation='Formal expression: je vous saurais gré de + infinitive.'),
                        Exercise(id='b2-u1-l1-e5', type='true_false', prompt='"Verlan" is created by reversing the syllables of a word.', options=['True', 'False'], answer=0, explanation='True. Verlan = l\\'),
                    ],
                    culturalNote='The French language is regulated by the Académie française, founded in 1635 by Cardinal Richelieu. The 40 \'immortels\' (members) work to protect French from English influence, suggesting French alternatives to English words (e.g., \'courriel\' for \'email\'). However, in everyday life, English loanwords like \'le week-end\', \'le parking\', and \'le shopping\' are everywhere.',
                    estimatedMinutes=40,
                ),
                Lesson(
                    id='b2-u1-l2',
                    title='The Francophone World',
                    titleFr='La francophonie',
                    description='Discover the diversity of French-speaking countries and their linguistic particularities.',
                    objectives=["Identify major francophone countries", "Understand regional variations of French", "Discuss French as a global language", "Recognize Quebec, Belgian, Swiss, African French"],
                    vocabulary=[
                        VocabItem(fr='la francophonie', en='the French-speaking world', ipa='', example='La francophonie compte 300 millions de locuteurs.', exampleEn='The French-speaking world has 300 million speakers.', category='francophonie'),
                        VocabItem(fr='un francophone', en='a French speaker', ipa='', example='Il est francophone.', exampleEn='He\\', category='francophonie'),
                        VocabItem(fr='la langue maternelle', en='mother tongue', ipa='', example='Le français est ma langue maternelle.', exampleEn='French is my mother tongue.', category='language'),
                        VocabItem(fr='la langue officielle', en='official language', ipa='', example='Le français est langue officielle au Sénégal.', exampleEn='French is the official language of Senegal.', category='language'),
                        VocabItem(fr='le Québec', en='Quebec', ipa='', example='Au Québec, on dit "char" pour "voiture".', exampleEn='In Quebec, they say "char" for "car".', category='regions'),
                        VocabItem(fr='la Belgique', en='Belgium', ipa='', example='En Belgique, on dit "septante" pour 70.', exampleEn='In Belgium, they say "septante" for 70.', category='regions'),
                        VocabItem(fr='la Suisse', en='Switzerland', ipa='', example='En Suisse, on dit "huitante" pour 80.', exampleEn='In Switzerland, they say "huitante" for 80.', category='regions'),
                        VocabItem(fr='l\\', en='French-speaking Africa', ipa='', example='Plusieurs pays africains sont francophones.', exampleEn='Several African countries are French-speaking.', category='regions'),
                        VocabItem(fr='un accent', en='an accent', ipa='', example='Il a un accent québécois.', exampleEn='He has a Quebec accent.', category='language'),
                        VocabItem(fr='un régionalisme', en='a regionalism', ipa='', example='Ce mot est un régionalisme.', exampleEn='This word is a regionalism.', category='language'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Regional variations of French',
                            explanation='French varies across regions. In Quebec, \'char\' = car, \'magasiner\' = to shop. In Belgium/Switzerland, numbers are simpler (septante, huitante, nonante). In African French, you hear \'en faire le koki\' (to gossip).',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Qu\u00e9bec: char (voiture)", "en": "car"}, {"fr": "Qu\u00e9bec: courriel (e-mail)", "en": "email (officially promoted)"}, {"fr": "Belgique: septante (soixante-dix)", "en": "seventy"}, {"fr": "Afrique: le go-\u00e0 (la ville)", "en": "the city (regional)"}]],
                            tip='If you learn French for Canada, study Quebec French specifically — pronunciation and vocabulary differ significantly.',
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "ai"}, {"pronoun": "tu", "form": "as"}, {"pronoun": "il/elle", "form": "a"}, {"pronoun": "nous", "form": "avons"}, {"pronoun": "vous", "form": "avez"}, {"pronoun": "ils/elles", "form": "ont"}],
                                sentenceRule='Subject + avoir + noun. Used for possession, age (J\\',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "J\\", "en": "I have a brother."}, {"fr": "Tu as vingt ans.", "en": "You are twenty."}, {"fr": "Il a faim.", "en": "He is hungry."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='b2-u1-l2-conj-0-1', type='conjugation', prompt='Conjugate "avoir" for "j\\', answer='ai', options=None, explanation='j\\'),
                            Exercise(id='b2-u1-l2-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "avoir".', answer='', options=['a', 'ai', 'as', 'avons'], explanation='il/elle a — correct conjugation of "avoir".'),
                            Exercise(id='b2-u1-l2-conj-0-3', type='fill_blank', prompt='Fill in the blank: "J\\', answer='ai', options=None, explanation='The correct form is "ai".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Mélanie', fr='D\\', en='Where are you from, Karim?'),
                        DialogueLine(speaker='B', name='Karim', fr='Je viens du Maroc. Le français est ma deuxième langue, mais on l\\', en='I\\'),
                        DialogueLine(speaker='A', name='Mélanie', fr='Et toi, Luc ?', en='And you, Luc?'),
                        DialogueLine(speaker='C', name='Luc', fr='Moi, je viens du Québec. Mon français est un peu différent, avec des mots comme "char" et "magasiner".', en='I\\'),
                        DialogueLine(speaker='A', name='Mélanie', fr='C\\', en='Fascinating! The French-speaking world is really diverse.'),
                        DialogueLine(speaker='B', name='Karim', fr='Oui, on est 300 millions de francophones dans le monde. L\\', en='Yes, we\\'),
                        DialogueLine(speaker='C', name='Luc', fr='Même si nos accents sont différents, on se comprend !', en='Even if our accents are different, we understand each other!'),
                    ],
                    exercises=[
                        Exercise(id='b2-u1-l2-e1', type='multiple_choice', prompt='How do they say "70" in Belgium?', options=['soixante-dix', 'septante', 'sept-dix', 'septante-dix'], answer=1, explanation='In Belgium and Switzerland: septante. In France: soixante-dix.'),
                        Exercise(id='b2-u1-l2-e2', type='fill_blank', prompt='Complete: "Au _____, on dit \\\\"char\\\\" pour \\\\"voiture\\\\"."', options=None, answer='Québec', explanation='Quebec French uses "char" for car.'),
                        Exercise(id='b2-u1-l2-e3', type='multiple_choice', prompt='How many French speakers are there in the world?', options=['30 millions', '100 millions', '300 millions', '1 milliard'], answer=2, explanation='About 300 million French speakers worldwide, growing fast in Africa.'),
                        Exercise(id='b2-u1-l2-e4', type='translate_to_fr', prompt='Translate: "French is my mother tongue."', options=None, answer='Le français est ma langue maternelle', explanation='Langue maternelle = mother tongue.'),
                        Exercise(id='b2-u1-l2-e5', type='true_false', prompt='French is growing fastest in Africa.', options=['True', 'False'], answer=0, explanation='True. Due to population growth, French is expanding rapidly in African countries.'),
                    ],
                    culturalNote='The Organisation Internationale de la Francophonie (OIF) has 88 member states. French is the official language in 29 countries — second only to English. The Democratic Republic of Congo is the most populous French-speaking country (95M people). French is also one of the official languages of the UN, EU, NATO, and the Olympic Games.',
                    estimatedMinutes=35,
                ),
            ],
        ),
        Unit(
            id='b2-u2',
            title='Science and Hypothesis',
            titleFr='Sciences et hypothèses',
            theme='Hypothesis & scientific discourse',
            description='Express hypotheses, talk about science and technology, and master conditional structures.',
            lessons=[
                Lesson(
                    id='b2-u2-l1',
                    title='Hypothesis and Discovery',
                    titleFr='Hypothèse et découverte',
                    description='Use advanced conditional structures and scientific vocabulary.',
                    objectives=["Use the conditionnel pass\u00e9 for unreal past", "Express hypothesis with ", " + plus-que-parfait", "Use scientific and technical vocabulary", "Discuss technological advances"],
                    vocabulary=[
                        VocabItem(fr='une hypothèse', en='a hypothesis', ipa='', example='Je formule une hypothèse.', exampleEn='I form a hypothesis.', category='science'),
                        VocabItem(fr='une découverte', en='a discovery', ipa='', example='C\\', exampleEn='It\\', category='science'),
                        VocabItem(fr='une expérience', en='an experiment', ipa='', example='L\\', exampleEn='The experiment failed.', category='science'),
                        VocabItem(fr='la technologie', en='technology', ipa='', example='La technologie progresse vite.', exampleEn='Technology progresses fast.', category='technology'),
                        VocabItem(fr='l\\', en='artificial intelligence', ipa='', example='L\\', exampleEn='AI is transforming work.', category='technology'),
                        VocabItem(fr='les données', en='data', ipa='', example='Les données sont collectées.', exampleEn='Data is being collected.', category='technology'),
                        VocabItem(fr='un algorithme', en='an algorithm', ipa='', example='Cet algorithme est complexe.', exampleEn='This algorithm is complex.', category='technology'),
                        VocabItem(fr='si j\\', en='if I had known', ipa='', example='Si j\\', exampleEn='If I had known, I wouldn\\', category='hypothesis'),
                        VocabItem(fr='j\\', en='I should have', ipa='', example='J\\', exampleEn='I should have studied more.', category='hypothesis'),
                        VocabItem(fr='à supposer que', en='supposing that', ipa='', example='À supposer qu\\', exampleEn='Supposing he comes...', category='hypothesis'),
                        VocabItem(fr='en admettant que', en='admitting that', ipa='', example='En admettant qu\\', exampleEn='Admitting he\\', category='hypothesis'),
                        VocabItem(fr='pour peu que', en='provided that / as long as', ipa='', example='Pour peu qu\\', exampleEn='As long as he makes an effort...', category='hypothesis'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Conditionnel passé — unreal past',
                            explanation='The conditionnel passé expresses what would have happened but didn\'t. It is formed with the conditional of avoir/être + past participle. Used with \'si + plus-que-parfait\' to express regret or unreal past.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Si j\\", "en": "If I had known, I would have come."}, {"fr": "J\\", "en": "I would have liked to see you."}, {"fr": "Tu aurais d\u00fb me pr\u00e9venir.", "en": "You should have warned me."}]],
                            tip='Être and avoir both use avoir as auxiliary in the conditionnel passé: j\\',
                        ),
                        GrammarRule(
                            title='Advanced "si" structures',
                            explanation='Beyond the three main \'si\' types, French has literary expressions of hypothesis: \'à supposer que\' + subjunctive, \'en admettant que\' + subjunctive, \'quand bien même\' + conditional (even if).',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "\u00c0 supposer qu\\", "en": "Supposing he comes, we\\"}, {"fr": "En admettant qu\\", "en": "Admitting he\\"}, {"fr": "Quand bien m\u00eame il serait l\u00e0, je ne le verrais pas.", "en": "Even if he were there, I wouldn\\"}]],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "ai"}, {"pronoun": "tu", "form": "as"}, {"pronoun": "il/elle", "form": "a"}, {"pronoun": "nous", "form": "avons"}, {"pronoun": "vous", "form": "avez"}, {"pronoun": "ils/elles", "form": "ont"}],
                                sentenceRule='Subject + avoir + noun. Used for possession, age (J\\',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "J\\", "en": "I have a brother."}, {"fr": "Tu as vingt ans.", "en": "You are twenty."}, {"fr": "Il a faim.", "en": "He is hungry."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='b2-u2-l1-conj-0-1', type='conjugation', prompt='Conjugate "avoir" for "j\\', answer='ai', options=None, explanation='j\\'),
                            Exercise(id='b2-u2-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "avoir".', answer='', options=['a', 'ai', 'as', 'avons'], explanation='il/elle a — correct conjugation of "avoir".'),
                            Exercise(id='b2-u2-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "J\\', answer='ai', options=None, explanation='The correct form is "ai".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Sophie', fr='Si l\\', en='If AI hadn\\'),
                        DialogueLine(speaker='B', name='Marc', fr='Nous aurions continué à faire beaucoup de tâches manuelles. J\\', en='We would have continued doing many manual tasks. I would have spent hours sorting data.'),
                        DialogueLine(speaker='A', name='Sophie', fr='Tu crois qu\\', en='Do you think we would have lost less time or more time?'),
                        DialogueLine(speaker='B', name='Marc', fr='À supposer que l\\', en='Supposing AI becomes too powerful, we should set limits.'),
                        DialogueLine(speaker='A', name='Sophie', fr='Tu as raison. J\\', en='You\\'),
                        DialogueLine(speaker='B', name='Marc', fr='En admettant qu\\', en='Admitting we regulate AI well, it can help us enormously.'),
                    ],
                    exercises=[
                        Exercise(id='b2-u2-l1-e1', type='multiple_choice', prompt='Complete: "Si j\\', options=['serais', 'aurais', 'suis', 'avais'], answer=0, explanation='Venir uses être. Conditionnel passé: je serais venu.'),
                        Exercise(id='b2-u2-l1-e2', type='fill_blank', prompt='Complete: "Tu _____ dû étudier davantage." (You should have studied more.)', options=None, answer='aurais', explanation='Conditionnel passé of devoir: tu aurais dû.'),
                        Exercise(id='b2-u2-l1-e3', type='multiple_choice', prompt='What structure for "If I had known, I would have come"?', options=['Si je sais, je viendrai', 'Si je savais, je viendrais', 'Si j\\', ', ', 'aurai su, je viendrai'], answer=2, explanation='Type 3: si + plus-que-parfait + conditionnel passé.'),
                        Exercise(id='b2-u2-l1-e4', type='translate_to_fr', prompt='Translate: "I should have warned you."', options=None, answer='J\\', explanation='Conditionnel passé of devoir: j\\'),
                        Exercise(id='b2-u2-l1-e5', type='true_false', prompt='The conditionnel passé expresses an unreal past action.', options=['True', 'False'], answer=0, explanation='True. It expresses what would have happened but didn\\'),
                    ],
                    culturalNote='France has a strong scientific tradition: Pierre and Marie Curie (radioactivity), Louis Pasteur (microbiology), Blaise Pascal (mathematics), and more recently CERN (in Switzerland, partly French). The CNRS (Centre National de la Recherche Scientifique) is Europe\'s largest research organization. France invests heavily in AI — Paris has one of Europe\'s largest AI research hubs, especially around Meta\'s FAIR lab.',
                    estimatedMinutes=40,
                ),
            ],
        ),
        Unit(
            id='b2-u3',
            title='Politics and Debate',
            titleFr='Politique et débat',
            theme='Defending viewpoints & complex discourse',
            description='Defend complex viewpoints, debate formally, and master discourse markers.',
            lessons=[
                Lesson(
                    id='b2-u3-l1',
                    title='Defending Your Position',
                    titleFr='Défendre sa position',
                    description='Use advanced discourse markers and structures to defend a position formally.',
                    objectives=["Use advanced discourse markers (d\\", "autre part, non seulement... mais aussi)", "Express concession and restriction", "Use the subjunctive in advanced contexts", "Structure a formal debate"],
                    vocabulary=[
                        VocabItem(fr='d\\', en='on one hand... on the other hand', ipa='', example='D\\', exampleEn='On one hand it\\', category='discourse'),
                        VocabItem(fr='non seulement... mais aussi', en='not only... but also', ipa='', example='Non seulement il est intelligent, mais aussi travailleur.', exampleEn='Not only is he smart, but also hardworking.', category='discourse'),
                        VocabItem(fr='toutefois', en='however / nevertheless', ipa='', example='Toutefois, il faut noter...', exampleEn='However, it should be noted...', category='discourse'),
                        VocabItem(fr='quoique', en='although / albeit', ipa='', example='Quoique fatigué, il continue.', exampleEn='Although tired, he continues.', category='concession'),
                        VocabItem(fr='sans compter que', en='not to mention that', ipa='', example='Sans compter que c\\', exampleEn='Not to mention it\\', category='discourse'),
                        VocabItem(fr='dans la mesure où', en='insofar as', ipa='', example='Dans la mesure où c\\', exampleEn='Insofar as it\\', category='discourse'),
                        VocabItem(fr='il n\\', en='nevertheless / it remains the case that', ipa='', example='Il n\\', exampleEn='It remains the case that it\\', category='discourse'),
                        VocabItem(fr='sauf si', en='unless', ipa='', example='Je viendrai sauf si tu refuses.', exampleEn='I\\', category='condition'),
                        VocabItem(fr='à condition que', en='on condition that', ipa='', example='À condition que tu viennes.', exampleEn='On condition that you come.', category='condition'),
                        VocabItem(fr='le débat', en='the debate', ipa='', example='Le débat est passionné.', exampleEn='The debate is passionate.', category='politics'),
                        VocabItem(fr='une opinion', en='an opinion', ipa='', example='Chacun a son opinion.', exampleEn='Everyone has their opinion.', category='politics'),
                        VocabItem(fr='voter', en='to vote', ipa='', example='Je vais voter demain.', exampleEn='I\\', category='politics'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Advanced discourse markers',
                            explanation='Discourse markers organize speech and signal relationships between ideas. At B2 level, you should use varied markers, not just \'mais\' and \'donc\'.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "D\\", "en": "On one hand, the project is ambitious; on the other, it\\"}, {"fr": "Non seulement il travaille vite, mais aussi il fait peu d\\", "en": "Not only does he work fast, but he also makes few mistakes."}, {"fr": "Toutefois, il faut reconna\u00eetre que le projet est risqu\u00e9.", "en": "However, one must acknowledge that the project is risky."}, {"fr": "Il n\\", "en": "It remains the case that the decision is up to the boss."}]],
                            tip='Mix formal and standard markers. Overusing \'cependant\' sounds academic; vary with \'mais\', \'pourtant\', \'toutefois\'.',
                        ),
                        GrammarRule(
                            title='Subjunctive after concession',
                            explanation='After \'quoique\' (although), \'bien que\' (although), \'pour que\' (so that), and \'sans que\' (without), use the subjunctive. These are common in formal writing and debate.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Quoiqu\\", "en": "Although he\\"}, {"fr": "Bien qu\\", "en": "Although she worked, she failed."}, {"fr": "Sans qu\\", "en": "Without anyone asking, he helped."}]],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "suis"}, {"pronoun": "tu", "form": "es"}, {"pronoun": "il/elle", "form": "est"}, {"pronoun": "nous", "form": "sommes"}, {"pronoun": "vous", "form": "\u00eates"}, {"pronoun": "ils/elles", "form": "sont"}],
                                sentenceRule='Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je suis \u00e9tudiant.", "en": "I am a student."}, {"fr": "Tu es fran\u00e7ais ?", "en": "Are you French?"}, {"fr": "Nous sommes \u00e0 Paris.", "en": "We are in Paris."}]],
                            ),
                            ConjugationVerb(
                                infinitive='avoir',
                                translation='to have',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "ai"}, {"pronoun": "tu", "form": "as"}, {"pronoun": "il/elle", "form": "a"}, {"pronoun": "nous", "form": "avons"}, {"pronoun": "vous", "form": "avez"}, {"pronoun": "ils/elles", "form": "ont"}],
                                sentenceRule='Subject + avoir + noun. Used for possession, age (J\\',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "J\\", "en": "I have a brother."}, {"fr": "Tu as vingt ans.", "en": "You are twenty."}, {"fr": "Il a faim.", "en": "He is hungry."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='b2-u3-l1-conj-0-1', type='conjugation', prompt='Conjugate "être" for "je":', answer='suis', options=None, explanation='je suis — correct form of "être".'),
                            Exercise(id='b2-u3-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "être".', answer='', options=['est', 'suis', 'es', 'sommes'], explanation='il/elle est — correct conjugation of "être".'),
                            Exercise(id='b2-u3-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "Je _____ étudiant." (I am a student.) — form of "être"', answer='suis', options=None, explanation='The correct form is "suis".'),
                            Exercise(id='b2-u3-l1-conj-1-1', type='conjugation', prompt='Conjugate "avoir" for "tu":', answer='as', options=None, explanation='tu as — correct form of "avoir".'),
                            Exercise(id='b2-u3-l1-conj-1-2', type='multiple_choice', prompt='Complete: "nous _____" with the correct form of "avoir".', answer='', options=['avons', 'ai', 'as', 'a'], explanation='nous avons — correct conjugation of "avoir".'),
                            Exercise(id='b2-u3-l1-conj-1-3', type='fill_blank', prompt='Fill in the blank: "Tu _____ vingt ans." (You are twenty.) — form of "avoir"', answer='as', options=None, explanation='The correct form is "as".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Modérateur', fr='Madame, quel est votre avis sur la réforme des retraites ?', en='Madam, what is your opinion on the pension reform?'),
                        DialogueLine(speaker='B', name='Élue', fr='D\\', en='On one hand, I understand citizens\\'),
                        DialogueLine(speaker='A', name='Modérateur', fr='Mais concrètement, que proposez-vous ?', en='But concretely, what do you propose?'),
                        DialogueLine(speaker='B', name='Élue', fr='Non seulement il faut relever l\\', en='Not only must we raise the retirement age, but also encourage seniors\\'),
                        DialogueLine(speaker='A', name='Modérateur', fr='Et vos opposants disent que c\\', en='And your opponents say it\\'),
                        DialogueLine(speaker='B', name='Élue', fr='Il n\\', en='It remains the case that without reform, the system will collapse. Although difficult, these measures are necessary.'),
                    ],
                    exercises=[
                        Exercise(id='b2-u3-l1-e1', type='multiple_choice', prompt='Complete: "_____ il est intelligent, _____ il travaille dur."', options=['D\\', 'autre part', 'Non seulement... mais aussi', 'Soit... soit', 'Ni... ni'], answer=1, explanation='Non seulement... mais aussi = not only... but also.'),
                        Exercise(id='b2-u3-l1-e2', type='fill_blank', prompt='Complete: "_____ qu\\', options=None, answer='Bien', explanation='Bien que or quoique + subjunctive = although.'),
                        Exercise(id='b2-u3-l1-e3', type='multiple_choice', prompt='Which means "nevertheless"?', options=['En outre', 'Toutefois', 'En effet', 'Quant à'], answer=1, explanation='Toutefois = however/nevertheless. En outre = furthermore. En effet = indeed.'),
                        Exercise(id='b2-u3-l1-e4', type='translate_to_fr', prompt='Translate: "Not only is she smart, but also hardworking."', options=None, answer='Non seulement elle est intelligente, mais aussi travailleuse', explanation='Non seulement... mais aussi + adjectives.'),
                        Exercise(id='b2-u3-l1-e5', type='true_false', prompt='"Bien que" is followed by the subjunctive.', options=['True', 'False'], answer=0, explanation='True. Bien que + subjunctive: bien qu\\'),
                    ],
                    culturalNote='France has a strong tradition of political debate — TV shows like \'C dans l\\\'air\', \'C à vous\', and \'Bourdin Direct\' feature heated discussions daily. The French \'concours\' (debating competition) and \'khâgne\' (literary prep class) train students in eloquence. The Académie française defines \'le bon usage\' — but the French people themselves constantly debate what is \'correct\' French.',
                    estimatedMinutes=40,
                ),
            ],
        ),
        Unit(
            id='b2-u4',
            title='Literature and Style',
            titleFr='Littérature et style',
            theme='Literature & stylistic devices',
            description='Discover French literature, understand stylistic devices, and analyze texts.',
            lessons=[
                Lesson(
                    id='b2-u4-l1',
                    title='French Literary Heritage',
                    titleFr='Le patrimoine littéraire français',
                    description='Discover major French authors and learn to analyze literary texts.',
                    objectives=["Identify major French authors and works", "Recognize literary genres", "Use literary vocabulary", "Analyze a short text"],
                    vocabulary=[
                        VocabItem(fr='un roman', en='a novel', ipa='', example='J\\', exampleEn='I read a novel by Victor Hugo.', category='literature'),
                        VocabItem(fr='une nouvelle', en='a short story', ipa='', example='Maupassant a écrit des nouvelles.', exampleEn='Maupassant wrote short stories.', category='literature'),
                        VocabItem(fr='un poème', en='a poem', ipa='', example='Ce poème est de Baudelaire.', exampleEn='This poem is by Baudelaire.', category='literature'),
                        VocabItem(fr='une pièce de théâtre', en='a play', ipa='', example='Cyrano est une pièce de théâtre.', exampleEn='Cyrano is a play.', category='literature'),
                        VocabItem(fr='un auteur', en='an author', ipa='', example='Cet auteur est célèbre.', exampleEn='This author is famous.', category='literature'),
                        VocabItem(fr='un personnage', en='a character', ipa='', example='Le personnage principal est complexe.', exampleEn='The main character is complex.', category='literature'),
                        VocabItem(fr='un genre littéraire', en='a literary genre', ipa='', example='Le roman policier est un genre littéraire.', exampleEn='The detective novel is a literary genre.', category='literature'),
                        VocabItem(fr='le style', en='the style', ipa='', example='Son style est unique.', exampleEn='Their style is unique.', category='literature'),
                        VocabItem(fr='une métaphore', en='a metaphor', ipa='', example='Cette métaphore est puissante.', exampleEn='This metaphor is powerful.', category='style'),
                        VocabItem(fr='une comparaison', en='a comparison', ipa='', example='Il utilise une comparaison.', exampleEn='He uses a comparison.', category='style'),
                        VocabItem(fr='la narration', en='the narration', ipa='', example='La narration est au présent.', exampleEn='The narration is in present tense.', category='style'),
                        VocabItem(fr='le symbolisme', en='symbolism', ipa='', example='Le symbolisme est riche.', exampleEn='The symbolism is rich.', category='style'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Stylistic devices in French',
                            explanation='Literary French uses specific devices: métaphore (metaphor), comparaison (comparison with comme), allitération (sound repetition), hyperbole (exaggeration), litote (understatement). Recognizing these helps you appreciate texts.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "M\u00e9taphore: \"Cet homme est un lion.\" (He IS a lion)", "en": "Direct comparison without \"like\"."}, {"fr": "Comparaison: \"Cet homme est courageux comme un lion.\"", "en": "Comparison with \"comme\"."}, {"fr": "Hyperbole: \"Je meurs de faim.\" (I\\", "en": "Exaggeration."}, {"fr": "Litote: \"Va, je ne te hais point.\" (le Cid) \u2014 meaning \"I love you.\"", "en": "Understatement expressing the opposite."}]],
                            tip='Famous French litotes: \'Ce n\\\'est pas mauvais\' (= it\'s excellent), \'Je ne te déteste pas\' (= I love you).',
                        ),
                        GrammarRule(
                            title='The "passé simple" — literary past tense',
                            explanation='The passé simple is used in literary texts (novels, history) for completed past actions. It is rarely used in spoken French but you must recognize it. Common forms: il aima, il finit, il vendit, il fut, il eut.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Il aima cette femme toute sa vie.", "en": "He loved this woman all his life."}, {"fr": "Elle naquit en 1900 et mourut en 1980.", "en": "She was born in 1900 and died in 1980."}, {"fr": "Le roi vit le ch\u00e2teau et l\\", "en": "The king saw the castle and admired it."}]],
                            tip='You don\\',
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='vouloir',
                                translation='to want',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "veux"}, {"pronoun": "tu", "form": "veux"}, {"pronoun": "il/elle", "form": "veut"}, {"pronoun": "nous", "form": "voulons"}, {"pronoun": "vous", "form": "voulez"}, {"pronoun": "ils/elles", "form": "veulent"}],
                                sentenceRule='Subject + vouloir + noun/infinitive. Je voudrais (conditional) = I would like — polite form for ordering. Irregular.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je veux un caf\u00e9.", "en": "I want a coffee."}, {"fr": "Tu veux venir ?", "en": "Do you want to come?"}, {"fr": "Je voudrais un th\u00e9.", "en": "I would like a tea."}]],
                            ),
                            ConjugationVerb(
                                infinitive='prendre',
                                translation='to take',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "prends"}, {"pronoun": "tu", "form": "prends"}, {"pronoun": "il/elle", "form": "prend"}, {"pronoun": "nous", "form": "prenons"}, {"pronoun": "vous", "form": "prenez"}, {"pronoun": "ils/elles", "form": "prennent"}],
                                sentenceRule='Subject + prendre + transport (Je prends le métro). Also: prendre un café, prendre le petit-déjeuner. Irregular -re verb.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je prends le bus.", "en": "I take the bus."}, {"fr": "Tu prends un caf\u00e9 ?", "en": "Will you have a coffee?"}, {"fr": "Nous prenons le train.", "en": "We take the train."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='b2-u4-l1-conj-0-1', type='conjugation', prompt='Conjugate "vouloir" for "je":', answer='veux', options=None, explanation='je veux — correct form of "vouloir".'),
                            Exercise(id='b2-u4-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "vouloir".', answer='', options=['veut', 'veux', 'veux', 'voulons'], explanation='il/elle veut — correct conjugation of "vouloir".'),
                            Exercise(id='b2-u4-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "Je _____ un café." (I want a coffee.) — form of "vouloir"', answer='veux', options=None, explanation='The correct form is "veux".'),
                            Exercise(id='b2-u4-l1-conj-1-1', type='conjugation', prompt='Conjugate "prendre" for "tu":', answer='prends', options=None, explanation='tu prends — correct form of "prendre".'),
                            Exercise(id='b2-u4-l1-conj-1-2', type='multiple_choice', prompt='Complete: "nous _____" with the correct form of "prendre".', answer='', options=['prenons', 'prends', 'prends', 'prend'], explanation='nous prenons — correct conjugation of "prendre".'),
                            Exercise(id='b2-u4-l1-conj-1-3', type='fill_blank', prompt='Fill in the blank: "Tu _____ un café ?" (Will you have a coffee?) — form of "prendre"', answer='prends', options=None, explanation='The correct form is "prends".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Prof', fr='Aujourd\\', en='Today, we\\'),
                        DialogueLine(speaker='B', name='Élève', fr='C\\', en='It\\'),
                        DialogueLine(speaker='A', name='Prof', fr='Exactement. Hugo utilise de nombreuses métaphores. Par exemple, "la nuit de l\\', en='Exactly. Hugo uses many metaphors. For example, "the night of ignorance" is a metaphor for education.'),
                        DialogueLine(speaker='B', name='Élève', fr='Et le style ? Hugo emploie le passé simple, non ?', en='And the style? Hugo uses the passé simple, right?'),
                        DialogueLine(speaker='A', name='Prof', fr='Oui, comme dans "Il aima Cosette profondément." Le passé simple est caractéristique du roman classique.', en='Yes, as in "He loved Cosette profoundly." The passé simple is characteristic of the classical novel.'),
                        DialogueLine(speaker='B', name='Élève', fr='C\\', en='Fascinating! French literature is rich.'),
                    ],
                    exercises=[
                        Exercise(id='b2-u4-l1-e1', type='multiple_choice', prompt='Who wrote "Les Misérables"?', options=['Émile Zola', 'Victor Hugo', 'Marcel Proust', 'Albert Camus'], answer=1, explanation='Victor Hugo wrote Les Misérables (1862). A monumental French novel.'),
                        Exercise(id='b2-u4-l1-e2', type='fill_blank', prompt='Complete: "Ce homme est un lion" est une _____.', options=None, answer='métaphore', explanation='A direct comparison without "comme" is a metaphor.'),
                        Exercise(id='b2-u4-l1-e3', type='multiple_choice', prompt='What is the passé simple of "être" for "il"?', options=['était', 'a été', 'fut', 'sera'], answer=2, explanation='Il fut = he was (literary past).'),
                        Exercise(id='b2-u4-l1-e4', type='translate_to_fr', prompt='Translate: "This poem is by Baudelaire."', options=None, answer='Ce poème est de Baudelaire', explanation='Use "être de" to indicate authorship: est de [author].'),
                        Exercise(id='b2-u4-l1-e5', type='true_false', prompt='The passé simple is commonly used in spoken French.', options=['True', 'False'], answer=1, explanation='False. It is used in literature, not in everyday speech.'),
                    ],
                    culturalNote='France has 16 Nobel Prize winners in Literature — more than any other country. Major authors: Molière (theater), Victor Hugo (romanticism), Marcel Proust (modernism), Albert Camus (existentialism), Simone de Beauvoir (feminism). The \'Prix Goncourt\' is France\'s most prestigious literary prize, awarded every November. Reading French literature is one of the best ways to reach true fluency.',
                    estimatedMinutes=40,
                ),
            ],
        ),
        Unit(
            id='b2-u5',
            title='Economy and Globalization',
            titleFr='L\'économie mondiale',
            theme='Economy, abstract nouns & complex sentences',
            description='Discuss economic issues, globalization, and use complex sentence structures.',
            lessons=[
                Lesson(
                    id='b2-u5-l1',
                    title='The Global Economy',
                    titleFr='L\'économie mondiale',
                    description='Use economic vocabulary and complex sentence structures to debate globalization.',
                    objectives=["Use economic vocabulary (croissance, ch\u00f4mage, inflation)", "Form complex sentences with ", ", ", "", "Use nominalization (verbs \u2192 abstract nouns)", "Discuss pros and cons of globalization"],
                    vocabulary=[
                        VocabItem(fr='l\'économie', en='the economy', ipa='', example='L\'économie mondiale.', exampleEn='The global economy.', category='economy'),
                        VocabItem(fr='la croissance', en='growth (economic)', ipa='', example='La croissance est forte.', exampleEn='Growth is strong.', category='economy'),
                        VocabItem(fr='le chômage', en='unemployment', ipa='', example='Le chômage baisse.', exampleEn='Unemployment is falling.', category='economy'),
                        VocabItem(fr='l\'inflation', en='inflation', ipa='', example='L\'inflation augmente.', exampleEn='Inflation is rising.', category='economy'),
                        VocabItem(fr='la récession', en='recession', ipa='', example='Une récession économique.', exampleEn='An economic recession.', category='economy'),
                        VocabItem(fr='la crise', en='crisis', ipa='', example='La crise de 2008.', exampleEn='The 2008 crisis.', category='economy'),
                        VocabItem(fr='la mondialisation', en='globalization', ipa='', example='La mondialisation a des avantages.', exampleEn='Globalization has advantages.', category='globalization'),
                        VocabItem(fr='le commerce', en='trade / commerce', ipa='', example='Le commerce international.', exampleEn='International trade.', category='economy'),
                        VocabItem(fr='l\'importation', en='import', ipa='', example='L\'importation de produits.', exampleEn='Importing products.', category='economy'),
                        VocabItem(fr='l\'exportation', en='export', ipa='', example='L\'exportation de vin.', exampleEn='Exporting wine.', category='economy'),
                        VocabItem(fr='la concurrence', en='competition', ipa='', example='La concurrence est rude.', exampleEn='Competition is fierce.', category='economy'),
                        VocabItem(fr='le marché', en='the market', ipa='', example='Le marché libre.', exampleEn='The free market.', category='economy'),
                        VocabItem(fr='le PIB', en='GDP', ipa='', example='Le PIB français.', exampleEn='The French GDP.', category='economy'),
                        VocabItem(fr='le pouvoir d\\', en='purchasing power', ipa='', example='Le pouvoir d\\', exampleEn='Purchasing power is decreasing.', category='economy'),
                        VocabItem(fr='le salaire minimum', en='minimum wage', ipa='', example='Le SMIC, salaire minimum.', exampleEn='The SMIC, minimum wage.', category='economy'),
                        VocabItem(fr='la pauvreté', en='poverty', ipa='', example='Lutter contre la pauvreté.', exampleEn='Fight against poverty.', category='economy'),
                        VocabItem(fr='les inégalités', en='inequalities', ipa='', example='Les inégalités sociales.', exampleEn='Social inequalities.', category='economy'),
                        VocabItem(fr='le développement durable', en='sustainable development', ipa='', example='Le développement durable est essentiel.', exampleEn='Sustainable development is essential.', category='globalization'),
                        VocabItem(fr='une multinationale', en='a multinational corporation', ipa='', example='Une multinationale américaine.', exampleEn='An American multinational.', category='economy'),
                        VocabItem(fr='délocaliser', en='to offshore / outsource', ipa='', example='Délocaliser la production.', exampleEn='To offshore production.', category='verbs'),
                    ],
                    grammar=[
                        GrammarRule(
                            title='Nominalization — turning verbs into abstract nouns',
                            explanation='In formal French (especially B2/C1 level), verbs are often turned into abstract nouns. This makes speech more sophisticated: \'la croissance\' (growth) instead of \'grandir\' (to grow), \'le développement\' (development) instead of \'développer\' (to develop). Common suffixes: -tion, -ment, -age, -ure, -esse.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "d\u00e9velopper \u2192 le d\u00e9veloppement", "en": "to develop \u2192 development"}, {"fr": "cro\u00eetre \u2192 la croissance", "en": "to grow \u2192 growth"}, {"fr": "d\u00e9cider \u2192 la d\u00e9cision", "en": "to decide \u2192 decision"}, {"fr": "gouverner \u2192 le gouvernement", "en": "to govern \u2192 government"}]],
                            tip='Abstract nouns let you express complex ideas compactly. Use them in formal writing and debates.',
                        ),
                        GrammarRule(
                            title='Complex sentences with concession',
                            explanation='At B2 level, you should master concession structures: \'bien que\' + subjunctive, \'quoique\' + subjunctive, \'sans que\' + subjunctive, \'tout en\' + gerund. These show nuance in arguments.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "Bien que la mondialisation ait des avantages, elle cr\u00e9e des in\u00e9galit\u00e9s.", "en": "Although globalization has advantages, it creates inequalities."}, {"fr": "Quoique le PIB augmente, le ch\u00f4mage reste \u00e9lev\u00e9.", "en": "Although GDP is increasing, unemployment remains high."}, {"fr": "Le gouvernement a agi sans que les citoyens soient consult\u00e9s.", "en": "The government acted without citizens being consulted."}, {"fr": "Tout en reconnaissant les difficult\u00e9s, je reste optimiste.", "en": "While acknowledging the difficulties, I remain optimistic."}]],
                            tip='After bien que / quoique / sans que / pour que / avant que → always use SUBJUNCTIVE.',
                        ),
                        GrammarRule(
                            title='Expressing cause and consequence formally',
                            explanation='Formal French uses several structures to express cause and consequence: \'en raison de\' + noun, \'grâce à\' + noun (positive), \'à cause de\' + noun (negative), \'étant donné que\' + indicative, \'dans la mesure où\' + indicative.',
                            examples=[GrammarExample(fr=ex['fr'], en=ex['en']) for ex in [{"fr": "En raison de la crise, le ch\u00f4mage a augment\u00e9.", "en": "Due to the crisis, unemployment increased."}, {"fr": "\u00c9tant donn\u00e9 que la demande baisse, les prix vont suivre.", "en": "Given that demand is falling, prices will follow."}, {"fr": "Dans la mesure o\u00f9 les salaires stagnent, le pouvoir d\\", "en": "Insofar as wages stagnate, purchasing power decreases."}]],
                        ),
                    ],
                    conjugation=ConjugationData(
                        verbs=[
                            ConjugationVerb(
                                infinitive='aller',
                                translation='to go',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "vais"}, {"pronoun": "tu", "form": "vas"}, {"pronoun": "il/elle", "form": "va"}, {"pronoun": "nous", "form": "allons"}, {"pronoun": "vous", "form": "allez"}, {"pronoun": "ils/elles", "form": "vont"}],
                                sentenceRule='Subject + aller + preposition + place. à + le = au, à + les = aux. Also: aller + infinitive = near future (Je vais manger).',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je vais au cin\u00e9ma.", "en": "I go to the cinema."}, {"fr": "Nous allons \u00e0 Paris.", "en": "We go to Paris."}, {"fr": "Je vais manger.", "en": "I am going to eat."}]],
                            ),
                            ConjugationVerb(
                                infinitive='être',
                                translation='to be',
                                tense='Présent',
                                conjugations=[{"pronoun": "je", "form": "suis"}, {"pronoun": "tu", "form": "es"}, {"pronoun": "il/elle", "form": "est"}, {"pronoun": "nous", "form": "sommes"}, {"pronoun": "vous", "form": "\u00eates"}, {"pronoun": "ils/elles", "form": "sont"}],
                                sentenceRule='Subject + être + adjective/noun/profession. Professions take NO article: Je suis professeur. Used for identity, nationality, location.',
                                sentenceExamples=[GrammarExample(fr=se['fr'], en=se['en']) for se in [{"fr": "Je suis \u00e9tudiant.", "en": "I am a student."}, {"fr": "Tu es fran\u00e7ais ?", "en": "Are you French?"}, {"fr": "Nous sommes \u00e0 Paris.", "en": "We are in Paris."}]],
                            ),
                        ],
                        practice=[
                            Exercise(id='b2-u5-l1-conj-0-1', type='conjugation', prompt='Conjugate "aller" for "je":', answer='vais', options=None, explanation='je vais — correct form of "aller".'),
                            Exercise(id='b2-u5-l1-conj-0-2', type='multiple_choice', prompt='Complete: "il/elle _____" with the correct form of "aller".', answer='', options=['va', 'vais', 'vas', 'allons'], explanation='il/elle va — correct conjugation of "aller".'),
                            Exercise(id='b2-u5-l1-conj-0-3', type='fill_blank', prompt='Fill in the blank: "Je _____ au cinéma." (I go to the cinema.) — form of "aller"', answer='vais', options=None, explanation='The correct form is "vais".'),
                            Exercise(id='b2-u5-l1-conj-1-1', type='conjugation', prompt='Conjugate "être" for "tu":', answer='es', options=None, explanation='tu es — correct form of "être".'),
                            Exercise(id='b2-u5-l1-conj-1-2', type='multiple_choice', prompt='Complete: "nous _____" with the correct form of "être".', answer='', options=['sommes', 'suis', 'es', 'est'], explanation='nous sommes — correct conjugation of "être".'),
                            Exercise(id='b2-u5-l1-conj-1-3', type='fill_blank', prompt='Fill in the blank: "Tu _____ français ?" (Are you French?) — form of "être"', answer='es', options=None, explanation='The correct form is "es".'),
                        ],
                    ),
                    dialogue=[
                        DialogueLine(speaker='A', name='Moderateur', fr='Aujourd\\', en='Today, we will debate globalization. Madam, your opinion?'),
                        DialogueLine(speaker='B', name='Économiste', fr='Bien que la mondialisation ait créé des richesses, elle a aussi creusé les inégalités. Le pouvoir d\\', en='Although globalization has created wealth, it has also deepened inequalities. Middle-class purchasing power is stagnating.'),
                        DialogueLine(speaker='A', name='Moderateur', fr='Et vous, monsieur ? Êtes-vous d\\', en='And you, sir? Do you agree?'),
                        DialogueLine(speaker='C', name='Entrepreneur', fr='Pas tout à fait. Étant donné que le commerce international s\\', en='Not quite. Given that international trade has developed, millions of people have escaped poverty, especially in Asia.'),
                        DialogueLine(speaker='B', name='Économiste', fr='Je le concède. Toutefois, la délocalisation a détruit des emplois dans les pays développés. Dans la mesure où les entreprises cherchent le moindre coût, les travailleurs locaux pâtissent.', en='I concede that. However, offshoring has destroyed jobs in developed countries. Insofar as companies seek the lowest cost, local workers suffer.'),
                        DialogueLine(speaker='C', name='Entrepreneur', fr='Sans que cela soit faux, il faut reconnaître que de nouveaux secteurs ont émergé. Le développement durable crée aujourd\\', en='Without that being false, we must acknowledge that new sectors have emerged. Sustainable development today creates numerous jobs.'),
                        DialogueLine(speaker='A', name='Moderateur', fr='Pour conclure, la mondialisation a donc des effets contrastés. Merci à nos invités.', en='To conclude, globalization thus has mixed effects. Thank you to our guests.'),
                    ],
                    exercises=[
                        Exercise(id='b2-u5-l1-e1', type='multiple_choice', prompt='Complete with the correct mood: "Bien qu\\', options=['est', 'soit', 'était', 'sera'], answer=1, explanation='Bien que + subjunctive: soit.'),
                        Exercise(id='b2-u5-l1-e2', type='multiple_choice', prompt='Which expression introduces a NEGATIVE cause?', options=['Grâce à', 'En raison de', 'À cause de', 'Étant donné que'], answer=2, explanation='À cause de = because of (negative). Grâce à = thanks to (positive).'),
                        Exercise(id='b2-u5-l1-e3', type='fill_blank', prompt='Complete: "_____ la crise, le chômage a augmenté." (Due to the crisis)', options=None, answer='En raison de', explanation='En raison de + noun = due to. (À cause de also works.)'),
                        Exercise(id='b2-u5-l1-e4', type='multiple_choice', prompt='Which is the nominalization of "développer" (to develop)?', options=['le développement', 'la développement', 'le développe', 'la développe'], answer=0, explanation='Développer → le développement (m).'),
                        Exercise(id='b2-u5-l1-e5', type='true_false', prompt='After "sans que", you use the subjunctive mood.', options=['True', 'False'], answer=0, explanation='True. Sans que + subjunctive: "sans que les citoyens soient consultés".'),
                        Exercise(id='b2-u5-l1-e6', type='matching', prompt='Match each economic term to its French name.', options=None, answer=None, explanation=''),
                        Exercise(id='b2-u5-l1-e7', type='translate_to_fr', prompt='Translate: "Although the GDP is increasing, unemployment remains high."', options=None, answer='Bien que le PIB augmente, le chômage reste élevé', explanation='Bien que + subjunctive (augmente), then main clause.'),
                    ],
                    activities=[
                        Exercise(id='b2-u5-l1-a1', type='transformation', prompt='Transform: "Le PIB augmente." → "_____ que le PIB augmente, le chômage reste élevé." (Although)', options=None, answer='Bien', explanation='Bien que or quoique + subjunctive for concession.'),
                        Exercise(id='b2-u5-l1-a2', type='transformation', prompt='Nominalize: "décider" (verb) → ?', options=None, answer='la décision', explanation='Verb → abstract noun: décider → la décision.'),
                        Exercise(id='b2-u5-l1-a3', type='transformation', prompt='Nominalize: "gouverner" (to govern) → ?', options=None, answer='le gouvernement', explanation='Verb → abstract noun: gouverner → le gouvernement.'),
                        Exercise(id='b2-u5-l1-a4', type='dictation', prompt='Listen and type what you hear.', options=None, answer='En raison de la crise, le chômage a augmenté.', explanation='Formal expression of cause.'),
                        Exercise(id='b2-u5-l1-a5', type='word_bank', prompt='Build: "Although globalization has advantages, it creates inequalities."', options=None, answer='Bien que la mondialisation ait des avantages elle crée des inégalités', explanation='Bien que + subjunctive (ait), main clause.'),
                        Exercise(id='b2-u5-l1-a6', type='fill_blank', prompt='Complete: "Dans la _____ où les salaires stagnent, le pouvoir d\\', options=None, answer='mesure', explanation='Dans la mesure où = insofar as. Formal connector.'),
                        Exercise(id='b2-u5-l1-a7', type='reorder', prompt='Reorder: "inégalités / la / creusé / mondialisation / a / des"', options=None, answer='La mondialisation a creusé des inégalités.', explanation='Subject + verb + object. "Creuser des inégalités" = deepen inequalities.'),
                    ],
                    culturalNote='France is the world\'s 7th largest economy by GDP. It has a mixed economy with strong state intervention — the government owns shares in major companies like Renault, EDF (electricity), and Air France. The famous \'SMIC\' (Salaire Minimum Interprofessionnel de Croissance) is France\'s minimum wage — about €1,398/month net in 2024. French workers work fewer hours than most (35-hour work week) but are among the most productive per hour in the world. The French welfare state (\'la Sécurité Sociale\') is one of the most generous in Europe.',
                    estimatedMinutes=45,
                ),
            ],
        ),
    ],
)